### ISSUE TITLE
Indexer: clean / manage indexes command 

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1006]
---

Tried implementing a strategy to check the existince when records are retrieved. It worked -- but wonder if it isn't better to just have a command / service to periodically clean the index.

**Comment by mamazu** [comment]
Partially related to #1374

**Comment by mamazu** [comment]
What else would you recon we need here?

**Comment by dantleech** [comment]
We could have a service which periodically scans and tidys the index, but not sure what problem that's trying to solve ATM.
