### ISSUE TITLE
[RPC] New feature: "Refactor this" context menu

### ISSUE THREAD

**Issue by tkotosz** [phpactor/phpactor#1011]
Currently phpactor provides 2 kinds of choice menus:
- `context_menu`: Provides a list of possible commands given the current context
- `transform`: Provides the list of transformation commands (see https://github.com/phpactor/phpactor/issues/1009)

I don't see much point in having the `transform` choice menu as I said in https://github.com/phpactor/phpactor/issues/1010 , would be better for the `context_menu` to offer these commands whenever they are relevant. But in addition to this I would like to have another context menu which could be triggered for selections. Phpstorm calls this the "Refactor this" menu and offers commands like "Extract to constant", "Extract to method", "Rename" etc... most of these are already available in phpactor RPC so would be really good to group them in a context menu like this.

What do you think?

In case you wanna have a look in phpstorm on linux it works like this OOB:
- "alt+enter": triggers the context menu (e.g. if I trigger it in the constructor it offers to complete the constructor and stuff like that, if I trigger it while I am on a function call then it offers to generate the method, etc...)
- "ctrl+alt+shift+t" (all modifiers +t): triggers the "refactor this" context menu (e.g. if I select some code and trigger it then it offers to extract to method, extract to constant, etc... or if I select a variable or I am on a variable then it offers to rename it)

**Comment by dantleech** [comment]
Possibly - the context menu doesn't work on selections at the moment, if it did then I don't see any reason not to have a single menu.

The `transform` menu is a legacy thing (which I still use frequently) which performs actions on the entire file.
 
LSP has `code actions` which is like a context menu, and there will be some refactoring to accomodate this I think.
