### ISSUE TITLE
[RPC] Unify parameter naming (path, offset, source)

### ISSUE THREAD

**Issue by tkotosz** [phpactor/phpactor#1016]
Most of the RPC commands take the following arguments:
- `path`: The current file path
- `source`: The current file source
- `offset`: The current cursor position as byte offset

Some commands do not require offset which is fine, but some commands like the `context_menu` takes the current file path as `current_path` instead of `path` which requires to handle this specific command in a different way all other, which seems totally unnecessary. So I think it would make sense to review the commands and make sure they use the exact same names for the exact same things.

So far I run into the following field names:
- source: The current file source
- path: The current file path
- offset: The current cursor position as byte offset
- source_path: Same as path
- current_path: Same as path
- offset_start: The start position of the current selection as byte offset
- offset_end: The end position of the current selection as byte offset

Side Note: Offset start and offset end are special, they needed for extract method and extract expression.

**Comment by dantleech** [comment]
closing as legacy :smile:
