### ISSUE TITLE
[RPC][rename_variable] Name suggestion missing from rename_variable command response

### ISSUE THREAD

**Issue by tkotosz** [phpactor/phpactor#1020]
When I execute the `rename_variable` command  from context menu it is correctly sending back a `name_suggestion` (the current name of the variable) BUT when I call it directly (without going through the context menu) with the exact same parameters then the `name_suggestion` is null. I guess there might be some state stored on phpactor side when going through the context menu maybe? Weird one for sure.

**Comment by mamazu** [comment]
What do you mean "with calling it directly"?

**Comment by dantleech** [comment]
@tkotosz is talking about calling the legacy RPC API directly I think, can be closed.
