### ISSUE TITLE
[RPC][import_class] Improve applying alias when importing class

### ISSUE THREAD

**Issue by tkotosz** [phpactor/phpactor#1023]
When importing a class using the `import_class` command and a name-collision happens then phpactor offers to alias the import:
```
{
    "name": "input_callback",
    "parameters": {
        "inputs": [
            {
                "name": "alias",
                "parameters": {
                    "default": "Parser",
                    "label": "\"Parser\" is already used, choose an alias: ",
                    "type": "None"
                },
                "type": "text"
            }
        ],
        "callback": {
            "parameters": {
                "qualified_name": "Behat\\\\Gherkin\\\\Parser",
                "path": "/home/tkotosz/Sites/BehatRSTSpecificationLocatorExtension/src/RST/Loader/RSTFileLoader.php",
                "offset": 1146,
                "alias": "None",
                "source": "..."
            },
            "action": "import_class"
        }
    }
}
```
Then when the alias is provided through the callback (in this case alias is "GherkinParser") then the following is returned:
```
{
    "name": "update_file_source",
    "parameters": {
        "path": "/home/tkotosz/Sites/BehatRSTSpecificationLocatorExtension/src/RST/Loader/RSTFileLoader.php",
        "edits": [
            {
                "end": {
                    "character": 0,
                    "line": 7
                },
                "text": "use Behat\\\\Gherkin\\\\Parser as GherkinParser;\\n",
                "start": {
                    "character": 0,
                    "line": 7
                }
            }
        ],
        "source": "..."
    }
}
```
Which is good, it is the correct use statement, but it is missing an edit which would actually change the class name to the alias at the place of invocation.
Note: The changed source code contained in the `source` parameter matches the edits correctly, so at least it is consistent and not only missing this edit from the edits list.

Use case:
I have used this in the constructor to import the class, so in this case the constructor argument's class name should be updated to be the alias.

**Comment by dantleech** [comment]
This is done https://github.com/phpactor/code-transform/commit/9df5d232203d0cc6854cda8431fa7aac5a082628 (pending release)
