### ISSUE TITLE
[RPC][rename_variable] Make rename variable scope aware?

### ISSUE THREAD

**Issue by tkotosz** [phpactor/phpactor#1024]
Currently when executing `rename_variable` then it offers to do rename in `local` scope or in `file` scope. It would be nice if the command could figure this out automatically based on the context. Something like this:

1. if the variable is a `$something` then do rename in `local` scope
2. if the variable is a `$this->something` then do rename in `file` scope

Note that the second case is actually tricky since `$this` might refer to a member of the parent class in which case the rename would fell outside of the `file` scope. (The current command fails in this case btw)

Note that there is a replace references command as well available through the context menu which can actually rename the variable in the second case even if it is outside of the `file` scope. But that one is probably not fully functional yet since it is a non-trivial refactoring operation. E.g. if the parent class is an abstract class and the member is a protected member then changing the member name only in the abstract class breaks all child class which still refer to the old member name.

So probably handing this is outside of the scope of this feature request. But the automatically picking the local/file mode for `rename_variable` sound feasible for me.

What do you think?

**Comment by dantleech** [comment]
You will often have a variable representing some concept multiple times in a class, so the `file` scope is to replace all of these.

`$this->something` is a class member - so the _variable rename_ should probably not work on that.

So it works as intended currently ..
