### ISSUE TITLE
[RPC][documentation] Missing documentation for "language" parameter

### ISSUE THREAD

**Issue by tkotosz** [phpactor/phpactor#1030]
It seems some commands like `goto_definition` has a language parameter which need to be provided otherwise it defaults to php.

For example this is needed for the [behat-extension](https://github.com/phpactor/behat-extension) otherwise it will do nothing.

**Comment by tkotosz** [comment]
Relevant part of the behat extension: https://github.com/phpactor/behat-extension/blob/master/lib/ReferenceFinder/StepDefinitionLocator.php#L40

**Comment by dantleech** [comment]
I think ultimately we should provide generated documentation for all this: https://github.com/phpactor/phpactor/issues/1032

**Comment by tkotosz** [comment]
Make sense :+1:
