### ISSUE TITLE
0.15.0 neovim ncm2 plugin class autocomplete stopped working

### ISSUE THREAD

**Issue by nacholibre** [phpactor/phpactor#1044]
Hi all,

first thanks for your work, with phpactor, ncm2 and ncm2-phpactor my neovim php autocomplete is the best I've ever had. 

Last week I've updated from 0.14.0 to 0.15.0 and I've noticed one issue, the class completion stopped working.

Example:
Let's say I want to inject dependency into class constructor, when I start typing the class name the autocomplete engine suggests a class
<img width="694" alt="Screenshot 2020-05-09 at 14 03 25" src="https://user-images.githubusercontent.com/1738437/81471996-e00e2c00-91fd-11ea-8282-b7d3ead53f9d.png">

With the new 0.15.0 release this doesn't work. I didn't find any other issues with the autocomplete.

**Comment by indeedhat** [comment]
I am having a lot of issues with completion hints in v0.15 with both the master and develop branches.

I am finding that i get very few completion options. most methods, virtual properties and constants just dont show up.

If i start typing the name of a member then leave and reenter insert mode the list will display the proper hints as would be shown in 0.14.x. Interestingly if i then delete the member part back to -> or :: i get the original limited list of hints again.

```php
// STEP 1
// in both these cases i get a very limited list of completion options
$thiis->|
ClassName::|

// STEP 2
// at this point i will still get very limited options
$this->prop|
ClassName::CONST|
// if i then hit esc, a to leave and reenter insert mode i will get the expected completion options
// for the given member

// STEP 3
// if while staying in insert mode i backspace to the original example my new completion options will dissapear
// i get the same options as in the first case and would have to go through the steps 1 and 2 to get my expected options again
$thiis->|
ClassName::|
```
Sorry if this is a bit confusing, ive done my best to explain but im not sure how clear it is

I dont get any of these options pre v0.15.0 so i have just reverted to 0.14.1 for now

**Comment by dantleech** [comment]
can you try increasing the `completion.limit` setting from the default `32` to something greater?

For example in `.phpactor.json` in your project root:

```
{
    "completion.limit": 32
}
```

Could be similar to #1057

**Comment by indeedhat** [comment]
That did the trick, i stupidly assumed that the completion limit was off by default when i first read the release notes and it never occurred to me to try upping the limit.

Thanks

**Comment by dantleech** [comment]
ok, it's too low by default (or maybe it should be disabled) it was put there to increase LSP completion, but has unintended side-effects. Will see about fixing it.

**Comment by indeedhat** [comment]
It for sure makes sense when using a language server, im just still using ncm2 cos i have been too lazy to update, i might give the language server approach a go

**Comment by dantleech** [comment]
I don't think the completion experience as good as NCM2 yet .,.. but for sure give it a go :)

**Comment by dantleech** [comment]
I've removed the limit in develop which should be released in 10 days or so ... :crossed_fingers:
