### ISSUE TITLE
[WR] Construtor property inference

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1046]
This feature was removed due to implementation problems (infinite loop in constructor when trying to infer porperty type of a consturctor property which references a previous property).

Add this feature in a way that doesn't break (maybe as a frame walker).

**Comment by mamazu** [comment]
What is this ticket about inferring which properties need to be set in the constructor? Don't we have a "generate constructor" now?

**Comment by dantleech** [comment]
This is about inferring the type of a property based on the type provided in the constructor - i.e. avoiding the need to `@var Foo`.  So less useful now.
