### ISSUE TITLE
Phpactor requires at least PHP 7.3.0

### ISSUE THREAD

**Issue by lukepass** [phpactor/phpactor#1052]
After a plugin update I am now receiving this error, how can I downgrade it to work with PHP 7.2?

`Phpactor returned an error: Phpactor requires at least PHP 7.3.0`

This is my `.vimrc`:

```
" https://phpactor.github.io/phpactor/vim-plugin.html
Plug 'phpactor/phpactor', { 'for': 'php', 'do': 'composer install --no-dev -o' }
Plug 'kristijanhusak/deoplete-phpactor'
```

Thanks.

**Comment by lukepass** [comment]
After a bit or trial and error I was able to restore a working version with this:

```
" https://phpactor.github.io/phpactor/vim-plugin.html
Plug 'phpactor/phpactor', { 'for': 'php', 'do': 'composer install --no-dev -o', 'tag': '0.13.5' }
Plug 'kristijanhusak/deoplete-phpactor'
```

I deleted the vim-plug folder and called `:PlugUpdate`.

**Comment by lukepass** [comment]
Unfortunately I can't update my PHP version right now, since I have a lot of projects using 7.2 :(
Where can I find indications about specifying a version in `:help phpactor`?

Thanks!

**Comment by dantleech** [comment]
https://phpactor.readthedocs.io/en/master/vim-plugin/man.html

The setting is `g:phpactorPhpBin`

**Comment by dantleech** [comment]
I updated the trouble shooting section: https://phpactor.readthedocs.io/en/master/usage/vim-plugin.html#phpactor-requires-at-least-php-7-3-0

**Comment by adovbos** [comment]
`let g:phpactorPhpBin = "/usr/bin/php7.3"` Not worked for me... Only after changing alternatives php to php7.3 worked

**Comment by dantleech** [comment]
Using language server or RPC client?

**Comment by adovbos** [comment]
TY for quick response. Using vim plugin in Neovim. Tried to echo g:phpactorPhpBin and it show /usr/bin/php7.3, so variable is set, any ideas how I can debug it?

**Comment by dantleech** [comment]
I wonder you are setting it after Phpactor loads? that's the only thing I can think of. I am setting it in `.vimrc` after `call plug#end()` if that makes any sense.

The value is read here:

https://github.com/phpactor/phpactor/blob/c2b3405ce5afc4e395ee2863a938dd3953f67c36/plugin/phpactor.vim#L15

**Comment by adovbos** [comment]
Ok, so problem was not in executing g:phpactorPhpBin, as it turns out... auto-complition works, but in command :PhpactorStatus that use
https://github.com/phpactor/phpactor/blob/c2b3405ce5afc4e395ee2863a938dd3953f67c36/autoload/phpactor.vim#L307
So it will launch it with php that is default. BTW sorry for my eng and thank you for support

**Comment by dantleech** [comment]
so it's launching `phpactor` in the global path? that's bad - bug then :+1:  thanks

**Comment by dantleech** [comment]
created https://github.com/phpactor/phpactor/issues/1073
