### ISSUE TITLE
[autocomplete] can't find string method

### ISSUE THREAD

**Issue by ftamhar** [phpactor/phpactor#1057]
I use laravel framework.
When I created the database: migrations, I did not find the **string method** in auto-complete.

I use "normal" RPC

![string](https://user-images.githubusercontent.com/24367921/82216036-e5305100-994a-11ea-8c08-8287f0ea050e.gif)

**Comment by dantleech** [comment]
Can you link to, or show, the Blueprint class?

**Comment by ftamhar** [comment]
here it is
[string](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Schema/Blueprint.php#L653)

**Comment by dantleech** [comment]
ok, looks like that class has lots of methods! try changing `completion.limit: 32` in your `.phpactor.json` (file)

**Comment by ftamhar** [comment]
in [this](https://github.com/phpactor/phpactor/blob/develop/config/packages/phpactor.json) file like this ?
```json
{
  "name": "phpactor/phpactor",
  "type": "package",
  "args": {
    "url": "git@github.com:phpactor/phpactor"
  },
  "vars": {
    "version": "0.13.0"
  },
  "completion": {
    "limit": 32
  }
}
```

**Comment by dantleech** [comment]
No -- that's a different thing :)

You need to create a `phpactor.json` configuration file, either locally (in the project root) or [globally](https://phpactor.readthedocs.io/en/develop/usage/configuration.htmlhttps://phpactor.readthedocs.io/en/develop/usage/configuration.html) with something like:
```
{
    "completion.limit":  1000
}
```

in `/project/root/.phpactor.json` or the global config file in the link above.
