### ISSUE TITLE
Nvim commands don't work

### ISSUE THREAD

**Issue by vaklinzi** [phpactor/phpactor#1061]
I have phpactor installed with composer globally and within vim with:
Plug 'phpactor/phpactor', {'for': 'php', 'branch': 'master', 'do': 'composer install --no-dev -o'} 

```
" init.vim
let g:phpactor_executable = '~/.config/nvim/plugged/phpactor/bin/phpactor'
let g:phpactorPhpBin = "/usr/local/bin/php"
```

:PlugInstall
I also tried with `develop` but the result is the same. I also tried running `composer install` from plugged folder although I didn't have any errors with PlugInstall but still all the commands from within vim don't work. I have almost the same error with every command:

![image](https://user-images.githubusercontent.com/16841490/82888673-4d39f500-9f52-11ea-8070-74e59fe9fa45.png)

I am with the latest version of neovim.
On MacOs Catalina
```
$ php -v
PHP 7.3.18 (cli) (built: May 14 2020 10:54:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.18, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.18, Copyright (c) 1999-2018, by Zend Technologies
```

I also tried to replay the issue from Vim commands with `phpactor rpc --replay --verbose
` but /.cache/phpactor/replay.json is empty. All the commands from cli are working properly but inside vim nothing works, even the autocompletion is trowing errors.

**Comment by dantleech** [comment]
Did you open a PHP file before doing this?

**Comment by dantleech** [comment]
So, if assume that VIM isn't lying and the variable `g:phpactorInitialCwd` isn't defined, then it implies that this file has not been loaded: https://github.com/phpactor/phpactor/blob/9cdd21cd47c950b0f2644005007ccae23f15bfbf/plugin/phpactor.vim#L10

**Comment by vaklinzi** [comment]
Yes, I opened my PHP project and tried to import a missing class. After that I tried the others commands but they have the same error. 

![image](https://user-images.githubusercontent.com/16841490/82892840-d9e7b180-9f58-11ea-9725-b2b115dc37ed.png)

**Comment by vaklinzi** [comment]
@dantleech so I should add `let g:phpactorInitialCwd = getcwd()` in my init.vim?

**Comment by dantleech** [comment]
No - it would be very strange -- does your CWD / project root path have spaces in it?

**Comment by vaklinzi** [comment]
Nope, no spaces in the path.

**Comment by dantleech** [comment]
```
 echo '{"action":"echo","parameters":{"message":"Hello"}}' | phpactor rpc
```
?

although seems like the message isn't even getting to Phpactor.

**Comment by vaklinzi** [comment]
![image](https://user-images.githubusercontent.com/16841490/82894675-a0fd0c00-9f5b-11ea-8bbd-6256c8425754.png)

**Comment by dantleech** [comment]
So VIM isn't sending the message to the process at all.

Similar to this unresolved issue: https://github.com/phpactor/phpactor/issues/934

Are you using VIM or Neovim?

**Comment by vaklinzi** [comment]
I am using the latest version of neovim.

![image](https://user-images.githubusercontent.com/16841490/82895171-7495bf80-9f5c-11ea-880a-c5bafaad7cc2.png)

**Comment by vaklinzi** [comment]
I even do not have this option from the other issue:

![image](https://user-images.githubusercontent.com/16841490/82895311-b161b680-9f5c-11ea-8d6f-5ea716ca889b.png)

![image](https://user-images.githubusercontent.com/16841490/82895373-cc342b00-9f5c-11ea-9186-662bf6635a9e.png)

**Comment by dantleech** [comment]
Ah OK - in that other PR the fix I suggested made it work in Neovim - but it was never comitted to master.

Can you try: https://github.com/phpactor/phpactor/pull/1062 before I merge it?

**Comment by vaklinzi** [comment]
It doesn't work... the same error :( What I did:
1. Deleted the plugged/phpactor
2. Added `Plug 'phpactor/phpactor', {'for': 'php', 'branch': 'master-list-system', 'do': 'composer install --no-dev -o'}` using this branch you mentioned `master-list-system`.
3. :PlugInstall (no errors, showing installing all the dependencies)
4. Opened my project
5. :PhpactorImportClass
6. The same error as before.

I tried this on vim, nvim & macvim all report the same error.

**Comment by vaklinzi** [comment]
I also tried to manually change the `cmd` variable as suggested in the other issue with:
![image](https://user-images.githubusercontent.com/16841490/82897271-0f43cd80-9f60-11ea-909e-c17d2afd241d.png)

but still the same error

**Comment by vaklinzi** [comment]
https://recordit.co/pmt8fN2PCE

**Comment by dantleech** [comment]
I'm not sure what else to suggest - its very strange.

You could in the meantime switch to using CoC and the langauge server (which supports auto-class import at least). It doesn't support the refactorings yet - but it will come in the next months.

**Comment by vaklinzi** [comment]
@dantleech Thank you very much for your time and effort. I appreciate it. Will be happy to use Phpactor when the issue is fixed.

**Comment by vaklinzi** [comment]
@dantleech I started debugging every variable in this line:
`let cmd = [g:phpactorPhpBin , g:phpactorbinpath,'rpc','--working-dir=' . g:phpactorInitialCwd]`
and it looks like `g:phpactorbinpath` is undefined or empty. Could please tell me what are the expected values here for these variables. I would like to hardcode every one with the expected values and see whether the issue will be fixed:
`let cmd = ["php" , "~/.config/nvim/plugged/phpactor/bin/phpactor",'rpc','--working-dir=' . "path/to/my_project"]` Are these valid values?

**Comment by vaklinzi** [comment]
@dantleech I am happy to say that I manage to resolve the issue bye trying to install phpactor with Vundle instead with vim-plug and it works like a charm. Now I have three times more options than before including the missing :PhpactorStatus. Everything works so nice! Thank so much for the effort and the fast response and to all your team for the great job. I am so happy to use it now. Good luck and keep the great work!

**Comment by dantleech** [comment]
Thanks for the support :) Although why it works on Vundle and not Plug raises more questions :thinking:  (I used vim plug)

**Comment by dantleech** [comment]
Also if `:PhpactorStatus` wasn't available but the other commands were - then it indicates that the `ftplugin` was loaded, but the `plugin` wasn't.

**Comment by dantleech** [comment]
Maybe https://github.com/junegunn/vim-plug/issues/519#issuecomment-245915714 ?

**Comment by elythyr** [comment]
I never used this plugin manager I think so I don't even know how it works.
As long as the `runtimepath` option is properly configured by the plugin manager it should work.
It's not even about phpactor but about vim/neovim way of loading any `*.vim` from within the runtimepath...

I would suggest to start using the `package` feature of both vim and neovim, it was introduced a while ago and basically remove the need for a package manager tweaking into our options like `runtimepath`.
You basically just need a package manager to update every plugins at once and that's it, no need to start it everytime you open vim/neovim.
By reducing the complexity you also reduce the risks of problems.

**Comment by przepompownia** [comment]
Maybe some information from `:help load-plugins` could be useful to investigate why ftplugins from runtimepath are loaded but plugins not. 

After abandoning `vim-pathogen` I switched to using each extension as an optional package kept on one pack directory as git submodule. Submodules are easy to upgrade all at once. Optional (`opt`) packages are loaded separately by `packadd` to allow exclude some of them for example for debug puropses. 

Some configuration defined before loading extension (especially in vimrc) may be owerwritten if such extension is badly written and require to be loaded later (e.g. by `autoload vimInit`).

**Comment by vaklinzi** [comment]
@elythyr @przepompownia After your comments I decided to try to remove both managers (vim-plug & vundle) and use the default with neovim/vim8. After watching http://vimcasts.org/episodes/minpac/ I decided to use minpack. Why?
1. It uses the default built in vim manager.
2. It's fast and clean - it's a thin layer over default manager just to make cloning and adding to the right folder for you.

With it phpactor works also as expected. I had some others problems with vim-plug, so maybe it's just vim-plug error while conflicting with some of my other plugins. I think you can calmly close the issue as maybe it's something with mine configuration.

**Comment by dantleech** [comment]
Thanks, still very odd that it doesn't work with VIM plugin, we can keep an eye on it and remember this issue :)

**Comment by elythyr** [comment]
@vaklinzi Another alternative is https://github.com/kristijanhusak/vim-packager, it works exactly the same way as minpac the migration is therefore extremely easy.
It brings one additional feature (at least for my use) which is a nice vertical split showing you what is going on during operations.
You can even take a look at the output of each commands to see what was going wrong and stuff like that.

Also another point worth noticing with the optional packages mentioned by @przepompownia, they don't work the same way as packages located in the `start` directory.
One issue we got here was that when you manually load a package with `packadd` you are actually doing it after the filetype was resolved and `FileType` event emitted, so `ftplugin` are not loaded properly (I guess the same goes for syntax and stuff).

**Comment by vaklinzi** [comment]
@elythyr thank you for the suggestion. vim-packager is really nice. Showing the output of the installation is really nice and I migrated all my plugins to it.

**Comment by vaklinzi** [comment]
@dantleech @elythyr @przepompownia Guys, I found how to make it work with plug. The only solution was to set `call plug#begin('~/.config/nvim')` instead `call plug#begin('~/.config/nvim/plugged')`. I hope that can be helpful for you :)

**Comment by dantleech** [comment]
Thanks for updating - mine is actually `~/.vim/plugged` I guess it can vary, good to know for the future :)

**Comment by vaklinzi** [comment]
@dantleech I also tried with `~/.vim/plugged` and it doesn't work. Looks like `plugged` is the reason but don't know why.
