### ISSUE TITLE
:PhpactorStatus doesn't use the bin path

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1073]
`:PhpactorStatus` shows the status in the `term://` in neovim, however it does not use the `php` bin path, which means it doesn't work for anybody that actually runs < php 7.3 by default.

And possibly - it's using `phpactor` only if it's in the global path?

cc @elythyr

**Comment by elythyr** [comment]
I'll take care of this issue next, but I might not have the time before the next week-end

Is it related to #1085 ?
I will take a closer look when fixing this ticket to be sure we use the proper working directory.
