### ISSUE TITLE
Key(s) are not known

### ISSUE THREAD

**Issue by plateena** [phpactor/phpactor#1084]
I got an error when running phpactor

> In Resolver.php line 92:

> `Key(s) "code_transform.fixer.indentation", "code_transform.fixer.member_newlines", "code_transform.fixer.tolerance" are not known, known keys: "console_dumper_default", "xdebug_disable", "command", "class_to_file.project_root", "code_transform.class_new.variants", "code_transform.template_paths", "code_transform.indentation", "code_transform.refactor.generate_accessor.prefix", "code_  
  transform.refactor.generate_accessor.upper_case_first", "completion_worse.completor.class.limit", "completion_worse.disabled_completors", "completion.dedupe", "completion.dedupe_match_short_des  
  cription", "completion.limit", "navigator.destinations", "navigator.autocreate", "rpc.store_replay", "rpc.replay_path", "source_code_filesystem.project_root", "worse_reflection.enable_cache", "  
  worse_reflection.cache_lifetime", "worse_reflection.enable_context_location", "worse_reflection.cache_dir", "worse_reflection.stub_dir", "file_path_resolver.project_root", "file_path_resolver.a  
  pp_name", "file_path_resolver.application_root", "file_path_resolver.enable_cache", "file_path_resolver.enable_logging", "logging.enabled", "logging.fingers_crossed", "logging.path", "logging.l  
  evel", "logger.name", "logging.formatter", "composer.enable", "composer.autoloader_path", "composer.autoload_deregister", "console.verbosity", "console.decorated", "extension_manager.extension_  
  vendor_dir", "extension_manager.vendor_dir", "extension_manager.config_path", "extension_manager.extension_list_path", "extension_manager.root_package_name", "extension_manager.minimum_stabilit  
  y", "extension_manager.repositories", "extension_manager.quiet", "worse_reference_finder.plain_text_break_chars", "php.version", "language_server.client_capabilities", "language_server.enable_w  
  orkspace", "language_server.session_parameters", "language_server_completion.trim_leading_dollar", "language_server_reference_reference_finder.reference_timeout", "indexer.enabled_watchers", "i  
  ndexer.index_path", "indexer.include_patterns", "indexer.exclude_patterns", "indexer.poll_time", "indexer.buffer_time", "indexer.project_root", "indexer.reference_finder.deep", "indexer.impleme  
  ntation_finder.deep", "container.extension_classes", "extension_manager.extension_vendor_dir", "extension_manager.vendor_dir", "extension_manager.config_path", "extension_manager.extension_list  
  _path"`

I'm installing phpactor as global in Ubuntu 20.04 to use in the CoC but got the error above. Please help me.

**Comment by dantleech** [comment]
That's very strange. Can you explain how you are installing Phpactor?

**Comment by plateena** [comment]
Clone the repo.

run composer install

then run  ./phpactor

**Comment by dantleech** [comment]
hmm, i've just done:
```
git clone git@github.com:phpactor/phpactor
composer install
./bin/phpactor status
Version: 8643fe6 (3 days ago) phpactor-code-transform-13efb324.76130fa3
Filesystems: git, simple, composer
Working directory: /home/daniel/tmp/phpactor

Config files (missing is not bad):

  ✘ /home/daniel/.config/phpactor/phpactor.json
  ✔ /home/daniel/.config/phpactor/phpactor.yml
  ✘ /home/daniel/tmp/phpactor/.phpactor.json
  ✘ /home/daniel/tmp/phpactor/.phpactor.yml

Diagnostics:

  ✔ Composer detected - Phpactor could work faster without an index
  ✔ Git detected - enables faster refactorings in your repository scope!
  ✔ XDebug is disabled. XDebug has a negative effect on performance.
```

**Comment by plateena** [comment]
I don't know what's wrong. This is the error

![image](https://user-images.githubusercontent.com/11329461/86610162-83ea3d00-bfdf-11ea-9e8a-8b082df50f70.png)

**Comment by dantleech** [comment]
hmm, the "unknown" configuration keys are from a previous, unreleased, version of `phpactor/code-transform-extension`.

can you do 

```
$ composer show | grep code-transform-extension
```
it should show:

```
phpactor/code-transform-extension            0.2.0             Code transform base package
```

**Comment by dantleech** [comment]
Finally maybe you can see which config files phpactor loads:

```
strace  ./bin/phpactor status -vvv 2>&1 | grep openat | egrep "phpactor.(yml|json)" 
```

**Comment by plateena** [comment]
Thanks for your help.
Phpactor did use config from somewhere else.

![image](https://user-images.githubusercontent.com/11329461/86684312-02bd9500-c035-11ea-8bae-120e6e5b4bdb.png)

Removing the phpactor.json then it works.
