### ISSUE TITLE
fileToClassCandidates() does not operate on phar:// paths

### ISSUE THREAD

**Issue by rquadling** [phpactor/phpactor#1086]
My use case is that I have a library that allows command line application construction using Symfony Console, wrap it up in a phar file and then allows me to distribute the file.

So the usual way this is used is a project is started, my library is imported, a small bootstrap file is created, a load of Symfony Command classes are defined, package it all up into a phar and it all works (more or less).

Works fine for non-phar setup.

In a phar, the `\Phpactor\ClassFileConverter\Adapter\Composer\ComposerFileToClass::fileToClassCandidates()` method throws an exception that the supplied path is not absolute, based upon the a check of the first character being a `'/'` (side note, will that work on Windows?).

But, simply changing the test to:
```php
        if (false === $filePath->isAbsolute() && 0 !== strpos($filePath, 'phar://')) {
            throw new \InvalidArgumentException(sprintf(
                'Path must be absolute or based within a PHAR archive'
            ));
        }
```

And everything is working again. The entries in the composer files in the vendor directory inside the phar archive have the 
`phar://` prefix to their various maps (hacked in a var_dump in my init() method for calls .

I'm using https://github.com/humbug/box as my phar creator.

As I've only just started with phar, I'm not sure I can easily produce a pull request with tests for this.

But hopefully someone else can build one.

_(This issue is in this project as the project https://github.com/phpactor/class-to-file does not allow any issues to be raised.)_

**Comment by dantleech** [comment]
Funny, I was looking at path issues today for Windows compatibility.

I've just pushed a fix to use webmozart `Path::isAbsolute` instead of the simple check, can you verify if it works?

**Comment by rquadling** [comment]
Brilliant!!! Rebuilt box with your amended code and all working.

Thank you very much!

**Comment by rquadling** [comment]
What's the timescale for a new release?

**Comment by dantleech** [comment]
Just tagged 0.3.4 :)
