### ISSUE TITLE
Sugestion using __get and __set

### ISSUE THREAD

**Issue by phaalonso** [phpactor/phpactor#1093]
When using phpactor there isn't a suggestion for my atributes when using __get or __set

![image](https://user-images.githubusercontent.com/26033899/89733678-8f40e600-da2d-11ea-9fcd-472503cbad04.png)

How I can fix this, or there is a workarround?

**Comment by dantleech** [comment]
You can/should add ”@method" annotations to your class. Should work then, otherwise think there might be an improvement for this us "develop"

**Comment by phaalonso** [comment]
Thanks, I will try use the annotation. I have thinking about the possibility of suggesting by default the attributes of the class. This can cause some problems but it will be good to have a option to enable it.

**Comment by dantleech** [comment]
Might be possible if Phpactor is very clever, I don't think Phpstorm could help here either (?)

**Comment by dantleech** [comment]
But the general ly accepted way to do this is with the annotation AFAIK

**Comment by indeedhat** [comment]
If im reading this right you want to have suggestions for your private props ($name/$email) when using the magic methods?!

if that is the case then its the `@property [type] $varName` annotation that you want. I can also confirm from a guy on out team this is necessary within phpactor to get auto completion.

**Comment by phaalonso** [comment]
Thanks for the help, adding the property did the trick!
[Here some tip if someone have the same problem in the future](https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.property.pkg.html)
```php
/**
 * show off @property, @property-read, @property-write
 *
 * @property mixed $regular regular read/write property
 * @property-read int $foo the foo prop
 * @property-write string $bar the bar prop
 */
class Magician {
	private $_thingy;
	private $_bar;

	function __get($var) {
		switch ($var) {
			case 'foo' :
				return 45;
			case 'regular' :
				return $this->_thingy;
		}}

	function __set($var, $val) {
		switch ($var) {
			case 'bar' :
				$this->_bar = $val;
				break;
			case 'regular' :
				if (is_string($val)) {
					$this->_thingy = $val;
				}
		}
	}
}

```

**Comment by dantleech** [comment]
Glad you got it working, I'm surpised if `@property-write` and `@property-read` work though, if they do it's a "bug" :laughing:
