### ISSUE TITLE
Erromessage in phpactor.log every second

### ISSUE THREAD

**Issue by gvanbeck** [phpactor/phpactor#1102]
It happens on MacOS
`[2020-09-17 08:37:24] phpactor.ERROR: Process "'find' '/Users/XXXXXXXXX/XXXXXXX/XXXXXXX' '-mindepth' '1' '-newerct' '2020-09-17 08:37:19.906458'" exited with error code 1: find: Can't parse date/time: 2020-09-17 08:37:19.906458  [] []`

it is temporary fixed by remofing the `.u` in the formatting
`https://github.com/phpactor/phpactor/blob/d49b1b6e06f45337166c865d8ca5fcd828ada6f6/vendor/phpactor/amp-fswatch/src/Watcher/Find/FindWatcher.php#L177`

**Comment by dantleech** [comment]
I've updated the library to be compatible (:crossed_fingers: ) with the BSD variant of `find`, could you try updating?

https://github.com/phpactor/amp-fswatch/pull/7

**Comment by elythyr** [comment]
@gvanbeck can we have an update on the issue please ?

**Comment by dantleech** [comment]
@gvanbeck updated in Slack and confirmed it to be working IIRC. Closing.
