### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by araujo0205** [phpactor/phpactor#1110]
Hello, 
I installed in vim base on this [link](https://phpactor.readthedocs.io/en/master/usage/vim-plugin.html)
After plug installed, I open a php file and execute `:PhpactorStatus`. But return this error:
```
executing job failed: No such file or directory
```
Any suggestions ?

I using Mac 10.15.7 and my vim is
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct  7 2020 23:36:35) instaled by homebrew.

**Comment by elythyr** [comment]
There is a bug on the command `:PhpactorStatus` at the time, can you try to execute this commande instead: `:call phpactor#rpc("status", {'type': 'formatted'})`

**Comment by araujo0205** [comment]
Thanks, this work for me.

**Comment by elythyr** [comment]
Great, can you close the issue then please ?

**Comment by araujo0205** [comment]
is good update the docs with the new command ?

**Comment by dantleech** [comment]
hmm, not sure we should close this. `:PhpactorStatus` should work. Probably we should revert the `terminal` change (sure we had a ticket about that somewhere)

**Comment by elythyr** [comment]
Yes we have, I will take care of it this week-end.

**Comment by elythyr** [comment]
Fix merged, we can close.
