### ISSUE TITLE
[Regression] Inferred types

### ISSUE THREAD

**Issue by elythyr** [phpactor/phpactor#1126]
I forgot that I had found a regression, I reproduced it today so I put an example here in order to not forget to fix it:
```php
<?php

namespace Test;

interface Foo
{
}

class FooBar implements Foo
{
}

class Bar
{
    private Foo $foo;

    public function __construct(Foo $foo)
    {
        $this->foo = $foo;
    }

    public function foo(): void
    {
        if (!$this->foo instanceof FooBar) {
            return;
        }

        // $this is now inferred as FooBar
    }
}
```

It's all in the comment, kind of really annoying :smile:

**Comment by dantleech** [comment]
Regression or bug? I don't think we did anything to change this behavior?

**Comment by elythyr** [comment]
For me it's a regression, I don't remember ever having this problem (except the previous time I mentioned but I didn't created the ticket right away).

**Comment by dantleech** [comment]
AFAIK this would always been the case, we don't track property types currently: https://github.com/phpactor/worse-reflection/blob/360a923947ac2c4646e81ebd12fa2d2391c94830/lib/Core/Inference/FrameBuilder/InstanceOfWalker.php#L18

The whole inference thing is a bit of a mess.

**Comment by elythyr** [comment]
I'm surprise I never had this issue before ><
I will finishing with https://github.com/phpactor/indexer-extension/pull/24#issuecomment-723561192 and try to fix this one next
