### ISSUE TITLE
phpactor + coc ,  autocompletion adds an additional `$` 

### ISSUE THREAD

**Issue by allan-simon** [phpactor/phpactor#1132]
my version of Phpactor :

Version: 7f73078 (9 days ago) Updated-CHANGELOG
also reproduced on Version: f12e272 (2 days ago) 2020-11-22-1131

my init.vim (I did it on a virtual machine)

```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'phpactor/phpactor', {'for': 'php', 'branch': 'develop', 'do': 'composer install --no-dev -o'}

call plug#end()

```

steps to reproduce

create a file `toto.php` 

```php
<?php

$toto = "";

$t<>
```
(with the cursor symbolized by `<>` ) now just after I've pressed the `t` I have this :+1: 
![Selection_298](https://user-images.githubusercontent.com/213167/100195673-fb215e80-2ef7-11eb-8223-e6a02f38f615.png)

If I select the toto from LS  I got the extra $ who appears 
![Selection_299](https://user-images.githubusercontent.com/213167/100195743-142a0f80-2ef8-11eb-848d-26d831dced40.png)

**Comment by dantleech** [comment]
See https://phpactor.readthedocs.io/en/develop/lsp/vim.html#two-dollars-on-variables it may be that this setting is has the wrong default, but closing this for now, feel free to discuss though.

**Comment by allan-simon** [comment]
indeed that fix this :)
