### ISSUE TITLE
Conflict with projects using thecodingmachine/safe

### ISSUE THREAD

**Issue by afranioce** [phpactor/phpactor#1133]
Projects using magento2 broken index because use [thecodingmachine/safe](https://github.com/thecodingmachine/safe) package
Manual index
![image](https://user-images.githubusercontent.com/893768/100526556-a48e7b80-31a8-11eb-9df3-c1fdaff50331.png)

Coc index
![image](https://user-images.githubusercontent.com/893768/100526594-0fd84d80-31a9-11eb-9910-f94638281b01.png)

**Comment by dantleech** [comment]
yes - this has been fixed in `develop` I think (we no longer include the composer autoloader directly).

**Comment by afranioce** [comment]
Thanks, the issue has fixed using develop branch.

**Comment by dantleech** [comment]
Great - will see if we can tag version 17 next weekend.
