### ISSUE TITLE
PHP 8.0 Language Support

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1135]
PHP 8 support falls into two separate categories:

- [x] Ensuring that all packages support 8.0 and Phpactor can be composer-installed in a PHP 8.0 environment
- [x] Adding support for language features

### Constructor promotion

**Status**: :heavy_check_mark: : Supported https://github.com/phpactor/worse-reflection/pull/77

- Detect properties established via. constructor promotion

Complexity: This should be possible in WorseReflection only and be relatively easy.
Urgency: High

### Named Parameters

**Status**: :heavy_check_mark: : Supported pending PR

https://github.com/phpactor/completion/pull/39

### Mixed type

**Status**: :heavy_check_mark: Fixed in tolerant PHP parser (pending confirmation)

https://github.com/microsoft/tolerant-php-parser/pull/350/files

`mixed` is now a built-in type and needs to be ignored in worse reflection

### Union Types

**Status**: :heavy_check_mark: :  Partially supported as far as possible without rewriting the type system :  https://github.com/phpactor/worse-reflection/pull/78

Given a union type, Phpactor will currently only understand the first one.

I think Phpactor currently supports Union types in docblocks to some extent, so
should be easy to implement this.

Complexity: WorseReflection probably easy.
Urgency: Medium

### Nullsafe Operator

**Status**: Supported

This seems to work without modification

### Attributes

**Status**: Kinda working

Class completion works in attributes (as it's just another qualified name), but we could additionally filter by
classes with the `#[Attribute]` attribute (in the same way we filter for
`@Annotation` annotations).

Complexity: `completion` library only - probably need to prevent the class completor for completing in Attributes, and have a dedicated Attribute completor which only lists valid attributes.

### Static return type

**Status**: Not supported

Although supported in annotations, the static return type is not understood (but `self` is).

Complexity: WorseReflection - the `self` / `static` for docblocks is not working already (both return `self` I think). So adding at least that same level of brokenness should be easy.
Urgency: Medium

### Throw Expression and Match

**Status**: Not supported

The throw expression can be used to control flow and therefore determine types, e.g.

```php
match ($class) {
    $class instanceof Foo => 'one',
    $class instanceof Bar => 'bar',
    default throw new Exception('asd');
}

// $class is instanceof Foo|Bar
```
This example is contrived - and may or not be something that is easy to implement - but there are likely other situations where the throw expression needs to be handled.

Complexity: Medium - WorseReflection - the `ExpressionBuilder` will need to understand `match` statements and the new throw expression.
Urgency: Low

**Comment by NielsCorneille** [comment]
Does "Supported" also mean supported in the language server? 
Or should that be tracked and worked on in an issue in the phpactor/languague-server repository??

**Comment by dantleech** [comment]
Yeah - this applies to the whole of Phpactor, so any issues should be raised on this repo.

**Comment by dantleech** [comment]
PHP 8 support is good enough.
