### ISSUE TITLE
RPC Open File regression via. #987

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1136]
Introduced in https://github.com/phpactor/phpactor/pull/987

When using `:PhpactorNavigate` we get the following error:

![image](https://user-images.githubusercontent.com/530801/100715149-ade93500-33ae-11eb-9391-0fd4e8a64460.png)

Due to the `Phpactor\Extension\Rpc\Response\OpenFileResponse`:

```
    const TARGET_FOCUSED_WINDOW = 'focused_window';
    const TARGET_VERTICAL_SPLIT = 'vsplit';
    const TARGET_HORIZONTAL_SPLIT = 'hsplit';
    const TARGET_NEW_TAB = 'new_tab';

```

Updating the targets however causes another problem:

```
Error detected while processing function phpactor#Navigate[1]..phpactor#rpc[24]..phpactor#_rpc_dispatch[124]..phpactor#_rpc_dispatch_input[43]..phpactor#input#choice[30]..phpactor#_rpc_dispatc
h_input_handler[3]..phpactor#rpc[24]..phpactor#_rpc_dispatch[56]..<SNR>164_openFileInSelectedTarget:
line   24:
E481: No range allowed: 0 edit spec/xxx/Bundle/StoreBundle/Mailer/Sender/SenderSpec.php
Error detected while processing function phpactor#Navigate[1]..phpactor#rpc:
line   24:
E171: Missing :endif
```

**Comment by dantleech** [comment]
cc @camilledejoye

**Comment by camilledejoye** [comment]
I'll try to look into it today

**Comment by dantleech** [comment]
cool thanks, if you don't get a chance today I'll try and investigate myself or revert the PR temporarily
