### ISSUE TITLE
Full Refactoring Support for Language Server

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1140]
I am not sure if I will have the time, but still, somebody might if I can't, so...

### How can we enable all the refactorings for VS Code? 
I mean in terms of calling Phpactor (I can research the corresponding code for VS Code). I noticed some of them are available on the command line while others seem to be more tricky to invoke and are available only in VIM. 

Considering how few tools do refactoring for PHP (I found only this one), even slow implementation should be better than nothing.

**Comment by dantleech** [comment]
The other actions are available contextually - e.g. 

```
class F
{
    public function __contsruct(string $arg)
    {
    }
}
```

then you should get code action for complete constructor

**Comment by BladeMF** [comment]
Bloody hell! I am missing this *so badly* in Symfony! This made my entire month!

**Comment by dantleech** [comment]
Maybe worth builidng a table listing the available refactorings from the docs and the ones missing from the language server? Could then pin this one.

**Comment by BladeMF** [comment]
Can you give an example of such table?

**Comment by dantleech** [comment]
Done https://github.com/phpactor/phpactor/issues/1184
