### ISSUE TITLE
Implement contracts omits arguments in some cases

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1141]
The test case is as follows (There are more, but this is the only case I managed to reproduce 100% of the time):

1. There are a class and a namespace:
![image](https://user-images.githubusercontent.com/12109622/102014788-768c6800-3d60-11eb-8354-f01bc5ab8b19.png)
![image](https://user-images.githubusercontent.com/12109622/102014791-7c824900-3d60-11eb-95a3-a30a53a1f0be.png)

2. Add a method to the namespace:
![image](https://user-images.githubusercontent.com/12109622/102014799-86a44780-3d60-11eb-9f2f-d762d32e6417.png)

3. Go to the class and invoke "Implement contracts". You get this:
![image](https://user-images.githubusercontent.com/12109622/102014814-9cb20800-3d60-11eb-9b07-f35da6b4ac9d.png)

4. Clone the method in the interface
![image](https://user-images.githubusercontent.com/12109622/102014821-acc9e780-3d60-11eb-8de0-537c17a5722a.png)

5. Invoke "Implement contracts" again and you get this:
![image](https://user-images.githubusercontent.com/12109622/102015021-98d2b580-3d61-11eb-9695-6be0e7cd7ffe.png)

The context is VS Code. It would seem there is some sort of a delay involved here since it seems to depend how quickly I invoke step 5. Also, when resetting the case it would sometimes implement an older version of the interface (just before the last edit). So probably it's a matter of waiting, but just saying - if the parser is currently running in the background because of some edit, maybe it should wait for it to finish?

**Comment by BladeMF** [comment]
The strange bit is that I created the second method by duplicating the first one, so there was never a version of the code with no arguments. The more I think about it, the more it seems like a race condition between the parser and the code transform.

**Comment by dantleech** [comment]
There is a 5 second cache which might explain it.

**Comment by dantleech** [comment]
https://phpactor.readthedocs.io/en/develop/reference/configuration.html#worse-reflection-cache-lifetime

**Comment by BladeMF** [comment]
Yea, can I set it to 1 sec to prove it? Will I run into some serious issues?

**Comment by dantleech** [comment]
No, 1 second should be fine

**Comment by dantleech** [comment]
@BladeMF was this a caching issue? as it works for me

```
class Bar extends Test {
    public function bar(?string $a): void
    {
    }

    public function baz(?string $b): void
    {
    }
}
```

closing for now, but happy to reopen
