### ISSUE TITLE
Add reserved words and keywords to completors

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1148]
These are currently missing from completion which makes it very annoying to type them as something else keeps getting completed.

[This file](https://github.com/microsoft/tolerant-php-parser/blob/f2ec9ea3bded38f7f30898e519f3ce51fd6e1cbb/src/TokenStringMaps.php) from TolerantParser contains all of them.

Version 1 could be just adding them and Version 2 could be filtering them according to the passed `$node`.

I implemented version 1 and will evaluate how hard version 2 is.

**Comment by dantleech** [comment]
I think adding them unconditionally would be noisy?

**Comment by BladeMF** [comment]
You have no idea! In the end I did some casing and now it feels mostly OK (but haven't used it extensively) - look at the [test cases here](https://github.com/BladeMF/completion/blob/reserved-words-completion/tests/Integration/Bridge/TolerantParser/WorseReflection/KeywordCompletorTest.php).
