### ISSUE TITLE
Double entries in completion inside function parameters

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1149]
All the current function parameters and the `$this` variable appear twice inside function parameters completion list:
![image](https://user-images.githubusercontent.com/12109622/103157140-abfd7080-47b8-11eb-921c-0cec73f28814.png)
The second entry has a different info text:
![image](https://user-images.githubusercontent.com/12109622/103157160-d2bba700-47b8-11eb-8d2f-256961bdc24d.png)

**Comment by dantleech** [comment]
I assume this is fixed now? closing optimistically

![image](https://user-images.githubusercontent.com/530801/189359243-a134b35c-e7e1-4d81-84ce-95b03d7a4ced.png)
