### ISSUE TITLE
The highlighter doesn't highlight the use statement

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1151]
In this case:
```php
<?php

namespace Temp2\Folder2;

use Temp2\Folder\{Class1, Class2 as C2};
use Temp2\Folder\Class3 as C3;

class TheNewName
{
	function __construct(Class1 $class1, C<>3 $c3)
	{
	}
}
```
the text `C3` on the row `use Temp2\Folder\Class3 as C3;` should be highlighted. Same for `Class1` and `C2`. The `Microsoft\PhpParser\Node::getImportTablesForCurrentScope` method has a nice showcase of how to use `NamespaceUseDeclaration` instances.

**Comment by dantleech** [comment]
Transferred to Phpactor. This is an issue with the document-highlight feature in `phpactor/language-server-phpactor-extensions`

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/language-server-phpactor-extensions/pull/13

**Comment by BladeMF** [comment]
I'll take a look if this convers these two cases:
```php
use Temp2\Folder\{Class1, Class2 as C2};
use Temp2\Folder\Class3 as C3;
```
I tried to fix this myself and then found out that when aliases are involved the structure is different. I found `Microsoft\PhpParser\Node::getImportTablesForCurrentScope` but dropped it as it looked like a couple of hours of work.
