### ISSUE TITLE
Find references on an interface returns references to subclasses

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1160]
When searching for references for an interface, it returns also the references of the classes that implement that interface. Not sure if by design or a bug so I am raising an issue.

I can't say I don't see the merit of finding the implementing classes.

**Comment by dantleech** [comment]
This is by design, although it overlaps with the "goto implementation" feature, could make the behavior configurable.

**Comment by BladeMF** [comment]
Yes, that could satisfy both camps. I need to fix my rename though 😂🤣😂🤣.
