### ISSUE TITLE
Variables defined in the new shorthand for list (square braces) do not get included in completion

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1163]
After the statement `[$source, $selectionOffset, $definitionLocation, $referenceLocations] = self::offsetsFromSource($source, $uri);` only the variable `$source` is included in the completion, the other three are not. 

The above works in this form: `list($source, $selectionOffset, $definitionLocation, $referenceLocations) = self::offsetsFromSource($source, $uri);`

**Comment by dantleech** [comment]
weird, I'd exect both to have the same representation in the AST and AFAIK list assigns are not supported (because Phpactor doesn't support tuple return types AFAIK)

**Comment by BladeMF** [comment]
Probably the `list` form just picks them up as arguments?

**Comment by BladeMF** [comment]
> (because Phpactor doesn't support tuple return types AFAIK)

Actually, what do you mean?

**Comment by dantleech** [comment]
`@return array{string,int,int}` is not supported, and Phpactor doesn't analyse the method's code to see what might be returned.

**Comment by dantleech** [comment]
ah, or you mean that the variable is not registered? in the case, yes, that makes sense.

**Comment by BladeMF** [comment]
> `@return array{string,int,int}` is not supported, and Phpactor doesn't analyse the method's code to see what might be returned.

I see what you mean, but that's not the problem I am describing.

> ah, or you mean that the variable is not registered? in the case, yes, that makes sense.

...that is. The variables are not registered and will probably not be renamed.

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/worse-reflection/pull/97
