### ISSUE TITLE
Find all references for local variables

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1164]
That _should_ be working for LSP, right? Since there is a different class handling it, probably the results should just be merged, correct?

**Comment by dantleech** [comment]
Which class is handling it?

**Comment by BladeMF** [comment]
`Phpactor\Extension\LanguageServerReferenceFinder\Handler\ReferencesHandler`

**Comment by dantleech** [comment]
That doesn't find variables? This finds references in the index. We don't include variables as there is no point in searching for variables outside of the current file / scope, so this doesn't need the index.

**Comment by BladeMF** [comment]
Yes, it doesn't - that is why I suggested that we add code for finding variable and argument references. When I use "Find all references" on a variable or an argument, I expect to find them, not just the definition. What is your expectation?

**Comment by dantleech** [comment]
In this case you need to implement a new implementation of `Phpactor\ReferenceFinder\ReferenceFinder` and register it in the extension so that it gets aggregated into `Phpactor\ReferenceFinder\ChainReferenceFinder`. No need to modify that class probably.

**Comment by BladeMF** [comment]
Hmm, interesting. That will simplify the rename code and make it more efficient.
If I am not mistaken, `Phpactor\CodeTransform\Adapter\TolerantParser\Refactor\TolerantRenameVariable` contains exactly that code. Probably a new class that returns Locations that TolerantRenameVariable uses as well?

**Comment by dantleech** [comment]
Could probably extract the "find" code from that class.

The code should probably be in this library:

- https://github.com/phpactor/worse-reference-finder

and registered in:

- https://github.com/phpactor/worse-reference-finder-extension

(i know it's needlessly complicated)

**Comment by BladeMF** [comment]
Good. Will post a detailed plan when ready.

**Comment by BladeMF** [comment]
Should TolerantRenameVariable use that code? If yes, that probably goes with a service container tag and an interface that the new class will implement.

Also, since the new code uses the Microsoft parser, isn't it `Tolerant`, rather than `Worse`?

**Comment by dantleech** [comment]
Probably better to keep it separate, only the RPC will use that class in code-transform. Could possibly make it use the new class afterwards, but no need to be concerned with it now.

It's fine to put the tolerant code in the worse extension - worse-reflection is entirely coupled to tolerant parser and that's unlikely to change anytime soon (and maybe worse-reflection will be able to do this operation natively at some point)

**Comment by BladeMF** [comment]
What's the relationship between the two, anyway (worse and tolerant)?

**Comment by dantleech** [comment]
Worse Reflection is the reflection/static-analysis part of Phpactor. It uses the Tolerant PHP Parser heavily.

**Comment by BladeMF** [comment]
How is `TolerantVariableReferenceFinder` for a name?

**Comment by dantleech** [comment]
Fine :+1: feel free to make a WIP PR - happy to comment on it when you like

**Comment by BladeMF** [comment]
Yep, already forked the necessary repos.
