### ISSUE TITLE
Error detected while processing function phpactor#GotoDefinition[1]..phpactor#_GotoDefinitionTarget[1]..phpactor#rpc[19]..function phpactor#GotoDefinition[1]..phpactor#_GotoDefinitionTarget[1]..phpactor#rpc:

### ISSUE THREAD

**Issue by dele-corporate** [phpactor/phpactor#1165]
Just reporting.
vim 8.2.2251

E605: Exception not caught: Could not parse response from Phpactor: Vim(let):E491: json decode error at 'Warning: "resource" is not a supported builtin type and will be interpreted as a class name. Write "\Safe\resource" or import the class with "use" to suppress this warning in /Users/dele/.vim/plugged/phpactor/vend
or/thecodingmachine/safe/generated/sockets.php on line 797^@Deprecated: Required parameter $cacheLifetime follows optional parameter $frameWalkers in /Users/dele/.vim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/ServiceLocator.php on line 63^@{"version":"1.0.0","action":"error","parameters":{"message":"
Could not find source with \"Controller\"","details":"0: Could not locate a candidate for \"Controller\"\n#0 \/Users\/dele\/.vim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/SourceCodeLocator\/ChainSourceLocator.php(42): Phpactor\\WorseReflection\\Bridge\\Phpactor\\ClassToFileSourceLocator->loca
te(Object(Phpactor\\WorseReflection\\Core\\ClassName))\n#1 \/Users\/dele

**Comment by dantleech** [comment]
Thanks - which PHP version? (I can reproduce on 8.0 but not 7.4 with E_ALL)

**Comment by dele-corporate** [comment]
yes it shows up when i try php8

**Comment by dantleech** [comment]
should be fixed in the `develop` branch now.
