### ISSUE TITLE
Show traits and their uses in Find all references

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1166]
I have nearly completed it along with indexing `use` statements. Added cases for children of:
* `NamespaceUseClause` and `NamespaceUseGroupClause`
* `TraitUseClause`

The only thing that bothers me is that `QualifiedName::getResolvedName` explicitly does not resolve children of `TraitUseClause` and I don't get why. Any ideas? I had to read the import table myself.

**Comment by dantleech** [comment]
No I think I ran into the same thing myself.

**Comment by BladeMF** [comment]
Well reading the table is very straightforward. I am just wondering whether I am missing something, but generally I think the only case is:
1. Get whatever is after the `use` statement
2. Find it in the imports
2.1. If found, use the full name from the imports
2.2. If not found, use the name in the `use` statement.

By the way, the the places where the trait was used came up by themselves in the references, really nice. 

There is a whole other world about the methods though with this:
```php
<?php
trait A {
    public function smallTalk() {
        echo 'a';
    }
    public function bigTalk() {
        echo 'A';
    }
}

trait B {
    public function smallTalk() {
        echo 'b';
    }
    public function bigTalk() {
        echo 'B';
    }
}

class Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
    }
}

class Aliased_Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
        B::bigTalk as talk;
    }
}
?>
```

**Comment by dantleech** [comment]
See https://github.com/phpactor/phpactor/issues/1162 You can use the `TolerantQualifiednameResolver` instead to get the FQN of the use

**Comment by BladeMF** [comment]
I saw it in traits, the other option is this:
```php
            $localName = $node->getText();
            /** @var ResolvedName[] $namespaceImportTable */
            list($namespaceImportTable, $functionImportTable, $constImportTable) = $node->getImportTablesForCurrentScope();

            if (isset($namespaceImportTable[$localName])) {
                $name = (string)$namespaceImportTable[$localName];
            }
```

**Comment by dantleech** [comment]
I think this issue is not required anymore, but there are still issues with renaming traits members vs. aliases which I'll look at.

**Comment by dantleech** [comment]
https://github.com/phpactor/phpactor/pull/1862
