### ISSUE TITLE
Missing `'info'` field in completions list

### ISSUE THREAD

**Issue by torimus** [phpactor/phpactor#1170]
When using _phpactor_ with Vim's native _omni-completion_, it would become handy when `info` field will be also supplied in final suggestions, in cases when `preview` or `popup` option is set in Vim's `completeopt` setting, to allow display contextual description in a preview/popup window.

https://github.com/phpactor/phpactor/blob/3688c92ff002f7a2501489fa4052d946a3d72dac/autoload/phpactor.vim#L61-L68

The value would be actually identical with one for `'menu'` key, i.e. _`short_description`_ string, or even possibly _`documentation`_ with proper formatting. Managed by assigned configure option for Vim plugin ?

**Comment by dantleech** [comment]
Sure -- not sure why we don't populate `info` tbh, feel free to make a PR. I think `documentation` should already be available in `suggestion`.

**Comment by dantleech** [comment]
Closing, although open to a PR
