### ISSUE TITLE
Tab completion adds dollar for static variables

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1174]
When having this:
![image](https://user-images.githubusercontent.com/12109622/104282070-24517a80-54b7-11eb-95ad-7b89f6cd2d9e.png)
`Tab` makes the code like this:
```php
self::$$container
```

**Comment by camilledejoye** [comment]
https://phpactor.readthedocs.io/en/master/lsp/vim.html#troubleshooting
https://phpactor.readthedocs.io/en/master/reference/configuration.html#language-server-completion-trim-leading-dollar

Could it be because phpactor is not configured correctly for your editor ?
Do you have the same issue when completing a variable ?

**Comment by BladeMF** [comment]
No. I specifically checked:
```json
	"phpactor.config":{
		"language_server_completion.trim_leading_dollar": true,
```
I think I can troubleshoot this myself when I have time, but my point was to put this on record so we don't forget to fix it 😀

**Comment by FatBoyXPC** [comment]
I have the same issue as well

**Comment by dantleech** [comment]
works for me, also with VS code:

![image](https://user-images.githubusercontent.com/530801/107257559-b60ac400-6a32-11eb-8e61-82fdcf915ac4.png)

Am I missing anything?

**Comment by FatBoyXPC** [comment]
I just checked on the latest and I don't have the issue anymore. Odd, but awesome!

**Comment by BladeMF** [comment]
Odd. I have it still.

> works for me, also with VS code:
> 
> ![image](https://user-images.githubusercontent.com/530801/107257559-b60ac400-6a32-11eb-8e61-82fdcf915ac4.png)
> 
> Am I missing anything?

Aren't you on a outdated version?

**Comment by dantleech** [comment]
Shouldn't be anymore...

**Comment by dantleech** [comment]
Assuming this is no longer an issue
