### ISSUE TITLE
Static variable completion list doesn't put variables at the top of the list

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1175]
When completing static variables, they are not on the top of the list:
![image](https://user-images.githubusercontent.com/12109622/104282212-5fec4480-54b7-11eb-8a7d-2cbfdbd92e4b.png)

**Comment by dantleech** [comment]
It is now possible to prioritize completions: https://github.com/phpactor/completion/pull/42

**Comment by BladeMF** [comment]
I am not sure if this should not be prioritised internally. if the $ was included in the sort, only variables will be up there.

**Comment by dantleech** [comment]
it's a class member, class memberes can be prioritised

**Comment by BladeMF** [comment]
I don't understand - aren't they all class members?

**Comment by dantleech** [comment]
class members are all methods, constants and properties of a class

**Comment by BladeMF** [comment]
Yes, so everything on this list is a class member of the current class. I don't see how that helps in that case. How do you imagine this prioritisation being used?

My argument is that static variables start with `$` and I have types `$` so the other things in the list should not be upper because they are a worse match for what I am typing. If there is something that starts exactly with what I am typing, then it should be on top.

**Comment by dantleech** [comment]
oh i see. not sure. maybe the completion doesn't take into account `$`

**Comment by BladeMF** [comment]
It looks that way. That's why I created the issue - so we don't forget to look at it one sunny day.

**Comment by dantleech** [comment]
![image](https://user-images.githubusercontent.com/530801/189378178-e3557e35-3cb5-44e6-948f-59633ec76cad.png)

not sure if this was fixed in code or phpactor, but seems to work for me
