### ISSUE TITLE
[text-document] = is not a word split in annotations

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#1176]
Hi!

Given this file:

```php
<?php

namespace App\Controller\V1\UserManagement\ECMS;

use Swagger\Annotations as SWG;
use Symfony\Component\HttpFoundation\Response;

class ResetPasswordController
{
    /**
     * @SWG\Post(
     *     @SWG\Response(
     *         response=Resp<>onse::HTTP_OK,
     *         description="Reset password sent successfully"
     * )
     */
    public function resetPassword()
    {
    }
}
```
A jump to definition results in `Error from Phpactor: Do not know how to goto definition of symbol type "<unknown>", Word "App\Controller\V1\UserManagement\ECMS\response=Response" could not be resolved to a class` as if the `=` character was not a FQCN split char, although it seems it is the case in [text-document](https://github.com/phpactor/text-document/blob/master/lib/Util/WordAtOffset.php#L11).

Is it because annotations are parsed differently?

**Comment by dantleech** [comment]
I don't think annotations are parsed differently :thinking:

**Comment by BladeMF** [comment]
I don't have any services beside coloring on the annotations, or even typehints in comments.

**Comment by dantleech** [comment]
you can import annotation classes in the RPC implementation due to hacks.

**Comment by dantleech** [comment]
@Einenlum you were rght, it was parsed differently:

- Updated to use the `text-document` [word extractor utility](https://github.com/phpactor/worse-reference-finder/commit/79715f9c734e0549e82aa071a4522f6dc8115772)
- Updated that utility with a [better splitting pattern[(https://github.com/phpactor/text-document/commit/0f75fb53e9f9633ade9a48eedc3f73fbed2c9145#diff-5a6b460addbd41686213a1da764de796ded9258b12adf5bddf23ab2349c9222cR14)

**Comment by Einenlum** [comment]
Nice! Thx a lot for your work! :heart:
