### ISSUE TITLE
Type completion for return value hint

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1180]
In that position:
```php
public function providePrepare(): <>
```
I should get types as completion. Currently I get keywords (which is also wrong).

**Comment by dantleech** [comment]
![image](https://user-images.githubusercontent.com/530801/104837015-cb645680-58a9-11eb-948d-c415826659c9.png)

works for me?

**Comment by BladeMF** [comment]
A VSCode-only issue then?
![image](https://user-images.githubusercontent.com/12109622/104837339-7ed64680-58bc-11eb-8784-8b8cf7a49568.png)

**Comment by dantleech** [comment]
I think you need to type at least one letter

**Comment by BladeMF** [comment]
Still text suggestions only:
![image](https://user-images.githubusercontent.com/12109622/104837557-08d2df00-58be-11eb-8bed-dbf45d97c6ed.png)

**Comment by BladeMF** [comment]
As opposed to:
![image](https://user-images.githubusercontent.com/12109622/104837569-1a1beb80-58be-11eb-9b41-45cdf827be7d.png)

**Comment by dantleech** [comment]
![image](https://user-images.githubusercontent.com/530801/104837624-b689c200-58ad-11eb-8a7a-c10d8af554e5.png)

**Comment by dantleech** [comment]
Maybe worth checking the language server log in VSCode? maybe it is returning but not completing for another reason?

**Comment by BladeMF** [comment]
Hm, right. Will take a look when I can. Let's leave this open.

**Comment by przepompownia** [comment]
![image](https://user-images.githubusercontent.com/11404453/167010674-3cb76b6d-b475-46dd-8a4e-863dc7d092d4.png)
For me, primitive types and `void` are not present. For some reason function names appear there. 
![image](https://user-images.githubusercontent.com/11404453/167011069-0982a744-c55f-4d8a-aa43-673ed8b5a840.png)

**Comment by dantleech** [comment]
the "culprit" is https://github.com/phpactor/phpactor/blob/1280fc4711a20dd051de6ce5c89829bc3130d565/lib/Completion/Bridge/TolerantParser/ReferenceFinder/NameSearcherCompletor.php#L18 which is not telling the difference between a "type" completion and a function/class completion.

For the docblock work there is now https://github.com/phpactor/phpactor/blob/1280fc4711a20dd051de6ce5c89829bc3130d565/lib/Completion/Bridge/TolerantParser/TypeSuggestionProvider.php#L10 which provides the return type suggestions.

So whateter the solution it should probably use that.

**Comment by dantleech** [comment]
should be fixed in #1558

**Comment by przepompownia** [comment]
![image](https://user-images.githubusercontent.com/11404453/167309278-e8a84e06-d508-4f78-9049-7a401e1838a0.png)
![image](https://user-images.githubusercontent.com/11404453/167309310-c975d2af-aae2-48a2-a44f-897694dd14d0.png)
