### ISSUE TITLE
`class:move` in combination with same class name and `use as`

### ISSUE THREAD

**Issue by matzeeable** [phpactor/phpactor#1183]
Hey phpactor team!

I just tried to use the `phpactor class:move` command, unfortunately it does not properly work in my composer project. Here is a step-by-step description, how you can reprocedure the issue on your local system:

**1. Add the following files to your project**

`src/inc/phpactor_testing/ClassA.php`

```php
<?php
namespace DevOwl\RealCookieBanner\phpactor_testing;

class ClassA {

}
```

`src/inc/phpactor_testing/another/ClassA.php`

```php
<?php
namespace DevOwl\RealCookieBanner\phpactor_testing\another;

use DevOwl\RealCookieBanner\phpactor_testing\ClassA as Phpactor_testingClassA;

class ClassA extends Phpactor_testingClassA {
    public static function test() {
        // Returns the full name of this class
        return ClassA::class;
    }
}

```

I have configured a PSR-4 autoloading in composer as follows, perhaps you need to modify it:

```
"DevOwl\\RealCookieBanner\\": [ "src/inc/" ]
```

**2. Run the command**

Run the following command within the composer project:

```
phpactor class:move src/inc/phpactor_testing/ClassA.php src/inc/phpactor_testing/new/ClassA.php
```

**3. Check the second class**

The second class `DevOwl\RealCookieBanner\phpactor_testing\another\ClassA` now contains a `use` which is not correct:

```php
<?php
<?php
namespace DevOwl\RealCookieBanner\phpactor_testing\another;

use DevOwl\RealCookieBanner\phpactor_testing\new\ClassA as Phpactor_testingClassA;
use DevOwl\RealCookieBanner\phpactor_testing\new\ClassA; // <----

class ClassA extends Phpactor_testingClassA {
    public static function test() {
        // Returns the full name of this class
        return ClassA::class;
    }
}
```

**What is important to reprocedure the issue:**

- Two classes in two different namespaces with the same class name (`ClassA`)
- In the second class depend on the other class and `use as`

I think `phpactor` does not respect the `use as`, what do you think?

Thanks for your reply! 😊

**Comment by dantleech** [comment]
I think you're correct. As [noted here](https://github.com/phpactor/phpactor/issues/1171) the `class:move` functionality is very old, and works for most but all cases.  There is some currently ongoing work to replace it.

**Comment by matzeeable** [comment]
Hi @dantleech !

Thanks for your prompt reply. How can we proceed? Should I close this ticket and subscribe to the other issue?

Regards,
Matthew 😊

**Comment by dantleech** [comment]
it's fine, I think we can update all these tickets when we resolve.

**Comment by matzeeable** [comment]
Is there any ETA for this or a prerelease, so I can help with testing? 😊

**Comment by dantleech** [comment]
no it's a long way from being finished currently.... :)

**Comment by dantleech** [comment]
I _thnik_ this works now.
