### ISSUE TITLE
Traits implementing requirements of other traits are not detected

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1185]
If we have these two traits:
```php
trait ORMHelperTrait
{
	protected abstract function getContainer(): ContainerInterface;
	protected abstract function getEntityManager(): EntityManagerInterface;

	public function getEntityRepo(string $entityName): ObjectRepository
	{
		$em = $this->getEntityManager();
		return $em->getRepository($entityName);
	}

	public function getEntityRecordById(string $entityName, int $id): object
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository($entityName);
		return $repo->findOneBy(['id'=>$id]);
	}
}
```

```php
trait ContainerHelperTrait
{
	protected function getContainer(): ContainerInterface
	{
		return static::$container;
	}

	protected function getEntityManager(): EntityManagerInterface
	{
		return $this->getContainer()->get(EntityManagerInterface::class);
	}
}
```

and use them in this class:

```php
class ListCompletedRoundIssuesTest extends KernelTestCase
{
	use UserHelperTrait;
	use ContainerHelperTrait;
	use ORMHelperTrait;
```

you get this:
![image](https://user-images.githubusercontent.com/12109622/105321679-6f167500-5bd0-11eb-8eee-3337a8a5d07a.png)

The actual code runs fine. Phpstan also doesn't find errors.

**Comment by dantleech** [comment]
Relevant code is here: https://github.com/phpactor/code-transform/blob/master/lib/Adapter/WorseReflection/Transformer/ImplementContracts.php#L121 probably just need to add some trait handling there.

**Comment by dantleech** [comment]
ok, this is because of the way that traits are "merged" into the list of class methods:

https://github.com/phpactor/worse-reflection/blob/5122b1a570ca2c029d1f5b24be11b4a7c6e2a71b/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php#L206-L229

methods are indexed by name, but this means that multiple methods from different sources implementing the same name will overwrite each-other.

not really sure what the best solution here is -- we should probably prioritise methods concrete methods over abstract ones.

**Comment by BladeMF** [comment]
Good job at finding that out. Using concrete classes with priority seems to be the simplest solution. Otherwise we should probably implement [this](https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict).

**Comment by dantleech** [comment]
`insteadof` is already supported: https://github.com/phpactor/worse-reflection/blob/5122b1a570ca2c029d1f5b24be11b4a7c6e2a71b/tests/Integration/Bridge/TolerantParser/Reflection/TraitImport/TraitImportsTest.php#L59-L67

**Comment by BladeMF** [comment]
**UPDATE**
It turns out it is a matter of the order of the traits. In the above example, this **does not** fire an exception:
```php
class ListCompletedRoundIssuesTest extends KernelTestCase
{
	use UserHelperTrait;
	use ORMHelperTrait;
	use ContainerHelperTrait;
```
In this case `ContainerHelperTrait` provides implementations for the methods defined in  `ORMHelperTrait`.

**Comment by dantleech** [comment]
This seems also to be fixed, probably as a side effect of trait resolution refactoring a month or so back.

**Comment by dantleech** [comment]
```
<?php

trait ORMHelperTrait
{
	protected abstract function getContainer(): ContainerInterface;
	protected abstract function getEntityManager(): EntityManagerInterface;

	public function getEntityRepo(string $entityName): ObjectRepository
	{
		$em = $this->getEntityManager();
		return $em->getRepository($entityName);
	}

	public function getEntityRecordById(string $entityName, int $id): object
	{
		$em = $this->getEntityManager();
		$repo = $em->getRepository($entityName);
		return $repo->findOneBy(['id'=>$id]);
	}
}

trait ContainerHelperTrait
{
	protected function getContainer(): ContainerInterface
	{
		return static::$container;
	}

	protected function getEntityManager(): EntityManagerInterface
	{
		return $this->getContainer()->get(EntityManagerInterface::class);
	}
}

class ListCompletedRoundIssuesTest
{
	use ContainerHelperTrait;
	use ORMHelperTrait;
}
```
