### ISSUE TITLE
Certain types are not found by the import class code-action

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1187]
(but are by the regular action)

![image](https://user-images.githubusercontent.com/530801/105418274-c0f0e680-5c34-11eb-965c-037b4cf14573.png)

In this example invoking `code-action` says "no results" even though the `Token` class has not been imported.

There are no errors in the log.
`

**Comment by BladeMF** [comment]
I have noticed this as well. Either "no reuslts", or are not deduplicated:
![image](https://user-images.githubusercontent.com/12109622/105463415-b1a38480-5c98-11eb-8932-92d50fb91d17.png)

**Comment by BladeMF** [comment]
Interestingly, not every class is duplicated:
![image](https://user-images.githubusercontent.com/12109622/105464047-9c7b2580-5c99-11eb-84af-a37c0bfda800.png)

**Comment by dantleech** [comment]
hm, i never don't get duplicated results. Can you check the `~/.cache/phpactor/.../search` file to see if they're duplicated there?

**Comment by BladeMF** [comment]
Pratically one (not sure how the other record didn't get removed):
![image](https://user-images.githubusercontent.com/12109622/105466308-b5390a80-5c9c-11eb-9149-b60ce3041821.png)

**Comment by dantleech** [comment]
You might need to debug the search: e.g. https://github.com/phpactor/workspace-query/blob/4509572233959bc7b9d258e96f85d3b0dd3698d4/lib/Adapter/Php/FileSearchIndex.php#L59

**Comment by BladeMF** [comment]
The import uses the search?

**Comment by dantleech** [comment]
to find the short names AFAIK

**Comment by dantleech** [comment]
This was caused by return types not being classed as "unresolved" now fixed.
