### ISSUE TITLE
[BC break] Introduced in Phpactor\Container\Extension

### ISSUE THREAD

**Issue by camilledejoye** [phpactor/phpactor#1194]
```
PHP Fatal error:  Declaration of Phpactor\Extension\PhpSpec\PhpSpecExtension::load(Phpactor\Container\ContainerBuilder $container) must be compatible with Phpactor\Container\Extension::load(Phpactor\Container\ContainerBuilder $container): void in /home/cdejoye/work/phpactor/extensions/phpactor/phpspec-extension/lib/PhpSpecExtension.php on line 19
```

A recent change was to add a void return type for the two methods defined in this interface.  
On my side the PHPUnit and PHPSpec extension were not updated, causing phpactor to crash.

**Comment by dantleech** [comment]
yes - updating them will fix the issue (may need to manually manipulate the files in `extensions`). can't currently think of another solution, maybe a composer hook ? :thinking:

**Comment by dantleech** [comment]
Added a post install hook in #1195, i think that should help.
