### ISSUE TITLE
Installation and workflow changes

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1196]
## No more develop

- Phpactor will have the default branch `master`
- :heavy_check_mark: There will be a warning if you are using `develop` https://github.com/phpactor/phpactor/pull/1200

## Extension Manager

**Status**: Rewriting (and simplifying) the extension manager is good - but not strictly necesary for the next release.

- No more embedded composer, the host `composer` will be used.
- The extension manager will create a new `composer.json` merging the default file and operating on that
- Extensions installed via. configuration (e.g. `{"extensions": [ "phpactor/behat-extension", "phpactor/phpspec-extension"]}` and at least provide a way to enable / disable individual extensions, possibly configure them)

## Updates

- :heavy_check_mark: Recommend `Plug 'phpactor/phpactor', { tag: '*'}` to get the latest tagged version for the VIM plugin
- `coc` and `vscode` plugins to provide option to install Phpactor based on latest tag (or configured tag) :question: 

## Main Package Versioning

**Status** Probably not worth the effort.

- Switch to date `20210204` versioning? Semver at this level means nothing (determining phpactor is if tools still pick the latest version)

**Comment by camilledejoye** [comment]
Is it a todo list ?

**Comment by dantleech** [comment]
TODO list / RFC / announcement: the biggest thing is updating the extension manager, which is a bit of work, I might leave that for the next release.
