### ISSUE TITLE
Auto import after completion does not work in RPC mode

### ISSUE THREAD

**Issue by CaptainQuirk** [phpactor/phpactor#1199]
Hi there,

Switching workstation I realized that the auto import feature is not working anymore.

### :gear: Settings

- Debian based distro (Ubuntu 20.04, Linux Mint 19.1)
- PHP 7.4
- Vim 8.1 (vim-gtk package)
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static   
```
I use vim inside a tmux session in a terminal.

####  phpactor configuration

I'm using the **master** branch.  
I have this in a `$HOME/.vim/plugin/phpactor.vim` file : 

```vim
let g:phpactorBranch = "develop"
autocmd FileType php setlocal omnifunc=phpactor#Complete
```

### :ballot_box_with_check: Steps to reproduce

1. Commence typing
2. Hit `<C-x><C-o>` to display the completion menu
3. Navigate to the choice I'm interested in
4. Type a character

### Actual result

I see a message saying  `Imported class <class>`. But nothing happens at the top of the file

### Expected result

I would like a use statement added at the top of the file

### :thinking: Notes and remarks

The feature works when I'm on the **develop** branch of **phpactor**. In fact, it stopped working because I didn't realize after switching the workstation that I forget to set the proper branch before running composer install.

Auto import works in other contexts like when I'm executing the `(i) implement contract` action on a class : all the objects added in new function signatures are added in the use section

**Comment by dantleech** [comment]
That's strange - it works for me on current `master`. I'm hoping to release a new `master` version in the next weeks, so if it works on `develop` it will likely be resolved then.

**Comment by CaptainQuirk** [comment]
It's actually the second workstation I'm witnessing it ! The first switch occured in last august or september. I ignored it at the time because calling `phpactor#UseAdd()` manually was not that much a burden !
I didn't mention that I have coc.nvim installed but nothing that handles php on this end !

**Comment by dantleech** [comment]
If you have CoC then you can use the Phpactor Language Server - which provides a much better auto-import than the VIM plugin

**Comment by weeman1337** [comment]
I don't know whether or not that is a separate issue: I am using Phpactor (`master` Branch) with `compe` and `vsnip`. Completion works with snippets. But If I completed a class there is no import ot that class happening.

**Comment by dantleech** [comment]
RPC and LSP are indeed separate in this case, but the auto-import works for me. Maybe check to see if you have another LS running, or duplicate suggestions.

**Comment by dantleech** [comment]
Closing as old and we should all be using LSP anyway.
