### ISSUE TITLE
Script bin/phpactor extension:update handling the post-install-cmd event returned with error code 255

### ISSUE THREAD

**Issue by Goku-San** [phpactor/phpactor#1205]
Hello, 
I am on Manjaro linux. I have installed composer and php through pacman. 
Composer version 2.0.8
PHP version 7.4.14
Vim 8.2
Phpactor as vim plugin only, with ```Plug 'phpactor/phpactor', {'for': 'php', 'tag': '*', 'do': 'composer install --no-dev -o'}``` command.
shell zsh version 5.8

This error occurred today, when I updated vim plugins.
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/goku/.vim/autoload/plugged/phpactor/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 288
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/goku/.vim/autoload/plugged/phpactor/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 288
Script bin/phpactor extension:update handling the post-install-cmd event returned with error code 255

shell returned 255
```
I tried reinstalling the plugin,  but that didn't help.
How can I solve this ??
I installed PHP recently and am trying to learn.
Thanks...

**Comment by dantleech** [comment]
A temportary fix would be to increase (or disable) the PHP memory limit:

```
$ php --info | grep php.ini
Configuration File (php.ini) Path => /etc/php/7.4/cli
Loaded Configuration File => /etc/php/7.4/cli/php.ini
```

Then edit `php.ini` and f.e. change `memory_limit` to `-1` to disable it:

```
memory_limit = -1
```

**Comment by dantleech** [comment]
Otherwise the `extension:update` after install is a new feature, and should probably demand more memory.

**Comment by Goku-San** [comment]
Hello @dantleech, thanks for the fast response.
I used your second recommendation ```composer install --no-scripts...``` . Everything installed correctly without errors and its working for now.

**Comment by dantleech** [comment]
Thank's I will update the installer to request more memory and then close this ticket.
