### ISSUE TITLE
Imported constants not recognised

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1207]
When using imported constants:
```php
use const CleverTogether\Bundle\ServiceBundle\Expressions\Conditions\in;
```
They appear neither in the completion nor in tooltips:
![image](https://user-images.githubusercontent.com/12109622/107739483-a250ad80-6d11-11eb-814e-6e1cd2cdd0b7.png)

**Comment by dantleech** [comment]
yes - constant imports are not supported at all currently

**Comment by BladeMF** [comment]
Maybe we should map out what the changes would look like (e.g. indexer, worse reflection)?

**Comment by dantleech** [comment]
I added constants to the index a few weeks back: https://github.com/phpactor/indexer-extension/commit/60fb9174511052c363c8be7c8ccc0d6a2daf35fa

It works on global constants at least -- I'm not sure why it doesn't work here - possibly a small fix.

**Comment by dantleech** [comment]
In general - in Worse Reflection:

- We need to add support for non-class constants _symbol resolution_ in WorseReflection
- Possibly add support for refecting constants (e.g. `$reflector->reflectConstant('Fqn\To\CONSTANT')`) and return a `ReflectionConstant` (which will have the source code location etc) 
- Add a source locator for these constants (e.g. implementation can be indexer based)

This should make it very easy to support both goto definition and hover.

**Comment by dantleech** [comment]
Will be fxied by https://github.com/phpactor/phpactor/pull/1868 reopen if not the case :)
