### ISSUE TITLE
Constants not picked up from interface (in some cases?)

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1211]
Something like:

```
class BaseCLass
{
    const FOOBAR = 'bar';
}
interface SomeInterface
{
    const FOOBAZ = 'foo';
}
class Concrete extends BaseCLass implements SomeInterface
{
    publci function baz()
    {
       self::FOO<>
    }
}
```
only returnes `FOOBAR`

**Comment by mamazu** [comment]
Seems to work now.
![image](https://github.com/phpactor/phpactor/assets/14860264/e5f2b980-eef8-4118-af1e-7502bcea3721)

however, if you copy the code from your example (which has a typo on the word `public`) there are no LSP suggestions.
