### ISSUE TITLE
Non-class results from `ClassSearch` slowing down `phpactor#UseAdd()`

### ISSUE THREAD

**Issue by dshoreman** [phpactor/phpactor#1216]
In my project, test reports are saved by date/time in subdirectories of */tests/reports/{coverage,metrics}*.  
When I call `phpactor#UseAdd()`, it [also scans those reports][1] because */tests* is listed in composer's PSR 4 `autoload-dev` list.

If I trigger `UseAdd()` on a `User` class (for example), I will get the file I want *plus* two for each report (there's both a `User` and `System\User`). The end result is some 200 choices split across several pages, which takes over *4 seconds* to load.

---

My first thought was to exclude the path. I found #782, but then I noticed **the results aren't PHP files**, let alone PHP classes. They just *happen* to match the path and filename of the real class... with a `.html` extension tacked on.

After some digging, I found the `classSearch` method ([called][2] by [`ImportClassHandler`][3]) which uses the `named` filter:

https://github.com/phpactor/phpactor/blob/dac62ddadb2f5ed3127621cb28358957f613bc1a/lib/Extension/SourceCodeFilesystemExtra/SourceCodeFilestem/Application/ClassSearch.php#L41-L42

...but a call to `->named('Foo.php')` *[isn't an exact match][4]* - it effectively filters on `"/Foo.php*"`.

---

As far as I can tell, when performing a class search we're *only* interested in `.php` files, *not* `.php.bak` or `.php.html` etc. so we can just compare the full filename. I'll send a PR shortly with a fix, but it still needs cleaning up so in the meantime I have a couple...

## Questions

* Is there anywhere (other than `ImportClassHandler`) that uses `classSearch()` and relies on the current functionality?
* Instead of a closure, a new method on `FileList` would probably be better:
  * Since it's a "stricter `named()`", thoughts on `->namedExactly('Foo.php')` or similar?

[1]: https://github.com/phpactor/source-code-filesystem/blob/master/lib/Adapter/Composer/ComposerFileListProvider.php#L69-L71
[2]: https://github.com/phpactor/phpactor/blob/dac62ddadb2f5ed3127621cb28358957f613bc1a/lib/Extension/CodeTransformExtra/Rpc/ImportClassHandler.php#L153-L156
[3]: https://github.com/phpactor/phpactor/blob/dac62ddadb2f5ed3127621cb28358957f613bc1a/lib/Extension/CodeTransformExtra/Rpc/ImportClassHandler.php#L80
[4]: https://github.com/phpactor/source-code-filesystem/blob/b96d5b4014fbb6813c459a00d998e80c2bef9aaa/lib/Domain/FileList.php#L110-L116

**Comment by dantleech** [comment]
The indexer is doing something similar but uses `include|excludePatterns` with a glob:

https://github.com/phpactor/workspace-query/blob/a8bac4d14ddf8b67373ba7969956916ccc37c0b2/lib/Adapter/Filesystem/FilesystemFileListProvider.php#L43-L70

Is the problem that `named` expects a fully path? In which case I would name it `withBasename('Foo.php')` (cirresponding to `SplFileInfo#getBasename()`

**Comment by dantleech** [comment]
But in answer to your question: it looks like `ClassSearch` is the only place that uses the `named()` method.

**Comment by dshoreman** [comment]
> Is the problem that `named` expects a fully path? In which case I would name it `withBasename('Foo.php')` (cirresponding to `SplFileInfo#getBasename()`

I thought it was only operating on filenames initially, then tests failed as soon as I created this issue. In hindsight (and after some sleep), `named` makes perfect sense; it's not operating on "filenames" but class names (fully qualified or not) converted to paths.

> But in answer to your question: it looks like `ClassSearch` is the only place that uses the `named()` method.

In which case we don't need a second method, even better! Once I've rebooted I'll go ahead and update `named` along with a couple tests that touch it. Thanks!

**Comment by dshoreman** [comment]
@dantleech I've just posted a PR to SCF that updates tests and the `rename` method. I've also updated the PR on this repo to include a regression test in case `ClassSearch` ever changes.

If there are no changes needed on phpactor/source-code-filesystem#19, I'll update composer on #1217 and squash/rename the commits, then that test should pass too :tada:
