### ISSUE TITLE
Aliased classes don't appear in completion

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1219]
If we have
```
<?php

use MarsIPM\Entity\StakeholderAssessment as ShAssessment;
```
In completion we have
![image](https://user-images.githubusercontent.com/12109622/110946352-6c6e0b80-8347-11eb-8bcd-848be0e315d4.png)
But:
![image](https://user-images.githubusercontent.com/12109622/110946378-755edd00-8347-11eb-904f-00c6412082a0.png)

**Comment by dantleech** [comment]
Relevant completor: https://github.com/phpactor/completion/blob/2347168e27a13e88418ea4dd44fc57778c2e8b93/lib/Bridge/TolerantParser/WorseReflection/WorseClassAliasCompletor.php#L18

**Comment by BladeMF** [comment]
Cheers.

Vladi.
________________________________

**Comment by BladeMF** [comment]
Does this completor remove the unaliased versions as well

Vladi.
________________________________
