### ISSUE TITLE
[Question][LSP] Support on neovim-lspconfig?

### ISSUE THREAD

**Issue by malukenho** [phpactor/phpactor#1220]
Is there any plan to provide a default config on `neovim-lspconfig`?

**Comment by dantleech** [comment]
I don't know what that is - but it sounds like we should support it yes.

**Comment by jesseleite** [comment]
Hey @malukenho @dantleech I was wondering about phpactor + nvim LSP as well. I'm sure you're aware Neovim has a built-in LSP client now, and many are switching away from COC, etc. (not that there's anything wrong with COC, etc).

I got started with intelephense pretty easily, because [neovim-lspconfig](https://github.com/neovim/nvim-lspconfig) (an official set of preconfigured language servers) provides an [intelephense binding and default config](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/intelephense.lua). All I had to do was:

1. Install intelephense on my machine,
    
    ```
    npm install -g intelephense
    ```

2. And then add this to my vim config:

    ```lua
    require'lspconfig'.intelephense.setup {}
    ```
    
    > Intelephense specific config options can be setup within that lua table.

I've been a happy phpactor user for quite some time now, but not sure how to go about setting it up with Neovim LSP. If we can figure it out, maybe we can PR to [neovim-lspconfig](https://github.com/neovim/nvim-lspconfig) so that it's just as easy for phpactor users to get up and rolling with it 🙂

I'd be glad to help and test where I can, but I'm a bit lost on where to start.

**Comment by dantleech** [comment]
There is already a PR: https://github.com/neovim/nvim-lspconfig/pull/769

I personally couldn't get it working however, maybe you could test it and leave feedback?

**Comment by jesseleite** [comment]
Oh rad, will give it a whirl for sure! Thanks!

**Comment by jesseleite** [comment]
That PR seems to work great 🤘

**Comment by dantleech** [comment]
Nice, it's been merged. I'll keep this ticket open until the documentation is updated.

**Comment by jesseleite** [comment]
Awesome!

@dantleech Curious though, for the little time I was using intelephense, I had these inline diagnostics popping up, ie...

![CleanShot 2021-03-20 at 18 50 05](https://user-images.githubusercontent.com/5187394/111887710-41219700-89ad-11eb-8f70-c7022d6297d9.png)

I'm not seeing these with phpactor though. I'm assuming phpactor has LSP logic for linting those kinds of errors? 🤔

**Comment by dantleech** [comment]
As you found there is the PHPStan extension, which requires PHPStan to be installed int he project or you can provide an absolute path in the config.

I'll try the LSP config today and see what happens

**Comment by dantleech** [comment]
ok, it's working for me again with the latest version of the plugin, for diagnostics I see this error:

```
[2021-03-21 08:32:52] phpactor.ERROR: Error when handling "Phpactor\LanguageServer\Core\Rpc\NotificationMessage" ({"method":"textDocument\/didSave","params":{"textDocument":{"uri":"file:\/\/\/home\/daniel\/www\/phpbench\/phpbench\/lib\/Attributes\/AbstractMethodsAttribute.php"}},"jsonrpc":"2.0"}): Exception [TypeError] Argument 3 passed to Phpactor\LanguageServerProtocol\TextDocumentItem::__construct() must be of the type int, null given, called in /home/daniel/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Service/DiagnosticsService.php on line 99 [] []
```

**Comment by dantleech** [comment]
Have fixed and it is available in the latest `master` I'll tag 0.17.1 today

![image](https://user-images.githubusercontent.com/530801/111900339-ee39f500-8a29-11eb-837a-1a8cadbb31ad.png)

**Comment by malukenho** [comment]
Awesome ❤️

**Comment by jesseleite** [comment]
Hmm, just updated, but still not working.  This is what I have so far...

Firstly, I have installed phpactor using vim-plug, because I have a few phpactor mappings:

```vim
Plug 'phpactor/phpactor', {'for': 'php', 'do': 'composer install'}
```

From there, I have an absolute path to phpactor in my nvim-lspconfig:

```lua
lspconfig.phpactor.setup {
  cmd = {'/Users/jesseleite/.config/nvim/plugged/phpactor/bin/phpactor', 'language-server'}
}
```

This seems to work, as I see phpactor active when I run `:LspInfo`, and I get phpactor completions, etc.

I then ran `extension:install "phpactor/language-server-phpstan-extension"` from the above phpactor binary, and I see phpstan is listed when I run `extension:list`:

![image](https://user-images.githubusercontent.com/5187394/111921091-0a10bb80-8a69-11eb-9175-103a89096861.png)

Finally, I have this in my project's `phpstan.neon`, as all of our PHP is within the repo's `src` folder:

```neon
parameters:
    level: 7
    paths: [ src ]
```

However, I'm not getting phpstan related diagnostics like in your screenshot. Assuming I need to reference the phpstan binary somewhere in my lspconfig?

**Comment by dantleech** [comment]
are you using the latest phpactor version? i released it this morning. otherwise the extension list shows available extensions in addition to installed ones, the installed ones are `bold`

**Comment by jesseleite** [comment]
![image](https://user-images.githubusercontent.com/5187394/111921291-3aa52500-8a6a-11eb-813e-46dfcce5e216.png)

Looks like the latest commit!

**Comment by dantleech** [comment]
ah, at least for me the diagnostics only worked after you save the file.

**Comment by jesseleite** [comment]
Double checking the phpstan extension is installed:

![image](https://user-images.githubusercontent.com/5187394/111921394-ad160500-8a6a-11eb-98c0-a6f74c867316.png)

Saved the file first:

![image](https://user-images.githubusercontent.com/5187394/111921418-d767c280-8a6a-11eb-9524-b355fbefc908.png)

And client is definitely attached to buffer:

![image](https://user-images.githubusercontent.com/5187394/111921435-efd7dd00-8a6a-11eb-91e2-e3d06e3ae015.png)

PS. Diagnostics show if I use intelephense or other LSP clients, just can't get phpstan to do it's thing 🤔

**Comment by dantleech** [comment]
In that case I guess enable logging https://phpactor.readthedocs.io/en/master/other/developing.html#logging

And see what happens when you save a file. (optionally add `logging.formatter: pretty` to get some more readable output)

**Comment by jesseleite** [comment]
Oh interesting, as I thought, I need to reference my global phpstan binary somehow...

```
phpactor.ERROR: Phpstan exited with code "127": sh: /Users/jesseleite/Code/cms/vendor/bin/phpstan: No such file or directory  [] []
```

I just don't know where to put it in my lspconfig 🤔

**Comment by dantleech** [comment]
me neither - you can probably pass `initializationOptions` in the config, but in anycase in `.phpactor.{json,yml}` you can specify `language_server_phpstan.bin: /path/to/phpstan`

**Comment by jesseleite** [comment]
Oh in the yaml, that worked thanks! ❤️❤️❤️

Curious on two things...

1) What is the purpose of `phpactor extension:install`, if I still have to link up the phpstan binary myself?

2) Given that phpactor seems harder to setup globally than intelephense (I got diagnostics and everything using the default intelephense config), what are the advantages to phpactor over intelephense?

PS. I ask this as someone who has been **_extremely_** happy with phpactor (standalone, not really LSP until now). I think intelephense has a specific advantage that `require'lspconfig'.intelephense.setup { }` is all that is required to get up and running with intelephense, diagnostics and all. It would be rad if it were that easy with phpactor + phpstan!

**Comment by dantleech** [comment]
> What is the purpose of phpactor extension:install, if I still have to link up the phpstan binary myself?

It will use `vendor/bin/phpstan` by default - the assumption is that it's installed as a project dependency. Which is also the benefit - you use the same version of PHPStan as your project.

> Given that phpactor seems harder to setup globally than intelephense (I got diagnostics and everything using the default intelephense config), what are the advantages to phpactor over intelephense?

:shrug: I'd be interested to know - I haven't used intelliphesnse.

> It would be rad if it were that easy with phpactor + phpstan!

This is a project-by-project combination though - if you use Psalm you might not want to get PHPStan diagnostics. But sure -- it could be easier to setup :thinking:

**Comment by jesseleite** [comment]
>This is a project-by-project combination though - if you use Psalm you might not want to get PHPStan diagnostics.

Totally fair. I guess the ease of intelephense is that you don't have to decide or configure which diagnostics extension you want to use; Diagnostics just work out-of-the-box. That said, I have no idea how phpstan, psalm, and intelephense diagnostics compare.

>But sure -- it could be easier to setup 🤔

And in your defense, this Neovim built-in LSP thing is quite new! 

I procrastinated for a long time on LSP, and I was blown away how easy it was to get up and running with [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), **_with_** diagnostics for lua, vimscript, js, vuejs, html, json, yaml, etc.  Given that most of these other LSP clients (at least as far as I have tried) ship with diagnostics, I wonder if phpactor could pull in phpstan as an enabled dependency by default, giving people the ability to disable and/or switch to psalm or whatever?

PS. I really appreciate all your work over the years on phpactor! Also, thank you for your help today!

**Comment by dantleech** [comment]
It's tricky - maybe offering basic PHP linting would be a good low-effort default - Phpactor does offer some diagnostics currently - but only for things it can refactor.

**Comment by dantleech** [comment]
just an update on this: phpstan (and psalm) are now bundled by default (but need to be enabled in config) and phpactor has basic PHP liniting enabled by default.

**Comment by JoyceBabu** [comment]
Is this released?

**Comment by dantleech** [comment]
not sure exactly to what you are referring, but most of the work from the past 3 months has been done in `master` and there has been no tag.
