### ISSUE TITLE
Phpstan plugin's error underline ignores whitespaces

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1222]
When underlining the offending line of code, the Phpstan plugin seems to ignore the leading whitespace but doesn't adjust the length for it:

![image](https://user-images.githubusercontent.com/12109622/111266359-1e048980-8633-11eb-8774-f25328450083.png)

**Comment by dantleech** [comment]
Yes - PHPStan doesn't provide offsets. The best we can do is underline the text on the line only.

**Comment by BladeMF** [comment]
Agreed. My point was, if we just know the line, we could just offset it to underline the whole line, rather than finish abruptly :-)

**Comment by dantleech** [comment]
Yes no excuse - I was lazy.

**Comment by BladeMF** [comment]
Having something not being perfect beats not having it in that case :-) You can just post where the relevant code is in case someone has time :-)

**Comment by dantleech** [comment]
https://github.com/phpactor/language-server-phpstan-extension/blob/master/lib/Model/DiagnosticsParser.php#L28

**Comment by dantleech** [comment]
Added this utlity for a similar purpose https://github.com/phpactor/text-document/blob/master/lib/Util/LineColRangeForLine.php
