### ISSUE TITLE
Document Nvim LSP configuation

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1225]
As https://github.com/neovim/nvim-lspconfig/pull/769#issuecomment-803469191 has been merged we can document setting up Phpactor with nvim LSP.

**Comment by weeman1337** [comment]
This is done, isn't it?

https://phpactor.readthedocs.io/en/master/lsp/vim.html

https://github.com/phpactor/phpactor/commit/6d400b88d5f790d91427e333caa0cd9d5b0441ad#diff-5b804b92d5f1dedbb5bac77e5c7240b8643167a36259098ee37d7ae8a16274b5

**Comment by dantleech** [comment]
Indeed, thanks!
