### ISSUE TITLE
[nvim][Telescope] LSP: server does not support workspace_symbol

### ISSUE THREAD

**Issue by weeman1337** [phpactor/phpactor#1227]
I am tried to set up Phpactor with NeoVim and [Telescope](https://github.com/nvim-telescope/telescope.nvim).

Telescope provides searching `lsp_workspace_symbols`. Unfortunately that doesn't work: `LSP: server does not support workspace_symbol`.

Another search `lsp_document_symbols` on the other hand is working.

I am not sure whether this is a missing feature of the Phpactor LSP or Telescope or NeoVim's LSP Client.

If I can help with additional information let me know.

**Comment by dantleech** [comment]
This is currently a missing feature in Phpactor - but I don't think it would be hard to implement as the search capabilities are already in place, I'll see if I can pick some low hanging fruit...

**Comment by dantleech** [comment]
Implemented in https://github.com/phpactor/phpactor/pull/1228 - currently only supporting classes, function names and and constnats according to what is currently indexed - so it will not find class members. I'm not sure what the more popular use cases are here.

**Comment by weeman1337** [comment]
Wow that was fast @dantleech . With the latest `master` it didn't work. I have run `composer i` and `./phpactor cache:clear`.

Running the completion returns `No results from workspace/symbol. Maybe try a different query: Telescope lsp_workspace_symbols query=example`. I am not sure whether that is a Telescope or Phpactor issue.

> currently only supporting classes, function names 

That is a great start.

**Comment by weeman1337** [comment]
I found that it is a Telescope issue:

- https://github.com/nvim-telescope/telescope.nvim/issues/568
- https://github.com/nvim-telescope/telescope.nvim/pull/705

So thanks for the preparation :)

**Comment by dantleech** [comment]
I guess it wouldn't harm to return all symbols for an empty string.
