### ISSUE TITLE
Completion for built in functions doesn't provide parameters

### ISSUE THREAD

**Issue by weeman1337** [phpactor/phpactor#1230]
Steps to reproduce:
- opan a PHP file
- start completion, e.g. `in_arr`
- complete
- it will be completed to `in_array`

Expected:
- `in_array()`

Notes:
- works with another language server
- as far as I understand [the code](https://github.com/phpactor/language-server-phpactor-extensions/blob/e7a1f49a2b78f285ba2bf78b37f2fcf409a5b1f9/lib/LanguageServerCompletion/Handler/CompletionHandler.php) this should be somehow working
- if I can help debugging this let me know

My Setup:
- NeoVim (latest 0.5)

<details>

<summary>config</summary>

```
call plug#begin(stdpath('data') . '/plugged')

Plug 'phpactor/phpactor', {'for': 'php', 'tag': '*', 'do': 'composer install --no-dev -o'}
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/nvim-compe'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'

call plug#end()

lua << EOT

local nvim_lsp = require('lspconfig')
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

require'lspconfig'.phpactor.setup{
    capabilities = capabilities,
    cmd = {
        "/home/weeman/.local/share/nvim/plugged/phpactor/bin/phpactor",
        "language-server"
    }
}

vim.o.completeopt = "menuone,noselect"

require('compe').setup({
    enabled = true,
    source = {
        path = true,
        buffer =     { menu = "[BUF]" },
        nvim_lsp =   { menu = "[LSP]" },
        nvim_lua =   { menu = "[Lua]" },
    },
})
EOT
```
</details>

**Comment by dantleech** [comment]
I think this works with method calls, but doesn't seem to be working with functions

**Comment by dantleech** [comment]
This method https://github.com/phpactor/completion/blob/2347168e27a13e88418ea4dd44fc57778c2e8b93/lib/Bridge/WorseReflection/Formatter/FunctionLikeSnippetFormatter.php#L14-L18 should have worked for both methods and functions.

**Comment by weeman1337** [comment]
Thanks for the fast response :rocket: 

I have investigated further and swapped `nvim-compe` with `deoplete.nvim`. Snippets are now working (for functions and method calls).

→ Sorry for bothering you with this issue. It is hard to configure everything in a way so that things are working..

**Comment by dantleech** [comment]
hmm, it should work, I can reproduce, it's a valid bug :smile:

**Comment by weeman1337** [comment]
I had some built in snippets active. So the issue is it doesn't complete built in function parameters.

**Comment by weeman1337** [comment]
@dantleech I hav tried to implement that. Thee the referenced PR.

**Comment by weeman1337** [comment]
With the merge of phpactor/completion#50 this is done I think?

**Comment by dantleech** [comment]
indeed :)
