### ISSUE TITLE
LSP: Renaming is unreliable

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1232]
Using the index seems at least unreliable, as the index may frequently be out of date for example:

![image](https://user-images.githubusercontent.com/530801/114507506-226c9400-9c2b-11eb-8175-41ed68e0f280.png)
_variable renamed instead of method_

The old method brute force scanned the FS, but it was very accurate. One middle solution would be to use the locate the files and then analyse them.

In the case above the file was changed on the FS and the watcher failed to update the file in the index, causing the reference to refer to the wrong position in the file, renaming the var instead of the member,

**Comment by BladeMF** [comment]
I agree with the general premise. I think the only problems I have seen are related with the files not being saved. The only time I have seen variable/member not being renamed was related to files not being saved. Actually I am not sure the `VariableReferenceFinder` uses the index at all.

**Comment by dantleech** [comment]
Variable reference finder doesn't, the member finder does.

**Comment by BladeMF** [comment]
I am a bit worried of invoking `WorseReflection` so many times per rename because I expect it would be really slow. 

Currently if you paste large chink of code and there are lots of unknown/unimported classes, giving the suggestion could take tens of seconds. I suspect a similar cause.

**Comment by dantleech** [comment]
The existing rename method(s) works very well given they read every single file in the project - although I do want to use the index for this now. You are referring to the diagnostics, which are very inefficient currently.

**Comment by BladeMF** [comment]
I can go along with that, as long as it doesn't become very slow.

**Comment by dantleech** [comment]
Should be fixed now.
