### ISSUE TITLE
LSP: Rename constant definitions not updated

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1233]
When renaming members, constant declarations seem not to be updated.

**Comment by BladeMF** [comment]
Interesting. Did you use my code as a base for this?

**Comment by dantleech** [comment]
No this is new code, the solution would be the same as for property declaratins: https://github.com/phpactor/language-server-phpactor-extensions/blob/985f99cf643ab24423b92998b8aa7318424d1c3d/lib/LanguageServerRename/Adapter/Worse/MemberRenamer.php#L22-L30

**Comment by BladeMF** [comment]
Let me finish the other review and will take a look at it. Just out of curiosity, why didn't the tests detect that? Probably the reference is at the wrong place?

**Comment by dantleech** [comment]
Fixed !
