### ISSUE TITLE
Question: Is there an indexer file ??

### ISSUE THREAD

**Issue by Goku-San** [phpactor/phpactor#1234]
Hello, 
I just set up phpactor with CoC but without the coc-phpactor extension using this [advice](https://phpactor.readthedocs.io/en/master/lsp/vim.html#lsp-client-vim-coc)

I just changed the command section instead  of ```'phpactor'```,
to the full path of the plugin bin ```~/.vim/autoload/plugged/phpactor/bin/phpactor```, and it works just fine.

When I open Laravel project (any .php file) it starts indexing! 
So is there a  indexer file ( if so, what is the name ) or is it just in memory ??

Thanks.

**Comment by dantleech** [comment]
The index file is in `~/cache/phpactor/xxxxx` the index is based on the directory in which you started Phpactor, so if you have any thing that automatically changes the current-working-directory that might cause the index to rebuild.

**Comment by Goku-San** [comment]
Ok, found it.

Thanks again for the fast response.

**Comment by dantleech** [comment]
Saying that, with the language server, it should not change as the root is initialized when the LS starts.

**Comment by Goku-San** [comment]
No, its not changing, its oki.

> When I open Laravel project (any .php file) it starts indexing!

By this I meant when a php file is opened in a project the LS starts, the indexer runs through the project to scan for changes.
I just didn't know where the file was.

The first time it took 60sec to index everything, now it 0.03 :) so no worries.
