### ISSUE TITLE
[CB] Provide camelization in twig templates.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#124]
e.g. when generating a value object we can assume that the value of the object is named after the class, currently it is just lowercased:

```
<?php

namespace Phpactor\ClassMover\Domain\Query;

final class MethodQuery
{
    private $methodquery;

```

**Comment by mamazu** [comment]
If this is still active, what code action would this affect. This sounds like an easy fix.

**Comment by dantleech** [comment]
Not even sure. 5 years and probably nobody needed this :D

**Comment by dantleech** [comment]
It's about the code generation, so anything that uses the code builder templates (generate decorator included). Probably it's even in Twig now
