### ISSUE TITLE
Generate setters

### ISSUE THREAD

**Issue by weeman1337** [phpactor/phpactor#1241]
It would be nice if phpactor could generate setters as well.

At the moment it is already possible to generate accessors. Getter generation should work in the same way. How should the function be named? Common speech would be `generate setters`. In phpactor maybe more `generate mutators` (compared to `accessors` ↔ `getters`).

I would also implement that :man_dancing:

**Comment by dantleech** [comment]
yes. currently there is only an API for generating single getters: https://github.com/phpactor/code-transform/blob/master/lib/Domain/Refactor/GenerateAccessor.php

The legacy RPC handler (in `lib/Extension/CodeTransformExtra/Rpc/GenerateAccessorHandler.php`) will also generate all accessors for a class.

This functionality is currently missing from the language server.

**Comment by Florian-Merle** [comment]
I guess this issue can be closed now.

See https://github.com/phpactor/phpactor/pull/1948
