### ISSUE TITLE
LSP Constructor snippet

### ISSUE THREAD

**Issue by weeman1337** [phpactor/phpactor#1247]
At the moment the LSP completion doesn't provide constructor snippets.

I have already implemented that locally. But I am not sure about how to do that regarding the architecture. My approach is just placing `NameSearchResultConstructorSnippetFormatter` next to [`NameSearchResultFunctionSnippetFormatter`](https://github.com/phpactor/completion/blob/master/lib/Core/Formatter/NameSearchResultFunctionSnippetFormatter.php).

What do you think @dantleech ?

**Comment by dantleech** [comment]
Acutlaly `NameSearcResultFunctionFormatter` is in the wrong place - it depends on an external lib (worse-reflection) so it should be in `Bridge/WorseReflection/Formatter`. Otherwise, yes I think it could be in the same place, it mostly depends on what it's dependencies are,

**Comment by weeman1337** [comment]
I will implement that later (and move the `NameSearcResultFunctionFormatter`),
