### ISSUE TITLE
LSP Class / function imports should be provided by additionalTextEdits instead as a command

### ISSUE THREAD

**Issue by weeman1337** [phpactor/phpactor#1248]
At the moment class and function imports are provided as a command with the completion item: https://github.com/phpactor/language-server-phpactor-extensions/blob/master/lib/LanguageServerCompletion/Handler/CompletionHandler.php#L123

My completion kind of freaks out because at the same time the completion is inserted the command modifies the document. Digging the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion) I found that it is suggested to provide imports via `additionalTextEdits`:

> Additional text edits should be used to change text unrelated to the
> current cursor position (for example adding an import statement at the
> top of the file if the completion item will insert an unqualified type).

Looking into the completion plugins I found that they support `additionalTextEdits` as well.

As I already found all the places I could work on this one if the approach is okay @dantleech .

**Comment by dantleech** [comment]
Hmm, that would be better. It was implemented this way in order  to reuse the existing legacy logic. It might be possible to do this from the LSP handler using the "code builder" package instead.

Strange that it freaks out for you though (I do notice glitches sometimes though, maybe relate)

**Comment by dantleech** [comment]
I think this only happens in relation to snippets (as noted in https://github.com/phpactor/completion/pull/52)

**Comment by weeman1337** [comment]
I will have a look at this one in the next days.

**Comment by weeman1337** [comment]
Regarding the architecture: Who should add the `additionalTextEdits`?

Should that be done in the `completion` package or in the `language-server-extension` one?

**Comment by dantleech** [comment]
I think `language-server-phpactor-extension`.

The completion result already provides the FQN of the class/function to be imported if it's required.

There is a semi-awful library `phpactor/code-builder` which you can use to generate the TextEdits required:

```
        $textEdits = $this->updater->textEditsFor(
            SourceCodeBuilder::create()->use($newName->__toString())->build(),
            Code::fromString($source->__toString())
        );
```
where `updater` implements `phpactor/code-builder:Domain\Updater`.

- [use of code-builder in class-mover package](https://github.com/phpactor/class-mover/blob/47166e1fb095ff178dacb7a1b765b5c6e59f42e5/lib/Adapter/TolerantParser/TolerantClassReplacer.php#L97)
- [utlity to convert phpactor text edits to LSP text edits](https://github.com/phpactor/language-server-phpactor-extensions/blob/320b8b0e1103a648f1f6a1892f5604e7c964252d/lib/LanguageServerBridge/Converter/TextEditConverter.php#L16)

**Comment by weeman1337** [comment]
Almost done @dantleech  :balloon: 

One thing is missing: I found out that during serialisation something like the following is the result:

```
"{"id":2,"result":{"isIncomplete":false,"items":[{"label":"RuntimeException","kind":7,"detail":"\u2193 RuntimeException","documentation":"","sortText":"0231-RuntimeException","insertText":"RuntimeException(${1})${0}","insertTextFormat":2,"additionalTextEdits":[{"\u0000Phpactor\\TextDocument\\TextEdit\u0000start":{"\u0000Phpactor\\TextDocument\\ByteOffset\u0000offset":53},"\u0000Phpactor\\TextDocument\\TextEdit\u0000length":0,"\u0000Phpactor\\TextDocument\\TextEdit\u0000replacement":"\nuse RuntimeException;"}]},{"label":"RuntimeException","kind":7,"detail":"\u2193 PHPUnit\\Framework\\MockObject\\RuntimeException","documentation":"","sortText":"0195-RuntimeException","insertText":"RuntimeException(${1})${0}","insertTextFormat":2,"additionalTextEdits":[{"\u0000Phpactor\\TextDocument\\TextEdit\u0000start":{"\u0000Phpactor\\TextDocument\\ByteOffset\u0000offset":22},"\u0000Phpactor\\TextDocument\\TextEdit\u0000length":0,"\u0000Phpactor\\TextDocument\\TextEdit\u0000replacement":"use PHPUnit\\Framework\\MockObject\\RuntimeException;\n"}]},{"label":"RuntimeException","kind":7,"detail":"\u2193 PHPUnit\\TextUI\\RuntimeException","documentation":"","sortText":"0191-RuntimeException","insertText":"RuntimeException(${1})${0}","insertTextFormat":2,"additionalTextEdits":[{"\u0000Phpactor\\TextDocument\\TextEdit\u0000start":{"\u0000Phpactor\\TextDocument\\ByteOffset\u0000offset":53},"\u0000Phpactor\\TextDocument\\Text
```

That is created by [LspMessageSerializer](https://github.com/phpactor/language-server/blob/d00472c50711f91091e6c93df89b435ecf386d6e/lib/Core/Server/Transmitter/LspMessageSerializer.php#L17). For example one key of the TextEdit is `"\u0000Phpactor\\TextDocument\\TextEdit\u0000start"`. Of course that isn't understood by the client.

I think the serialisation isn't done properly. Should I implement `JsonSerializable` for `TextEdits` and `TextEdit`?

**Comment by dantleech** [comment]
No - it should not be a _Phpactor_ text edit, but an LSP text edit as [per the link above](https://github.com/phpactor/language-server-phpactor-extensions/blob/320b8b0e1103a648f1f6a1892f5604e7c964252d/lib/LanguageServerBridge/Converter/TextEditConverter.php#L16) you can concert it.

**Comment by weeman1337** [comment]
Argh - my fault. Next time I will look through the hints more carefully.

**Comment by weeman1337** [comment]
This is done
