### ISSUE TITLE
LSP: Completion option whether or not to add imports for global functions

### ISSUE THREAD

**Issue by weeman1337** [phpactor/phpactor#1249]
There are different factions out in the world. Some people prefer to import global functions others don't.

Maybe there should be an option for that.

**Comment by dantleech** [comment]
This is the option you are looking for: https://phpactor.readthedocs.io/en/master/reference/configuration.html#language-server-code-transform-import-globals

**Comment by weeman1337** [comment]
That option targets classes and functions. I was just talking about functions.
