### ISSUE TITLE
Issue when creating classes with special characters

### ISSUE THREAD

**Issue by Willdogx** [phpactor/phpactor#1264]
I have a class Logroño.php, and when I create the class with phpactor the following is created:
```
<?php

declare(strict_types=1);

namespace App\Business\Comparison\Service;

class Logro%C3%B1o
{
}

```

I am using vscode by the way

**Comment by BladeMF** [comment]
What is the path of the file? Is the namespace correct?

**Comment by Willdogx** [comment]
the path is src/Business/Comparison/Service/Logroño.php and the namespace is correct. Also the file is in utf-8

**Comment by BladeMF** [comment]
Oh, I see. That's actually `ñ`, but URL encoded.

**Comment by Willdogx** [comment]
Yes. Actually in my case I no longer need that class, but still it's something that one may need, I was trying to create a model based on a spanish city, be it good or bad design, sometime one may need to use special characters.
Is there some reason for url encoding the class name?
I can try to fix it and do a pull request

**Comment by Willdogx** [comment]
Sorry for the delay.
vscode is encoding the uris in the request, which makes sense, since it's an uri
```
[[0;32mINFO[0;0m][[1;37m466259.279438[0;0m] IN:{
    "jsonrpc": "2.0",
    "id": 104,
    "method": "textDocument\/documentSymbol",
    "params": {
        "textDocument": {
            "uri": "file:\/\/\/home\/santi\/Projects\/symfony-api-test\/src\/Business\/Model\/Logro%C3%B1o.php"
        }
    }
}
```

And I fixed the issue by doing a `urldecode` in the constructors of
[TextDocumentItem](https://github.com/phpactor/language-server-protocol/blob/master/src/TextDocumentItem.php)
[TextDocumentIdentifier](https://github.com/phpactor/language-server-protocol/blob/master/src/TextDocumentIdentifier.php)
[VersionedTextDocumentIdentifier](https://github.com/phpactor/language-server-protocol/blob/master/src/VersionedTextDocumentIdentifier.php)

which are being used by Phpactor\LanguageServer\Core\Workspace\Workspace

What do you think? do you want me to do a pull request?

**Comment by dantleech** [comment]
hmm, those protocol classes are auto-generated. I think we need to update the [transpiler](https://github.com/phpactor/language-server-protocol). I will investigate.

**Comment by dantleech** [comment]
I've updated the protocol - which involved updating to 3.15 and potentially breaking things (the constructor argument order is not preserved when transpiling). If you want to try it: https://github.com/phpactor/language-server-protocol/pull/14 if it breaks too much we can cherry pick the urldecode changes.

**Comment by dantleech** [comment]
ok, it will take some work to update everything to work with newly transpiled protocol.  I might get round to updating things to merge that above PR this week, or not ... so feel free to PR your changes and any others that are visible in that PR.

**Comment by dantleech** [comment]
assunming this is fixed
