### ISSUE TITLE
Incorrect range for coc-funcobj-i

### ISSUE THREAD

**Issue by gbprod** [phpactor/phpactor#1265]
Hi,

I've got a problem with `coc-funcobj-i`. My settings : 

    xmap if <Plug>(coc-funcobj-i)
    omap if <Plug>(coc-funcobj-i)
    xmap af <Plug>(coc-funcobj-a)
    omap af <Plug>(coc-funcobj-a)

When I use it, it will include the first `{` of the method : 

Example here using `vif` : 

![2021-05-10-154757_757x368_scrot](https://user-images.githubusercontent.com/3751019/117669472-36ae9d00-b1a7-11eb-88ee-ce22fefb9694.png)

Expected : 

![2021-05-10-154816_670x294_scrot](https://user-images.githubusercontent.com/3751019/117669497-3ca47e00-b1a7-11eb-899d-9326c2490ddd.png)

Thanks for your awesome work !
I can try to fix it (if you have any advice to where I should look :) )

**Comment by dantleech** [comment]
to be honest i'm not entirely sure how this is meant to work, currently it's just using the range from the node in the AST [here](https://github.com/phpactor/language-server-phpactor-extensions/blob/master/lib/LanguageServerSelectionRange/Model/RangeProvider.php)
