### ISSUE TITLE
Missing method finder disagreement with completors

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1269]
That method `children()` is in the completor list, but `WorseMissingMethodFinder` (I think) is saying it doesn't exist.
![image](https://user-images.githubusercontent.com/12109622/118237732-44626c00-b4a0-11eb-971b-e02e29c7cd6d.png)

I wonder if its because of the union return value?
![image](https://user-images.githubusercontent.com/12109622/118237852-66f48500-b4a0-11eb-8886-3a804b13773a.png)

The method definition:
![image](https://user-images.githubusercontent.com/12109622/118238042-ab802080-b4a0-11eb-981f-f6de8cc6d4fa.png)

**Comment by dantleech** [comment]
I think that's coming from the hover - it's rendering the exception message

**Comment by dantleech** [comment]
I don't think that's coming from the missing method finder, more likely the hover or signature provider

**Comment by BladeMF** [comment]
See the yellow underline? That's the diagnostic. The hover is reporting phpstan errors.

**Comment by dantleech** [comment]
Seems to work now, tested in VS code
