### ISSUE TITLE
Suggest methods when using `parent::`

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1272]
When here:
```php
function __construct() {
  parent::<>
}
```
no completions are suggested. I expect the `__construct` to be suggested.

_(Not sure if that is not reported somewhere)_

**Comment by dantleech** [comment]
Moving to https://github.com/phpactor/phpactor/issues/1177

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/phpactor/commit/3e7cb48b0ca429f92bcd57c236c39f170e9d23b1
