### ISSUE TITLE
Can't run update extension command if no extension lockfile

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#1282]
On the composer.json schema, a call to `phpactor extension:update` is made. But if no lockfiles are generated beforehand, composer will hard crash on this.

So we should IMO generate a basic lockfile in here so it is used and updated afterwards or something along those lines ?

Because currently it triggers the following errors as I have no extensions installed (non core I mean) :

```bash
$ phpactor extension:update
Loading composer repositories with package information
Updating dependencies
Nothing to install or update
Generating autoload files

In Locker.php line 279:
                                                     
  No lockfile found. Unable to read locked packages  
                                                     

extension:update
```

**Comment by mamazu** [comment]
Is this still relevant since there isn't any extension command anymore?
