### ISSUE TITLE
Use composer2 for extensions

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#1283]
Currently, it looks like composer1 is used to manage extenions, while the version was released months ago.

It triggers warning that we should update to composer2 :

```bash
$ phpactor extension:update
<warning>Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2</warning>
...
```

**Comment by dantleech** [comment]
Yes this is a big piece of technical debt. The solution I prefer is removing the composer dep entirely and depending on the host composer bin.

**Comment by dantleech** [comment]
See #1250

**Comment by Taluu** [comment]
Closing as it duplicates #1250 then. Good to know it's being considered. :}
