### ISSUE TITLE
iterable still returned as unresolvable

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1286]
[Here](https://github.com/phpactor/worse-reflection/blob/05909171023c13002dcbbdd1cbf7a825162ebd26/lib/Bridge/TolerantParser/Patch/TolerantQualifiedNameResolver.php#L31) it says that `iterable` needs to be removed later and a PR is cited. That PR is merged.

Currently `iterable` is causing problems in `WorseUnresolvableClassNameFinder` and I think needs to be excluded there along with 'parent', 'self' and 'static'.

**Comment by BladeMF** [comment]
cc @camilledejoye 
I think it's your comment there.

**Comment by dantleech** [comment]
Note that I changed the diagnostics to not report not-found errors by default: https://github.com/phpactor/language-server-phpactor-extensions/commit/e6758bb15c80cffef8be114403fe3c8402b19bee

**Comment by BladeMF** [comment]
The trouble with this is that:
* it is causing exceptions in my last PR and I am not sure how to fix it (whether it is a real case or not).
* `iterable` is being reported as unknown class

**Comment by BladeMF** [comment]
@dantleech @camilledejoye We need to do something because this causes exceptions in any file with `iterable` inside. I suggest we add it to the list [here](https://github.com/phpactor/code-transform/blob/master/lib/Adapter/WorseReflection/Helper/WorseUnresolvableClassNameFinder.php#L93).

**Comment by dantleech** [comment]
I think we should check to see if it's an instanceof `ResolvedName` before calling that method, or otherwise ensure that it is a `ResolvedName` and has that method..

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/code-transform/commit/f461294d4d7e69ca93367ea0893082068532d950
