### ISSUE TITLE
how to use omni complete

### ISSUE THREAD

**Issue by likelxl** [phpactor/phpactor#1289]
i want use phpactor in vim, how to set?
i installed it in ~/.vim/pack/plugins/start, but my config is below, where is wrong?
```
omnifunc=phpcomplete#CompletePHP
```

**Comment by dantleech** [comment]
https://phpactor.readthedocs.io/en/master/usage/vim-plugin.html ?

**Comment by likelxl** [comment]
i have seen this document and follow it, i can use the command, but only can not set omnifunc to phpactor, because the posix extend functions are not work well.
![录屏_deepin-terminal_20210604151918](https://user-images.githubusercontent.com/12811070/120762171-926f0a80-c548-11eb-908d-eb1c27f020c4.gif)

**Comment by dantleech** [comment]
```

**Comment by weeman1337** [comment]
As mentioned above using language servers may provide the best experience.

* vim: https://github.com/prabirshrestha/vim-lsp
* neovim: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#phpactor

In addition to that you need a completion plugin, for example:
* vim: https://github.com/ncm2/ncm2 + https://github.com/ncm2/ncm2-vim-lsp
* neovim: https://github.com/hrsh7th/nvim-compe or https://github.com/nvim-lua/completion-nvim

CoC on the other hand implements LSP completely separated from vim built in / plugin methods. Works quite well but does not fit my philosophy having smaller tools composed getting stuff done.

If it helps you can have a look at my (neovim) setup [here](https://pubcode.weimann.digital/projects/dotfiles/blob/master/.config/nvim/lua/weeman).
