### ISSUE TITLE
Can I use this plugin with vim and lsp

### ISSUE THREAD

**Issue by bsde1234** [phpactor/phpactor#1291]
I am using vim and [lsp](https://github.com/prabirshrestha/vim-lsp). Is it possible to combine this plugin with vim-lsp here https://github.com/prabirshrestha/vim-lsp ? Thanks

**Comment by dantleech** [comment]
It would be possible, only CoC and NeoVim LSP are docmented. The configuration is likely similar to the COC instructions "without the Phpactor extension"

**Comment by weeman1337** [comment]
@bsde1234 did you give CoC or NeoVim LSP a try?

For NeoVim you should use their LSP Config plugin: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md

If you have any questions or trouble just ask here I will try to help.

**Comment by dantleech** [comment]
Closing this now as NVIM LSP and CoC are probably better options.
