### ISSUE TITLE
[VIM] How to activate Class name completion?

### ISSUE THREAD

**Issue by Slamdunk** [phpactor/phpactor#1295]
Hi, sorry for the newbie question: I've have phpactor enabled and running flawlessly with `ncm2` on Vim 8.2, and it correctly suggests variables, methods, constants etc, but not classnames, neither mine nor default ones like `stdClass`, what am I missing?

Once I write the class name, the `imp(o)rt_missing_classes` works as expected, so the map is there and working.

Config (part of):
```
Plug 'phpactor/phpactor', {'for': 'php', 'tag': '*', 'do': 'composer install --no-dev --prefer-dist --classmap-authoritative'}
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2'
Plug 'phpactor/ncm2-phpactor'

autocmd BufEnter *.php,*.phtml call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
```

**Comment by dantleech** [comment]
It should "just work" - the non-language server class completion depends on `composer` being used IIRC. it's possible that it's been inadvertently disabled.

You might try `phpactor index:build` to see if that helps (it might be trying to use the index)

**Comment by Slamdunk** [comment]
Hi, indeed a `phpactor index:build` on the project pops the class completion up, but there are some blocking drawbacks:

1. the command must be run manually, for each project
2. on a regular project of mine, it takes up to 12 min
3. it significantly slows VIM down

None of this is your fault of course, and I don't expect you to solve it.

But I wonder: what if the class completion could simply get the list from `get_declared_classes()` + `vendor/composer/autoload_classmap.php` generated from a `composer install --optimize-autoloader`?
I guess the indexing would be not necessary at all, and we could achieve 99% of the use cases, WDYT?

**Comment by dantleech** [comment]
It should already work without the index.

```
 phpactor container:dump --tag=completion_worse.tolerant_completor
```

the completor is `scf_class` - it will infer the class names from the file names according to PSR0/PSR4

**Comment by Slamdunk** [comment]
The [doc says](https://phpactor.readthedocs.io/en/master/reference/completion.html#scf-class) that `[scf_class] is disabled by default when using the Language Server.` which, AFAICT, is the one used for VIM+ncm2.

Do you know how could I re-enable it?

**Comment by dantleech** [comment]
It's not used by `phpactor-ncm2` -  (see [coc](https://github.com/neoclide/coc-html) for a LS client).

 > Note that there is also a declared_class completor, so I wonder if something else is up.

maybe it doesn't trigger? you can try and invoke Omni complete to manually trigger class completion (IIRC this might be what I did...) https://phpactor.readthedocs.io/en/master/vim-plugin/man.html (see `omni-completion`)

**Comment by Slamdunk** [comment]
Indeed with vim built-in `omni-completion` instead of `ncm2` it works.
`omni-completion` is a bit rough to get it working while typing, but I guess we can't have everything :)

My I ask to see your VIM configuration file, just to be inspired?

**Comment by dantleech** [comment]
My VIM configuratio nisn't very inspired, but my Phpactor configuration can be found in `:help phpactor` (I use the CoC language server client with Phpactor - which is a different experience)
