### ISSUE TITLE
regression: LSP aliases created for existing names

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1300]
Given `ResultInterface` is already imported, and it is the same one we are completing here:

![image](https://user-images.githubusercontent.com/530801/122638606-fbc84f00-d0ec-11eb-9fff-962c98c2dd14.png)

It will import:

```
use PhpBench\Model\ResultInterface;
use PhpBench\Model\ResultInterface as PhpBenchResultInterface;
```

cc @weeman1337 - not sure if that's realated to your changes recently?

**Comment by weeman1337** [comment]
Could be this one: https://github.com/phpactor/code-transform/commit/871509e723b6ce77524ca5735335a0dcf11f6751 If this causes the issue the fix should better be on the compltion side checking for the same FQN.

Give me some seconds I will have a look.

**Comment by weeman1337** [comment]
Is this one solved with the re-work of the class name import on completion?
