### ISSUE TITLE
Can I start with websocket server instead of tcp server?

### ISSUE THREAD

**Issue by huanghantao** [phpactor/phpactor#1301]
It seems that `phpactor language-server --address=127.0.0.1:9901 -vvv` will start a tcp server, can I start a websocket?

**Comment by dantleech** [comment]
Do you mean a unix-socket? (Websocket [is TCP](https://en.wikipedia.org/wiki/WebSocket)?) or why would you want a websocket?

**Comment by huanghantao** [comment]
I don't mean unix socket, just like: https://github.com/TypeFox/monaco-languageclient/blob/master/example/src/client.ts#L40

It seems that the language client use websocket connection. This is the result of tcpdump:

[lsp.txt](https://github.com/phpactor/phpactor/files/6684748/lsp.txt)

Because Github doesn't support `.pcap`, so I change the ext name to `.txt`

**Comment by dantleech** [comment]
So no, if I understand it, not currently. The http://github.com/phpactor/language-server package only supports TCP and stdio. Support could probably be added via. https://github.com/amphp/websocket-server

**Comment by huanghantao** [comment]
Do you have any plans for future support?

**Comment by dantleech** [comment]
It's the first time I've seen this requirement, so I'm not sure how common this is. no current plans.

**Comment by huanghantao** [comment]
OK, maybe I can implement one myself, but I'm not familiar with `phpactor`, can you tell me which components I need to use phpActor?

**Comment by huanghantao** [comment]
I would like to try a Web IDE for PHP, but the browser can't use socket directly, so websocket are usually used.

**Comment by dantleech** [comment]
This is the part which decides which strategy to use: https://github.com/phpactor/language-server/blob/3475c59d76d8f5a7eb3d8745387f734dc057c8e4/lib/LanguageServerBuilder.php#L105-L129

So I would look at how https://github.com/amphp/websocket-server can be integrated with that if applicable

**Comment by huanghantao** [comment]
Thank you very much
