### ISSUE TITLE
Type inference in arrow functions is not working

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1303]
This doesn't work:
![image](https://user-images.githubusercontent.com/12109622/123079367-8d54fb00-d424-11eb-9837-b132e65c3c81.png)

But this does:
![image](https://user-images.githubusercontent.com/12109622/123079431-9e057100-d424-11eb-822e-a8b453d82288.png)

**Comment by dantleech** [comment]
![image](https://user-images.githubusercontent.com/530801/164889077-ead18e15-5049-4a03-ab0a-c481fd50b689.png)
