### ISSUE TITLE
[NVIM] Problems with the installation

### ISSUE THREAD

**Issue by guiwestrup** [phpactor/phpactor#1306]
![image](https://user-images.githubusercontent.com/23106111/124139098-aa5d7f80-da5d-11eb-8b6d-9c2c2d54116c.png)

i already had installed the phpactor, but in nvim he had a problem, after the command 'PlugClean', hes return:
![image](https://user-images.githubusercontent.com/23106111/124139329-e4c71c80-da5d-11eb-8690-37ab18c73f5f.png)

Always, when i run the command 'PlugUpdate' :
![image](https://user-images.githubusercontent.com/23106111/124139458-032d1800-da5e-11eb-961b-b8603310d32e.png)

When i go in folder ~/.vim/plugged/phpactor:
![image](https://user-images.githubusercontent.com/23106111/124139572-20fa7d00-da5e-11eb-9607-91b87a81dee3.png)

Anyone have idea how to resolve?

**Comment by weeman1337** [comment]
Could you check what running `composer install` in `~/.vim/plugged/phpactor` shows?

**Comment by guiwestrup** [comment]
Nice! That was it, the php that was on my pc was missing some libs.
Thank you so much!
