### ISSUE TITLE
Import class does not pick up typed properties

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1310]
In this example:

```php
class ListTest extends KernelTestCase
{
	private Renderer $renderer;
	private Environment $twig;
```
`Renderer` and `Environment`  are not picked up as types for importing. If I say, for example, use the same classes in a method like `Renderer::class`, they are then suggested.

**Comment by dantleech** [comment]
actually i can't reproduce this, assuming it was fixed in the meantime :)
