### ISSUE TITLE
Undefined index: didChangeWatchedFiles on nvim-lspconfig

### ISSUE THREAD

**Issue by afranioce** [phpactor/phpactor#1311]
I'm using the neovim 0.5 + nvim-lspconfig

![image](https://user-images.githubusercontent.com/893768/125803202-fa3e247b-9de6-4d9d-8475-ffe96cc57ea8.png)

**Comment by demonking** [comment]
Has get some more information, but will analyse it at another time further

```
LSP[phpactor] File watcher died: Inotify exited with status code "1": Setting up watches.  Beware: since -r was given, this may take a whi
le!
Failed to watch /home/xxxx/app; upper limit on inotify watches reached!
Please increase the amount of inotify watches allowed per user via `/proc/sys/fs/inotify/max_user_watches'.
```

**Comment by dantleech** [comment]
@demonking this is a common issue, you need to increase the `inotify` watches as indicateed (e.g. see [stackoverflow](https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached))

**Comment by dantleech** [comment]
The main issue can be fixed by checking for the existence of the array key [here](https://github.com/phpactor/language-server-phpactor-extensions/blob/0b9e415d354e80d7268e229a0577373caaa8b068/lib/LanguageServerIndexer/Watcher/LanguageServerWatcher.php#L64) and returning false if it is not existing.

**Comment by dantleech** [comment]
Hmm, the above referenced code uses null coalesce `??` so it should not produce that error. Are you using that version of the code @afranioce ?

**Comment by demonking** [comment]
@dantleech i have used the same code, only after modification and break up the coalesce into 2 if's i could get my error.

**Comment by dantleech** [comment]
> into 2 if's i could get my error

you mean fix the error?

**Comment by Feleys** [comment]
Hi, I've same issue with afranioce.
neovim version: 0.5
phpactor version: dev-master@1194ce124a358e115d8e88c9309367cd7acf62ba

If you need more info pls tell me, thank you!

```
[ WARN ] 2021-09-14T10:09:39+0800 ] ...neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]	"The language server phpactor triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ ERROR ] 2021-09-14T10:09:40+0800 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"phpactor"	"stderr"	"PHP Notice:  Undefined index: didChangeWatchedFiles in /Users/kyrie/.config/temp/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerIndexer/Watcher/LanguageServerWatcher.php on line 64\nNotice: Undefined index: didChangeWatchedFiles in /Users/kyrie/.config/temp/phpactor/vendor/phpactor/language-server-phpactor-extensions/lib/LanguageServerIndexer/Watcher/LanguageServerWatcher.php on line 64\n"

**Comment by camilledejoye** [comment]
This should be fixed by https://github.com/phpactor/language-server/pull/38

@dantleech for the coalesce operator:
```php
(bool)$this->clientCapabilities->workspace['didChangeWatchedFiles'] ?? false
```
It a priority issue:
```php
(bool) ($this->clientCapabilities->workspace['didChangeWatchedFiles'] ?? false)
```
