### ISSUE TITLE
Broken dependencies on Packagist (composer 2)

### ISSUE THREAD

**Issue by meldafert** [phpactor/phpactor#1322]
Hello,
I was attempting to install phpactor by just doing `composer require phpactor/phpactor`.
This however fails with:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpactor/phpactor ^0.17.2 -> satisfiable by phpactor/phpactor[0.17.2].
    - phpactor/phpactor 0.17.2 requires phpactor/worse-reflection ^0.4.6 -> found phpactor/worse-reflection[dev-master, 0.4.x-dev (alias of dev-master)] but it does not match your minimum-stability.
```
Looking at [packagist](https://packagist.org/packages/phpactor/phpactor#0.17.2), that does appear to be correct.
`phpactor/phpactor 0.17.2` requires `phpactor/worse-reflection ^0.4.6`, however that version is not published yet - the latest stable one on available on packagist is [0.4.5](https://packagist.org/packages/phpactor/worse-reflection#0.4.5), at least at the time of writing.
There is however an unstable version on packagist [dev-master](https://packagist.org/packages/phpactor/worse-reflection#dev-master), which composer (rightfully, imo) ignores.

Is this an issue with composer 2 no longer allowing unstable versions? I am using composer version 2.1.9.

EDIT: This also affects versions 0.17.1 and 0.17.0.
The version I managed to get running is 0.16.2.

**Comment by Lctrs** [comment]
You can install v0.17 by adding this to your `composer.json` : 
```
{
  ...
  "minimum-stability": "dev",
  "prefer-stable": true
}
```
