### ISSUE TITLE
autocomplete with require_once not work

### ISSUE THREAD

**Issue by cxwx** [phpactor/phpactor#1325]
```
<?php
require_once('../jpgraph/src/jpgraph.php');
$graph = new Graph(900, 500);
$graph->
?>
```
could not autocomplete
does `phpactor` support `require_once('')`  ?

**Comment by dantleech** [comment]
if used as an LSP it will use an indexer, I assume `Graph` is in the global namespace, in which case it should work, `require_once` or not.

If this is using the vanilla VIM plugin (i.e. no indexer) then this will not work, require_once is not followed.
