### ISSUE TITLE
Behat extension support over LSP

### ISSUE THREAD

**Issue by dklymenk** [phpactor/phpactor#1328]
Hello,

I am wondering if the behat extension is supposed to work when using phpactor over LSP.

Things I did:

1. Installed the extension `phpactor extension:install phpactor/behat-extension`
2. Tweaked my nvim config to start phpactor in `cucumber` files.
3. Made sure I have `behat.yml.dist` file at the project root.
4. Opened a `*.feature` file. The filetype is correctly recognized as `cucumber`, the phpactor server is started, I see the "indexing completed" message, but neither the go to definition nor the auto-completion work. There is no feedback, no error on go to definition and the only auto-completion I get is some basic current buffer one.

Please let me know if It is supposed to work and If can provide any additional information.

P.S. Thank you very much for phpactor.

**Comment by dantleech** [comment]
I've ported the Behat extension to the monolith, you just need to enable it and configure your LSP client: https://phpactor.readthedocs.io/en/master/integrations/behat.html
