### ISSUE TITLE
PHP 8.1 Support / upgrade Tolerant PHP parser

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1331]
In order to support 8.1 we at least need to update the tolerant PHP parser. This is easier said than done as the 1.0 version broke B/C.

**Comment by BladeMF** [comment]
Do we know what's affected by this BC break?

**Comment by dantleech** [comment]
Mostly everything as the API changed

**Comment by Einenlum** [comment]
Do you talk about the 0.1.0 version?
Seems like the main branch and 0.1.1 tag are [still accepting >=7.2](https://github.com/microsoft/tolerant-php-parser/blob/main/composer.json#L6).

**Comment by dantleech** [comment]
I mean the internal API has changed so we can't simply update the dependency regardless of the supportee PHP version

**Comment by dantleech** [comment]
Updated worse reflection: https://github.com/phpactor/worse-reflection/pull/110

**Comment by dantleech** [comment]
The following packages need to be updated:

- [ ] phpactor/class-mover
- [ ] phpactor/code-builder
- [ ] phpactor/code-transform
- [ ] phpactor/completion
- [ ] phpactor/indexer-extension
- [ ] phpactor/language-server-phpactor-extensions
- [ ] phpactor/reference-finder
- [x] phpactor/worse-reflection

**Comment by dantleech** [comment]
Packages that need 8.0/8.1 support

- code-builder: support for union types (?)

**Comment by dantleech** [comment]
Done
