### ISSUE TITLE
Unknown text document "file://…"

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#1336]
This has happened to me while performing various actions. For instance, when using `:lua vim.lsp.buf.definition()`, I get

`phpactor: -32603: Exception [Phpactor\LanguageServer\Core\Workspace\Exception\UnknownDocument] Unknown text document "file:///home/gregoire/workspace/dev-workspace/www/ms.search.manomano.com/src/SmartCategories/Application/Rollback.php"`

Note that `:PhpactorGoToDefinition` works just fine.

Closing the editor and reopening it works as well, so it might be related to new files (indexing?) and LSP.

**Comment by dantleech** [comment]
yeah, that's likely because of the indexer, but it shouldn't be fatal. be good to get a stack trace from the log file

**Comment by dantleech** [comment]
do yu still get this?

**Comment by greg0ire** [comment]
Nope, now it seems to work great 👍
