### ISSUE TITLE
autocomplete doesn't work for named arguments in procedural functions

### ISSUE THREAD

**Issue by dhenfie** [phpactor/phpactor#1339]
autocomplete does not work for named arguments in procedural functions,
however it works for method

**Comment by Rambhosale** [comment]
Adding a screenshot of a similar issue
Autocomplete suggestion name for a variable is empty, but the variable type is fetched correctly and after selecting the empty option it gets completed by the correct variable
![image](https://user-images.githubusercontent.com/21305685/152629666-137a991b-f847-41a5-a5c7-9d7843c5bd3f.png)

But the autocomplete is working correctly for methods autocomplete
![image](https://user-images.githubusercontent.com/21305685/152629722-6126181a-18ed-4bd9-8aa8-3b383f894c8f.png)

**Comment by dantleech** [comment]
don't think the above is related to this ticket, could you open another?

r.e. the original ticket named arguments are not tested for procedural function calls, but it should be fairly easy to add support:

https://github.com/phpactor/completion/blob/master/lib/Bridge/TolerantParser/WorseReflection/WorseNamedParameterCompletor.php
https://github.com/phpactor/completion/blob/master/tests/Integration/Bridge/TolerantParser/WorseReflection/WorseNamedParameterCompletorTest.php

**Comment by dantleech** [comment]
reviewing this, i think i was confused with my original comment, of course this ticket is fine.
