### ISSUE TITLE
Missing autocomplete suggestion name for variables

### ISSUE THREAD

**Issue by Rambhosale** [phpactor/phpactor#1342]
Adding a screenshot of a similar issue

**Started getting this issue after upgrading the PHP version from 8.0 to 8.1.2**

Autocomplete suggestion name for a variable is empty, but the variable type is fetched correctly and after selecting the empty option it gets completed by the correct variable
![image](https://user-images.githubusercontent.com/21305685/152629666-137a991b-f847-41a5-a5c7-9d7843c5bd3f.png)

But the autocomplete is working correctly for methods autocomplete
![image](https://user-images.githubusercontent.com/21305685/152629722-6126181a-18ed-4bd9-8aa8-3b383f894c8f.png)

**Comment by Rambhosale** [comment]
@dantleech I have been using phpactor for some time after trying some other options and this one fits my use cases and is reliable, I am thinking about contributing to this project. I have roughly gone through Microsoft's LSP documentation and this project's code, I am a little lost on where to start exactly, for example solving the above mentioned issue, if **possible** can you list a brief overview on which parts to start with, debug and your workflow setup to developed/solve it.

**Comment by dantleech** [comment]
So, maybe unfortunately, Phpactor is split into _many_ repoisotires. For LSP however almost all related functionality is here: https://github.com/phpactor/language-server-phpactor-extensions with, for example the completion request being handled [here](https://github.com/phpactor/language-server-phpactor-extensions/blob/master/lib/LanguageServerCompletion/Handler/CompletionHandler.php).

It in turn will delegate to the https://github.com/phpactor/completion` library...

**Comment by Rambhosale** [comment]
Thanks for giving the directions, I'll give a try solving this issue

**Comment by Rambhosale** [comment]
I tried using the LSP with bare minimum config on a docker container and it was working fine, so I think it should be an issue with my config and not related to phpactor hence closing this issue
