### ISSUE TITLE
getIterator should either be compatiable 

### ISSUE THREAD

**Issue by more-pepsi** [phpactor/phpactor#1344]
Can't get anything to run 

"\/Users\/bill\/.vim\/plugged\/phpactor\/vendor\/jetbrains\/phpstorm-stubs"
    ],
    "indexer.poll_time": 5000,
  1   2022-02-12T15:40:32.400 INFO (pid:87379) [services] - registered service "languageserver.haskell"
    1 2022-02-12T15:40:32.433 INFO (pid:87379) [plugin] - coc.nvim initialized with node: v13.9.0 after 97ms
    2 2022-02-12T15:40:32.452 ERROR (pid:87379) [language-client-index] - Error: spawn phpactor ENOENT
    3     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    4     at onErrorNT (internal/child_process.js:467:16)
    5     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    6   errno: -2,
    7   code: 'ENOENT',
    8   syscall: 'spawn phpactor',
    9   path: 'phpactor',
   10   spawnargs: [ 'language-server' ]
   11 }
   12 2022-02-12T15:40:32.453 ERROR (pid:87379) [server] - unhandledRejection  Promise {
   13   <rejected> 'Launching server "phpactor" using command phpactor failed.'
   14 } Launching server "phpactor" using command phpactor failed.
   15 2022-02-12T15:41:10.030 INFO (pid:87379) [attach] - receive notification: openLog []
~
~

605: Exception not caught: Could not parse response from Phpactor: Vim(let):E474: Unidentified byte: PHP Deprecated:  Return type of Php
actor\ConfigLoader\Core\PathCandidates::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or
the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/bill/.vim/plugged/phpactor/vend
or/phpactor/config-loader/lib/Core/PathCandidates.php on line 24^@Deprecated: Return type of Phpactor\ConfigLoader\Core\PathCandidates::g
etIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute sh
ould be used to temporarily suppress the notice in /Users/bill/.vim/plugged/phpactor/vendor/phpactor/config-loader/lib/Core/PathCa
ndidates.php on line 24^@PHP Deprecated:  Return type of Phpactor\FilePathResolver\Expanders::getIterator() should either be compatible w
ith IteratorAggregate::getIterator(): Traversable, or the #[\Return

**Comment by dantleech** [comment]
The master branch now disables Deprecation warnings by default, which should solve this issue until the next major PHP release.
