### ISSUE TITLE
Help with extension

### ISSUE THREAD

**Issue by haringsrob** [phpactor/phpactor#1348]
Hey!

I was wondering if you could help me forward.

I am working on a completion extension.

With the following code:

```php
function test(string $b) {}

function bar() {
    var_dump('foo');
    test('ba<cursor>');
}
```

Based on the cursor position, what is the best way to get the function that I am in? (so test for this example).

When using the ToleranCompletor, the node is a `CompoundStatementNode` but it contains the full contents up until the cursor. And I cannot seem to figure out how to travers or get the correct position.

Thanks in advance!

**Comment by haringsrob** [comment]
As the extension manager is now obsolete this doesn't matter much anymore.

@dantleech are you open for built in helper functionality for Laravel (with a config toggle?)

**Comment by dantleech** [comment]
yes, I'd be happy to have it integrated into the monolith.

**Comment by dantleech** [comment]
and sorry i missed this, to get the function would be something like:

```
$node = $rootNode->findDescendentNodeAtPosition($offset);
$functionNode = $node->getFirstAncestor(CallExpression::class); // null|CallExpression
```

or similar. I think the `TolerantCompletor` would already provide you with the node at offset:
```
interface TolerantCompletor
{
    /**
     * @return Generator & iterable<Suggestion>
     */
    public function complete(Node $node, TextDocument $source, ByteOffset $offset): Generator;
}

```

**Comment by haringsrob** [comment]
Thanks! I will have a go at it maybe today.

**Comment by dantleech** [comment]
was going to say follow up i a [Discusson](https://github.com/phpactor/phpactor/discussions) but I see you already did and I never saw it :/
