### ISSUE TITLE
InMemoryIndex could be used at runtime

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1356]
I keep the index storage on in-memory filesystem (`XDG_CACHE_HOME = '/tmp'`) and persist it sometimes to disk. 

Looking at how indexing works in LSP I found that `SerializedIndex` with `FileRepository` is used to that. There is also `InMemorySearchIndex` that seems to be unused (at least by `IndexAgentBuilder`).

We can expect that using in-memory index can be faster that the filesystem equivalent (even if the FS is placed in memory). On the other side building the index can take very long time. After I switched locally to `InMemorySearchIndex`, it took about 8 minutes for some project. It (and frequent crashes while building) means that it's good to keep a backup somewhere (I do it for backup from/restore to `/tmp`). In practice, building the index starting on partially outdated backup takes significantly shorter than starting from the empty set.

@dantleech what do you think about using both repositories: `FileRepository` (or something more appropriate) as a backup storage to keep the index across sessions and `InMemorySearchIndex` that can be created from it, used at runtime and persisted on some event or on the user demand?

**Comment by dantleech** [comment]
Not sure what sort of performance we gain could be made:

- All lookups are effectively key/value
- The search index _is_ loaded into memory and flushed to disk on write (and is < 1MB I think)

If loading the main index into memory increases perforamnce then we need to weigh that against the memory impact (I can have ~10 or more projects at the same time, if each of them uses 500MB for an index ....)

**Comment by przepompownia** [comment]
> If loading the main index into memory increases perforamnce then we need to weigh that against the memory impact (I can have ~10 or more projects at the same time, if each of them uses 500MB for an index ....)

Maybe it would be per-project selectable thing or to be switched to a persistent storage in case of exceeding some configured memory amount. 

Thanks for response. Maybe I'll try to make such simple comparison in some time (~650 MB index).

**Comment by dantleech** [comment]
Closing this but feel free to continue the discussion
