### ISSUE TITLE
The "languageserver.phpactor"  server crashed 4 times in last 3 minutes

### ISSUE THREAD

**Issue by Goku-San** [phpactor/phpactor#1362]
Hello,

Like the title states the error is The "languageserver.phpactor"  server crashed 4 times in last 3 minutes. This is what I got from coc.nvim.

**System**  **Manjaro Linux**
**OS** **XFCE**
**PHP** version **PHP 8.1.3 (cli) (built: Feb 16 2022 13:27:56) (NTS)**
**Vim** version **8.2.4464**
**PHP actor** version **latest**. Just reinstalled via vim. Tried with both commands, same result.
```vim
Plug 'phpactor/phpactor', {'for': 'php', 'do': 'composer install --no-dev -o'}
Plug 'phpactor/phpactor', {'for': 'php', 'branch': 'master', 'do': 'composer install --no-scripts --no-dev -o'}
```
After reading #1092 I tried this command ``/path/to/phpactor index:build --reset -vvv`` and this is the result
<details><summary>$ ~/.vim/autoload/plugged/phpactor/bin/phpactor index:build --reset -vvv</summary>
<pre><code>
[DEBU][533455.286168] Resolved path "%cache%/index/%project_id%" to "/home/goran/.cache/phpactor/index/TodoList-e7fa36"[]
[DEBU][533455.286640] Resolved path "%project_root%" to "/home/goran/PhpAndLaravel/allLaravel/api/Bitfumes/Laravel-8.x/TodoList"[]
[DEBU][533455.287031] Resolved path "%project_root%" to "/home/goran/PhpAndLaravel/allLaravel/api/Bitfumes/Laravel-8.x/TodoList"[]
[DEBU][533455.304396] Resolved path "%application_root%/vendor/jetbrains/phpstorm-stubs" to "/home/goran/.vim/autoload/plugged/phpactor/vendor/jetbrains/phpstorm-stubs"[]
[DEBU][533455.304496] Resolved path "%cache%/worse-reflection" to "/home/goran/.cache/phpactor/worse-reflection"[]
[DEBU][533455.305067] Resolved path "%project_root%/vendor/autoload.php" to "/home/goran/PhpAndLaravel/allLaravel/api/Bitfumes/Laravel-8.x/TodoList/vendor/autoload.php"[]
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Filesystem\Filesystem" not found in /home/goran/.vim/autoload/plugged/phpactor/lib/Filesystem/Adapter/Simple/SimpleFilesystem.php:31
Stack trace:
#0 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(223): Phpactor\Filesystem\Adapter\Simple\SimpleFilesystem->__construct()
#1 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(239): Phpactor\Indexer\IndexAgentBuilder->buildFilesystem()
#2 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(216): Phpactor\Indexer\IndexAgentBuilder->buildFileListProviders()
#3 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(209): Phpactor\Indexer\IndexAgentBuilder->buildFileListProvider()
#4 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(118): Phpactor\Indexer\IndexAgentBuilder->buildIndexer()
#5 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(108): Phpactor\Indexer\IndexAgentBuilder->buildTestAgent()
#6 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(175): Phpactor\Indexer\IndexAgentBuilder->buildAgent()
#7 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#8 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(129): Phpactor\Container\PhpactorContainer->get()
#9 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#10 /home/goran/.vim/autoload/plugged/phpactor/lib/Extension/WorseReflection/WorseReflectionExtension.php(82): Phpactor\Container\PhpactorContainer->get()
#11 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Extension\WorseReflection\WorseReflectionExtension->Phpactor\Extension\WorseReflection\{closure}()
#12 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(222): Phpactor\Container\PhpactorContainer->get()
#13 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#14 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(167): Phpactor\Container\PhpactorContainer->get()
#15 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#16 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(202): Phpactor\Container\PhpactorContainer->get()
#17 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#18 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(149): Phpactor\Container\PhpactorContainer->get()
#19 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#20 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/CommandLoader/ContainerCommandLoader.php(45): Phpactor\Container\PhpactorContainer->get()
#21 /home/goran/.vim/autoload/plugged/phpactor/lib/Extension/Console/PhpactorCommandLoader.php(11): Symfony\Component\Console\CommandLoader\ContainerCommandLoader->get()
#22 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/Application.php(585): Phpactor\Extension\Console\PhpactorCommandLoader->get()
#23 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/Application.php(674): Symfony\Component\Console\Application->has()
#24 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/Application.php(259): Symfony\Component\Console\Application->find()
#25 /home/goran/.vim/autoload/plugged/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#26 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#27 /home/goran/.vim/autoload/plugged/phpactor/bin/phpactor(47): Symfony\Component\Console\Application->run()
#28 {main}
  thrown in /home/goran/.vim/autoload/plugged/phpactor/lib/Filesystem/Adapter/Simple/SimpleFilesystem.php on line 31
Fatal error: Uncaught Error: Class "Symfony\Component\Filesystem\Filesystem" not found in /home/goran/.vim/autoload/plugged/phpactor/lib/Filesystem/Adapter/Simple/SimpleFilesystem.php:31
Stack trace:
#0 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(223): Phpactor\Filesystem\Adapter\Simple\SimpleFilesystem->__construct()
#1 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(239): Phpactor\Indexer\IndexAgentBuilder->buildFilesystem()
#2 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(216): Phpactor\Indexer\IndexAgentBuilder->buildFileListProviders()
#3 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(209): Phpactor\Indexer\IndexAgentBuilder->buildFileListProvider()
#4 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(118): Phpactor\Indexer\IndexAgentBuilder->buildIndexer()
#5 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/IndexAgentBuilder.php(108): Phpactor\Indexer\IndexAgentBuilder->buildTestAgent()
#6 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(175): Phpactor\Indexer\IndexAgentBuilder->buildAgent()
#7 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#8 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(129): Phpactor\Container\PhpactorContainer->get()
#9 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#10 /home/goran/.vim/autoload/plugged/phpactor/lib/Extension/WorseReflection/WorseReflectionExtension.php(82): Phpactor\Container\PhpactorContainer->get()
#11 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Extension\WorseReflection\WorseReflectionExtension->Phpactor\Extension\WorseReflection\{closure}()
#12 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(222): Phpactor\Container\PhpactorContainer->get()
#13 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#14 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(167): Phpactor\Container\PhpactorContainer->get()
#15 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#16 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(202): Phpactor\Container\PhpactorContainer->get()
#17 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#18 /home/goran/.vim/autoload/plugged/phpactor/lib/Indexer/Extension/IndexerExtension.php(149): Phpactor\Container\PhpactorContainer->get()
#19 /home/goran/.vim/autoload/plugged/phpactor/vendor/phpactor/container/lib/PhpactorContainer.php(79): Phpactor\Indexer\Extension\IndexerExtension->Phpactor\Indexer\Extension\{closure}()
#20 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/CommandLoader/ContainerCommandLoader.php(45): Phpactor\Container\PhpactorContainer->get()
#21 /home/goran/.vim/autoload/plugged/phpactor/lib/Extension/Console/PhpactorCommandLoader.php(11): Symfony\Component\Console\CommandLoader\ContainerCommandLoader->get()
#22 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/Application.php(585): Phpactor\Extension\Console\PhpactorCommandLoader->get()
#23 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/Application.php(674): Symfony\Component\Console\Application->has()
#24 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/Application.php(259): Symfony\Component\Console\Application->find()
#25 /home/goran/.vim/autoload/plugged/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#26 /home/goran/.vim/autoload/plugged/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#27 /home/goran/.vim/autoload/plugged/phpactor/bin/phpactor(47): Symfony\Component\Console\Application->run()
#28 {main}
  thrown in /home/goran/.vim/autoload/plugged/phpactor/lib/Filesystem/Adapter/Simple/SimpleFilesystem.php on line 31
</code></pre>
</details>

**The important part is**
```
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Filesystem\Filesystem" not found in /home/goran/.vim/autoload/plugged/phpactor/lib/Filesystem/Adapter/Simple/SimpleFilesystem.php:31
```
Thanks in advance for any guidance...

**Comment by dantleech** [comment]
it's because some depdencies that were only included in `dev` were required for `non-dev` durin the migration to the monolith. I've updated, can you try again?

**Comment by Goku-San** [comment]
Thanks for the update. It works with both commands.
