### ISSUE TITLE
LSP rename: missing `RenameFile` operation in `documentChanges`

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1366]
Currently when I try to rename some class form LSP client I have to rename its file manually. For a simple class with no references the server sends to the client `WorkspaceEdit` with a single `TextDocumentEdit` (as I guess from its format) inside `documentChanges`. It's enough to change the file content by some client's response handler. The original name remains untouched. 

After dumping such example edit in Lua format
```lua
{ -- WorkspaceEdit
  documentChanges = {
  { -- TextDocumentEdit
      edits = {
      {
          newText = "Arctgx\\PhpactorTestEnv",
          range = {
            ['end'] = {
              character = 32,
              line = 2
            },
            start = {
              character = 10,
              line = 2
            }
          }
        },
      {
          newText = "V",
          range = {
            ['end'] = {
              character = 7,
              line = 4
            },
            start = {
              character = 6,
              line = 4
            }
          }
        }
      },
      textDocument = {
        uri = "file:///home/arctgx/dev/arctgx/phpactor-test-env/src/Z.php",
        version = 7
      }
    },
  },
}
```
and adding `RenameFile` and applying such simulated response on the client side
```lua
local out = { -- WorkspaceEdit
  documentChanges = {
    { -- RenameFile
        kind = 'rename',
        oldUri = "file:///home/arctgx/dev/arctgx/phpactor-test-env/src/Z.php",
        newUri = "file:///home/arctgx/dev/arctgx/phpactor-test-env/src/V.php",
      },
  { -- TextDocumentEdit
      edits = {
      {
          newText = "Arctgx\\PhpactorTestEnv",
          range = {
            ['end'] = {
              character = 32,
              line = 2
            },
            start = {
              character = 10,
              line = 2
            }
          }
        },
      {
          newText = "V",
          range = {
            ['end'] = {
              character = 7,
              line = 4
            },
            start = {
              character = 6,
              line = 4
            }
          }
        }
      },
      textDocument = {
        uri = "file:///home/arctgx/dev/arctgx/phpactor-test-env/src/V.php",
        version = 7
      }
    },
  },
}
vim.lsp.util.apply_workspace_edit(out, vim.lsp.get_client_by_id(1).offset_encoding)
```
I get the expected change. It suggests that `RenameFile` should be added to `documentChanges`.

**Comment by dantleech** [comment]
interesting. We currently have:

https://github.com/phpactor/phpactor/blob/85f0b0e9baa403d5624e130b55dc30a4b87e2d76/lib/Extension/LanguageServerRename/Handler/FileRenameHandler.php#L21

Which would, in theory, pick up file renames from the IDE, it's not however very reliable, and in general the indexed-based renaming functionality in Phpactor doesn't work so great currently, but that's another story.

If it's possible to add a rename operation to the workspace edits when renaming a _class_ (as opposed to a file) then we should do that.

**Comment by przepompownia** [comment]
> If it's possible to add a rename operation to the workspace edits when renaming a class (as opposed to a file) then we should do that.

If I correctly understood [workspace/willRenameFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) idea, it's not indended to response with renaming command but only with editions inside files intended to rename by the client hence the aforementioned opposition. 

This command seems to be not directly supported by nvim's built-in client (so there is no handler that possibly makes renaming afterward or something other that allows learning what possibly should be done ;)) but it's still possible to run it manually and use some other handler that uses WorkspaceEdit object:
```lua
vim.lsp.buf_request(1, 'workspace/willRenameFiles', { files = {{ oldUri = vim.uri_from_bufnr(1), newUri = vim.uri_from_bufnr(1):gsub('Z', 'V')} } }, function(...) vim.pretty_print(...); vim.lsp.handlers['workspace/applyEdit'](...) end)
```
but it fails because [FileRenamer attempts to find references to something not existing yet](https://github.com/phpactor/phpactor/blob/85f0b0e9baa403d5624e130b55dc30a4b87e2d76/lib/Extension/LanguageServerRename/Adapter/ClassMover/FileRenamer.php#L58) (i.e. file under the new target path).

Both `FileRenameHandler` and [RenameHandler](https://github.com/phpactor/phpactor/blob/85f0b0e9baa403d5624e130b55dc30a4b87e2d76/lib/Extension/LanguageServerRename/Handler/RenameHandler.php) use [`LocatedTextEditConverter`](https://github.com/phpactor/phpactor/blob/85f0b0e9baa403d5624e130b55dc30a4b87e2d76/lib/Extension/LanguageServerRename/Util/LocatedTextEditConverter.php#L25) to  to build `WorkspaceEdit` but it's factory does not allow to insert `RenameFile` instances into `documentChanges`.

**Comment by dantleech** [comment]
Right, `willRenameFiles` allows the client to tell the server that _it_ will rename a file.

The Phpactor LSP library is only supporting 3.10 but the changes you describe are in 3.13:

> Since version 3.13.0 a workspace edit can contain resource operations (create, delete or rename files and folders)  

I'll see if I can update the protocol lib.

**Comment by dantleech** [comment]
>  ... to build WorkspaceEdit but it's factory does not allow to insert RenameFile instances into documentChanges.

I see, it should be easy to add those operations.

**Comment by przepompownia** [comment]
@dantleech Please let me know if you would like to implement it. 

For example I have doubt if `ClassRenamer::rename` should yield not only `LocatedTextEdit` but also `RenameFile` (or its equivalent class) (probably one in practice). This and some other doubts stops me from proposing a PR too early.

**Comment by dantleech** [comment]
I think yielding a "RenameFile" operation would work:

For reference this is what the old RPC class mover does: https://github.com/phpactor/phpactor/blob/7e476e8b7ebfbabcc99cbe5763ad0345038d4313/1#L69-L78
