### ISSUE TITLE
`FileSearchIndex`: prevent from crashing because of the lack of memory

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1372]
When I start the server with an empty index I often get crash when `FileSearchIndex` attempts to flush its internal record array to the file named `search` (`array_unique` on the table of rows). 
```
- [ERROR][2022-03-17 17:02:32] .../vim/lsp/rpc.lua:420	"rpc"	"/home/arctgx/.vim/pack/bundle/opt/phpactor/bin/phpactor"	"stderr"	"Fatal error: Out of memory (allocated 380633088) (tried to allocate 139971984183561 bytes) in /home/arctgx/.vim/pack/bundle/opt/phpactor/lib/Indexer/Adapter/Php/FileSearchIndex.php on line 82\n"
```
I still have no idea what is the source of strange amount `139971984183561 bytes` and how to prevent such overflow in some good way. 

Currently I have a problem with reproducing it but I'll try to catch all entries into a separate log when after encountering this bug again. 

I have `memory_limit` set to `-1` and 12 GB RAM.

**Comment by dantleech** [comment]
strange, it flushes every 10,000 writes:

https://github.com/phpactor/phpactor/blob/7e476e8b7ebfbabcc99cbe5763ad0345038d4313/lib/Indexer/Adapter/Php/FileSearchIndex.php#L19

You could try reducing that number (perhaps to 100 or so) and then seeing how big the file is and what's in it.

**Comment by dantleech** [comment]
is this still an issue? is it reproducable?

**Comment by przepompownia** [comment]
I didn't check why but in about last month I did not notice such crash (while before it was a regular behavior, especially on indexing from scratch) so at the moment we can close this.
