### ISSUE TITLE
New command: IndexCleanup

### ISSUE THREAD

**Issue by flavioheleno** [phpactor/phpactor#1374]
Hi, thanks for your hard work in phpactor, it is a very useful tool and I love it!

I just found out that my phpactor cache folder was using around ~5GB of my local storage and tried to find 
an "official" way to clean it, but ended up just deleting the sub directories myself.

Is it suitable to add an "IndexCleanupCommand" to phpactor? If so, I'm happy to provide a PR implementing it.

Would also appreciate any guidance on what you'd like to see in such command (eg. parameters etc).

**Comment by dantleech** [comment]
I was thinking similar:

- Command to show the indexes and allow you to interactively purge those indexes

```
(1) deploy-b9cc03                 512MB
(2) lautsprecher-teufel-efcafd    1.2GB
(3) phpactor-c6a5f2               274MB
(4) vetpartners-drupal-b78a49     301MB
(5) vetpartners-sylius-515090     831MB

Purge: 1
```
or similar.

The file path is only defined relative to the current "project" in the `IndexerExtension` as:

```
"indexer.index_path": "%cache%\/index\/%project_id%"
```

so could take the `dirname` of that to show the existing indexes.

**Comment by flavioheleno** [comment]
Wow, that's neat @dantleech!

The only thing I'd do differently is add a `(6) All     <total space>`, in which case it would drop all cache directories
so that I'd not have to go 1-5 manually.
