### ISSUE TITLE
phpactor#Update don't work with dein.vim plugin manager

### ISSUE THREAD

**Issue by lhyaax** [phpactor/phpactor#139]
I set bundle dir to  `~/.cache/vimfiles`, and  install phpactor by [dein.vim](https://github.com/Shougo/dein.vim), 
then I  could see the plugin dir is .`cache/vimfiles/repos/github.com/phpactor/phpactor`.
when I run `phpactor#Update()`,  ` s:phpactorpath` return .`cache/vimfiles/.cache/vimrc/.dein/plugin`, 
not `.cache/vimfiles/repos/github.com/phpactor`, so could't find `.git` and `vendor`.
dein.vim cache plugin?
I am a newbie.  can you help me ,thx.

**Comment by dantleech** [comment]
Which platform are you on Windows? Linux? Mac?

It should return the path of `phpactor.vim` and the parent directory should be the directory containing both the `.git` source.

You will currently *always* need to run `compoer install` in the download directory as stated in the documentaiton.

**Comment by dantleech** [comment]
Closing die to lack of info.

**Comment by ekes** [comment]
For what it's worth I just installed:
```
call dein#add('phpactor/phpactor', {'build': 'composer install'})
call dein#update()
```
This is only the second thing I've installed with it, so possibly not optimum way (like what does the for: php do in the documented version?). But it's a start for anyone wondering.
