### ISSUE TITLE
Crash in projects with encodings other than UTF-8

### ISSUE THREAD

**Issue by sleetdrop** [phpactor/phpactor#1391]
I have an old project which has php files in Chinese encoding GB18030, phpactor crashes from time to time. I got the following error in the debug log:
`phpactor.CRITICAL: Could not encode JSON: "Malformed UTF-8 characters, possibly incorrectly encoded" [] []`

**Comment by dantleech** [comment]
hm, is this using an LSP client or is it only happening with the VIM plugin? if an LSP client, which one?

**Comment by sleetdrop** [comment]
I use [sublime-phpactor-plugin](https://github.com/tkotosz/sublime-phpactor-plugin)

**Comment by sleetdrop** [comment]
I use [sublime-phpactor-plugin](https://github.com/tkotosz/sublime-phpactor-plugin) follow the guide here https://phpactor.readthedocs.io/en/master/usage/getting-started.html

**Comment by dantleech** [comment]
AFAIK the LSP specification assumes documents are UTF-8 - at least there is no LSP way I can see to tell the server the document encoding: https://microsoft.github.io/language-server-protocol/specification#textDocumentItem

Can you provide or point me to a file encoded in GB18030?

**Comment by sleetdrop** [comment]
Not every GB18030 encoded file would cause this crash, and it didn't show the problematic file name in the debug log. I will dig  the code a bit later and add some extra logs. If I got something new, I will provide it here.

**Comment by PierreRambaud** [comment]
I also encounter an issue, but I don't know if it's related to the encoded file :thinking: 
It just stopped and emacs no longer respond until I kill the phpactor server

**Comment by dantleech** [comment]
that sounds more like phpactor getting locked up, e.g. https://github.com/phpactor/phpactor/issues/1627

**Comment by dantleech** [comment]
Hopefully fixed in #2557
