### ISSUE TITLE
Php 8.1 phpactor starting with error

### ISSUE THREAD

**Issue by infectos** [phpactor/phpactor#1398]
I have been using phpactor with php 7.4 successfully.
After updating my php version to 8.1 and updating phpactor to the latest version it doesn't start properly.
I use phpactor with neovim lsp-config.
that's what I got in `nvim/lsp.log`
```
[START][2022-04-03 03:46:42] LSP logging initiated 
[ERROR][2022-04-03 03:46:44] .../vim/lsp/rpc.lua:420    "rpc"   "phpactor"  "stderr"    "Starting language server, use -vvv for verbose output\n"
```
I don't know how to debug through nvim lsp

**Comment by dantleech** [comment]
are you using the latest version?

**Comment by infectos** [comment]
I am using this versions
`Phpactor dev-master@a218a0a8375f1ad3903edc3192f3176b947fbf28`
`PHP 8.1.3 (cli) (built: Feb 21 2022 14:48:42) (NTS)`
`NVIM v0.6.1`

**Comment by dantleech** [comment]
I think so: you can enable logging:


```
# ~/your/project/.phpactor.json
{
    "logging.enabled": true,
    "logging.path": "phpactor.log",
    "logging.level": "warning",
    "logging.formatter": "pretty"
}
```

**Comment by infectos** [comment]
Thank you for helping.
Turns out it was a matter of permissions.
`[[0;31mERRO[0;0m][[1;37m001427.261657[0;0m] Error in service "indexer" "Phpactor\Extension\LanguageServerIndexer\Handler\IndexerHandler:Phpactor\LanguageServer\Core\Service\{closure}": RecursiveDirectoryIterator::__construct(/_docker-infrastructure/docker/.data/postgres): Failed to open directory: Permission denied[]`
As I understand if there is a folder without proper permission, phpactor stops indexing with error.

**Comment by dantleech** [comment]
I've created this PR https://github.com/phpactor/phpactor/pull/1405 which will show an error in the client if a service stops unexpectedly.

As for "fixing" this issue I'm not sure. Probably the best way would be to change the indexing paths:

```
    "indexer.include_patterns": [
        "\/**\/*.php"
    ],
```

and maye that should default to something more sensible based on `composer.json`

**Comment by infectos** [comment]
I think we can close issue now, as it is not related to php version, and you created PR.
