### ISSUE TITLE
Use cases to help with the current type refactoring

### ISSUE THREAD

**Issue by camilledejoye** [phpactor/phpactor#1406]
Hi,

I see a lot of things going on about types lately, that's such a great news!
I don't know if you remember but a while back we talked about an issue related to type inference for class' properties. The type was inferred onto the `$this` variable instead of `$this->attrName` symbol.

With your latest changes this is now solved 🎉 
I didn't had the time to look to the changes closely though but when I tried it out I noticed a few things that I wanted to share if it can help you add more "complexe" or "realistic" use cases in the test scenario.

From this starting code:
```php
interface Timeline {
    public function getItems(): iterable;
}

class Trip implements Timeline {
    public function getItems(): iterable
    {
        return [];
    }

    public function getLinkedCustomer(): string
    {
        return 'James Bond';
    }
}

function doSomething(Timeline $timeline) {
    if ($timeline instanceof Trip) {
        $timeline->getLinkedCustomer();
    }
}

class Test {
    private Timeline $timeline;

    public function doSomething(): void
    {
        if ($this->timeline instanceof Trip) {
            $this->timeline->getLinkedCustomer();
        }
    }
}
````

The completion result include the methods from the inferred type by the signature are not correct in this example:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/11501572/161594902-104f3b10-33bc-4aec-819f-27a2a000551e.png">

Even though during the completion of class members the completor is able to use the resolved type, the diagnostics does not:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/11501572/161594408-c07f4b94-4ffb-4fff-82a5-286f240a18a8.png">
Neither are the go to definition in LSP or RPC.

We can also see that in the completion result for the class members the property is typed as `Timeline` when it could be interesting to instead have `Timeline|Trip` ?
<img width="668" alt="image" src="https://user-images.githubusercontent.com/11501572/161596103-e6c9dc55-f25c-4e3b-a33c-c37c00c67c82.png">

It might also be required by the indexer.
Because when searching for references for `Trip::getLinkedCustomer()` I have the call from the standard function (line 21) but not the one within the class (because inference from class member and standard variable still seems a bit different I guess).

So again, thank you for all the hard work. I hope this can help you in this huge entreprise that who just started around types.

**Comment by dantleech** [comment]
yes, I think this comes from the fact that with the new system there is only "one" type, which can itself be a union type, whereas in the old system there were/are multiple types (`Types`). So in some cases the Union is probably being returned but the code doesn't know how to use it, or similar.

one of the outstanding tasks is to remove all the references to `Types` which should resolve most of these issues I hope.

> We can also see that in the completion result for the class members the property is typed as Timeline when it could be interesting to instead have Timeline|Trip

yes, this will be solved (i hope) in #1402 currently we only support adding or removing a type in `if` and `assert` statements, but with that PR types should be fully "combinable".

**Comment by dantleech** [comment]
ok, with this [branch](https://github.com/phpactor/phpactor/pull/1416) I think it addresses the non-indexer issues:

![image](https://user-images.githubusercontent.com/530801/162636503-158d0c64-7671-4916-b654-7026303270c4.png)

![image](https://user-images.githubusercontent.com/530801/162637108-83ce20d5-099d-47bf-ab3e-0c3c2a8b3640.png)

**Comment by dantleech** [comment]
Everything seems to be fixed now, including the indexing (I can find all 3 methods), that PR was merged :tada:

**Comment by dantleech** [comment]
Oops, actually the adding the interface type _was_ working but now isn't, I created another issue to track that: https://github.com/phpactor/phpactor/issues/1419

thanks for this issue though, has been a good use case :)
