### ISSUE TITLE
go to definition and jump back

### ISSUE THREAD

**Issue by lhyaax** [phpactor/phpactor#142]
with vim,  I try
```
nnoremap <c-]> :call phpactor#GotoDefinition()<CR>

nnoremap <c-t> :call phpactor#JumpBack()<CR>
```
phpactor.vim plugin
```
""""""""""""""""
" Goto defintion
""""""""""""""""
function! phpactor#GotoDefinition()
    .........
    let cur_pos = getcurpos()
    let cur_pos[0] = bufnr('%')
    if !exists('s:phpactor_jump_stack')
        let s:phpactor_jump_stack = []
    endif
    call add(s:phpactor_jump_stack, cur_pos)
    .........
endfunction


""""""""""""""""
" Jump back
""""""""""""""""
function! phpactor#JumpBack()
    if !exists('s:phpactor_jump_stack') || len(s:phpactor_jump_stack) == 0
	return
    endif
    let prev_pos = s:phpactor_jump_stack[-1]
    let prev_buf = prev_pos[0]
    let prev_pos[0] = 0
    unlet s:phpactor_jump_stack[-1]
    exec 'buffer '.prev_buf
    call setpos('.', prev_pos)
endfunction
```

it's not work well.  probably, map wrong?

**Comment by dantleech** [comment]
Well, I guess you would need to store the filename of the current buffer. And I am not sure how global variables work in VIM tbh.

But --- VIM already has this feature `<ctrl-i>` jump back to previous cursor pos, `<ctrl-o>` jump forward.

https://www.cyberciti.biz/faq/unix-linux-vim-go-back-to-last-cursor-position/

**Comment by lhyaax** [comment]
thanks!  Goods man.  it's work!

I'll trouble you again,

I edit composer.json like this

```
    "autoload-dev": {
        "classmap": ["application/"],
        "files": [,
            "application/function.php"
        ]
    }
```
I want go to definition of funtion or complete function  in application/function.php,  It's not work. Could you give me some advices?

**Comment by dantleech** [comment]
Yeah - function completion is not supported currently as the system depends on class-autoloading. An alternative would be to just create a static class containing your functions.
