### ISSUE TITLE
Connection with LSP server crashes probably on content change

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1423]
https://user-images.githubusercontent.com/11404453/163055793-c3c0e1b5-6f55-43a4-b961-767f74318295.png
![image](https://user-images.githubusercontent.com/11404453/163055793-c3c0e1b5-6f55-43a4-b961-767f74318295.png)
![image](https://user-images.githubusercontent.com/11404453/163056893-b8a2b02e-695b-4e0c-85ed-48bba75d1522.png)

At the moment it's hard for me to catch more information

**Comment by przepompownia** [comment]
It's possible that the process survives thus no exceptions. On the process list I discovered ~25 orphaned processes.

**Comment by dantleech** [comment]
I've never got this, which version of neovim ? I'm using:
```
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by przepompownia** [comment]
I use master version 
```
NVIM v0.7.0-dev+1444-g7e1e90673                                                                                                                                                                                                                 
Build type: RelWithDebInfo                                                                                                                                                                                                                      
LuaJIT 2.1.0-beta3 
```
but have no problem with other language servers. If it will be needed I can make git bisect on neovim but it'll require some free time. To test the latest stable version I also have to prepare some compatibility reverts.

**Comment by dantleech** [comment]
ok thanks, i've updatred to 0.7.0 also so will see how that goes.

**Comment by dantleech** [comment]
have used this version for the past 3 days, but not geting this issue..

**Comment by przepompownia** [comment]
In the recent three working days I was unable to reproduce this problem. I was forced to run nvim and subprocesses with restricted memory (`systemd-run --scope -p MemoryMax=3072M nvim ...`) to avoid freezing the whole system before it'll run oom-killer (it not occured without phpactor). 

I keep neovim and phpactor updated to the recent changes so let's observe whether the problem persists. If so, in some free time I'll try to reproduce the problem without neovim, using another LS client etc.

**Comment by dantleech** [comment]
Not sure if related, but if I restart the server with `LspRestart`, most of the time nvim is killed with a `137`

**Comment by DanielSiepmann** [comment]
I receive `137` when I start neovim via `git mergetool` for merge conflicts in PHP files and finish via `:wqa`.
This breaks the whole merge workflow.

Disabling phpactor as lsp provider solves the issue. Might also be related?

**Comment by dantleech** [comment]
ok, not sure if the 137 is related to the original issue, but I can reliably stop the 137 by disabling the `inotify` (and `find`) file watchers:

```
    "indexer.enabled_watchers": [
        "php"
    ]
```

the `inotifywait` command (or `find` command) are spawened from the Phpactor process, and so maybe this a problem with Phpactor not terminating those properly (?)

**Comment by dantleech** [comment]
Fixed the 137 issue, not actually sure if that fixes the issue initially reported. If not, let's create a new issue.
