### ISSUE TITLE
Invalid diagnostics for "add missing @return`

### ISSUE THREAD

**Issue by camilledejoye** [phpactor/phpactor#1477]
Hi,

I just encountered this case:
![image](https://user-images.githubusercontent.com/11501572/165076689-11b3ab52-3406-4fbb-a611-d9dfd0dde460.png)

First thing, could be done later, maybe those notifications should have a lower level ?
It feels more like an information than a warning to me at first.

Then, maybe this diagnostics should only be sent when either:
* No return type is defined in PHP
* The PHP returned type is a generic one (`iterable`, `array` and any `SomeType<T>`)

**Comment by dantleech** [comment]
hm, are you on the lastest version? as of yesterday it should only according to the criteria you specified (more or less)

https://github.com/phpactor/phpactor/blob/3e7ca31ffd7f6b06f3d83a7508961702cb798b18/lib/CodeTransform/Adapter/WorseReflection/Transformer/UpdateDocblockTransformer.php

**Comment by dantleech** [comment]
This should fix it:

https://github.com/phpactor/phpactor/pull/1478/files#diff-6b23b2aeabfbe479032007e2cb716ad62377bf084d99f86129a202c18cd05db7R7-R9

**Comment by dantleech** [comment]
Confirm:

```
1. Missing return type `FlightAvailability` (fix with "Add missing return types" code action)
```

(no NULL) and adding a PHP return type makes the diagnostic disapear even if it could add a NULL.

**Comment by camilledejoye** [comment]
I confirm that this is solved.
I don't know on which version I was yesterday though, I normally update daily but I had local changes so it might have failed.
