### ISSUE TITLE
importing/not-importing globals not working as expected

### ISSUE THREAD

**Issue by gvanbeck** [phpactor/phpactor#1492]
Hey,

I can't figure this out.
in my config I have:
`  
"language_server_code_transform.import_globals": false,
`
but after completion of, say `array_merge` the function is imported at the top: `use function array_merge;`

I searched through the issues but can't find a solution. Is this a bug? Or am I looking for the wrong thing here?

Thx guys, for the amazing work!

**Comment by dantleech** [comment]
hi, should be fixed in https://github.com/phpactor/phpactor/pull/1495 (importing globals on completion now disabled by default)

**Comment by gvanbeck** [comment]
indeed it' s fixed for me. Thx.
