### ISSUE TITLE
LSP: Go to definition inside docblock

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1508]
```php
/**
 * @property Resolver $resolver
 */
class Phpactor
{
```
Similar issues like finding references to class or virtual property probably need to wait for resolving any of newly created ones.

**Comment by dantleech** [comment]
This works for me?

**Comment by przepompownia** [comment]
Right, sometimes it is possible to jump and not investigate why it works partially. I used only imported names to test. 

Initially I wanted to report problem with completion/go to only `ClassName[]` form but at the time of writing the Issue I did not able to jump also to not-arrayed type.

**Comment by dantleech** [comment]
it does work only on imported names (and i think fully qualified names, possibly qualified ones too).. there have historically been issues with jumping to `Foo[]` and `Bar<Baz>` but that should be ok now, so good to find out what's not working.

**Comment by dantleech** [comment]
Should be fixed as of #1517

**Comment by przepompownia** [comment]
Fixed :+1:
