### ISSUE TITLE
Bugs in completion/go to inside docblock

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1516]
Thanks for making phpdocs more alive ( https://github.com/phpactor/phpactor/issues/1507). Even in this version it can save us lot of time although it still requires some fixes.

Sometimes completion works as expected, sometimes (on `lib/Phpactor.php`) it still behaves in a strange way such as on the screencast https://asciinema.org/a/9mI44uwaDhfb1aDdPxntkRNBK (with `--stdin` but keystrokes are not shown unfortunately). 

Currently `Phpactor\Phpactor` has imported only `Resolver` class: `Phpactor\MapResolver\Resolver`. 
-please try to add virtual properties:
```php
/**
 * @property Resolver $resolver
 * @property Phpactor\MapResolver\Resolver $resolver2
 */
```
- try to go to both definitions (I cannot go to them)
- complete both the class names. On `Resolver` II get alias `AmpResolver` (`use Amp\Dns\Resolver as AmpResolver`). 
- if you'll get `AmpResolver` in effect, try to go to it. I can go to the incorrectly selected definition. 
- undo all changes and try to add a real property with type `Resolver` (for me it works as expected).

**Comment by dantleech** [comment]
confirmed - this is specific to the class docblock, method docblocks work fine -- probably an easy fix, checking

**Comment by przepompownia** [comment]
Confirmed, thanks :slightly_smiling_face:
