### ISSUE TITLE
Cannot complete on arguments defined in lambda functions

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1522]
For example, in `\Phpactor\Phpactor` please try to complete some public method of Resolver:
```php
        $f = fn (Resolver $resolver) => $resolver->set;
```

**Comment by dantleech** [comment]
![image](https://user-images.githubusercontent.com/530801/166187438-fa4a29d9-4299-4314-b7bc-1cf327d02bfb.png)

however it does not work outside of a class context

**Comment by dantleech** [comment]
![image](https://user-images.githubusercontent.com/530801/166187575-49615ca1-d664-459f-b1ea-4232b20e4b5a.png)

**Comment by dantleech** [comment]
hm, seems to be on an assignment outside of a class context

**Comment by dantleech** [comment]
it's a caching issue, fixed in #1523

**Comment by przepompownia** [comment]
![image](https://user-images.githubusercontent.com/11404453/166220509-afa4f393-f353-4119-b14f-99b91a2a4de6.png)
:+1:
