### ISSUE TITLE
Completion `@var` type from inside docblock: restricted results 

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1538]
As in previous example let's open `lib/view.php` in Phpactor project and try to create phopoc `/** @var Resolver $x */` where  `Resolver` is `Phpactor\MapResolver\Resolver`. I cannot get the expected result.

![image](https://user-images.githubusercontent.com/11404453/166906505-7a8bfaa0-4af1-4539-8c75-6114badcc7c5.png)

In the same file manual adding import works for this class:
![image](https://user-images.githubusercontent.com/11404453/166906663-7d10d016-dde3-4fdb-8225-ff96c4d86c6f.png)

**Comment by dantleech** [comment]
looks like it's not de-duplicating the suggestions with the same name even though they have different namespaces.

**Comment by dantleech** [comment]
pulling https://github.com/phpactor/phpactor/issues/1538 into this ticket as likely the same thing.

**Comment by dantleech** [comment]
should be fixed now.

**Comment by przepompownia** [comment]
Confirmed in af0d2ef3 (in opposite to the current master). 
![image](https://user-images.githubusercontent.com/11404453/167307525-f7decd25-ec83-42ad-a798-ea92129f5077.png)
thanks!
