### ISSUE TITLE
Finding references to promoted properties (and so rename) does not work

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1541]
For reproduction let's change some traditional property declaration to promoted in the constructor, look at references and try to rename the property. 

For me, no references found and then the declaration is the only occurrence of renaming.

**Comment by dantleech** [comment]
closing as is basically duplicated of https://github.com/phpactor/phpactor/issues/1324

**Comment by dantleech** [comment]
Sorry it's not the same

**Comment by przepompownia** [comment]
Not the same because of different backend for RPC (#1324) and LSP (here)? https://github.com/phpactor/phpactor/issues/1366#issuecomment-1074458538

**Comment by dantleech** [comment]
that was for RPC yes, but equally renaming _properties_ just doesn't work at the moment. not sure if there is a difference between that issue and this one, but i'm going to try and "fix" renaming this weekend.

**Comment by dantleech** [comment]
This should be fixed now, we should support properties, promoted properties, constants and enum cases.

**Comment by przepompownia** [comment]
I am impressed with the speed at which you are making numerous fixes and new features. Even superficial viewing `git diff` results takes some time from me. 

I create new issues to not forget about them within my regular job time. Sorry if sometimes I forget to look for a duplicate.

In the current diff see that you probably fixed the bug with redundant TextEdit too. 

References work, first test suggest that can also rename the promoted property. Thank you!

**Comment by dantleech** [comment]
no worries, at this point it's at least possible to deal with the issues whereas pre-monolith it wasn't. i should probably aim to triage or just close 90% of the issues and start fresh.
