### ISSUE TITLE
Reference Finder: Allow finding references to `__construct`

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1563]
It seems that no similar issue exists. 

Currently to look at where `new ExampleClass` is called we need, for example, to get references to `ExampleClass` and filter the results to match with preceding `new`.

**Comment by dantleech** [comment]
yeah this is something i often need to do, finding `new Foo` when searching by `__construct` seems like a good solution

**Comment by dantleech** [comment]
tried a simple version of this by treating `new Foobar()` as a reference to `Foobar#__construct()` but this breaks assumptions (e.g. renaming `__construct` won't work, and possibly other things that assume that the references are class members).

probably need to explicitly indicate `new Object` calls in the index and handle them specicially when looking for references.
