### ISSUE TITLE
Exclude from index

### ISSUE THREAD

**Issue by infectos** [phpactor/phpactor#1569]
I need to exclude some directories from indexing.
For example I have `_docker-infrastructure` directory that I don't want to index at all. And all its sub-directories too. Because I don't have permissions in some files inside, but that is another story.
Inside my project I have the `.phpactor.json` file
```
{
    "indexer.exclude_patterns": [
            "\/vendor\/**\/Tests\/**\/*",
            "\/vendor\/**\/tests\/**\/*",
            "\/vendor\/composer\/**\/*",
            "\/_docker-infrastructure\/**"
    ],

    "logging.enabled": true,
    "logging.path": "phpactor.log",
    "logging.level": "warning",
    "logging.formatter": "pretty"
    
}
```
Unfortunately, it doesn't work. I still got the error when lsp starts.
```
LSP[phpactor] Error in service "indexer" "Phpactor\Extension\LanguageServerIndexer\Handler\IndexerHandler:Phpactor\LanguageServer\
Core\Service\{closure}": RecursiveDirectoryIterator::__construct(/home/myname/backend/_docker-infrastructure/do
cker/.data/postgres): Failed to open directory: Permission denied
```
I am not experienced with glob and it might be the wrong glob pattern.

**Comment by KasparRosin** [comment]
I think you need to have it like this, to exclude the files recursively inside _docker-infrastructure
`\/_docker-infrastructure\/**\/*`

**Comment by infectos** [comment]
> 

Doesn't work too

**Comment by infectos** [comment]
> I think you need to have it like this, to exclude the files recursively inside _docker-infrastructure `"\/_docker-infrastructure\/**\/*"`

It doesn't work too

**Comment by dantleech** [comment]
the filtering happens after accessing the file, i've updated to ignore these errors in https://github.com/phpactor/phpactor/pull/1576 should be fine ...
