### ISSUE TITLE
LSP Process can live on after quitting neovim

### ISSUE THREAD

**Issue by DanielSiepmann** [phpactor/phpactor#1599]
Not sure if this is an issue of phpactor or https://github.com/neovim/nvim-lspconfig/. I'm only using phpactor as LSP right now.

When I close a neovim instance which created an LSP Process, this process will still live. This can stack up to an huge number of processes after a week of work. I tend to close neovim instances and start from new when switching a concrete task within a project.

Would be cool if the LSP process is being killed as soon as the neovim process is killed.

Let me know if you need further info. Using neovim
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

and phpactor 45207d99c7db718d0d5467a0cbd1a98587ee7551 with php `7.4.29`

**Comment by dantleech** [comment]
lsp requires that the client first send a `shutdown` request, and only if the server responds does it send a further `exit` request. nvim isn't sending the `exit` request for some reason. `vscode` on the otherhand does.

i notice that the `gopls` language server does exit successfully with nvim, so presumably something to do with Phpactor (wven though it does respond to the `shutdown` request.

in the worst case could just add an self-destruct timeout after `shutdown` has been recieved.

**Comment by dantleech** [comment]
it seems that nvim doesn't like to wait around, this PR reduces the grace period that Phpactor gives to it's services to shutdown: https://github.com/phpactor/phpactor/pull/1600

this improves the situation signficantly. but still a chance that phpactor won't respond in time, so probably also want to implement a self-destruct.

**Comment by DanielSiepmann** [comment]
Thank you, I try to update soon. My setup is a bit to complex right now for easy updates. Will let you know whether it solved the issue for me once I gave it a try.

**Comment by przepompownia** [comment]
Maybe #1600 solves my similar problem for which I not found any time to describe and checking where it happens.

**Comment by dantleech** [comment]
Reducing the grace period causes other problems, we periodically need to check if we need to kill the `inotify` watcher, and if we don't kill it then `nvim` crashes. I've pushed the grace period up to 100ms but added a self-destruct if the exit notification wasn't sent after 2.5 seconds, that should ensure no zombie processes.

**Comment by DanielSiepmann** [comment]
Looks fine now. I still had stale processes after the first changes. The update to self destruct solved it.
I no longer see processes lying around. Thanks for the fast fix.
