### ISSUE TITLE
Complete names of variables passed to anonymous function scope

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1602]
![image](https://user-images.githubusercontent.com/11404453/168571101-e29d5db4-1139-43e4-ae97-f1bca439bfa4.png)

**Comment by dantleech** [comment]
yeah, odly this should have been fixed but is probably regressed since the introduction of "better" contextual completion

**Comment by dantleech** [comment]
or ... my bad, don't think this was ever supported. done in #1605

**Comment by przepompownia** [comment]
Thanks! Let me report next minor issues to not forget about them :grin: I also have some bigger but they are not so simple to report as a screenshot with title.
