### ISSUE TITLE
No Trait Virtual Method Reflection

### ISSUE THREAD

**Issue by ging-dev** [phpactor/phpactor#1603]
phpactor can suggest virtual methods, but when i click save, the method doesn't exist warning.

![image](https://user-images.githubusercontent.com/42226341/168612507-f5540069-41f7-46bb-b2af-d99bdfd732be.png)

**Comment by dantleech** [comment]
yes that diagnostic is notorius.

**Comment by dantleech** [comment]
Looks like neither Traits or Enums support "virtual" methods or properties, bit confused how it works so far:

https://github.com/phpactor/phpactor/blob/042c2f2733189118f8fe95a03b9701e43c81c98f/lib/WorseReflection/Bridge/TolerantParser/Reflection/Collection/ReflectionClassCollection.php#L45-L53

**Comment by dantleech** [comment]
should be fixed in : https://github.com/phpactor/phpactor/pull/1619
