### ISSUE TITLE
Don't complete variable names unavailable in anonymous functions

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1609]
![image](https://user-images.githubusercontent.com/11404453/168687705-bc66e826-548e-4c92-9ae0-cac443a7ae19.png)

The next thing simple to report: `$fox` is available for completion. For static function `$this` is also available.

![image](https://user-images.githubusercontent.com/11404453/168687941-9c4964d2-aae9-4054-a40f-00efa5339449.png)

**Comment by przepompownia** [comment]
Thanks for filtering out the most unnecessary elements. `$this` in `static function` is still present.

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/phpactor/pull/1615
