### ISSUE TITLE
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.

### ISSUE THREAD

**Issue by nasrul21** [phpactor/phpactor#1616]
I got a warning when I run `composer install` on phpactor directory.
```
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
```
I think we should change `webmozart/path-util` package with `symfony/filesystem`.
How about that?

**Comment by dantleech** [comment]
yes we can, bit annoying that package became part of a package that has nothing to do with the Path util.

**Comment by dantleech** [comment]
are you successfully using Phpactor as a dependency btw? what is your use case?

**Comment by dantleech** [comment]
and it's a little but annoying as the package is used over 4 other packages, so not a 5 minute job.

**Comment by mamazu** [comment]
The first merge request for this: phpactor/class-to-file#28

**Comment by mamazu** [comment]
So I have updated all of the packages to their respective minimum version without the abandoned package but running `composer why webmozart/path-util` reveals that pslam is using it as well.

```
phpactor/phpactor dev-master requires webmozart/path-util (^2.3)
vimeo/psalm       4.29.0     requires webmozart/path-util (^2.3)
```

Which I am assuming it not that easy to fix as well.

**Comment by dantleech** [comment]
Psalm is only included so we can test against it, tbh could probably remove the dep, or install it when required during build and skip the test locally if it's not present.

**Comment by easbarba** [comment]
Hey, got this new one too: 

```sh
Package league/uri-parser is abandoned, you should avoid using it. No replacement was suggested
```
