### ISSUE TITLE
Support nested traits

### ISSUE THREAD

**Issue by mpociot** [phpactor/phpactor#1618]
Right now nested traits are not supported. The following code only gives me "onTraitOne" as an available method, while it should detect both methods:

```php
trait TraitTwo {
    public function onTraitTwo() {}
}

trait TraitOne {
    use TraitTwo;

    public function onTraitOne() {}
}

class One {
    use TraitOne;
}
```

<img width="910" alt="CleanShot 2022-05-19 at 22 38 36@2x" src="https://user-images.githubusercontent.com/804684/169400475-b542c798-c933-418c-8b46-3e028feb4d90.png">

**Comment by dantleech** [comment]
should be done now
