### ISSUE TITLE
Do not complete static method on an object instance

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1631]
![image](https://user-images.githubusercontent.com/11404453/169622053-827a2cf9-c75f-4cbb-9745-0be64554b349.png)
![image](https://user-images.githubusercontent.com/11404453/169622154-bb4a2e8a-d785-41d6-a083-a6a44ad95e7c.png)

Maybe similar to #1614

**Comment by dantleech** [comment]
it's valid to call a static method from an instance, even it seems "wrong". A common case is in PHPUnit test cases, people still use `$this->assertEquals()` even though the assertions are static. PHPUnit is probably the reason I kept this behavior.

**Comment by przepompownia** [comment]
Indeed, it's still valid for 8.1. 

You might consider whether it is worth configurability but I myself do not encourage you to do so.

**Comment by dantleech** [comment]
ok, closing this as a non-issue then for the moment.
