### ISSUE TITLE
Support project specific installed phpstan extensions and configuration

### ISSUE THREAD

**Issue by DanielSiepmann** [phpactor/phpactor#1639]
I open this issue in order to not clutter https://github.com/phpactor/phpactor/pull/1633.

I'm not 100% sure I got the current situation regarding phpstan support. Here is my current understanding:

phpactor ships with phpstan out of the box. The results are provided via lsp as diagnostics.
Some Projects which are edited via vim might already have phpstan as dev dependency, together with a configuration and phpstan extensions like:
- https://packagist.org/packages/phpstan/phpstan-phpunit
- https://packagist.org/packages/jangregor/phpstan-prophecy
- https://packagist.org/packages/saschaegerer/phpstan-typo3
- …

Would it be possible to use that instead of the shipped phpstan if available? Not sure how complicated that might be, as there might be different PHP versions and phpactor would need to call phpstan with the proper configuration. Maybe that is pretty easy. There is already an option to define the path to phpstan: https://github.com/phpactor/phpactor/blob/master/doc/integrations/phpstan.rst this could be set dynamically to either project specific phpstan or phpactor shipped phpstan.
Also the level might not be set anymore if a configuration already exists. Phpstan should pick up the configuration absed on naming. But we could also add an option to set the configuration name, as some might not follow the convention.

That would allow phpactor to provide the project specific phpstan results.

**Comment by dantleech** [comment]
this is already the case. Phpactor will integrate with the Phpstan binary in `vendor/bin/phpstan` by default (but it can be confifigured). It will use the existing phpstan config.

**Comment by DanielSiepmann** [comment]
Cool. I probably remember some older state. I had the situation where ale reported way more issues from phpstan than the LSP integration of phpactor. But I worked on my setup. So probably updates and fixes solved the issue on my end.

**Comment by DanielSiepmann** [comment]
We configure level within the phpstan project configuration. So ale and phpactor should pick this up as it is not explicitly set.

**Comment by DanielSiepmann** [comment]
I have a single PHP project where this is happening. I'll try to find some time in future to debug the setup. It seems to work fine in all other projects.

**Comment by DanielSiepmann** [comment]
Okay, this has nothing todo with phpstan.
I receive the following issue on one very large PHP project:
```W         self::assertInstanceOf(     ■ Method "assertInstanceOf" does not exist```

I can get rid of it when I open the phpunit `TestCase.php` which extends the `Assert` class.
Maybe some issue with some limits during indexing? E.g. related to [language_server_indexer.workspace_symbol_search_limit](https://phpactor.readthedocs.io/en/master/reference/configuration.html#language-server-indexer-workspace-symbol-search-limit)

**Comment by dantleech** [comment]
hm, there are no limits on indexing.how big is the project? how long does it take to index?

**Comment by DanielSiepmann** [comment]
How to debug how long it takes?
```
phploc 7.0.2 by Sebastian Bergmann.

Directories                                       8865
Files                                            27590

Size
  Lines of Code (LOC)                          3934994
```

Doesn't sound that large …
But you already say there should be no such limit anyway. Not sure what's causing the issue or how to debug the issue.

**Comment by dantleech** [comment]
yes that's not especially large. 

can you get completion results on `self::assert` ? what does the test case extend? any intermediate classes between the test case and `Phpunit\Framework\TestCase` ?

**Comment by DanielSiepmann** [comment]
Yeah we use https://github.com/TYPO3/testing-framework/blob/main/Classes/Core/Functional/FunctionalTestCase.php in between. But same result if I extend the `Phpunit\Framework\TestCase` instead.

No auto completion in both cases either.

**Comment by dantleech** [comment]
in that case enable logging at `debug` level and grep for `TestCase` that might tell you if the PHPUnit class is being found.

just to be sure - do you have PHPUnit as a dependency?
