### ISSUE TITLE
Support `$this` as a documented return type.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#164]
f.e.

```
    /**
     * Sets the name of the command.
     *
     * This method can set both the namespace and the name if
     * you separate them by a colon (:)
     *
     *     $command->setName('foo:bar');
     *
     * @param string $name The command name
     *
     * @return $this
     *
     * @throws InvalidArgumentException When the name is invalid
     */
    public function setName($name)
```

Note that this is a good case where the `return` should override any run-time return type of the method, as we can return the implementing class and not the declaring class.

**Comment by cmizzi** [comment]
Hum, the PHPDoc doesn't tell "self" instead of "$this" ?

**Comment by weirdan** [comment]
@cmizzi `$this` is from the [proposed FIG standard on phpdoc](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#keyword) (point 15). PHPDoc documentation also doesn't mention `static` which is, however, allowed as a return type hint in PHP 7.1+

**Comment by dantleech** [comment]
`$this` now works.

**Comment by CaptainQuirk** [comment]
This doesn't seem to work for a subclass on `dev-develop@97b8be8ee143e5fb5a1f9e60ded1d8085accad7b`
