### ISSUE TITLE
Hover sometimes unresponsive

### ISSUE THREAD

**Issue by ging-dev** [phpactor/phpactor#1665]
Sometimes Hover is not responding on vscode/sublime text, this happens randomly.

**Comment by dantleech** [comment]
this is probably because phpactor is busy doing something. without further information i can't really help with this.

**Comment by ging-dev** [comment]
> this is probably because phpactor is busy doing something. without further information i can't really help with this.
> 
> * is the file you are working on large or has a "large" inheritence hierarchy?
> * does it happen after saving a file?

It happens quite randomly. Also the Hover should not be displayed when the mouse pointer is moved to the Docblock.

https://user-images.githubusercontent.com/42226341/170819202-436f04a5-d6e7-4eaf-80e5-7916bc17bb53.mp4

**Comment by dantleech** [comment]
how long is the delay?

**Comment by dantleech** [comment]
>  Also the Hover should not be displayed when the mouse pointer is moved to the Docblock.

there are two probems here:

1) the cache is misbehaving, so the results are inconsistent and sometimes the type cannot be resolved. this is something i need to fix.
2) we shouldn't return an empty hover response

**Comment by ging-dev** [comment]
> how long is the delay?

it's about 300ms by default setting.

**Comment by dantleech** [comment]
i've improved the hover here: https://github.com/phpactor/phpactor/pull/1669

it's stil not perfect and really needs some deeper refactoring to be better.

for the delay issue : 300ms - or 1/3 of a second, isn't that much? i'd think VS code already adds aronud 250ms or so to make sure you stopped the mouse over something

**Comment by dantleech** [comment]
I've fixed the "inconsistency" issue in #1673 .

not sure how to follow up on the "unresponsive" aspect of this ticket, but maybe this fixes that also. Feel free to open a new ticket if not.

**Comment by dantleech** [comment]
ok, this time hopefully... https://github.com/phpactor/phpactor/pull/1675
