### ISSUE TITLE
How to use with Psalm

### ISSUE THREAD

**Issue by gazsp** [phpactor/phpactor#1712]
Hi there. Thanks for your work on Phpactor. It works well and is very nicely written :-) That being said, I'm wondering if you could provide a bit more detail about how the Psalm integration is supposed to work. 

I have Phpactor installed (and symlinked), and Psalm installed in a project locally. If I follow the docs [here](https://phpactor.readthedocs.io/en/master/integrations/psalm.html?highlight=psalm#psalm) and enable Psalm, then I'm guessing I should expect to see syntax errors / other messages from Psalm in my editor, as well as be able to use the features of Phpactor at the same time, but this doesn't happen. The 'normal' features of Phpactor work fine, but if I create a syntax error in a file (for example), no message from Psalm shows up in my editor (the messages from Psalm do show up if I use it as a standalone language server).

I've tested the Phpactor + Psalm integration in two editors - Helix and Sublime Text, and the result is the same - no messages from Psalm are ever shown (as far as I can tell). Here's a snippet from `phpactor config:dump`:

```
    "language_server_psalm.bin": "%project_root%\/vendor\/bin\/psalm",
    "language_server_psalm.enabled": true,
```

I've confirmed that the Psalm path / binary is correct:

```
~/htdocs/contently  master ﯂  
 ls -la vendor/bin/psalm
-rwxr-xr-x 1 gazsp gazsp 3185 Jun  8 10:51 vendor/bin/psalm
```
and that it runs...

```
~/htdocs/contently  master ﯂  
 vendor/bin/psalm                        
Target PHP version: 7.4 (inferred from composer.json)
Scanning files...
Analyzing files...
```

Could you let me know if my understanding of how this is supposed to work is correct, or if I'm doing something wrong? Is there a way to try and debug what's going on? Running with `-vvv` doesn't show anything relevant.

Thanks.

**Comment by dantleech** [comment]
I've enabled Psalm and the logs show the first error:

```
Psalm exited with code "1": Config not found for path /home/daniel/www/phpactor/phpactor/
```

After creating the file I get the diagonstics from Pslam:

![image](https://user-images.githubusercontent.com/530801/172782456-ab982324-b5d3-4ff6-9982-11d87191ee49.png)

If you want to debug you can enable [logging](https://phpactor.readthedocs.io/en/master/other/developing.html#logging)

Probably we should show the user an error if Psalm/Phpstan are enabled and the binary crashes for some reason.

**Comment by gazsp** [comment]
I have a config file there - and I don't see any errors or mention of Psalm when looking through the logs, other than:

```
[2022-06-09 07:13:53] phpactor.DEBUG: Resolved path "%project_root%/vendor/bin/psalm" to "/home/gazsp/htdocs/contently/vendor/bin/psalm" {"channel":"FPR"} []
```
:-(

**Comment by dantleech** [comment]
If you want to go to the next level of debugging, add `dump($stdout)` here:

https://github.com/phpactor/phpactor/blob/298ae1bc980a0898e45bfa8d8ada58b428638140/lib/Extension/LanguageServerPsalm/Model/PsalmProcess.php#L51

and, in the Phpactor dir (ensuring you installed with dev dependencies) run:

```
./vendor/bin/var-dump-server
```

then restart the language server. you should then be able to see the process output from Psalm

**Comment by gazsp** [comment]
`analyse` never gets called. The constructor does. I'll keep digging...

**Comment by gazsp** [comment]
So it's working in Sublime Text, not in Helix. To be honest, I think it may be to do with me using phpbrew, and not setting the correct default PHP version when trying to debug, so installing everything on a project with PHP 7, but then defaulting to PHP 8 when trying to use Phactor etc. No idea why Helix isn't working, but it's a not a concern really as it's not my main editor.

Thanks for your help and swift responses - I'll close this for now!
