### ISSUE TITLE
Phpactor reports ObjectProphecy's 'magic' methods as non-existing

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1736]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/12109622/175944691-01a238e6-60d1-40ee-bf07-988c0bfaf720.png">
I am pretty sure we've talked about this before. Am I missing something I should enable/disable? 

Clearly these are not undefined methods, this library is meant to be used like this. There is an extension to `phpstan` that removes those errors - [https://github.com/Jan0707/phpstan-prophecy](url).

**Comment by dantleech** [comment]
See https://github.com/phpactor/phpactor/pull/1633. Prophecy requires custom code to work properly. Looking at phpstan-prophecy this will not be easy...

**Comment by BladeMF** [comment]
Strangely enough it does not report them as problems every time. Don't see what is the difference between when it does and when it doesn't. When it does not it doesn't bother me.
