### ISSUE TITLE
phpactor falls into infinite loop

### ISSUE THREAD

**Issue by ging-dev** [phpactor/phpactor#1737]
```php
<?php

use Illuminate\Contracts\Database\Query\Builder;

function test(Builder $q) {

}
```

Something seems to be causing phpactor to fail to resolve `Builder` class

**Comment by BladeMF** [comment]
Not sure if these two are related, although I never found the cause of mine. #1735

**Comment by dantleech** [comment]
can you check the `Builder` for recursive dependenceies, then it is likely this issue: https://github.com/phpactor/phpactor/issues/1627 reopen if not.
