### ISSUE TITLE
What units is `worse_reflection.cache_lifetime` in?

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1749]
Reading `Phpactor\WorseReflection\Core\Cache\TtlCache` it would seem that this is the same units as `microtime`, which is microseconds (10e-6), which means no cache at all? 

Is it me or the default value was meant to be 5 million (or at least multiplied by a million)? Sorry if it's a dumb question.

**Comment by BladeMF** [comment]
True, I misread the docs, sorry.

**Comment by dantleech** [comment]
it's not documented, so you are right to ask ...
