### ISSUE TITLE
[SCFS] Handle files not under version control

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#175]
According to the docs and my experience, `MoveFile` changes references, but it does not rename the class itself. That would be a nice feature to have.

**Comment by dantleech** [comment]
Are you talking about `class:move` ? 

It should rename the class - but there is an issue:

- If the file is not under VC it does not get moved / renamed.

This is because we use the GIT index to find references.

Could this be the case? If so can we rename the issue?

**Comment by greg0ire** [comment]
I'm not sure if I'm talking about `class:move`, I tried `:call phpactor#MoveFile()`.

**Comment by greg0ire** [comment]
So that would probably mean making a second pass just for files that are not under VC. Less performant, but there should be fewer files, so it might be ok.

**Comment by greg0ire** [comment]
Note: adding the file to the index is enough: `git add -N path/to/file.php`

**Comment by dantleech** [comment]
> I'm not sure if I'm talking about

Looks like the naming is wrong, but hopefully will be moving everything over to [RPC](https://github.com/phpactor/phpactor/wiki/WIP-Phpactor-RPC-Protocol) soon :)

> So that would probably mean making a second pass just for files that are not under VC. Less performant, but there should be fewer files, so it might be 

Depends on scope - i.e. the vendor directory. We could also ensure the file is added to GIT before performing the move.

**Comment by greg0ire** [comment]
> Depends on scope - i.e. the vendor directory.

I think only files that appear as untracked should be changed, so `git ls-files --others --exclude-standard`

**Comment by dantleech** [comment]
> I think only files that appear as untracked

Sounds like a solid plan, relevant changes will need to be made in https://github.com/phpactor/source-code-filesystem

**Comment by dantleech** [comment]
Should be fixed now ...

**Comment by greg0ire** [comment]
Thanks a lot!
