### ISSUE TITLE
What cache are code actions relying on?

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1750]
I tried to time which code actions were slow and found out that probably `TransformerCodeActionPovider` are sharing some sort of cache, because always the first of them is slow, and the others are not. If I stop the first one, then the second one becomes slow (700ms or so). VS Code issues `textDocument/codeAction` request _very_, _very_ frequently so I am trying to track down what is slowing it down.

**Comment by dantleech** [comment]
I think this is thw same issue as #1751  

Code action performance should have been improved a month or so ago by porting problematic code actions to the new diagnositcs engine there may still be some issues with perf, but I think rather covered by the other issue.
