### ISSUE TITLE
Performance improvement suggestions

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1751]
I have serious performance problems with the new version. After some digging, I think I found one of the reasons: when the user is typing, VS Code fires in rapid succession `codeAction`, `hover`, `signatureHelp` and other requests and then cancels most of them. Neither of those handlers supports cancelling and they _all_ run to completion, which can result to requests taking up to 2 minutes each and `phpactor` being unresponsive for 5-10 minutes. I imagine `vim` does not behave in such a way and this is why I am the only one suffering. When LiveShare is being used and there is more than one user requesting stuff from the language server it becomes even worse.

What I tried is hacking some code that passes the `CancellationToken` from the `HandlerMethodRunner` to each handler. Then all the handlers call `yield new Delayed(0);` and then `if($cancellationToken->isRequested()) { return whatever; }`. After the few tests I ran this evening this does not swamp `phpactor`, but will test additionally tomorrow.

The point of this issue is to open a discussion into this behavior, because currently is not immediately obvious how to implement it properly. 

Currently I am just passing additional undeclared argument and then taking it with `$cancellationToken = func_get_arg(2);`, because otherwise the argument resolver gets messed up. I think that if all but the high-prority handlers call `yield` then they can all check for immediate cancellations and still preserve their order but allow for cancellations to be processed with priority.

Hope that makes sense.

**Comment by BladeMF** [comment]
The current results are _very_ promising. I actually changed completions to "high priority" (removed the delay there) so I get them fast, but wait for code actions, hovers, etc.

**Comment by dantleech** [comment]
thanks, can you test https://github.com/phpactor/phpactor/pull/1756 and see if there is anything else to do there?

**Comment by BladeMF** [comment]
sure, will do as soon as I can.

**Comment by dantleech** [comment]
closing as have added support for cancellation
