### ISSUE TITLE
Support Psalm & Phpstan prefix

### ISSUE THREAD

**Issue by ciricode** [phpactor/phpactor#1760]
```php
/**
 * @psalm-template T
 */
class User {
	/**
	 * @psalm-return T
	 */
	public function attributes()
	{

	}
}
```

**Comment by dantleech** [comment]
Would you be up for making a pull request?

Support them in the parser:

https://github.com/phpactor/phpactor/blob/9f758f69390d3b97b932ff9ef97b761bc5ca1bac/lib/DocblockParser/Parser.php#L109-L110

Register them as types that require parsing in the factory:

https://github.com/phpactor/phpactor/blob/9f758f69390d3b97b932ff9ef97b761bc5ca1bac/lib/WorseReflection/Bridge/Phpactor/DocblockParser/DocblockParserFactory.php#L15-L27

Add a simple test:

https://github.com/phpactor/phpactor/blob/9f758f69390d3b97b932ff9ef97b761bc5ca1bac/lib/WorseReflection/Tests/Unit/Bridge/Phpactor/DocblockParser/DocblockParserFactoryTest.php#L214-L217
