### ISSUE TITLE
Object of class RecursiveIteratorIterator could not be converted to string

### ISSUE THREAD

**Issue by panders23** [phpactor/phpactor#177]
Hi,

i'm currently facing the following problem with HEAD:

```
  [Symfony\Component\Debug\Exception\ContextErrorException]                                          
  Catchable Fatal Error: Object of class RecursiveIteratorIterator could not be converted to string
```

command to reproduce the issue:

```
~/phpactor/bin/phpactor class:search HttpClient
```

Same error happens in vim with `:call phpactor#ClassExpand` 

I'm using the setup as described here: https://github.com/phpactor/phpactor/blob/master/plugin/README.md

**Comment by dantleech** [comment]
1. Is this a regression - was it previously working?
2. Can you should the stack trace? (add `--verbose` to the command).
3. Are you able to reproduce this on an open-source code base? (e.g. Symfony Standard Edfition).

**Comment by dantleech** [comment]
Seems to be reproduced now by Travis with some version of 7.1: https://travis-ci.org/phpactor/phpactor/jobs/273672984

**Comment by dantleech** [comment]
Possibly related to this in `7.1.9`? https://bugs.php.net/bug.php?id=74977

**Comment by dantleech** [comment]
PHP Bug: https://bugs.php.net/bug.php?id=75155&edit=2

Implemented temproary workaround be re-implementing `ArrayIterator`: https://github.com/phpactor/source-code-filesystem/blob/master/lib/Iterator/AppendIterator.php

**Comment by panders23** [comment]
You're right, i'm using php 7.1.9 on arch. Your workaround fixed my issue, thank you.
