### ISSUE TITLE
Unable to locate class when trying to omnicomplete on Drupal project class

### ISSUE THREAD

**Issue by fenetikm** [phpactor/phpactor#178]
I am getting the following when trying to omnicomplete using the Vim plugin:

> Error detected while processing function phpactor#Complete[18]..phpactor#ExecStdIn:
> line    8:
> E605: Exception not caught: Unable to locate class "Drupal\ua_arop_module\Controller\AropController"

This when I am trying to complete on $this-> or on a parameter (UserInterface $user) etc.

Any thoughts on where to start trying to debug this or what information might assist? Thanks in advance.

**Comment by dantleech** [comment]
Most probably scenario is that the class you are trying to complete is not managed by composer.

You could confirm this by creating the following file:

```php
<?php

require 'vendor/autoload.php';

new Drupal\ua_arop_module\Controller\AropController();
```

It may also be that Drupal uses more than one autoloader (i.e. it's own package manager for extensions etc.). In that case you would need to find the other autoloader and add some Phpactor config.

**Comment by fenetikm** [comment]
Right, that test file does indeed throw a class not found.

When running tests I have phpunit.xml set to use a `app/core/tests/bootstrap.php` and if I require that it finds the class.

Could that be helpful?

**Comment by dantleech** [comment]
Yeah, there is likely another autoloader somewhere, I would dig in `bootstrap.php`, or maybe `find ./ -name "autoload.php"`.

You can then edit or create some configuration: https://github.com/phpactor/phpactor#configuration

And set `autoload: [ 'vendor/autoload.php', 'relative/path/to/other/autoload.php' ]`

**Comment by fenetikm** [comment]
Cool - I'll try some things. I'll re-open this when I have something further.

**Comment by fenetikm** [comment]
Just following up on this: from what I can tell, Drupal doesn't have another composer autoloader - the reason being that contributed modules are themselves their own little projects and they can be downloaded by other mechanisms into a custom folder and when that happens they don't get added into the root composer.json. 

Having said that, you can add them in, by hand (ugh), to composer.json in an autoload section and phpactor works as expected. I am probably going to look at a) writing a script to update my composer.json and b) something like the langserver autocompletion.

Thanks for your work on this at any rate, it's looking fantastic.

**Comment by dantleech** [comment]
Thanks, at some point it may also be worth having "indexing" source locator, which would probably be good in any case as it would enable Phpactor to work without or in addition to composer.

**Comment by fenetikm** [comment]
Following up on this again :) (for someone who may stumble upon it)

So I wrote a simple script to generate a composer.json file to include all of the Drupal modules (core, contrib and custom) into autoload / psr-4 which then gets merged into the main composer.json using the wikimedia/composer-merge-plugin.

Works a treat now, thanks for all your hard work thus far 👍

**Comment by fenetikm** [comment]
...and I have just tried the custom autoloader that is on the integrations page and sadly that will only work if you are running Vim in the same environment as where Drupal is installed (probably not that common nowadays?)

Maybe a one-liner in the integration page to say that is a requirement would be handy.

**Comment by dantleech** [comment]
> This is because it hits the database I guess (PDO error is being thrown).

Hmm, it's possible that I was running it locally. Feel free to make a PR with your findings.

Maybe there is another way to initialize the modules without touching the DB :thinking:

**Comment by fenetikm** [comment]
I am going to create (have started) a composer plugin to merge in the Drupal contrib/custom/core modules into the autoload-dev. I feel like that is perhaps _slightly_ better than dropping the autoloader file into the root directory. I'll create a PR once I have that done.

**Comment by fenetikm** [comment]
Okay dokay, I finished up a first version of a composer plugin to accomplish this.

https://github.com/phpactor/phpactor/pull/357
