### ISSUE TITLE
`StringBackedEnum::from` is reported as missing method

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1810]
Having this enum:
```php
enum SectionType:string
{
	case Stakeholder = StakeholderAssessment::class;
	case BusinessSuccessFactor = BusinessSuccessFactorAssessment::class;
}
```
and then using it like this:
```php
SectionType::from($parts[0])
```
produces this:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/12109622/179934154-d2dc74c0-fb77-4b3b-bc22-32cc7aa26909.png">

**Comment by dantleech** [comment]
should be fixed in #1810 would currently require the 8.1 runtime
