### ISSUE TITLE
@throws annotation not considered

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1817]
![image](https://user-images.githubusercontent.com/530801/180598435-dd22f1b3-6de0-4534-9481-fc29fbd41fc1.png)

**Comment by mamazu** [comment]
Where is the code located. Then I'll take care of it.

**Comment by dantleech** [comment]
it says "easy" but it's maybe not entirely obvious, the docblock parser needs to support the `@throws` tag:

- Tag nodes are defined [here](https://github.com/phpactor/phpactor/blob/4e503473993182595196cec50f90c23022ad336e/lib/DocblockParser/Ast/Tag/PropertyTag.php#L9)
- Parsed [here](https://github.com/phpactor/phpactor/blob/4e503473993182595196cec50f90c23022ad336e/lib/DocblockParser/Parser.php#L86)
- Whitelisted [here](https://github.com/phpactor/phpactor/blob/4e503473993182595196cec50f90c23022ad336e/lib/WorseReflection/Bridge/Phpactor/DocblockParser/DocblockParserFactory.php#L15)
- Smoke tests for the parser [here](https://github.com/phpactor/phpactor/blob/4e503473993182595196cec50f90c23022ad336e/lib/DocblockParser/Tests/Unit/Printer/examples/var1.test#L1-L11)
- Test for this specific thing (the diagnostic false positive) [here](https://github.com/phpactor/phpactor/blob/4e503473993182595196cec50f90c23022ad336e/lib/WorseReflection/Tests/Integration/Bridge/TolerantParser/Diagonstics/UnusedImportProvider/Trait.test#L1-L10)

The diagnostic provider should understand the ne `ThrowsTag` without modification, so the test is just an acceptance test for everything else.
-
