### ISSUE TITLE
The defacto php language server

### ISSUE THREAD

**Issue by unansweredocd** [phpactor/phpactor#1830]
Hey,

Thank you for all the awesome work you're doing on phpactor. I created an issue on the psalm repository about a defacto php language server. Lots of folks there that work on php language server stuff, would you be willing to give your two cents? If all the work that's being done on this can be combined then all of us that do php would benefit.

https://github.com/vimeo/psalm/discussions/8328

**Comment by unansweredocd** [comment]
Thanks for leaving a comment.

**Comment by dantleech** [comment]
you're welcome, will follow the discussion :)
