### ISSUE TITLE
Bump release versions

### ISSUE THREAD

**Issue by afranioce** [phpactor/phpactor#1860]
Hi, I'm using the neovim with [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer/) but it actually recommends migrating to [mason.nvim](https://github.com/williamboman/mason.nvim) have been to get release tags, the current tag of phpactor is [0.18.0](https://github.com/phpactor/phpactor/releases/tag/0.18.0) on Jan 03, 2022, to use the latest version, it allows install using the command `MasonInstall phpactor@master` but the package does research for new versions that have the latest tag (see the image attached), every time.
So could you generate the release tags for the next versions?

![Screenshot_20220906_080708](https://user-images.githubusercontent.com/893768/188622080-9b7c31a5-7f10-4a16-8af7-ffb504053e48.png)

**Comment by dantleech** [comment]
I'm planning to tag a new release in the next few days.

**Comment by dantleech** [comment]
Done ! https://github.com/phpactor/phpactor/releases/tag/2022.09.11
