### ISSUE TITLE
Implementation for WorkspaceSymbols

### ISSUE THREAD

**Issue by ahmedash95** [phpactor/phpactor#1876]
Hello and Thanks for this great project. I want to ask if there is a plan to implement the [WorkspaceSymbols](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceFeatures). 

I can support making PRs if you are open to accept the feature.

**Comment by dantleech** [comment]
It is "supported": 

https://github.com/phpactor/phpactor/blob/873fa51ae06eb3dd568ac02c111503b88b76e723/lib/Extension/LanguageServerIndexer/Handler/WorkspaceSymbolHandler.php#L13-L27

![image](https://user-images.githubusercontent.com/530801/190633255-2e0f5ddc-88e1-48c9-856e-da15f19d331f.png)

although far from perfect

**Comment by ahmedash95** [comment]
Thanks @dantleech for the quick response. glad to know its supported. but still have a question. so in PHPStorm the file structure functionality would list class method & properties. and even would include methods and props from parent classes like `class FormRequest extends Request`. so is there a functionality like that in phpactor? I'm totally new to LSP world.

**Comment by dantleech** [comment]
yes, at a file level this is called `document symbols` in LSP. In VS Code:

![image](https://user-images.githubusercontent.com/530801/190634541-d25de81f-d3c0-4356-8eaa-706ae32587e1.png)

although it seems it does not show inherited members (not sure if it should or not)

**Comment by ahmedash95** [comment]
I'm using [gbprod/phpactor.nvim](https://github.com/gbprod/phpactor.nvim) plugin with neovim. and I can't find the function to display document symbols (not sure if it's from the plugin or I'm missing function name). any idea how to get it like the first screenshot from telescope?

> although it seems it does not show inherited members (not sure if it should or not)

I think it can be an option and use can decide whether to enable or disable. but I believe it would be very useful.

**Comment by ahmedash95** [comment]
ah I see now. the workspace symbols must be triggered from the client and as fzf user. I was able to get it through fzf -> document symbols

<img width="678" alt="image" src="https://user-images.githubusercontent.com/8272048/190635726-e82459a6-afa4-48dd-a5c0-04db320adfa3.png">


so my final question now is would you like to import the functionality of document symbols to show inherited members?

**Comment by dantleech** [comment]
I don't think this would be expected behavior, from the spec:

> The document symbol request is sent from the client to the server. The returned result is either
> 
> - SymbolInformation[] which is a flat list of all symbols found in a given text document. Then neither the symbol’s location range nor the symbol’s container name should be used to infer a hierarchy.
> - DocumentSymbol[] which is a hierarchy of symbols found in a given text document.

So the scope seems to be the current text document. Interested to see if other language servers handle this differently tho.

**Comment by ahmedash95** [comment]
Can't argue because of the spec. but being able to look for inherited members from current document has saved me a lot of time during my +4 years working with PHPStorm. so I will check other language servers to prove my point and hopefully get it implemented.

**Comment by dantleech** [comment]
More significantly it would not be possible because there is no way to reference the document containing an inherited member.

**Comment by ahmedash95** [comment]
> 

That's true. I was checking the spec and I can see it won't be possible. looks like I've to write a plugin myself to just provide that. 

Thanks for all the help and replies 🙏🏻

**Comment by dantleech** [comment]
Phpactor does provide (legacy) support for navigating to [arbitrary destinations](https://phpactor.readthedocs.io/en/master/reference/navigation.html#jump-to-or-generate-related-file), e.g. parent class, interfaces etc:

https://github.com/phpactor/phpactor/blob/92377984b63ecb848259a9af822db3abf0f69279/lib/Extension/Navigation/Navigator/WorseReflectionNavigator.php#L10

Not sure that's a good solution here though, having a hierarchical list would be better.

**Comment by ahmedash95** [comment]
for future visitors, I was able to build a small neovim plugin that does what I was looking for

https://github.com/ahmedash95/deep-symbols
