### ISSUE TITLE
rpc class_new creates an Untitled buffer in Neovim

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#1881]
Since very recently, when I use rpc class_new, it creates a second Untitled buffer.

![1](https://user-images.githubusercontent.com/5675200/191029831-27f72a6b-2a80-45f9-97d6-995a031d310d.png)
![2](https://user-images.githubusercontent.com/5675200/191029824-9f71a33a-5561-46c8-a81b-72b0ada23331.png)

I did a git bisect, and it seems like the bug was added in [this commit](https://github.com/phpactor/phpactor/commit/ab2e706f07773b0c0b67cf9fa246a0c16cf16253).

**Comment by dantleech** [comment]
Will ve fixed in #1884
