### ISSUE TITLE
Jump to interface definition from implementation definition

### ISSUE THREAD

**Issue by ckilb** [phpactor/phpactor#1883]
It seems like PhpActor is not able to find the methods (type) definition from an interface.

Interface:
```php
<?php

interface FooInterface
{
    /**
     * @return string
     */
    public function getBar(): string;
}
```

Class:
```php
<?php

class Foo implements FooInterface
{
    public function getBar(): string
    {
        return 'abc';
    }
}
```
FooInterface::getBar() -> go to implementation -> works ✅
Foo::getBar() -> go to (type) definition -> does not work ❌

Let me know if you need any additional info.

**Comment by dantleech** [comment]
Implemented in #1886
