### ISSUE TITLE
Cannot detect existing method implementation

### ISSUE THREAD

**Issue by ShahinSorkh** [phpactor/phpactor#1888]
In a brand new laravel project, when you are editing a TestCase, LSP complains about `Missing methods "createApplication"` even though it _is_ defined in the base class using a trait.

TestCase:
![image](https://user-images.githubusercontent.com/13497697/192083473-c479692d-2556-40cd-a993-d82f7a2d2ac4.png)

Base class:
![image](https://user-images.githubusercontent.com/13497697/192083595-7ff419e1-9aac-4567-8ffb-99bee2c3c1d8.png)

The trait:
![image](https://user-images.githubusercontent.com/13497697/192083605-3df6c31b-8e45-43fe-a62c-ed5f690facc0.png)

BaseTestCase in `vendor/laravel/../TestCase.php`:
![image](https://user-images.githubusercontent.com/13497697/192084322-22f8a8fd-0879-4c1d-a588-1b350dd70012.png)

**Comment by dantleech** [comment]
I don't know about the latest Laravel, but using a Larvel demo I get the `createApplication` function

![image](https://user-images.githubusercontent.com/530801/192087857-6aa46aee-e9d3-448f-bd3b-5837a8608fce.png)

**Comment by ShahinSorkh** [comment]
```
shahin@ragnarok ~> phpactor --version
Phpactor 0.18.1@670359cfc9534580156203fda7dfd3c72e130a45
```

I get autocompletion for the method but still complains "Missing methods ...".

![image](https://user-images.githubusercontent.com/13497697/192212085-0cef5ccb-fae8-4bf4-b2f8-e2bff26630f4.png)

**Comment by ShahinSorkh** [comment]
Though it seems to be fixed in the latest version.

```
shahin@ragnarok ~> phpactor --version
Phpactor 2022.09.11@4665d3e3bc52f15cfd5732a3b48ef154bc7018cc
```

**Comment by dantleech** [comment]
yes indeed this problem was explicitly fixed :)
