### ISSUE TITLE
Add support for organize imports 

### ISSUE THREAD

**Issue by ahmedash95** [phpactor/phpactor#1889]
Hello, a feature that would be great to have is the ability to organize/sort imports. some languages servers support it (eg [TypeScript LS](https://github.com/typescript-language-server/typescript-language-server/blob/8725b9bee4432b7520ebd9adc67f4c65303b2c8c/src/tsServer/requests.ts#L68). so what do you think about it? 

I can help by creating a PR and as I'm new to the project I'll consider [ImportMissingClassesHandler](https://github.com/phpactor/phpactor/blob/3e7cb48b0ca429f92bcd57c236c39f170e9d23b1/lib/Extension/CodeTransformExtra/Rpc/ImportMissingClassesHandler.php#L15) as a reference

**Comment by dantleech** [comment]
There is already "remove unused" imports - which overlaps a bit with tthis, but not sure at what point we should just say "use a CS fixer". Having the imports sorted is more a stylistic issue, also need to consider `use Foobar\{Bar,Baz}` etc so not necessarily simple.
