### ISSUE TITLE
Could not locate autoloaderPath file

### ISSUE THREAD

**Issue by benplummer** [phpactor/phpactor#189]
In Vim, when trying to invoke omni complete in insert mode I receive the following:

`[InvalidArgumentException] Could not locate autoloaderPath file "//vendor/autoload.php"`

Is there possibly some configuration I'm missing somewhere?

**Comment by dantleech** [comment]
No, could it be that you havn't initialized (or are not working) in a git repository?

**Comment by dantleech** [comment]
I'm guessing the suspect code is here: https://github.com/phpactor/phpactor/blob/master/lib/Container/CoreExtension.php#L367 and that it is traversing down to the root of the filesystem.

Does this happen if you invoke Phpactor from the root of your project which is managed with GIT?

Maybe could be fixed with https://github.com/phpactor/phpactor/issues/190

**Comment by benplummer** [comment]
Just tried invoking omni complete in a file when I've opened Vim from the root of that file's project and it works.

However, if I open Vim from a completely different directory e.g. `~/` and open that same file and try to invoke omni complete, I receive the same exception that I originally stated.

Not sure if this is intended behaviour?

**Comment by dantleech** [comment]
The original intended usage was to invoke Phpactor from the project root. Recently support was added to invoke it from sub-directories within the root (and so traversing down the file tree to find git/composer). But not sure that was a good idea...

**Comment by benplummer** [comment]
No problem. Thanks for the suggestions and for the plugin! I'll keep a look out for if any changes are made.

**Comment by dantleech** [comment]
This PR should address the problem anyway: https://github.com/phpactor/phpactor/pull/194

**Comment by dantleech** [comment]
Closing as it will be fixed when #194 is merged (probably tomorrow)
