### ISSUE TITLE
Annoying "No formatter has been enabled, please check your configuration" message on save

### ISSUE THREAD

**Issue by gbprod** [phpactor/phpactor#1898]
Hello !

Currently, I use [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) in Neovim to format php files on save using `php-cs-fixer`.
Since the last phpactor update, I recieve a "No formatter has been enabled, please check your configuration" each time I save a file.
Seems to comes from [this class](https://github.com/phpactor/phpactor/blob/9180c96df6ef8818a8ef6a0b4aa448269b986fe7/lib/Extension/LanguageServer/Formatter/NoFormatterConfiguredFormatter.php) and since you've introduced [PhpCsFixer extension](https://github.com/phpactor/phpactor/pull/1897).

For the moment, I've not planned to switch to your extension but I'd like to avoid this notification message, maybe we could remove [this error message](https://github.com/phpactor/phpactor/blob/9180c96df6ef8818a8ef6a0b4aa448269b986fe7/lib/Extension/LanguageServer/Formatter/NoFormatterConfiguredFormatter.php#L23) ? or maybe, there's another solution ?

Thanks for you're feedback !

**Comment by dantleech** [comment]
Oops, didn't expect that side effect. I guess `null-ls` is seeing Phpactors "support" for formatting and using it by default, and by default it shows that message. Will have a look later.

**Comment by dantleech** [comment]
should be fixed..

**Comment by gbprod** [comment]
Yes ! 
Thanks !
