### ISSUE TITLE
Classes in symlink dependencies are not proposed to be imported in code action (but are in rpc)

### ISSUE THREAD

**Issue by gbprod** [phpactor/phpactor#1901]
I have a strange issue for a long time using PhpActor for importing classes.
Sometimes, when I use Lsp CodeAction to import classes, some are not listed. In this case, I use RPC call and it works.
I've noticed that classes not listed in CodeAction are those from local composer dependencies (composer use symlinks to add vendor).

Maybe it will be clearer with an example :

If I have a `composer.json` almost like this : 
```json
{
    "name": "gbprod/test",
    "type": "project",
    "require": {
        "php": "^7.4|^8.0",
        "symfony/symfony": "^6.2",
        "packages/pack": "dev-master"
    },
    "repositories": [
        { 
            "type": "path", 
            "url": "../../packages/pack" 
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable" : true
}
```
All classes in `packages/pack` will not be proposed to be imported in CodeAction (but they are in RPC) while all classes from `symfony/symfony` will be.
I think it's because this package comes from a `path`.

I hope my explanation is clear enough :sweat_smile: 

Thanks for your feedback

PS: I use Neovim 0.8, [here is my setup if it could help](https://github.com/gbprod/gbvim)

**Comment by dantleech** [comment]
I don't think the indexer will follow syminks by design (it's the second argument of SimpleFileListProvider below):

https://github.com/phpactor/phpactor/blob/61b4e374691c944e40ef01f3f77519e4848f0a7d/lib/Indexer/IndexAgentBuilder.php#L223

you could try setting the `followSymlinks` flag to `true`  there, if that works maybe could make it a config option.

**Comment by gbprod** [comment]
Thanks for your reply !
I've tried with follow symlinks enabled and it works !!!

I've made a pull request to add this option, hope this is ok for you :)
