### ISSUE TITLE
[RFC][Docs] Document code actions automatically

### ISSUE THREAD

**Issue by mamazu** [phpactor/phpactor#1926]
## The idea

Currently there is an automatic generator for the old RPC Commands and the extension configuration as well as some but not all code actions.

## The problem

The problem I see is that by default the documentation for the code action is quite verbose. It contains a section about why we need it and an example of what it does. Documenting all this in code somewhere in the CodeAction class would be an utter mess. I also don't really have an idea how to solve that. 

In the end something would like to have would be a command that can generate the documentation for the code actions and that can also fail if you add a new undocumented code action. This would be the A+ solution.

**Comment by dantleech** [comment]
The old RPC command documentation is really about the protocol, e.g. the action accepts this request and returns this response. That is not required for the code actions, the protocol is known and it doesn't really benefit the user to know their API.

The "refactorings" section is more general than code actions, it covers any Phpactor ability to modify the code, the "common" way should now be code actions but some of the actions are f.e. available via. LSP, Legacy and CLI.

Also, we cannot, f.e. determine from the code action API how the code action is invoked, or anything useful about it all really other than _it exists_.

The actual equivilent of "RPC commands" is an "LSP command", these can be invoked by the user from the client.

**Comment by mamazu** [comment]
So what you would suggest is to not document the code actions automatically but rather on a case by case basis?

**Comment by dantleech** [comment]
yes, at least for now. it would not be trivial to replace the existing `refactoring.rst` with generated documentation.

**Comment by mamazu** [comment]
Agreed. Maybe in the future.
