### ISSUE TITLE
Too many open files error when autocompleting use statement

### ISSUE THREAD

**Issue by danrot** [phpactor/phpactor#1938]
I am having some issues with phpactor on my new Apple M1 machine in a pimcore project, and I am not sure how to fix it...

I have the `src/Kernel.php` file which looks as follows:

```php
<?php

declare(strict_types=1);

/**
 * Pimcore.
 *
 * This source file is available under two different licenses:
 * - GNU General Public License version 3 (GPLv3)
 * - Pimcore Enterprise License (PEL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 * @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
 * @license    http://www.pimcore.org/license     GPLv3 and PEL
 */

namespace App;

use Pimcore\HttpKernel\BundleCollection\BundleCollection;
use Pimcore\Kernel as PimcoreKernel;
use 0

class Kernel extends PimcoreKernel
{
    /**
     * Adds bundles to register to the bundle collection. The collection is able
     * to handle priorities and environment specific bundles.
     */
    public function registerBundlesToCollection(BundleCollection $collection): void
    {
        // provides REST API functionality
        if (class_exists(\FOS\RestBundle\FOSRestBundle::class)) {
            $collection->addBundle(new \FOS\RestBundle\FOSRestBundle());
        }

        // OpenAPI 3.0 docs
        if (class_exists(\Nelmio\ApiDocBundle\NelmioApiDocBundle::class)) {
            $collection->addBundle(new \Nelmio\ApiDocBundle\NelmioApiDocBundle());
        }
    }
}
```

It is no problem to use autocompletion for the `$collection` variable (neither completing this variable name itself nor using it for property resp. method complection after `->`). But if I try to write a `use` statement on top and use autocompletion I receive the following error:

```
Error from Phpactor: RecursiveDirectoryIterator::__construct(/Users/danielrotter/Documents/Development/andermatt-pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/geo): Failed to open directory: Too many open files
```
In addition to that instead of a correct value I get just a `0` in the editor... Adding a screenshot here to make absolutely clear how that looks:

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/405874/198692675-11e71c37-38a6-421e-a307-72534fd8e8b2.png">

I once had a [similar issue with xdebug](https://superuser.com/questions/787888/too-many-files-open-on-mac-osx-after-running-apache-in-php-with-xdebug-for-som). I think back then setting something like `ulimit -n unlimited` fixed this issue for me, but it does not help now... Any ideas what is happening here?

**Comment by dantleech** [comment]
There was a similar here but due to something else: https://github.com/phpactor/phpactor/issues/1376.

Are you using the "vim plugin" functionality to import the class? If so I'd recommend configuring the LS client to import automatically when selecting a completion result.

If you _are_ using the VIM plugin then I would probably check to see if it found `composer.json` or a `.git` repository. Run `:PhpatorStatus` and put the results here.

**Comment by danrot** [comment]
I was using the vim plugin... But I am just spontaneously rebuilding my neovim configuration. I've seen that neovim comes with support for the language server already. I always thought that I need a separate plugin for and was afraid of a bloated setup... I am trying it using the language server and get back to you, although it might not be a real solution to this problem.

**Comment by dantleech** [comment]
yeah, my suspicion is that it's not finding a good way to scan the files in your repo so it's using a recursive brute force method. If you paste the output of `:PhpactorStatus` is should confirm if that's the case or not. The VIM plugin still augments the functionality provided via. the LSP server, so still relveant

**Comment by danrot** [comment]
Will provide the output of `:PhpactorStatus` in case it is not working once I've finished my new setup 🙂

**Comment by danrot** [comment]
I have set it up now with LSP and installed phpactor using mason.nvim, and now the problem does not appear anymore...

**Comment by dantleech** [comment]
great, problem solved forever! :tada:
