### ISSUE TITLE
LSP: Crashing on "unrecognized/unsupported"

### ISSUE THREAD

**Issue by MGatner** [phpactor/phpactor#1951]
I'm working on integrating **Phpactor** with **BBEdit** via LSP (taking notes for a PR!). I'm running into an issue where the IDE does not support a feature is causing phpactor to crash:
```console
2022-11-14 10:36:57.730: _ProcessLSPServerRequest: unrecognized/unsupported: {
    id = "61974118-51de-49c2-89d5-aee7dbcde69e";
    jsonrpc = "2.0";
    method = "window/workDoneProgress/create";
    params =     {
        token = "4b03225f-a5de-44f7-b390-7fbe625842f3";
    };
}
2022-11-14 10:36:57.763: The language server for PHP in HTML has unexpectedly terminated: {
    method = "bbedit/serverTaskDidTerminate";
    taskStatus = 255;
    taskStderr = "<no data>";
}
```

 I contacted BBEdit and the author states:
 > The "unrecognized/unsupported " message from BBEdit means merely that it got a request from the server that it didn't understand. In that case it will return a specific method not found LSP response. If the language server crashes because of that, the server needs to be fixed; so I recommend you file a bug with the server developer about it.

It seems like `method not found` should be an acceptable response to the server?

Phpactor version: 2022.10.11@03b00d8176a331323b5a85c48f370a59eb316d9c
PHP version: PHP 8.0.25 (Xdebug v3.1.5)
BBEdit version: 14.6.1 (14D24, Apple Silicon, sandboxed)

**Comment by dantleech** [comment]
hm, I guess we can at least tolerate it, or have a "strict" mode. I'm honestly not sure if the expected behavior is specified: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification.

Feel free to open a PR, although I guess the fix would be at https://github.com/phpactor/language-server

**Comment by dantleech** [comment]
hm, Phpactor does _not_ crash in this situation (at least for me). The exception is caught and returned over the protocol as an error :thinking: 

```
"error": {                                                                                                                                                  
      "code": -32601,                                                                                                                                           
      "message": "Exception [Phpactor\\LanguageServer\\Core\\Handler\\HandlerNotFound] Handler \"phpactor/not_error\" not found, available handlers: \"phpactor/
debug/config\", \"phpactor/debug/workspace\", \"phpactor/status\", \"phpactor/service/start\", \"phpactor/service/stop\", \"phpactor/service/running\", \"worksp
ace/executeCommand\", \"workspace/didChangeWatchedFiles\", \"textDocument/didOpen\", \"textDocument/didChange\", \"textDocument/didClose\", \"textDocument/didSa
ve\", \"textDocument/willSave\", \"textDocument/willSaveWaitUntil\", \"phpactor/stats\", \"textDocument/codeAction\", \"textDocument/formatting\", \"textDocumen
t/completion\", \"completionItem/resolve\", \"textDocument/signatureHelp\", \"textDocument/definition\", \"textDocument/typeDefinition\", \"textDocument/referen
ces\", \"textDocument/implementation\", \"textDocument/documentHighlight\", \"phpactor/indexer/reindex\", \"workspace/symbol\", \"textDocument/hover\", \"textDo
cument/documentSymbol\", \"textDocument/selectionRange\", \"textDocument/prepareRename\", \"textDocument/rename\", \"workspace/willRenameFiles\" at /home/daniel
/www/phpactor/phpactor/vendor/phpactor/language-server/lib/Core/Handler/Handlers.php#29",     
```

How are you running the language server?

Possibly an issue with BBEdit?

**Comment by dantleech** [comment]
ah, hm, perhaps this is rather that the client returns a "response" for the "workDoneProgress" request, but not the one that Phpactor expects. Would be good to see a log showing the exact error.

In anycase there are two things here:

- Do not send the work done progress notification if the client does not support it.
- Do not crash the server on an unepxected response to a specific request (assuming that's what happened)

**Comment by MGatner** [comment]
I'm happy to harvest logs! I didn't find instructions in the docs - anything in particular I should do?

**Comment by dantleech** [comment]
You can enable logging on Phpactor's side with: https://phpactor.readthedocs.io/en/master/other/developing.html#logging

although the best log may be from BBEdit if possible (assuming it would capture the crash, if there was one)

**Comment by MGatner** [comment]
What I sent above is everything that BBEdit logged. It doesn't crash, just the LSP module never activates. It tried restarting Phpactor a few times but gives up after repeat failures. 

I will turn on logging in Phpactor and see what I can grab.

**Comment by dantleech** [comment]
ah ok. I think BBEdit is probably doing some weird stuff here. But definitely a "bug" that we send the workDone request when the client doesn't support it.

**Comment by MGatner** [comment]
> To keep the protocol backwards compatible servers are only allowed to use window/workDoneProgress/create request if the client signals corresponding support using the client capability window.workDoneProgress
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverInitiatedProgress

BBEdit does not include `window.workDoneProgress` in its client capabilities so it seems that the server should not be sending the request to begin with.

**Comment by siegel** [comment]
According to the [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverInitiatedProgress):

> To keep the protocol backwards compatible servers are only allowed to use window/workDoneProgress/create request if the client signals corresponding support using the client capability window.workDoneProgress which is defined as follows: [...]

BBEdit does not signal `window.workDoneProgress` in its client capabilities, so when it receives the unsupported request, it returns a `MethodNotFound` (-32601) error code through the protocol. (See discussion starting [here]( https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#responseMessage).)

**Comment by siegel** [comment]
In response to the unsupported request, the client returns a `MethodNotFound` protocol error. More on that is [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#responseMessage) in case you decide it's advantageous to add robust handling of client-returned errors of this sort.

**Comment by dantleech** [comment]
Great, will look into it 👍

**Comment by dantleech** [comment]
I've updated to show notification messages in the window instead of the workDoneProgress API if the feature is disabled. can you confirm if this resolves the issue @MGatner ?

**Comment by MGatner** [comment]
Awesome! I will try this today... probably won't be off mobile for another 8 hours or so

**Comment by dantleech** [comment]
closing now, let me know if its fixed though :)
