### ISSUE TITLE
vim plugin: PhpactorImportMissingClasses command attempts to import X times

### ISSUE THREAD

**Issue by kedodrill** [phpactor/phpactor#1952]
I might be missing an option, or this very well may be intended, but I'm noticing that the PhpactorImportMissingClasses command will attempt to import multiple times for the same class.

For example, if I have **two** try/catch statements in the same class that have 
`... } catch (Exception $e) { ...`
 (`Exception` is written **twice** in the file), the command will attempt to import `Exception` (showing the list of possible classes) **twice**.

Now this may be intended since perhaps we want to import classes of the same name but use aliases, but maybe there could be an option to just scan once for classes with the same name (basically remove duplicates). Sorry if this is already an option, couldn't seem to find something like this.

Thank you!

**Comment by dantleech** [comment]
hm, this is the "legacy" way of doing things - LSP being the preferred way now. Unfortuantely the code is a little split:

works (LSP):

https://github.com/phpactor/phpactor/blob/9a62c67fc15a20199405f1984d820ab1c45751b0/lib/Extension/LanguageServerCodeTransform/LspCommand/ImportAllUnresolvedNamesCommand.php#L48

doesn't work so well (legacy RPC)

https://github.com/phpactor/phpactor/blob/9a62c67fc15a20199405f1984d820ab1c45751b0/lib/Extension/CodeTransformExtra/Rpc/ImportMissingClassesHandler.php#L50

the code is actually quite similar, the difference with the first is that it wraps the diagnostics in a NameWithByteOffsets value object that provides a `onlyUniqueNames` method.

**Comment by kedodrill** [comment]
ah, interesting. I am actually considering going ahead and switching to neovim, would that solve this? I'll do a little testing and see if it's different, but from what you're saying I think it would?

**Comment by dantleech** [comment]
neovim, or CoC in VIM (I think?). But yeah, Neovim is probably a good switch to make.

**Comment by kedodrill** [comment]
Cool, thank you for the configs! I'll check it out later and will probably end up switching for ncm2. Sounds good, I will keep this open then.

**Comment by kedodrill** [comment]
hmm. I've been messing around with things but man LSP is complicated. I'm not really sure I even need a completer / autocomplete system...and I'm not really a fan of node/js. Anyhow...if there's anything I can do to test new changes or whatever, I'm down. Might even check into that function some tomorrow

**Comment by dantleech** [comment]
Neovim has a native LSP (which is what I use). CoC is an alternative that uses NJS.

**Comment by kedodrill** [comment]
Gave it another try using native LSP from neovim and feeling good about my config so far. Everything seems to be working well. Lua is still...interesting...and my config certainly is a lot bigger. But it's working well.

**Comment by kedodrill** [comment]
figure this could be closed since you have deprecated the old RPC way of doing things

**Comment by dantleech** [comment]
in this case it uses the same stuff as the LSP under the hood, is it still an issue?
