### ISSUE TITLE
PHP 7.4 is no longer supported. Upgrade to PHP 8.0

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#1956]
If you are getting errors when starting the server in Nvim or Code or anything else since your last update it may be becasuse you are running PHP 7.4

```
php --version
```

Update to PHP 8.0 to resolve this.

**Comment by Herz3h** [comment]
In my case, since I'm not using any lspconfig, I had to downgrade to an earlier version (vim-plug syntax below): 

`Plug 'phpactor/phpactor', {'for': 'php', 'do': 'composer install', 'tag': '0.18.1'}`

**Comment by dantleech** [comment]
> I had to downgrade to an earlier version

the last version to support 7.4 is tag `2022.11.12` (https://github.com/phpactor/phpactor/releases/tag/2022.11.12)

**Comment by phil-s** [comment]
The following (at minimum) still state that phpactor requires PHP 7.3:

* https://phpactor.readthedocs.io/en/master/usage/vim-plugin.html
* https://phpactor.readthedocs.io/en/master/usage/standalone.html

**Comment by dantleech** [comment]
PR welcome ;)

**Comment by phil-s** [comment]
That would be ludicrous.  IMHO.

**Comment by dantleech** [comment]
in what way? :thinking:

**Comment by dantleech** [comment]
I appreciate that you have pointed out the issue, and I have now fixed it. It is not ludicrous to suggest that people contribute to the project, and as you say it's a trivial fix that can be done in a matter of seconds - which is why it's a good thing for people to do for themselves - and I'm happy to guide people with that. You are helping me, the unpaid maintainer of this project, in a very small but significant way with such things.

**Comment by phil-s** [comment]
Thank you.

FWIW I didn't actually say (and nor do I believe) that it's ludicrous to suggest that people contribute to the project.  I think contributions are a very good thing.  In this instance I contributed to the project by reporting an error in the documentation.  I merely thought a pull request would be ludicrous for this particular issue.  I do appreciate that a PR might be the method of contribution which is *preferred* in general, but there's a threshold below which I think the difference is pretty negligible for the maintainer (who can perform such a fix extremely quickly without a PR), but more significant for the contributor (as the process of putting together a PR is time-consuming regardless of its content).  If I have anything substantial to contribute, though, I'll certainly create a PR.
