### ISSUE TITLE
Document highlight does not work with recent changes

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1960]
I switched back to 707e7d90 (before `constructor_property_promotion`) to make it working for me.

Can you confirm this bug? I get it on two separate environments.

**Comment by dantleech** [comment]
Hm yes noticed same thing today, thought it was my nvim config

**Comment by przepompownia** [comment]
Thanks @dantleech It's work again!

**Comment by dantleech** [comment]
don't undetstand why :smile:
