### ISSUE TITLE
UnitEnum methods not recognized as an existing function

### ISSUE THREAD

**Issue by michelv** [phpactor/phpactor#1967]
### Cases

Hi,

Looks like phpactor does not recognize the existence of `UnitEnum::cases()`.

Here is a reproducer:

```php
<?php

declare(strict_types=1);

enum MyEnum
{
    case A;
    case B;
    case C;
}

var_export(MyEnum::cases());
```

Error message: `Method "cases" does not exist on class "MyEnum"`

Context: branch 'master' of phpactor, used by vscode-phpactor, PHP 8.1.11.

### Other Methods

Hi,

Looks like phpactor does not recognize the existence of BackedEnum::from() or ::tryFrom().

Here is a reproducer:

```php
<?php

declare(strict_types=1);

enum MyEnum: string
{
    case A = 'a';
    case B = 'b';
    case C = 'c';
}

var_export(MyEnum::from('a'));
var_export(MyEnum::tryFrom('d'));
```

Error messages:
* `Method "from" does not exist on class "MyEnum"`
* `Method "tryFrom" does not exist on class "MyEnum"`

Context: branch 'master' of phpactor, used by vscode-phpactor, PHP 8.1.11.

**Comment by michelv** [comment]
Indeed I needed to re-index. It's odd, I was pretty sure that I had requested a re-index multiple times. You can close the issue. 👍

**Comment by dantleech** [comment]
Good news

**Comment by Einenlum** [comment]
It seems like I also have this bug.

![1](https://user-images.githubusercontent.com/5675200/211026106-944b6bbe-612d-4a9b-b1af-f9decdbc796e.png)

phpactor was installed with Mason:

![mp](https://user-images.githubusercontent.com/5675200/211026136-6d962c52-b928-43cd-9c33-40d17a24345c.png)

I reindexed multiple times and restarted vim, but no luck for now.

**Comment by gbprod** [comment]
Same for me...

**Comment by dantleech** [comment]
yes, seems something regressed potentially
