### ISSUE TITLE
Class "st" not found when changing return type to string

### ISSUE THREAD

**Issue by madflow** [phpactor/phpactor#1974]
I am evaluating phpactor if it can replace intelephense in my Neovim setup. What I witness when using phpactor is, that it reports missing classes, when changing the return type.

For example:

![Kapture 2022-12-03 at 15 04 32](https://user-images.githubusercontent.com/183248/205444987-347d3358-9873-4dc2-a9cf-f1e31fea72a1.gif)

I have installed phpactor with Mason, I am using Neovim 0.8.

**Comment by dantleech** [comment]
hm, I get this occasionally too. in theory the diagnostics should "sleep" while you are typing and only analyse after a second or two, but maybe that's not working as expected.

**Comment by dantleech** [comment]
I've identified the race condition here and addressed it in: https://github.com/phpactor/phpactor/pull/1987

There's likely still improvements to be made, relevant code [here](https://github.com/phpactor/language-server/pull/52)

But let me know if this fixes it and then close this issue if appropriate.

**Comment by dantleech** [comment]
![recorded](https://user-images.githubusercontent.com/530801/209409661-2109b26a-85d1-4b83-8077-3f1c50bd3c9d.gif)

for me it updates about 1 second after the last text edit

**Comment by madflow** [comment]
@dantleech I can confirm the "new" (for me) behaviour. Now there is a short flash of the wrong diagnostics. Maybe I initially messed up the update or something else has changed.

In everyday coding live this does not really happen to me or I cannot see it anymore. I agree that it can be improved. So... close this issue at will - for me it is resolved :D

**Comment by dantleech** [comment]
this should be better now, closing but reopen if it's still an issue for you
