### ISSUE TITLE
Class completion does not work inside a constant value

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1978]
![image](https://user-images.githubusercontent.com/11404453/205521990-81bfde35-3300-4639-bb11-15d104d869be.png)

**Comment by dantleech** [comment]
context is very hit and miss currently, mainly due to the parser which get's confused, but this is the relevant code: https://github.com/phpactor/phpactor/blob/960dda9710454c041c7914b7270d9f4b5fbc6984/lib/Completion/Bridge/TolerantParser/ReferenceFinder/ExpressionNameCompletor.php#L34-L36
