### ISSUE TITLE
Completion: private constants are visible from outside

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1979]
Example from Phpactor: 
![image](https://user-images.githubusercontent.com/11404453/205522708-c86d4f30-dec4-4f94-8f24-53acdb2098f1.png)

**Comment by dantleech** [comment]
code is here: https://github.com/phpactor/phpactor/blob/960dda9710454c041c7914b7270d9f4b5fbc6984/lib/Completion/Bridge/TolerantParser/WorseReflection/WorseClassMemberCompletor.php#L190

you can see the privacy logic is applied for methods and properties in this class, but not constants.

**Comment by przepompownia** [comment]
Thank you for direct hint! I did not started from a test but want to add the case for #1984
