### ISSUE TITLE
Go to implementation not working

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [phpactor/phpactor#1981]
Hi, I am trying phpactor with neovim lua configuration.
It seems that all is working fine except for go-to implementations.
I tried into an interface class implemented by other classes but if I use the `:PhpactorGotoImplementations ` nothing happens. 
It remains blocked without any results. 
How can I debug it?
Phpactor is updated with the branch master

**Comment by AlessandroMinoccheri** [comment]
I am using LSP with that configuration but it doesn't work.
For `go to definition`  for example it works fine.

**Comment by dantleech** [comment]
with LSP you can use:

https://github.com/dantleech/dotfiles/blob/master/.config/nvim/coc.vim#L26

instead of the VIM command **however** the VIM command does work for me.

i assume the index is built? you can run `phpactor index:search` to dump it, (and maybe `grep`  for your class to see if it's indexed)

**Comment by AlessandroMinoccheri** [comment]
The implementation class is not indexed, I think it's that the problem

**Comment by AlessandroMinoccheri** [comment]
ok I did it:

```
phpactor index:clean
phpactor index:build
```

and now all it works fine.

**Comment by dantleech** [comment]
hm, if using LSP it should do it automatcailly when starting the server, but it will only re-index files changed after the last index time. if you add the LSP commands to your config:

https://phpactor.readthedocs.io/en/master/lsp/vim-lsp.html

you will have `:LspPhpactorReindex` command
