### ISSUE TITLE
`posix_kill` function does not exists

### ISSUE THREAD

**Issue by megasteve19** [phpactor/phpactor#1989]
Actually this error not directly from phpactor. It's from a dependency: `amphp/process`. Which is not direct dependency too.

Error happens in [this line.](https://github.com/amphp/process/blob/76e9495fd6818b43a20167cb11d8a67f7744ee0f/lib/Internal/Posix/Runner.php#L197) I'm able to fix it temporarly by doing;

```php
try {
	\posix_kill($pid, 9);
} catch (\Throwable $th) {
	//throw $th;
}
```

But ofcourse, It's not a solution. My php version is `8.1.13`, and `posix_kill` function really doesn't exists. What can I do to solve this issue?

**Comment by mamazu** [comment]
You might want to open an issue over at `amphp/process` they might have a better idea on what could be going wrong here. Just as a hint.

**Comment by dantleech** [comment]
you will need `pnctl` extension enabled to avoid this error. This might well be an Amphp issue.

Which O/S / Distribution are you on?
```
php --info  | grep pcntl
pcntl
pcntl support => enabled
```

is what i get (Ubuntu)

**Comment by megasteve19** [comment]
Yes, you are right. Currenty I'm using Ubuntu and there's no problem at all. My computer at job is Fedora, so It's explains. Thanks for taking your time :)
