### ISSUE TITLE
Language server textDocument/publishDiagnostics notifications are always empty

### ISSUE THREAD

**Issue by joecarl** [phpactor/phpactor#1990]
Hi. I'm implementing a language client for my custom IDE and I can't get `textDocument/publishDiagnostics` correctly. I've managed to implement correctly `textDocument/completion`, `textDocument/hover`, and `textDocument/signatureHelp` request/responses. But when it comes to parse the `textDocument/publishDiagnostics` notifications, the diagnostics array is always empty.
This is the notification I always get, even if the file has obvious syntax errors.
```
{
    "jsonrpc": "2.0",
    "method": "textDocument/publishDiagnostics",
    "params": {
        "uri": "file:///home/user/test/index.php",
        "version": 3,
        "diagnostics": []
    }
}
```
`uri` and `version` are correct but I think the diagnostics array shouldn't be empty.

Also, I only receive `textDocument/publishDiagnostics` notifications after a `textDocument/didChange` request. I don't know why I don't receive the diagnostices right after `textDocument/didOpen` too. 
I've tried to enable phpstan and psalm extensions in the `.phpactor.json` config file but the results don't change.

This is the content of my `.phpactor.json` file 
```
{
	"language_server_phpstan.enabled": true,
	"language_server_phpstan.bin": "/home/user/phpactor/vendor/bin/phpstan",
	"language_server.profile": true,
	"language_server.trace": true,
	"language_server_psalm.enabled": true,
	"language_server_psalm.bin": "/home/user/phpactor/vendor/bin/psalm",
	"language_server_php_cs_fixer.enabled": true,
	"language_server_php_cs_fixer.bin": "/home/user/phpactor/vendor/bin/php-cs-fixer"
}
```

I'm using the `2022.12.12` release. And this is my initialization request params:

```
{
	clientInfo: {
		name: "Test Language Client",
		version: '0.1.0'
	},
	capabilities: {
		textDocument: {
			publishDiagnostics: {
				relatedInformation: true,
				tagSupport: {
					valueSet: [1, 2],
				},
				versionSupport: true,
				codeDescriptionSupport: true,
				dataSupport: true,
			},
			synchronization: {
				dynamicRegistration: true
			}
		}
	},
	trace: 'verbose',
	rootUri: "file:///home/user/test"
}
``` 

At this point I don't know what else I can do. Any help is appreciated. 

Also how can I get the `textDocument/completion` to complete with code which has not been loaded yet? Because I just got it to complete with functions which are defined in the current file or in files which have been previously opened with `textDocument/didOpen`. Does it mean that I have to send `textDocument/didOpen` request for each file in my project folder (vendor folder included)? (I hope no...)

Thanks in advance!

**Comment by dantleech** [comment]
>  the diagnostics array is always empty.

By default Phpactor will use only the PHP linter (`php-lint`) (f.e. `PHP Parse error:  syntax error, unexpected identifier`.

Currently the PHP linter uses [PHP_BIN](https://github.com/phpactor/phpactor/blob/57891476c6b1d6d27f2f78c9023d60a551048808/lib/Extension/LanguageServerDiagnostics/LanguageServerDiagnosticsExtension.php#L20) to reference the PHP binary used for linting.

Phpstan and Psalm extensions will require that you either install them in `vendor` or configure a path where the respective executables can be found..

> I don't know why I don't receive the diagnostices right after textDocument/didOpen too. I don't know why I don't receive the diagnostices right after textDocument/didOpen too.

The diagnostics should be published by default on open, update and save.

> Also how can I get the textDocument/completion to complete with code which has not been loaded yet? 

When the initialization request is sent AND the [initialized](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialized) notification is recieved an [event is fired](https://github.com/phpactor/phpactor/blob/57891476c6b1d6d27f2f78c9023d60a551048808/vendor/phpactor/language-server/lib/Listener/ServiceListener.php#L27) the indexer should start.

**Comment by joecarl** [comment]
Thankyou so much!!!

> After the [initialized](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialized) notification is recieved from the client an [event is fired](https://github.com/phpactor/language-server/blob/3cbbaa3ed4e2c7b2e8c9799038beddae2c4019e5/lib/Listener/ServiceListener.php#L27) the indexer service should start.

Definitely I wass missing that part, I never sent the initialized notification T_T. Now the service seems to be doing more stuff, and my diagnostics array is not empty Yay!!.

Anyway there must be something else that I'm doing wrong because the indexer doesn't seem to be indexing my files, I keep getting "Class not found..." errors. Is there any extra config param that I have to set so that the indexer indexes my project files? Thanks.

**Comment by dantleech** [comment]
Cool!

You can debug the index with `phpactor index:search | grep ThingThatShouldBeIndxed`. If it is running it will either send progress notifications or, if your client did not indicate support for that, it will send messages to the window (e.g. `10% done`).

In general you can enable [logging](https://phpactor.readthedocs.io/en/master/other/developing.html#logging) to see if anything odd is happening.

**Comment by joecarl** [comment]
Thankyou so mush for your hints, I finally got it working, I was setting the rootUri incorrectly :/
Now I have a final question: is there any possibility that I can specify URIs relative to the project rootpath?

**Comment by dantleech** [comment]
I don't think so, all text document URIs are absolute AFAIK.

**Comment by joecarl** [comment]
Ok, I will see what I can do about that...
Thankyou so much for your time. I will close this thread.
