### ISSUE TITLE
Complete attribute classes

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#1999]
Given #1998 and previous examples with class constant completion (#1979,  #1985) I started to find how to restrict the suggestion list to `Attribute`s only. This led me to the question which [Completor](https://github.com/phpactor/phpactor/blob/master/lib/Completion/Core/Completor.php) should be used to it: any existing or some new?

**Comment by dantleech** [comment]
I actually thought we supported this (and attributes generally) already but I can find any evidence of it.

It should be a new completor, but the bigger part of the task is probably supporting attributes in WorseReflection.

- We should add an `attributes()` accessor to the `ReflectionClass` and the `ReflectionAttribute` class: https://github.com/phpactor/phpactor/blob/01afb965caf309c679dea5dbdc4c1723cd2b3522/lib/WorseReflection/Core/Reflection/ReflectionClassLike.php#L15
- We will then be able to filter only attribute classes.

**Comment by przepompownia** [comment]
I looked around for similar examples. It promises to be some work, but in the convention of existing mechanisms so I can try to do it as much as possible, with possible your help, modifications, new test cases etc.

It seems that starting from "bottom" can be easier for me at the moment so I started from `AttributeQualifier`.

**Comment by dantleech** [comment]
i think this is done!
