### ISSUE TITLE
from/tryFrom on Enum not working (?)

### ISSUE THREAD

**Issue by nataneb32** [phpactor/phpactor#2000]
There as a "bug" in the tolerant parser. Where the interface attributes was broken.

It also broke the enum attributes, like from, value.

I fixed it: https://github.com/microsoft/tolerant-php-parser/pull/395

**Comment by Einenlum** [comment]
It seems indeed like my lsp server doesn't recognize `from` and `tryFrom` enum methods.

![1](https://user-images.githubusercontent.com/5675200/211022916-aa3c1e01-7017-4b81-8377-ce021d7cc585.png)

**Comment by dantleech** [comment]
> It seems indeed like my lsp server doesn't recognize from and tryFrom enum methods.

is this related? i think it's a different issue.

**Comment by Einenlum** [comment]
> > It seems indeed like my lsp server doesn't recognize from and tryFrom enum methods.
> 
> is this related? i think it's a different issue.

Oh, sorry. Seems like I found a (closed) issue related to what I got. Will post there.

**Comment by dantleech** [comment]
Assume this is `#[ThisIsAnAttribute]` attributes? Can you provide an example that exposes the broken behavior?

**Comment by dantleech** [comment]
`tryFrom`? have you got some code that reproduces the issue?

**Comment by mamazu** [comment]
This has also been fixed with the merge request: https://github.com/phpactor/phpactor/pull/2267

As noted by this comment: https://github.com/phpactor/phpactor/issues/2256#issuecomment-1557074351

**Comment by mamazu** [comment]
@nataneb32 can you confirm this is fixed?

**Comment by dantleech** [comment]
assuming fixed, reopen if not the case
