### ISSUE TITLE
Hover text formatting could be improved.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2004]
### Discussed in https://github.com/phpactor/phpactor/discussions/2003

<div type='discussions-op-text'>

<sup>Originally posted by **haolian9** December 29, 2022</sup>
Hi,
I'm not sure if this is a problem on my neovim setup or on the phpactor side.
that's what I got in nvim, do you think it's an expected response?

```
### array_map

Applies the callback to the elements of the given arrays
https://php.net/manual/en/function.array-map.php

Callback function to run for each element in each array.

An array to run through the callback function.

after applying the callback function to each one.

<?php function array_map(callable()|null $callback, array $array, array[] $arrays): array
```

as you can see, the parameter part is missing, IMO it should be something like that: (here's [the official doc](https://www.php.net/manual/en/function.array-map))

```
callback: 
    Callback function to run for each element in each array.

array:
    An array to run through the callback function.

arrays:
    after applying the callback function to each one.
```

I do checked the response from phpactor before nvim's builtin lsp client
processing it, and the lsp client did not trim/filter these info.
</div>

**Comment by dantleech** [comment]
Imrpoved

**Comment by haolian9** [comment]
wow, great!

(actually i was planning to give this issue a try, with your commits I now have a easier start point to dive into the source code, haha)
