### ISSUE TITLE
Differentiate between comment and doc comment in NVIM LSP?

### ISSUE THREAD

**Issue by mamazu** [phpactor/phpactor#2010]
![image](https://user-images.githubusercontent.com/14860264/210154760-5e077325-c7c2-4dd8-99f9-c558cf0a1543.png)

Would it be possible to also differentiate between comments and doc_comments and maybe get some highlighting in the doc comments as well? If so maybe point me to it and I can work on it.

**Comment by dantleech** [comment]
Phpactor doesn't provide syntax highlighting. Is that what you mean?

**Comment by mamazu** [comment]
Okay, then where does the syntax highlighting come from? The tree on the right is the AST that Treesitter has generated. I thought this is coming from something inside of phpactor.

**Comment by dantleech** [comment]
No, it's all neomvim/treesitter :l
