### ISSUE TITLE
Doesn't appear to do anything, with mysterious "ERROR" in :LspLog

### ISSUE THREAD

**Issue by downhiller** [phpactor/phpactor#2027]
I'm trying to move from a standard nvim setup to nvim IDE.  I've used kickstart.nvim, and after installing phpactor when I edit a php file I get no autocompletion.
`:LspLog` shows:

```
[START][2023-01-04 12:11:23] LSP logging initiated
[ERROR][2023-01-04 12:11:23] .../vim/lsp/rpc.lua:733    "rpc"   "phpactor"      "stderr"        "Starting language server, use -vvv for verbose output\n"
```

Which seems odd to me, as the line that says `[ERROR]` doesn't appear to obviously actually BE an error...?  But maybe someone here who knows more than me can point me in the right direction?

`:LspInfo` shows:

```
Language client log: /root/.local/state/nvim/lsp.log
Detected filetype:   php

1 client(s) attached to this buffer:

Client: phpactor (id: 1, bufnr: [1])
 filetypes:       php
 autostart:       true
 root directory:  /var/www/sites/myproject
 cmd:             phpactor language-server

Configured servers list: phpactor, sumneko_lua
```

If I edit the `init.lua` file, I DO get autocompletion (with a very similar `:LspInfo` output:

```
Language client log: /root/.local/state/nvim/lsp.log
Detected filetype:   lua

1 client(s) attached to this buffer:

Client: sumneko_lua (id: 1, bufnr: [1])
 filetypes:       lua
 autostart:       true
 root directory:  /var/www/sites/myproject
 cmd:             lua-language-server

Configured servers list: phpactor, sumneko_lua
```

...so the issue seems to lie with phpactor rather than nvim/lsp/mason/whatever (I'm a complete noob to this, no idea what I'm talking about...)

Thank you!

**Comment by dantleech** [comment]
> Which seems odd to me, as the line that says [ERROR] doesn't appear to obviously actually BE an error...?

this is likely just indicating that it's output on `stderr` stream, which is fine and expected.

you can check my [dotfiles](https://github.com/dantleech/dotfiles/tree/master/.config/nvim) also can you determine if other LSP functionality is working? e.g. goto definition

**Comment by downhiller** [comment]
LSP functionality seems to work entirely in lua files, but not at all in php files.  I've set `vim.lsp.set_log_level(0)` and see a bunch of `[DEBUG]` lines but nothing that feels useful.  There's a `"LSP[phpactor]" "client.request"` and a bunch of `"rpc.send"      {  jsonrpc = "2.0",  method = "textDocument/didChange"`, but still nothing happens.  No completion, no goto definition.

**Comment by dantleech** [comment]
Are you using PHP 8.0 or above?

**Comment by dantleech** [comment]
You can try enabling Phpactor's logs: https://phpactor.readthedocs.io/en/master/other/developing.html#logging

**Comment by downhiller** [comment]
Yes, PHP 8.2.  I tried enabling phpactor logs but it doesn't seem to work - as far as I can tell the logfile doesn't get created, and (in case the issue was that it can't create the file, unlikely, I know) if I `touch phpactor.log` myself nothing is written to it.

**Comment by dantleech** [comment]
can you run the phpactor "binary"? `~/path/to/phpactor/bin/phpactor` ? maybe try running the indexer manually `phpactor index:build`

**Comment by downhiller** [comment]
I can.  Running `phpactor index:build` gave this response:

```
Building job...done
Building index:

No files found
```

My project is in `/var/www/sites/myproject`

I have `phpactor` in `/var/www/sites/myproject/phpactor/bin/phactor`, with a symbolic link putting it at `/usr/local/bin/phpactor` as well.

I ran `phpactor index:build` from `/var/www/sites/myproject`.

If I run `phpactor status` from `/var/www/sites/myproject` I get this:

```
Version: "b4b079cc (29 hours ago) Int-range-2025
Filesystems: git, simple, composer
Working directory: /var/www/sites/myproject

Config files (missing is not bad):

  ✘ /root/.config/phpactor/phpactor.json
  ✘ /root/.config/phpactor/phpactor.yml
  ✔ /var/www/sites/myproject/.phpactor.json
  ✘ /var/www/sites/myproject/.phpactor.yml

Diagnostics:

  ✔ Composer detected - Phpactor could work faster without an index
  ✔ Git detected - enables faster refactorings in your repository scope!
  ✔ XDebug is disabled. XDebug has a negative effect on performance.
```

If I run it from anywhere else (relying on the `/usr/local/bin/phpactor` symlink I get this:

```
Version: "b4b079cc (29 hours ago) Int-range-2025
Filesystems: simple
Working directory: /var/www/sites

Config files (missing is not bad):

  ✘ /root/.config/phpactor/phpactor.json
  ✘ /root/.config/phpactor/phpactor.yml
  ✘ /var/www/sites/.phpactor.json
  ✘ /var/www/sites/.phpactor.yml

Diagnostics:

  ✔ XDebug is disabled. XDebug has a negative effect on performance.
  ✘ Composer not found - some functionality will not be available (e.g. class creation) and class location will fallback to scanning the filesystem if index not enabled - this can be slow. Make sure you've run `composer install` in your project!
  ✘ Git not detected. Some operations which would have been better scoped to your project repository will now include vendor paths.
```

Does any of that help you help me? 😂😭

**Comment by dantleech** [comment]
Try `phpactor index:build --reset`

**Comment by downhiller** [comment]
`phpactor index:build --reset` did seem to do something, took a couple of minutes and then spat out:

    Building job...done
    Building index:

     9590/9590 [============================] 100% 34 secs/34 secs 212/1,611 mb

But alas still nothing works.

nvim v0.8.0

Thank you for your continued efforts!

**Comment by dantleech** [comment]
Which PHP version operating system, neovim version, or other relevant information do you have?

**Comment by downhiller** [comment]
PHP 8.2.1 now (was 8.2.0 when I originally posted)
CentOS Stream release 8
nVim 0.8.0

Nothing weird/unusual...

**Comment by downhiller** [comment]
So, without me doing anything, it's started working, a week later.  I suspect the issue is that I have an assets directory inside my project root, with 2TB of jpg files in it.  Will phpactor have been stuck indexing that?  I've been meaning to move them out of the project root for some time...

**Comment by dantleech** [comment]
no, Phpactor should ignore anything that's not a `.php` file :thinking:

**Comment by downhiller** [comment]
I've found now that actually, it still "doesn't work".  The only thing I did differently to last week was open a file, get sidetracked, and not try editing it until it had sat there a few minutes.  Indeed if I open the same file now, it "doesn't work".  But after a few minutes (no idea how long) it does work.  Without doing more testing, I don't know how long it takes - maybe it's 30 seconds, maybe it's 3 minutes, but it's certainly a problem.

Any ideas?  This is a powerful machine (128GB ram, 64core epyc, loads of free memory, current load average < 2)

**Comment by downhiller** [comment]
I added a line to the exclude_patterns:

    "indexer.exclude_patterns": [
       "/vendor/**/Tests/**/*",
       "/vendor/**/tests/**/*",
       "/var/cache/**/*",
       "/vendor/composer/**/*",
       "/photos/**/*"
    ]

And re-ran `phpactor index:build --reset` just in case it was getting snared up iterating over 50million jpeg files (even if it ignores them once it's identified them), but same issue.

**Comment by dantleech** [comment]
did you try moving the photos directory outside of the project root to see if it's that?

**Comment by downhiller** [comment]
I didn't - not trivial.  But can do if it'll make the difference.  Do you think it might be?  Even though I've added that line to the .json file?

**Comment by dantleech** [comment]
just `mv photos ../`  and see if Phpactor works as expected?

**Comment by downhiller** [comment]
Sorry, had a big job running and didn't want to interrupt it.  Have tried that now, made no difference.  I did another `phpactor index:build --reset` which took 34 seconds, as opposed to something like 10 minutes when the `/photos` directory is present.

**Comment by downhiller** [comment]
Sorry, had a big job running and didn't want to interrupt it. Have tried that now, makes a big difference. I did another phpactor index:build --reset which took 34 seconds. When I do it with photos present it sits on Building job... for 2-3 minutes before it builds the index.

Anyway, now when I launch a file I get the index/build info that appears in the bottom right of the file within a second or two, instead of the 1min50 (timed three times) that it was taking before.

Thank you, sorry it was something so stupid and simple.  I had thought that excluding that directory in phpactor.json would do the trick, but I guess it still steps in and checks every single file to see if it matches the exclude pattern or not!
