### ISSUE TITLE
Type error on finding references

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#2029]
Looking around for #1842 I tried to list references to `resolve` from [lib/WorseReflection/Core/Inference/Resolver.php](https://github.com/phpactor/phpactor/blob/b4b079cc8bf43f6fd9d03507b0c850b0d02109d2/lib/WorseReflection/Core/Inference/Resolver.php#L9) and get regular error instead (on two environments independently):

```
   Error  23:11:10 notify.error phpactor: -32603: Exception [TypeError] Phpactor\DocblockParser\Ast\TypeList::Phpactor\DocblockParser\Ast\{closure}(): Argument #1 ($element) must be of type Phpactor\DocblockParser\Ast\Element, null given at /home/arctgx/.vim/pack/bundle/opt/phpactor/lib/DocblockParser/Ast/TypeList.php#40
```

**Comment by dantleech** [comment]
Here is the fix I think: https://github.com/phpactor/phpactor/pull/2030 but need to add a test

**Comment by przepompownia** [comment]
Both on the slower and faster machine I get one usage in NodeContextResoler - after about one minute but without error.
