### ISSUE TITLE
Cannot install via. Composer

### ISSUE THREAD

**Issue by ctf0** [phpactor/phpactor#2031]
```bash
❯ composer global require phpactor/phpactor:dev-master -W
Changed current directory to /Users/xxx/.composer
./composer.json has been updated
Running composer update phpactor/phpactor --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpactor/phpactor dev-master -> satisfiable by phpactor/phpactor[dev-master].
    - phpactor/phpactor dev-master requires microsoft/tolerant-php-parser dev-encapsed-as-string-literal -> found microsoft/tolerant-php-parser[dev-roblourens-readme-fix, dev-roblou/fixTemplateStringParse, dev-main, dev-nullableTypes, dev-lexicalGrammarTestSetup, dev-newStaticError, dev-searchExclude, dev-iteratorPerfTest, dev-parseIncludeRequire, v0.0.1, ..., v0.1.2] but it does not match the constraint.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by dantleech** [comment]
hm, we're using a forked version (via. `repositories`) of tolerant parser currently, which means that `composer require` will not work, but this isn't really a supported installation method. You should install it as follows:

https://phpactor.readthedocs.io/en/master/usage/standalone.html

nonetheless I'll see if I can fix it.

**Comment by ctf0** [comment]
i have tried with https://phpactor.readthedocs.io/en/master/usage/standalone.html#global-installation but i cant run the bin file
```
❯ phpactor -h
zsh: permission denied: phpactor
```

i tried with `sudo chown -R "$USER":admin ~/phpactor/bin` but nothing changed.

**Comment by mamazu** [comment]
Shouldn't the executable be marked with the `+x` in the repository so that it is clones the file as executable?

**Comment by dantleech** [comment]
I've added our fork of tolerant-php-parser to packagist now, so `composer require` should work again.

**Comment by dantleech** [comment]
hm, scratch that, the file [exists](https://github.com/phpactor/phpactor/blob/master/templates/help/markdown/Phpactor/WorseReflection/Core/Type.twig).

when do you get this error? I think if anything it should be encountered on hover:

![image](https://user-images.githubusercontent.com/530801/211273482-a64346eb-174e-4ccf-9df3-c6b52a5126e6.png)

**Comment by ctf0** [comment]
> when do you get this error? I think if anything it should be encountered on hover:

![Screen Shot 2023-01-09 at 11 13 38 AM](https://user-images.githubusercontent.com/7388088/211274195-ccdf9dee-91d3-42c3-acda-dab746c9a7cd.png)

**Comment by dantleech** [comment]
hm, works for me 

![image](https://user-images.githubusercontent.com/530801/211275429-48feed50-6aba-458f-8bbd-bcadf12757cc.png)

i guess you have updated phpactor, composer install, restarted vs code etc?

**Comment by ctf0** [comment]
> i guess you have updated phpactor, composer install, restarted vs code etc?

yes all done, i even removed the cache folder `/Users/xxx/.cache/phpactor` & reindexd using `Phpactor: Re-index workspace` but still gives same error everytime.

i also checked my global composer installes & found that `beyondcode/expose` is using twig, which i've also removed.

but sadly the error still exists 😭 .

**Comment by dantleech** [comment]
oh, I wonder if it's relative paths and installing via. `composer` .... that might explain it.

maybe try the normal `git clone ` installation method, or if using VS code, it should actually install Phpactor automatically.

**Comment by ctf0** [comment]
yeah i did just that, i went back to the git clone way, as for the vscode, i dont believe it does that.

**Comment by dantleech** [comment]
it _should_ do: https://github.com/phpactor/vscode-phpactor#installation

**Comment by ctf0** [comment]
i did that, but the extension doesnt install the core pkg `phpactor` on its own, the user have to install both pkgs

**Comment by dantleech** [comment]
it should install Phpactor automatically, but I have seen issues with that not working on MacOS if you are using MacOS (I wasn't able to investigate the issue unfortunately).

**Comment by ctf0** [comment]
oh ok, if there is something i can do, plz tell me where to start.
