### ISSUE TITLE
PHP8-posix extension not required by default

### ISSUE THREAD

**Issue by dacianb** [phpactor/phpactor#2034]
Hello everyone!
I recently stumbled upon this project and wanted to try it out by using the Kate LSP Client...
After following the instructions for a global install i configured the client but there was a error in the LSP output window:
```
PHP Fatal error: Uncaught Error: Call to undefined function posix_kill() in /home/dacian/Documents/Dev/Tools/phpactor/vendor/amphp/process/lib/Internal/Posix/Runner.php:197
```
I am using openSUSE Tumbleweed with the latest updates and PHP8 from the official repos. After some digging around i found that the posix PHP extension was not installed on my machine, so i did exactly that, after it works perfectly.
I would suggest adding the posix extension to the composer.json file as a required.

Thanks.

**Comment by dantleech** [comment]
:+1: feel free to open a PR
