### ISSUE TITLE
Generate construtor does not work with attributes

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2059]
```
#[Attribute]
class MyAttribute
{
}
````

```
#[MyAttribute('foo')]
```

:point_up: should be able to generate the constructor.

**Comment by mamazu** [comment]
What do you mean? If the class has Attributes you can't generate a constructor?

**Comment by dantleech** [comment]
No, generate a constructor on an Attribute class, e.g. when using new Attributes.

**Comment by dantleech** [comment]
updated description
