### ISSUE TITLE
PHP Versions

### ISSUE THREAD

**Issue by FatBoyXPC** [phpactor/phpactor#206]
Tried looking for an email or twitter to ask this instead, so I apologize in advance! Is it possible to specify a path to the php binary I'm using? I've got a few versions of PHP installed and would like to force it to 7 if at all possible!

**Comment by greg0ire** [comment]
https://twitter.com/phpactor ;)

**Comment by FatBoyXPC** [comment]
Thanks!

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/phpactor/commit/92648078e94e3e43e96b159851be8c403ef215e8 !

**Comment by FatBoyXPC** [comment]
OMG thank you! I'll get to playing with this plugin this weekend!

**Comment by FatBoyXPC** [comment]
I finally installed this plugin and it's **amazing**! However, when I go into `~/.vim/bundles/phpactor/plugin/phpactor.vim` I don't see `let g:phpactorPhpBin` on L#11 or L#244. I did confirm that the commit shows up in the git log, though!

**Comment by FatBoyXPC** [comment]
I deleted my last comment because I realize it was incorrect, however, I'm having trouble actually getting this variable set. I'm using a vim distribution called spf13, and even though I've put this in all of the vim files (even the ones I'm not supposed to edit), whenever I `:echo g:phpactorPhpBin` I get `php` instead of the path I've specified

**Comment by dantleech** [comment]
Ah, I guess it is being overridden, we should probably check to see if the variable is already set before creating 

Are you setting the variable before or after Phpactor is registered?

**Comment by FatBoyXPC** [comment]
I'm not sure, but I **hope** it's both before *and* after, because I've put it in **all** the vimrc files that spf13 tells me to put it in (including just plain vimrc which it warns against).

Also, you might want a new issue for this, but I'm in a laravel app, and I get this when I try to GotoDefinition on `PartnerOnboarding::findByCode`:
`Phpactor: Containing class for member "findByCode" could not be determined`.

I do have `use PartnerOnboarding` just below my namespace, and when I GotoDefinition with my cursor on `PartnerOnboarding` on that same line, it finds that class just fine!

**Comment by dantleech** [comment]
> I'm not sure, but I hope it's both before and after,

Ok, I will have a look...

> Also, you might want a new issue for this

Yes, please create a new issue :)
