### ISSUE TITLE
Only suggest Attributes (i.e. classes with the Attribute attribute) for Attribute completion.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2060]
It "works" but only for searching all classes and only on the "short name". There are two things to make it more convenient:

- :heavy_check_mark:  Index "flags" associated with the class - while we probably don't want to index all the attributes a class has, it would be useful to know if it _is_ an attribute so we can efficiently filter it in the index. So we can add an "ATTRIBUTE" flag.
- :heavy_check_mark:  ~We can separately support completion on namespace segments.~ :point_left:  implemented.
- ... profit?

**Comment by mamazu** [comment]
Is there anything I can do to help with this issue. At my company we are just getting started to work with attributes but trying to find the right class in a Symfony framework called `Route` is always guesswork.

**Comment by mamazu** [comment]
Question is how do I need to change the query to only return "attribute classes" when completing an attribute

**Comment by przepompownia** [comment]
I started to play with #2100. No test case was touched yet. Feel free to make changes if you think this might be a good start.

**Comment by przepompownia** [comment]
Is there anything else missing to close this issue?

**Comment by dantleech** [comment]
Nope I think that's it :)
