### ISSUE TITLE
Class renaming using a prebuilt index

### ISSUE THREAD

**Issue by afshinm** [phpactor/phpactor#2069]
Is it possible to rename (or transform) a class using a prebuilt Phpactor Index? We are hoping to run cronjobs to keep the index up to date but then we would like to use this index for some of the refactoring tasks that we want to perform, like renaming a class and its references in the codebase.

**Comment by dantleech** [comment]
Probably... but how big is the index that it needs to be built with a cron? I wouldn't expect that to be a happy use case.

**Comment by afshinm** [comment]
@dantleech 1.5GB, `296,627`files

**Comment by dantleech** [comment]
The indexnis updated incrementally nonce built, so not sure using a crown will help that much. Ideally we need to improve th e indexer to enable it to use multiple cores.

**Comment by afshinm** [comment]
Got it, thanks @dantleech. Right now, when I use `phpactor references:class MyClass.php --replace "MyNewClass" -vvv`, the operation takes at least 15mins to complete and to me it seems like that command is ignoring the fact that there is a pre-built index on my machine. 

How can I debug that to make sure it's actually using the existing index folder instead of generating a new one? I see that there is a `--filesystem` argument but not sure how to use that.

**Comment by dantleech** [comment]
ah... it's possible (!) that one is _not_ using the index (it's a legacy command and if so uses a *more* brute-force method). The LSP uses the index

**Comment by afshinm** [comment]
Oh, interesting. I can try the LSP today and will let you know how it goes. Would it be useful to have a CLI interface for that? I'm happy to contribute if you think it's a good addition to the library.

**Comment by dantleech** [comment]
It's a bit of a minefield. The renaming stuff is split heavily between the "indexed" (LSP) method and the legacy non-indexed method. The legacy one actually works more reliably, but can be much slower. So it's perhaps not an easy place to start contributing (for you or me :smile: )

**Comment by afshinm** [comment]
Understood. Thanks a lot @dantleech.
