### ISSUE TITLE
Option to switch from complete constructor to make promoted properties?

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2071]
e.g. in PHP 8:

```
    public function __construct(UserRepository $userRepository)
    {
    }
```

we currently provide code actions to "complete constructor" but, for me at least, it's _far_ more common that I have to go back and prefix `private` or `public`

provide a code action to "promote" constructor properties.

**Comment by mamazu** [comment]
Could it be that we don't have a way to build promoted properties in the code right now? If not, I could try to create it.

**Comment by dantleech** [comment]
Yes for sure, which is triggered exactly the same as `complete constructor`  but will promote properties instead of adding the properties + assignments.

**Comment by dantleech** [comment]
Done
