### ISSUE TITLE
Show namespace on hover

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2081]
it would be very useful sometimes to see which namespace a class belongs to:

![image](https://user-images.githubusercontent.com/530801/218258118-47331b42-0493-48b3-a548-daad8e929663.png)

**Comment by mamazu** [comment]
If you can point me to where the hover pop-ups are generated I'll see what I can do.

**Comment by dantleech** [comment]
I'll probably pick this up, it's pretty simple but want to play around with it

**Comment by dantleech** [comment]
Done in #2088
