### ISSUE TITLE
Class “Query” not found

### ISSUE THREAD

**Issue by cizordj** [phpactor/phpactor#2098]
Hi, it seems that phpactor cannot find the class “Query” on ruflin's [elastica](https://github.com/ruflin/elastica) library. The class physically exists in `src/Query.php` but the phpactor shows me a different class when I hover it: `src/Query/Match.php`. It also shows me a message `Class “Query” not found` and when I go to the definition it opens the `Match` class.

I created a little repository to reproduce this issue:
[phpactor-issue-class-query-not-found](https://github.com/cizordj/phpactor-issue-class-query-not-found)

Just run composer install and open the class: `ClassQueryNotFound.php`, you'll get the message from phpactor.

My php version:
```
PHP 8.2.2 (cli) (built: Feb  7 2023 11:27:52) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.2, Copyright (c), by Zend Technologies
```

Phpactor version:
```
Phpactor dev-master@56c3f1ba6932f74088471350aded6c912c4af60c
```

I'm using phpactor through neovim's lsp.

**Comment by cizordj** [comment]
[phpactor.log](https://github.com/phpactor/phpactor/files/10769905/phpactor.log)
I am attaching this log which might help.

**Comment by dantleech** [comment]
hmm, confirmed

![image](https://user-images.githubusercontent.com/530801/219762054-d6cfbd7c-7a67-4171-bc9c-c795e2b7734c.png)

but when I jump to definition it goes to `Match`

**Comment by dantleech** [comment]
the first "issue" is that the class is invalid in PHP 8.0 - `match` is a reserved word, as such the Parser refuses to recognise the name The second is that the indexer would cocatenate the class name on the namespace, in this case there is no class name so it indexes the file under `Elastica\Query`

I assume you're on a code base < 8.0? If so this probably is not worth fixing...

**Comment by dantleech** [comment]
Have fixed the indexer to _not_ index if the class name is missing (as is the case if it's a "reserved word" for right or wrong). Closing for now, but happy to discuss further.

**Comment by cizordj** [comment]
I tested on my machine and the Query class is being found, thank you so much
