### ISSUE TITLE
Container: Add typed parameter accessor

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2102]
In order to make the Container more type safe:

### getTyped

Currently `get()` can accept either a `class-string<T>` or a string. If it's a `class-string<T>` it will return `T`  - i.e. `get(Foo::class)` will return `Foo`. Some services cannot be mapped to class names however.

For these we can add `getTyped(string $id, classs-string<T> $type): T`. So `$container->get('foobar', Foobar::class)` will evaulate to `Foobar`.

## Parameter

Currently `getParameter($p)` returns `mixed`. We can improve this by returning `Parameter`:

```
$container->getParameter('foo')->toInt(); // int
$container->getParameter('foo')->toFloat(); // float
$container->getParameter('foo')->toString(); // string
```

**Comment by dantleech** [comment]
I've added `$service = $container->expect('service_id', MyService::class);` and Phpactor has the new version. A solution for typed parameters is still open though.

**Comment by mamazu** [comment]
Maybe it would make sense to introduce special methods for service that we need regularly?

**Comment by dantleech** [comment]
No, that would be bad: it would couple to the container to other packages. But also "what we use regularly" would change and the class would attract more and more methods.

**Comment by mamazu** [comment]
Should be done with #2149
