### ISSUE TITLE
Autoconfiguration

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2103]
When the application starts (and/or periodically) check to see if any available extensions can be applied to the user's project.

In general this would work by, for example, checking if composer has `phpstan` and then checking to see there is a `phpstan.enabled` entry in `phpactor.json`, if there is not offer to enable PHPStan (and provide messaging to the user that they'll need to restart the LS)

Such a method could be done with most if not all of the 3rd party extensions:

- PHPStan
- Psalm
- Symfony
- Behat
- PHPUnit
- etc

The concept can be general enough that, for example, Symfony may also offer to add ignore paths (again, only if none are set in the local config)

**Comment by mamazu** [comment]
Would that also mean autowiring like in symfony that it automatically does the container stuff?

Like this: https://symfony.com/doc/current/service_container/autowiring.html#an-autowiring-example

**Comment by dantleech** [comment]
No, nothing like that (and I really disklike that sort of thing - you save on the 2 minutes it costs to connect something manually at the cost of hidden complexity).

This is just about automatically setting up `.phpactor.json` if we detect that things could be enabled.
