### ISSUE TITLE
Provide deprecation information

### ISSUE THREAD

**Issue by mamazu** [phpactor/phpactor#2104]
Currently phpactor doesn't report when a method is deprecated. It would be nice if there would be a way to do that probably best with a diagnostic?

**Comment by dantleech** [comment]
It does show deprecations but not as a diagnostic:

![image](https://user-images.githubusercontent.com/530801/219959982-dec28ae5-f778-404e-af30-59b797a67e44.png)

But yes, adding it as a diagnostic should be possible.

**Comment by mamazu** [comment]
Thanks for working on it. :)
