### ISSUE TITLE
Does it support call static methods ?

### ISSUE THREAD

**Issue by dagang007** [phpactor/phpactor#2125]
When a class has some static methods by using  __callStatic() , will phpactor show completion of these methods ? 
or these methods have been listed by using php doc `@method` at  top of class file. 
I tried , it  completed well with instance methods . but didn't  with callstatic methods . 
And I didn't even see phpactor running . Typing `ps aux|grep php` , it only showed one process : python3  /... /yarp.py ...ncm2_phpactor

**Comment by dantleech** [comment]
can you provide a code example?

**Comment by dagang007** [comment]
When I type `A::he` , I hope phpactor could complete this static method . 
`namespace B;
/*
* Class A
* @package B
* @method hello()
*/
Class A{
    public static function __callStatic($method, $params){ ... }
}`
Another question is command like `PhpactorGotoDefinition` working well , but why there's no process like `php phpacotor` running ?

**Comment by dantleech** [comment]
> When I type A::he , I hope phpactor could complete this static method .

the syntax is as follows for static methods:

```
/**
 * @method static Bar foobar(string $baz)
 */
```

(i.e. `@method [static] <type> <methodname>(<parameters>)`)

**Comment by dantleech** [comment]
> Another question is command like PhpactorGotoDefinition working well ,

`:PhpactorGotoDefinition` will simply invoke the `phpactor` command and get an answer - this is the "old/legacy" way the Phpactor works - and it does not invovle a long running process

If you are using the LanguageServer then you will have a long running `phpactor` process.

**Comment by dantleech** [comment]
Closing now as I think it's answered :)

**Comment by dagang007** [comment]
Thanks a lot
