### ISSUE TITLE
Multiline property docs not recognised

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#2126]
This is not recognised (notice the yellow underscore, saying `Method "__construct" is missing @param $mediaOptions`):
<img width="248" alt="image" src="https://user-images.githubusercontent.com/12109622/222750891-694c3acc-28e5-4e57-9839-1b8e6373c30a.png">
But this is:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/12109622/222750969-9458126e-687e-4702-934d-310b8aa9554b.png">

**Comment by BladeMF** [comment]
Enclosing in braces solves this:

```php
	/**
	 * @return (Generator<string,array{
	 * 		Exception,
	 * 		(callable(QueueEntry):string),
	 * 		(callable(ObjectProphecy<Queue>,QueueEntry):void)
	 * 	}>) */
	public function _providePublishExceptions(): Generator
	{
	}
```

**Comment by mamazu** [comment]
From a first look it doesn't seem to be a parsing error it does parse it correctly as a `@param` tag with an array shape type. Any idea where else it could be? Does it affect following `@param` definitions?

**Comment by BladeMF** [comment]
It does not seem to affect other `@param`s after that. Enclosing it does not seem to solve it either:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/12109622/229200222-f1fe435f-5926-4105-a358-3de409f95796.png">
It does not give a parse error.

**Comment by BladeMF** [comment]
There is another hint. I think it is in the `[]` form. This works:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/12109622/229200942-c278b340-5e45-46a8-bddc-8d8950ba729b.png">

**Comment by mamazu** [comment]
Refs #2172

**Comment by dantleech** [comment]
Was this fixed?

**Comment by mamazu** [comment]
Nope I only fixed the handling of the `[]`

**Comment by mamazu** [comment]
After some more testing. It is fixed, I just got confused by the test syntax.

**Comment by mamazu** [comment]
@dantleech You want to close this?
