### ISSUE TITLE
Inline block parser could recognize var parameter in form @var Type $name

### ISSUE THREAD

**Issue by stepiiik** [phpactor/phpactor#213]
Hi,

at first - thanks for this library. Its really useful for my workflow <3

I use var in docblock in form like @var Type $name. Im not sure but i thought that this is kind of standard (http://docs.phpdoc.org/references/phpdoc/tags/var.html)

```php
/** @var Type $test */
$test = getSomething(); // this is not recognized

/** @var $test2 Type */
$test = getSomething(); // this works
```

Could it be possible to work in both ways?

Thanks

**Comment by dantleech** [comment]
Hi, yeah I have encountered and have issues with the same, will see about changing to support both (or maybe just the standard).

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/worse-reflection/commit/6ea8848670bdb2bd3cbd6f11339eaa4f51e8aca9 !

**Comment by greg0ire** [comment]
Is this support to work for properties too?

This works:
```php
<?php
/**
 * @param MyClass
 */
 private $myProperty;
```
and this doesn't:

```php
<?php
/**
 * @var MyClass
 */
 private $myProperty;
```

**Comment by dantleech** [comment]
Hmm, `@param` works? I didn't think it should.  `@var` certainly works for me on properties.

**Comment by greg0ire** [comment]
Sorry, I must have been confused, it works as expected now. Not sure what happened. Maybe I didn't save and it has an influence.

**Comment by dantleech** [comment]
Yeah - that is an issue - we currently read from the file, we should be passing the current source.

**Comment by Taluu** [comment]
Hum, AFAIC, `/** @var Type */` works on the properties but not on variables ;

```php
<?php

class Foo
{
    /** @var Bar */
    private $bar;

    /** @param $noTypeHint Baz */
    public function baz($noTypeHint)
    {
        /** @var Baz */
        $var = $noTypeHint;

        /** @var $var2 Baz */
        $var2 = $noTypeHint;
    }
}
```

So here, `$this->bar` works as expected, but not `$noTypeHint`, `$var` or `$var2`. Can't typehint because inheritance, so I can't typehint the parameters of `Foo::baz()`.
