### ISSUE TITLE
Non-outsourced diagnostics providers will not run unless "language_server.diagnostic_outsource" is true.

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#2131]
Just in case I misread the code, my problem is this: when `language_server.diagnostic_outsource` is `false`, the phpstan diagnostics provider never runs. Is this expected?

**Comment by dantleech** [comment]
no, phpstan is not outsourced, onoly worse reflection diagnostics (i.e. run phpactor's "phpstan" in a separate process)

**Comment by BladeMF** [comment]
Well, php linting does not run as well if that setting is off. I turned it on for now. Anything I should be aware of?

**Comment by dantleech** [comment]
My lazy and bad coding, fixed in #2135
