### ISSUE TITLE
Completion: Try and be a bit more clever with visibility.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#214]
Currently all members are listed for completion, regardless of their visiblity.

- If not in a class. All members must be public.
- If in a class:
    - All members not of that class must be public.
    - All methods of the actual class are visible.
    - Protected and public methods of parent classes are visible.

**Comment by phux** [comment]
> Protected and public methods of parent classes are visible.
This is already implemented, right?
I've tested it with `lib/Console/Command/ClassInflectCommand.php`:
- I see the parent's public & protected methods like `ignoreValidationErrors()` and `interact()`
- I don't see the parent's private methods like `validateName`

**Comment by dantleech** [comment]
No, I clearly see the private methods. The auto complete  logic is [very simple](https://github.com/phpactor/phpactor/blob/master/lib/Application/Complete.php#L52). The idea is to break it out into a separate component to be more aware of context and provide completions for new classes, use statements, functions etc.

**Comment by phux** [comment]
Weird! Here is what I get (latest master):

![2017-11-13-092311_956x1055_scrot](https://user-images.githubusercontent.com/852372/32715986-913b2dfa-c854-11e7-9aaa-900df5fe9f4e.png)

As you can see, only the private properties and methods of the ClassInflectCommand are shown, nothing private from its parent.

**Comment by dantleech** [comment]
Indeed, very strange. Are you using the `neo-complete` plugin (for neovim) or the omni-complete? Maybe you have some other plugin which is somehow filtering? (I would say maybe another plugin is doing the completion by the abbreviations look like Phpactor).

I have:

![untitled](https://user-images.githubusercontent.com/530801/32726851-bb623cec-c87a-11e7-8962-8622ffed97db.png)

In anycase, Phpactor certainly isn't doing it... yet :)

**Comment by phux** [comment]
I am using omnicomplete via `<c-x><c-o>` with `:set omnifunc=phpactor#Complete`.

**Comment by phux** [comment]
Indeed phpactor does it, or better the `worse-reflection` package.

`worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php` Line 147

**Comment by dantleech** [comment]
Completetion is not a "bit more" clever. closing. :)
