### ISSUE TITLE
Refactor: Extract into local variable

### ISSUE THREAD

**Issue by leo-unglaub** [phpactor/phpactor#2165]
Hey,
first of all, i love your project. Works so well on my projects codebase. Thanks so much for making it open source. :heart: 

A refactoring task that comes up quite often (at least in my use cases) is that i have a value that i want to move to a local variable. Right now i can only refactor it an move the values to a class constant. But in my experience most often you want it to be a local variable.

Here is an example, this is what i want to refactor:
```php
class Example
{
	public function __construct()
	{
		$this->doSomething("This is an example");
	}

	public function doSomething(string $param1): void
	{
	}
}
```

Currently i would get the following:
```php
lass Example
{
    const NEW_CONSTANT = 'This is an example';

	public function __construct()
	{
		$this->doSomething(self::NEW_CONSTANT);
	}

	public function doSomething(string $param1): void
	{
	}
}
```

Would it be possible/a good idea to add another refactoring method called "extract local" that would generate the following?

```php
class Example
{
	public function __construct()
	{
		$var1 = "This is an example";
		$this->doSomething($var1);
	}

	public function doSomething(string $param1): void
	{
	}
}
```

Thanks so much and greeting :)

**Comment by mamazu** [comment]
Hey maybe you are looking for this functionality called: [Extract expression](https://phpactor.readthedocs.io/en/master/reference/refactorings.html#extract-expression)

**Comment by dantleech** [comment]
... yes, only extract expression does not work with LSP (only legacy VIM currently)

**Comment by BladeMF** [comment]
> ... yes, only extract expression does not work with LSP (only legacy VIM currently)

Yes it does?

**Comment by dantleech** [comment]
Good job!
