### ISSUE TITLE
(possible) regression(?): new file not indexed. 

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2190]
After creating a new class in a new file, the class is not indexed and cannot be auto-completed from the context of the f..e test.

**Comment by mamazu** [comment]
It has been like that since I use phpactor. I should have created an issue for that earlier.

**Comment by dantleech** [comment]
this is a regression in my local branch. creating a new class in `master` works as expected for me....

**Comment by dantleech** [comment]
confirmed just on local branch... feel free to raise a specific issue
