### ISSUE TITLE
Project: allow to store test cases describing known bugs

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#2198]
For example, consider #2195. It contains a data set provided for `IndexedReferenceFinderTest::testFinder` with expected value for which the test fails before resolving #2195. 

We could store such tests in the project and treat them in a special way. I don't know any widely known good practice to do it (or if the whole proposition is a known anti-pattern). 

1. probably we would need to use some test group, e.g. `bugs` to exclude it from the default CI job,
2. probably we should run such test group separately to control the current number of failed cases (and don't forget to change  some test that stopped failing),
3. a strange alternative to `2.`: assertions are negations of expected values: after fixing some bug such its corresponding test starts failing with some appropriate message, e.g. ```assertNotTrue($expectedTrueValue, 'Check if #2195 was fixed and possibly convert this test.')```.

What do you think about storing such cases (@dantleech especially)?

**Comment by mamazu** [comment]
I totally agree that tracking what fails and what doesn't in terms of bugs can really be helpful. Technically it would be possible to add another PhpUnit test suite with only bug tests like you described in number 3.

**Comment by mamazu** [comment]
I think the only thing this protects against is accidentally fixed test and their regression. But I don't think that this is that important, if you want to tackle an issue just copy over the test in the ticket I guess.

**Comment by dantleech** [comment]
Closing as I think we can do this more effectively with PRs

**Comment by przepompownia** [comment]
@dantleech @mamazu thanks for submitting your opinion!

**Comment by dantleech** [comment]
and feel free to discuss further if required, just trying to combat the issue queue 😄
