### ISSUE TITLE
Global function definition not aknlowledged in file until restart

### ISSUE THREAD

**Issue by len0xx** [phpactor/phpactor#2203]
I use neovim and recently configured phpactor to handle LSP for my neovim client. But during the tests I found an interesting problem. Variables and autocompletion seems to work fine, but there's a problem with functions:

When I create a function in a file and try to use it, LSP says the `function is not found`. But after restarting neovim the problem goes away.
Is there a way to fix this problem?

![image](https://user-images.githubusercontent.com/21990466/232114407-bbc4f7a6-4625-48da-87c7-d0b6dac7c563.png)

![image](https://user-images.githubusercontent.com/21990466/232114576-2552d2fa-42d0-492b-97db-6d48d8d6f3da.png)

My neovim config:
```lua
lspconfig.phpactor.setup {
    capabilities = capabilities,
    on_attach = on_attach,
    root_dir = lspconfig.util.root_pattern("composer.json", ".git", "index.php"),
    init_options = {
        ["language_server_phpstan.enabled"] = false,
        ["language_server_psalm.enabled"] = false
    }
}
```

System configuration:
macOS 13.2.1 aarch64

**Comment by dantleech** [comment]
looks like this is the case when the function has _no namespace_. if you add a namespace it that file it should work.

**Comment by len0xx** [comment]
But It should not work this way in regular php, right? 😅
Isn't there a way to globally solve the problem?

**Comment by dantleech** [comment]
Yes, I do acknowledge that it's a bug 😅

**Comment by dantleech** [comment]
as of #2331 the function should be found after _saving_ the file, hopefully that's a good enough improvement :)

**Comment by abdullahilbaki** [comment]
same problem with me 
![image](https://github.com/phpactor/phpactor/assets/86188702/c73b7740-15a9-425d-a748-ace5d17a0e0d)
