### ISSUE TITLE
Error with specific return types and extended class

### ISSUE THREAD

**Issue by KJ2ME** [phpactor/phpactor#2207]
For more fast explanation an image first:

![image](https://user-images.githubusercontent.com/8014685/232164767-b6ac50e3-4271-4005-8485-b25868173618.png)

The error is "undefined method someBfunction", but is defined and the code works.

The same error but without "new static":

![image](https://user-images.githubusercontent.com/8014685/232165166-bb202db4-c716-49af-98d8-04d30653f526.png)

It works fine on PHP, but phpactor shows as an error.

I know that I can use "static" as return type, but on the other way cannot be reported as error, because is not.

**Comment by dantleech** [comment]
I think this works as expected.

You return `A` - the type system has no way to know that it's the subclass `B`

instead you can `function doSomethingThatReturnsNonStatic(): static` (!) and it will return B and it works:

```
<?php

class A {
    public static function someAFunction(): void {
    }
    public static function doSomethingThatReturnsNonStatic(): static {
    }
}

class B extends A {
    public static function someBFunction(): string
    {
    }
}

$a = B::doSomethingThatReturnsNonStatic();
wrAssertType('string', $a->someBFunction());
``` 

please reopen if this is not the case!

**Comment by dantleech** [comment]
you can additionally do `/** @return static */` btw
