### ISSUE TITLE
Possible bug with same name properties / methods

### ISSUE THREAD

**Issue by haringsrob** [phpactor/phpactor#2214]
Given the following code:
```php
<?php

class test {
    public string $foo;

    public function foo(): string {
        return $this->foo;
    }
}

$b = new test();

$b->|CURSOR|
```

When at cursor it only provides the method foo as autocomplete option.

I found this because I have virtual methods that are the same as methods yet have a different return type.

<img width="266" alt="Screenshot 2023-04-17 at 13 33 07" src="https://user-images.githubusercontent.com/866743/232472343-5c379cb5-8bd5-4ce7-9c54-5aed611e592e.png">

**Comment by dantleech** [comment]
yes it's true :+1:
