### ISSUE TITLE
do not show if variable is not defined

### ISSUE THREAD

**Issue by matroskin20906** [phpactor/phpactor#2216]
If in code is use variable, that is not defined phpactor language server in neovim do not show warning about undefined variable usage

**Comment by dantleech** [comment]
can you provide a code example or a screenshot?

**Comment by matroskin20906** [comment]
`lsp.configure('phpactor', {
    init_options = {
        ["language_server.diagnostics_on_update"] = false,
        ["php.version"] = 8,
    }
})` this is my phpactor config and this is code example 
![Screenshot_20230418_111034](https://user-images.githubusercontent.com/30923572/232714219-1ddf3ba9-576b-4eb3-a4f6-6691b7be3f0b.png)

variable $asdfcjkl do not exists

**Comment by dantleech** [comment]
to be clear what is the problem?

1. Phpactor SHOULD show a diagnostic error but it doesn't
2. Phpactor SHOULD NOT show a diagnostic error (because it's valid PHP code) but it does
3. Phpactor is working as expected but you'd like to disable this feature

?

**Comment by mamazu** [comment]
@matroskin20906 Can you localize the problem or give more context? Is it because of the array? I added a test for that assigning to an array and the test properly reports the variable as missing.

**Comment by dantleech** [comment]
![image](https://user-images.githubusercontent.com/530801/233212532-5e39ebd4-c114-4760-9a7a-143935eeb38f.png)

are you using the latest version?

**Comment by matroskin20906** [comment]
I am using Neovim v0.8.3 and phpactor 2023-04-10
this problem exists with array and with another variable. Some phpactor features work, on screenshot info about not having ';' 
![Screenshot_20230420_132753](https://user-images.githubusercontent.com/30923572/233339470-9d58a368-2602-4e32-8fe1-cc7e88f06468.png)

**Comment by matroskin20906** [comment]
`local lspconfig = require("lspconfig")

lspconfig.phpactor.setup{
    on_attach = on_attach,
    init_options = {
        ["language_server_phpstan.enabled"] = false,
        ["language_server_psalm.enabled"] = false,
    }
}`
here is my config

**Comment by matroskin20906** [comment]
As I can see, last release was 2023-04-10. If this functionality will be in next release, great, thanks for help, this issue can be closed

**Comment by dantleech** [comment]
ok, closing for now, feel free to update to `master` to verify
