### ISSUE TITLE
[RFC] Updating phpactor templates

### ISSUE THREAD

**Issue by mamazu** [phpactor/phpactor#2217]
~~Currently the templates generate code that is very type lenient. When adding a property it generates code with the type hint still being an annotation not a proper type hint.~~

Same could be said for adding `declare(strict_types=1)` to the file. Do we want that or should should that be a user thing? I think for new code we should have the best standards applied and if the user wants to (or has to) write legacy code they need to change the templates to accommodate them.

**Comment by dantleech** [comment]
Do you have an example? Generated code should not add superfluous annotations

**Comment by mamazu** [comment]
Looks like I was using an outdated version of phpactor appearently. What do you think about the `strict_types`

**Comment by dantleech** [comment]
The extent to which types are used for annotations is determined by the PHP version you declare in `composer.json`.

Currently you can edt templates and set `strict_types` to true either globally or per-project although this is an underdocumented feature: https://phpactor.readthedocs.io/en/master/reference/templates.html

**Comment by mamazu** [comment]
Sorry, follow up question: I want to override the template under `/templates/code/SourceCode.php.twig`. Can I just place the file with the correct content here and be done with it?

`/home/mamazu/.config/phpactor/templates/code/SourceCode.php.twig`

**Comment by dantleech** [comment]
i think so

**Comment by dantleech** [comment]
```
/home/daniel/.config/phpactor/templates/SourceCode.php.twig
```

**Comment by mamazu** [comment]
Works like a charm, thanks.
