### ISSUE TITLE
Enum methods not resolving + Enum $this not working

### ISSUE THREAD

**Issue by haringsrob** [phpactor/phpactor#2218]
It seems that there are some issues with enumeration classes.

![Screenshot 2023-04-19 at 10 12 13](https://user-images.githubusercontent.com/866743/233163459-84a4fd1e-258d-48d0-b3f2-b9ac2b4a9e0d.png)
![Screenshot 2023-04-19 at 10 12 26](https://user-images.githubusercontent.com/866743/233163463-22003643-d3d9-40bb-930b-18c66b04461f.png)

**Comment by dantleech** [comment]
should be fixed in #2219
