### ISSUE TITLE
Array Destructuring doesn't register as a variable definition

### ISSUE THREAD

**Issue by mamazu** [phpactor/phpactor#2223]
## Steps to reproduce

Create a test case containing:
```php
<?php

[$a, $b] = [1, 2];

echo $a;
echo $b;
```

This should not throw any diagnostics. Here are two problems:

1. The diagnostic provider should throw an error on the array destructuring expression (easy, early return in the diagnostic)
2. The variables should be defined after the array destructuring and be part of the frame (I don't know where this logic should be)

If you can point me in the right direction for number 2. I can implement a fix for that.

**Comment by dantleech** [comment]
> The diagnostic provider should throw an error on the array destructuring expression (easy, early return in the diagnostic)

what's the error?

**Comment by dantleech** [comment]
for 2) it should probably be handled here: https://github.com/phpactor/phpactor/blob/60647e7ca973bb9451c07a80a50a0d2e5e2c0c84/lib/WorseReflection/Core/Inference/Resolver/AssignmentExpressionResolver.php#L55-L58

**Comment by dantleech** [comment]
Fixed both cases in 2226

**Comment by mamazu** [comment]
Found another one:

```php
$test = [
    [1, false],
    [2, true],
];
foreach($test as [$number, $even]) {
    echo $number . ': '. $even.PHP_EOL;
}
```

Says that `$number` and `$even` are undefined.
