### ISSUE TITLE
Failing when using spaces and special characters in folders

### ISSUE THREAD

**Issue by jota0222** [phpactor/phpactor#2228]
It seems that if I have a project in a path which has an especial character or spaces in it, the path sent to the indexer have URL encoded characters which it cannot handle. 

It happens using either STDIO or LSP options.

![imagen](https://user-images.githubusercontent.com/12126375/233753132-0f48fd03-0d9c-4cca-a6e8-e4315cc21aa5.png)

![imagen](https://user-images.githubusercontent.com/12126375/233756368-ac0df8e3-e543-4d4d-978a-80a76ffa33ad.png)

**Comment by dantleech** [comment]
Will be fxied in #2229
