### ISSUE TITLE
If > 1 definition exists offer choice of definitions to jump to

### ISSUE THREAD

**Issue by mamazu** [phpactor/phpactor#2233]
I don't know if that is a local problem but in every project I opened phpactor never found the "real" Phpunit and always referred to stubs.

## Steps to reproduce
* Checkout the phpactor repository
* Open a test (it should already show that the assertion methods like `assertCount` `assertSame` etc could not be found)
* Go to definition of the Phpunit `Testcase` class the test is extending 

Then you should be redirected to `lib/CodeTransform/Tests/Workspace/TestCase.php` which is just a stub in this project and not the real test case.

This isn't a phpactor problem, but I think this is a problem in general. If your project has polyfills like older version of phpunit had the Testcase in a different namespace so some packages alias the new version to a stub.

## Other considerations
What I could do on a per project basis is exclude the files that I know are stubs in the index pattern. But I don't know if that is a good idea.

**Comment by dantleech** [comment]
I think this should only happen in the Phpactor project since we introduced the possiblity that the "TestCase" artifact is left in the file tree?

More generally we should probably allow navigating to any of the matching classes.

**Comment by dantleech** [comment]
Will probably need to support indexing a list of paths for any given class FQN in the index, which probably isn't a big deal.

**Comment by mamazu** [comment]
As far as I can see the definition finder already returns a list of definitions it's just that we only ever take the first one. But improvement is already on the way.

**Comment by dantleech** [comment]
yes, but the indexer only supports a single path for any given FQN

**Comment by mamazu** [comment]
Refs #2243

**Comment by dantleech** [comment]
As mentioned in the other PR, PHPStorm does not support this feature and it makes no sense to analyse > 1 file for the same class definition, in this specific case the problem can be resolved by ignoring the Workspace folder in `.phpactor.json`:

```
    "indexer.exclude_patterns": [
        "/vendor/**/Tests/**/*",
        "/vendor/**/tests/**/*",
        "/**/Workspace/**/*",
        "/var/cache/**/*",
        "/vendor/composer/**/*"
    ],
```
