### ISSUE TITLE
Issue moving class from VIM

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#225]
`Error from Phpactor: Could not move file "/home/daniel/www/<>/tests/Acceptance/Context/Yves/CustomerContext.php" to "/home/daniel/www/<>/tests/Acceptance/Con
text/Yves/CustomerRegistrationContext.php"`

This happens in a large client project on a versioned file.

**Comment by dantleech** [comment]
We should provide a mechanism for automatically logging all the details of exceptions like this (or provide the command which can reproduce it on the CLI).

**Comment by cmizzi** [comment]
Any news on that ? It would be great to make this functionality working, I need it :P

**Comment by dantleech** [comment]
Current news is that the failure is usually GIT related (untracked files f.e.). It is easier to use this functionality from the CLI:

```
$ phpactor class:move lib/to/MClass.php
```

In which case you get better clue as to what's going on.

Fix should be quite easy, it's just finding the time.

**Comment by dantleech** [comment]
@cmizzi in my case this was caused by a file permission error, fixed in https://github.com/phpactor/phpactor/commit/d9f63d879307ff3a436785ce87feb379590e9134.

I don't know if this is the same issue as you are having.

You can now check by enabling logging in `.phpactor.yml`:

```
logging.enabled: true
```

By default it will write a file called `phpactor.log` in the current working directory.

It will log all errors and warnings - can you enable this and tell me what the problem is?

**Comment by dantleech** [comment]
Closing now, as the above commit fixed the issue for me.

**Comment by cmizzi** [comment]
That's right. It was a permission issue too :/
