### ISSUE TITLE
Trait method not recognized when applied to an Enum

### ISSUE THREAD

**Issue by CalebDW** [phpactor/phpactor#2256]
Hello!

It seems that when a trait with a method is applied to an Enum, the method is not recognized as existing:

![image](https://user-images.githubusercontent.com/4176520/236446802-fec20aa8-0eeb-4d7c-a24c-c821188c6fa7.png)

Any thoughts?

Thanks!

**Comment by CalebDW** [comment]
In addition, it seems that the code actions want to remove the traits altogether:

Prompt:

![image](https://user-images.githubusercontent.com/4176520/236447328-c910be99-4078-42b0-8a97-ead64c62c937.png)


After applying action:

![image](https://user-images.githubusercontent.com/4176520/236447401-8eb9899a-612b-4813-a355-a8a325579daa.png)

**Comment by dantleech** [comment]
I guess we don't consider traits on Enums at all, so this is a bug/missing feature :+1:

**Comment by mamazu** [comment]
Where would the best way to start with this be?

**Comment by CalebDW** [comment]
Also looks like the native enum methods aren't recognized either (`::cases`, `::tryFrom`, `::from`).

**Comment by mamazu** [comment]
@CalebDW Can you check if it is fixed with the most recent version of phpactor?

**Comment by CalebDW** [comment]
@mamazu, the native PHP methods work (`::cases()`, `::from()`) but static and instance methods are still not being recognized.

**Comment by mamazu** [comment]
Are you talking about static and instance methods via traits?

**Comment by mamazu** [comment]
Thanks for the feedback. I will have to dig deeper then.
