### ISSUE TITLE
Option to show full class name in completion items

### ISSUE THREAD

**Issue by haringsrob** [phpactor/phpactor#2260]
Currently when completing it shows only some parts.

It would (for me) be useful to show the full class.

<img width="241" alt="Screenshot 2023-05-07 at 09 41 47" src="https://user-images.githubusercontent.com/866743/236664563-2d7f265d-7a85-4503-b6e3-455426dd4ad7.png">

**Comment by dantleech** [comment]
you could perhaps add an option to swap out the `LabelFormatter` implementation here: https://github.com/phpactor/phpactor/blob/50e5bda61fabd15d070a587212503c427f0cb2f4/lib/Extension/Completion/CompletionExtension.php#L101-L103

**Comment by dantleech** [comment]
note also that the item detail does currnetly show the FQN:

![image](https://github.com/phpactor/phpactor/assets/530801/4efb2328-d6db-41d9-8fd3-5f06e4ce0687)

**Comment by mamazu** [comment]
There already is a `PassthruLabelFormatter`. Currently as far as I can see it's used nowhere but I am going to make a PR to make it configurable.
