### ISSUE TITLE
TODO finder.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#228]
Command to find TODOs

**Comment by dantleech** [comment]
Not really sure how this would be much better than `Ggrep` / `git grep`

**Comment by greg0ire** [comment]
@dantleech whatever `grepprg` is set to?

**Comment by dantleech** [comment]
@greg0ire I think I was thinking of a command to list TODOs, e.g.

```
+----------------+-----+-----------------------------+
| File           | Ln  | Todo                        |
+----------------+-----+-----------------------------+
| /path/to.php   | 10  | This should be refactored   |
| /path/to.php   | 36  | This too                    |
+----------------+-----+-----------------------------+
```

Which could present a good summary of work-to-be-done, but in VIM the implementation would be pretty much the same as using fugitive `:Ggrep "TODO"`

**Comment by greg0ire** [comment]
Yeah so you would like more something build on top of `:Ggrep` or `:grep` (a custom VIM command?) than an external command you would call from vim. Should probably not be part of phpactor (or just the vim plugin part, maybe)

**Comment by dantleech** [comment]
Well, I think the only feature here would be having the CLI provide a well-formatted summary, Phpactor _could_ also only parse comments to avoid false positives, but those would be pretty rare and it would be slow.

**Comment by dantleech** [comment]
Bah, closing this.
