### ISSUE TITLE
Auto-completion not working for Enum instances

### ISSUE THREAD

**Issue by CalebDW** [phpactor/phpactor#2284]
Hello! Thanks for all the work getting traits to work in Enums!

However, I noticed that auto-completion for Enum properties and methods does not work outside of the Enum (and the auto-completion that does occur inside the Enum is incorrect). Note that Enums are stateless and therefore are unable to have properties, but all Enums have a `name` property and BackedEnums have a `value` property.

Inside the Enum, auto-completion sort of works:
![image](https://github.com/phpactor/phpactor/assets/4176520/34074754-9237-449b-832e-cbd65fb24d51)
but it's not showing properties and it is showing static methods (`cases`, `from`, etc.) which don't make sense on an Enum instance.

Outside the Enum, there's no auto-completion suggestions from the LS.
![image](https://github.com/phpactor/phpactor/assets/4176520/7275c724-b223-46eb-aade-ca10df0b6c52)

```php
<?php

namespace Phpactor\Enums;

enum ScheduleType: int
{
    case ProductionDay = 1;
    case Break         = 2;
    case Unscheduled   = 3;

    public function label(): string
    {
        return match ($this) {
            self::ProductionDay => 'Production Day',
            default => $this->name,
        };
    }
}

class Test
{
    public function testing(): void
    {
        $a = ScheduleType::ProductionDay;
    }
}
```

Thanks!

**Comment by mamazu** [comment]
I agree with the fact that enums are a little wonky in php. Technically you are right you shouldn't be able to configure non-static methods on an enum. But looks like you can in PHP so phpactor supports it. One thing to note here is that if you start the expression outside of the enum with
```php
ScheduleType::
```
Then this will only suggest static methods and
```php
ScheduleType->
```
will also include the non-static methods. This is thanks to php's "You can call static methods non-statically rule". I don't like it but phpactor implements it correctly.

eg. 
![image](https://github.com/phpactor/phpactor/assets/14860264/e1de4331-9d6d-4129-8d7a-4362c1975f42)
and
![image](https://github.com/phpactor/phpactor/assets/14860264/0c0d800c-ebc8-4caa-af23-513d79f8db6a)
> `hallo` is missing because it's not static

And your second example `$a = ScheduleType::ProductionDay->` returns nothing because `ScheduleType::ProductionDay` is an int.

If I missunderstood your point feel free to correct me.

**Comment by CalebDW** [comment]
>  This is thanks to php's "You can call static methods non-statically"-rule.

Ah interesting, that explains it---I wasn't too concerned about that part but just thought I'd mention it.

> And your second example $a = ScheduleType::ProductionDay-> returns nothing because ScheduleType::ProductionDay is an int.

This is incorrect, `ScheduleType::ProductionDay->value` is an int, but `ScheduleType::ProductionDay` is a [singleton class instance](https://www.php.net/manual/en/language.enumerations.overview.php):
> In PHP, Enums are a special kind of object. The Enum itself is a class, and its possible cases are all single-instance objects of that class. That means Enum cases are valid objects and may be used anywhere an object may be used, including type checks.

You can find example of using methods on enum cases in the [docs](https://www.php.net/manual/en/language.enumerations.methods.php)

**Comment by mamazu** [comment]
Okay, that doesn't make sense that the enum values are objects again. (But that's just php.)

Do you happen to know what type of object they are? They seem to have at least a `label()` and a `value()` function.

**Comment by CalebDW** [comment]
It's all in the docs...

> Enums appear in many languages with a variety of different features. In PHP, Enums are a special kind of object. The Enum itself is a class, and its possible cases are all single-instance objects of that class. That means Enum cases are valid objects and may be used anywhere an object may be used, including type checks.

They're singleton instances of the Enum class. The docs also list some [differences with objects](https://www.php.net/manual/en/language.enumerations.object-differences.php):

    - Constructors and Destructors are forbidden.
    - Inheritance is not supported. Enums may not extend or be extended.
    - Static or object properties are not allowed.
    - Cloning an Enum case is not supported, as cases must be singleton instances.
    - Magic methods, except for those listed below, are disallowed.
    - Enums must always be declared before they are used.

Note that while Enums cannot have state (i.e., properties), they do have a `name` property and BackedEnums have a `value` property.

> They seem to have at least a label() and a value() function.

The `label()` method is something I added to the Enum for when human readable labels are necessary (like for front-end select options), they don't have a `value()` function

**Comment by dantleech** [comment]
We have a "todo" test for this:

https://github.com/phpactor/phpactor/blob/b64c10e2f9772e94938e7ec05bc9ad58a4d2db7e/lib/WorseReflection/Tests/Inference/enum/backed_enum_case.test#L7-L8

i'll check to see if this can now be implemented

**Comment by dantleech** [comment]
should be working now

**Comment by CalebDW** [comment]
Thanks!! Auto-complete is working for cases!


However, (I hate to keep bugging lol) I noticed that I am not able to go to the definition of methods called on Enum cases---to reuse the earlier example:

```php
<?php

namespace Phpactor\Enums;

enum ScheduleType: int
{
    case ProductionDay = 1;
    case Break         = 2;
    case Unscheduled   = 3;

    public function label(): string
    {
        return match ($this) {
            self::ProductionDay => 'Production Day',
            default => $this->name,
        };
    }
}

class Test
{
    public function testing(): void
    {
        $a = ScheduleType::ProductionDay->label(); // unable to goto `label` definition here
    }
}
```
