### ISSUE TITLE
Feature: Move whole directories

### ISSUE THREAD

**Issue by CalebDW** [phpactor/phpactor#2287]
Hello!

I recently had to move a whole directory, and I didn't want to move a ton of individual classes. I was able to loop over them with the below one-liner (probably could be shorter):
```bash
find <path> -type f | while read path; do export newPath="$(echo $path | sed 's/<find>/<replace>/')"; phpactor class:move $path $newPath; done
```

but it would be nice if phpactor could do the same thing with two arguments.

Thanks!

**Comment by dantleech** [comment]
You can do this on the CLI: `phpactor class:move path1 path2`

**Comment by CalebDW** [comment]
Ah! I was trying to use `phpactor class:move <path-to-dir>/* <path-to-new-dir>/
