### ISSUE TITLE
Generic tag reported to be incompatible when correct for child generic classes

### ISSUE THREAD

**Issue by CalebDW** [phpactor/phpactor#2295]
Hello!

I'm experiencing a problem similar to #2262, but this time when making child classes generic:

Code Example: 

```php
<?php

namespace Phpactor;

abstract class Model
{
}

/** @template TModel of \Phpactor\Model */
class Factory
{
}

/**
 * @template TModel of \Phpactor\Schedule
 * @extends Factory<TModel>
 */
class ScheduleFactory extends Factory
{
}

class Schedule extends Model
{
}

/** @extends ScheduleFactory<ChildSchedule> */
class ChildScheduleFactory extends ScheduleFactory
{
}

class ChildSchedule extends Schedule
{
}
```

From [PHPStan](https://phpstan.org/blog/generics-in-php-using-phpdocs):
![image](https://github.com/phpactor/phpactor/assets/4176520/36de3faf-171a-4b05-ae82-3cb9fa57eb6f)

Thanks!

**Comment by calebdw** [comment]
@dantleech, this was fixed but started reporting again...was there a regression?

![image](https://github.com/phpactor/phpactor/assets/4176520/6c460ae6-c988-4e00-9789-d405877ab5b7)

**Comment by dantleech** [comment]
the tests would indicate that it's fine: https://github.com/phpactor/phpactor/blob/6f23af24bfd45a07861c705b8e551cae8b6fc328/lib/WorseReflection/Bridge/TolerantParser/Diagnostics/DocblockMissingExtendsTagProvider.php#L309-L331

maybe something else changed on your side?
