### ISSUE TITLE
Globals and Super-globals incorrectly get reported as undefined

### ISSUE THREAD

**Issue by vendion** [phpactor/phpactor#2302]
In code that depends on user defined globals as well as PHP's built in super-globals `phpactor` is now incorrectly reporting them as undefined.

![image](https://github.com/phpactor/phpactor/assets/145018/2f47f1bb-1a90-42d4-8789-7b350a60de31)

This is happening with the newly released 2023.06.17, but in older versions it worked fine.

**Comment by dantleech** [comment]
Should be fixed, tagged a new release: https://github.com/phpactor/phpactor/releases/tag/2023.06.17-1

**Comment by vendion** [comment]
@dantleech Thanks for the prompt fix!
