### ISSUE TITLE
IndexCleanCommand uses symfony/finder when is not declared as dependency

### ISSUE THREAD

**Issue by rodrigoaguilera** [phpactor/phpactor#2304]
I discovered there is a command to clean the index cache but trying to use gave m the error
```
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Finder\Finder" not found
```
I required the package in my root composer.json but I think it is an undeclared dependency of phpactor.

**Comment by dantleech** [comment]
Indeed, we should either use something else or add that dep in `composer.json`

**Comment by dantleech** [comment]
Have removed the dep in #2306 but will wait a few days before tagging a new release just incase any new issues arrive.

In the mean time `rm -Rf ~/.cache/phpactor/index` :sweat_smile:

**Comment by dantleech** [comment]
Fixed and tagged a new release :+1:
