### ISSUE TITLE
Add PHP-CS-Fixer configuration discovery

### ISSUE THREAD

**Issue by Abdillah** [phpactor/phpactor#2315]
PHP-CS-Fixer ideally should activated on files mentioned in the configuration. This is mainly, PHP-CS-Fixer only works for modern PHP file (no HTML and PHP mix). Therefor, config discovery and usage is important to avoid auto formatting file not intended to.

Reference: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7124#issuecomment-1623228475

## Proposal
There are two part of implementation: toggle auto-discovery of config file option (also its name) and use the discovered config path in the command line call.

**Comment by dantleech** [comment]
hi, what is auto-formatting the code? which editor are you using?

**Comment by Abdillah** [comment]
I use Helix editor. I can disable the auto-formatting, but it will be very handy if phpactor can do automatically.

**Comment by dantleech** [comment]
probably this should be done in the PHP-CS-FIxer config?

https://cs.symfony.com/doc/config.html

then it will address the problem both in Phpactor and when you run `php-cs-fixer fix`

**Comment by Abdillah** [comment]
Unfortunately, the PHP-CS-Fixer is a bit tricky.
When using the program **with filename or path** specified, it doesn't want to read the config. That's an [expected situation](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/2465#issuecomment-272646633) from the dev.

**Comment by dantleech** [comment]
can you confirm that passing `--config=.php-cs-fixer.php` (or whatever) fixes the issue for you?

in which case we can consider adding a `'language_server_php_cs_fixer.config` option to force the reading of a config file

**Comment by Abdillah** [comment]
Sure, I'll try to capture it on screen till tomorrow, god willing.

**Comment by Abdillah** [comment]
Hello, I'm sorry for the lateness.

I've tried to reproduce the the command of `--config=.php-cs-fixer.php` and it seems my assumption is not correct.

![image](https://github.com/phpactor/phpactor/assets/3030950/1b6800be-99ed-4e6c-b2f0-f94be6eac3c3)

Fortunately, there actually an option to set "path-mode" from "override" (default) to "intersection" (with the config).

![image](https://github.com/phpactor/phpactor/assets/3030950/c8947136-d469-49de-80cc-19bb17934f8c)

Is it possible to add extra flag or parameter option instead? It will be put along with the bin option on execution.

---

`$ cat .php-cs-fixer.dist.php`
```
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('public/')
    ->exclude('vendor/')
    ->in([
        'lib/',
        'src/',
    ])
;

$config = new PhpCsFixer\Config();
return $config->setRules([
        '@PSR12' => true,
        // 'array_syntax' => [ 'syntax' => 'short' ],
    ])
    ->setIndent("    ")
    ->setFinder($finder)
```

**Comment by afranioce** [comment]
I'm facing the same issue, the project working is on PHP 7.0, ag.: run the `format` it adds the void on methods and runs diagnostics it shows the same warning (PHP 7.0 still does not have support for it)

**Comment by Abdillah** [comment]
Hi @afranioce, do you mean you have a setting that set a rule for PHP 7 project but ignored?
What's your config file? What this format you run specifically?

The background of this issue is likely different with your use case, hope we can find common problem.

**Comment by afranioce** [comment]
@Abdillah I think so, as mentioned before by @dantleech, I mean the solution to add the `--config` should solve the problem, when I run the CLI php-cs-fixer to format or lint the direct per file I don't have the issue because I put the `--config` argument, just using the phpactor formatter.

**Comment by Abdillah** [comment]
There are two configs `.php-cs-fixer.dist.php` located in project root and `.php-cs-fixer.php` in subdirectory as I understand [the documentation](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/config.rst). In this case, have you tried to rename the file into `.dist.php`? In my case with `.dst.php` config and without `--config`, already read the rule correctly.

**Comment by Abdillah** [comment]
I think this issue is shifted from its original title and intention. In my side, it is now more of a bug "file should be ignored by PHP Actor when excluded in the config." The config discovery is fine though, it just not used as intended.

What do you think @dantleech, should I create a new issue and proposed solution? Or can we continue the potential solution here.

**Comment by dantleech** [comment]
I think its fine here for now :)

**Comment by dantleech** [comment]
ok, so we don't use paths at all - we pass the source code directly to the process via. `stdin` this is because the "CS fixer" should work on documents that have not been saved and that do not exist on the disk.

If we were invoking `php-cs-fixer` with a path, then `--path-mode=intersection` would be the solution, but we're not.

I'm not sure there is anything we can reasonably do here:

- Adding php-cs-fixer specific include/exclude "path" is duplicating config and extra complexity
- It might be possible to read the `.php-cs-config` but again extra complexity + change of runtime crashing as we need to interpret PHP code

I think the easier solution here is to disable auto-formatting and invoke the formatting action by hand and/or on a pre-push hook.

Closing for now, but still happy to hear other ideas.
