### ISSUE TITLE
Diagnostics: Missing arguments

### ISSUE THREAD

**Issue by Dmitrev** [phpactor/phpactor#2328]
It seems like missing arguments are not reported at the moment:

```php
<?php

declare(strict_types=1);

namespace App;

class test
{
    public function testing(int $a): void {

    }
}

$test = new test();
$test->testing(); // Expected missing $a here
```

Editor: Neovim 0.9.0
PhpActor: 2023.06.17

Lua config:

```
   phpactor = {
      language_server_psalm = {
         enabled = true
      }
   },

```

**Comment by dantleech** [comment]
there are lots (_lots_) of "missing" diagnstics - i'm probably happy for them to be added if a list can be compiled, but it's recommended to use the PHPStan integration if that's a possiblity, it does a much better job.

**Comment by Dmitrev** [comment]
I'm happy with that, makes sense to outsource that to PHPStan. That would avoid any conflicts between PHPStan & PHPActor

Thanks for your quick response @dantleech, I'll close this as this issue is not actionable.

**Comment by dantleech** [comment]
oh, you are using Psalm -- then ignore the above.

The Psalm integration isn't perfect:

- You need to save the file to trigger the diagnostics
- The Psalm cache isn't always working great, and it can take some time.

**Comment by Dmitrev** [comment]
@dantleech I didn't properly installed Psalm, so that would explain why it's not working, I'll take your advice to just use PHPStan instead, cheers man!
