### ISSUE TITLE
Undefined variable when dynamically declared and passed by ref

### ISSUE THREAD

**Issue by mecha** [phpactor/phpactor#2329]
Phpactor marks variables as undefined if they are dynamically declared when passed by reference to a function:

```php
function foo(?int &$value): void
{
    $value = 123;
}

foo($num); // phpactor: Undefined variable "$num"
```

Curiously, no error is raised for built-in PHP functions that do the same, like `preg_match()` and its 3rd argument:

```php
preg_match('/^php(.*)$/', 'phpactor', $matches);
```

I couldn't find any documentation on config options to tweak this behavior. Is this intended behavior?

---

Sales pitch:
I understand that this form of function output is archaic 😅 but I have legitimate reasons and I really need to suppress these errors. I have hundreds of them in my code-base and they are over-shadowing other more important diagnostics.

**Comment by dantleech** [comment]
yes Phpactor should support this, and it _does_ for built in functions at least, not sure why it doens't work here, so assuming it's a bug

**Comment by mecha** [comment]
Yep. I found [this test][1] while poking around the code to see if I could figure this out and maybe submit a PR, which coincidentally also use `preg_match()` to assert that no diagnostics are raised.

[1]: https://github.com/phpactor/phpactor/blob/master/lib/WorseReflection/Bridge/TolerantParser/Diagnostics/UndefinedVariableProvider.php#L269

**Comment by mamazu** [comment]
Could it be the variable names that have to be the same?  Because in the `preg_match` example, the parameter and the variable passed have the same name. Maybe that would be worth investigating?

**Comment by mecha** [comment]
@mamazu I had the same thought, but it looks like the name doesn't matter.

---

I think this may be _part_ of the cause:

The [`UndefinedVariableProvider`][1] tries to get the parameter offset for an argument ([here][2]), and then does a loose falsey check. If the offset is `0`, it will wrongly assert that the argument is not being passed by reference. The check should probably be changed to explicitly compare against `null`:

```php
if ($offset !== null) {
    return false;
}
```

Maybe. 


[1]: https://github.com/phpactor/phpactor/blob/master/lib/WorseReflection/Bridge/TolerantParser/Diagnostics/UndefinedVariableProvider.php
[2]: https://github.com/phpactor/phpactor/blob/master/lib/WorseReflection/Bridge/TolerantParser/Diagnostics/UndefinedVariableProvider.php#L381

**Comment by mamazu** [comment]
So this means that it only works if the pass by reference isn't the first parameter?

**Comment by mecha** [comment]
The code seem to indicate that, but in my case the position of the argument didn't matter. I have code that looks like this:

```php
if ($result->isOk($data, $err) {
    // ...
} else {
    throw $err;
}
```

Phpactor currently raised diagnostics for both `$data` and `$err`.

That said, [I added a test][1] with 2 arguments that are passed by reference and no diagnostics are raised after fixing the offset check. Not sure why exactly.

[1]: https://github.com/phpactor/phpactor/compare/master...mecha:phpactor:gh-2329

**Comment by mecha** [comment]
It appears that the context for method calls is not an instance of `FunctionCallContext`, but instead an instance of `MemberAccessContext`, so they fail [this check][1].

I think I've figured out how to fix this. I'll submit a PR.

[1]: https://github.com/phpactor/phpactor/blob/master/lib/WorseReflection/Bridge/TolerantParser/Diagnostics/UndefinedVariableProvider.php#L387
