### ISSUE TITLE
Editorconfig auto-configuration extension

### ISSUE THREAD

**Issue by danrot** [phpactor/phpactor#2334]
I have my neovim setup to use the `.editorconfig` file in the project root. In one project I have set it up to use tabs instead of spaces, i.e. like that:

```editorconfig
root = true
[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = tab
indent_size = 4
trim_trailing_whitespace = true

[*.yaml]
indent_style = space
indent_size = 4
```

Now when I use code actions from phpactor like "Implement contracts" it inserts the missing method, but the newly created code is indented using spaces. I would expect it to use tabs for indentation if neovim would insert tabs when I write it out on my own.

**Comment by dantleech** [comment]
you can configure the indentation [here](https://phpactor.readthedocs.io/en/master/reference/configuration.html#code-transform-indentation).

It would be possible to introduce a simple `editorconfig` [extension](https://github.com/phpactor/phpactor/blob/836235017ba0419f77ded78f93252455242e7682/lib/Extension/LanguageServerPhpstan/LanguageServerPhpstanSuggestExtension.php#L16) which automated that setting.

**Comment by danrot** [comment]
Ok, didn't know that 🙂 However, isn't it possible to set `"\t"` as a default, and let neovim handle how that is interpreted? If the editor is configured to indent using spaces, it should replace that with four spaces anyway, at least that's how I would imagine it to work 😅

**Comment by dantleech** [comment]
`\t` is just a character as far as the editor is concerned I think :)

**Comment by dantleech** [comment]
Closing this, essentially this comes down to automatically configuring Phpactor's single indentation setting based on two settings in `.editorconfig` - I'm not against the idea necessarily, but it would be best implemented as an auto-configuration extension, but I think that could be a separate issue.

**Comment by dantleech** [comment]
https://github.com/phpactor/phpactor/issues/2342
