### ISSUE TITLE
Add support for default methods of enums

### ISSUE THREAD

**Issue by tenmajkl** [phpactor/phpactor#2341]
Enums have default static methods, `cases` for each and `from` with `tryFrom` for backed enums. These methods don't have autocompletition. I could add it, but I don't know codebase of phpactor well.

**Comment by dantleech** [comment]
Auto completion should work, have you got an example?

**Comment by dantleech** [comment]
![image](https://github.com/phpactor/phpactor/assets/530801/4570a69b-c988-4c39-8cac-209adbe440fc)

![image](https://github.com/phpactor/phpactor/assets/530801/b46f0414-d2bf-44b1-ab4e-9e349bf2b5cf)
