### ISSUE TITLE
Crash when using php-cs-fixer

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#2348]
With `language_server_php_cs_fixer.enabled`, after creating a new interface with `:PhpactorClassNew`, I get a crash that seems to emanate from here:

https://github.com/phpactor/phpactor/blob/e52651ca42c63043226c63d36fe2d4ebfb66cdd0/lib/Extension/LanguageServerPhpCsFixer/Provider/PhpCsFixerDiagnosticsProvider.php#L195-L197

**Comment by greg0ire** [comment]
The crash happens also when using the code action, and more importantly, when opening the interface again after quitting vim completely.

**Comment by greg0ire** [comment]
The crash seems to happen only when there is a cs issue, and can happen with classes as well (being an interface does not matter).

**Comment by greg0ire** [comment]
Could it be that the triggering condition is: have a diff whose first line is a replaced line?

https://github.com/phpactor/phpactor/blob/e52651ca42c63043226c63d36fe2d4ebfb66cdd0/lib/Extension/LanguageServerPhpCsFixer/Provider/PhpCsFixerDiagnosticsProvider.php#L174-L192

I think when that's the case, none of the `if` statement here will kick in.

**Comment by dantleech** [comment]
cc @Einenlum

**Comment by dantleech** [comment]
Should be fixed now!
