### ISSUE TITLE
Undefined variable $matches with list unpacking

### ISSUE THREAD

**Issue by Whax** [phpactor/phpactor#2361]
Hi,

with the following code 

```php
$str = '2023_001';
if(preg_match('#([0-9]+)_([0-9]+)#', $str, $matches) {
  list($a, $b, $c) = $matches;
  dump($a, $b, $c);
}
```
phpactor considers `$matches` as undefined.

![image](https://github.com/phpactor/phpactor/assets/5028767/ea9bac9a-9797-449c-93e8-5c8c719ec5ec)

PR #2291 only fixes the  `preg_match` part.

**Comment by dantleech** [comment]
ok, first attempt was just wrong, should be fixed properly now :stuck_out_tongue:

**Comment by Whax** [comment]
Hey,

thanks for the job, it fixed it ! ;)
