### ISSUE TITLE
@var annotation behaving erratically

### ISSUE THREAD

**Issue by JoyceBabu** [phpactor/phpactor#2366]
I have a PHP template file, which is included from my template engine class. Hence the variables are not defined within the template file, and I am trying to define the variables using @var annotation. But phpactor is behaving erratically when @var annotation is used to specify the type of a variable.

```
<?php

/** @var string $a */
/** @var string $b */
/** @var string $c */
?>
<?php

echo $a + $b;

echo $a;
echo $b;

```

<img width="782" alt="image" src="https://github.com/phpactor/phpactor/assets/502942/034897a9-95d4-47b2-b8da-d584454e32d5">

But if I change the `+` operator to `.`, it no longer works.

<img width="688" alt="image" src="https://github.com/phpactor/phpactor/assets/502942/defeb790-7506-40d1-811d-3243e1023a95">

**Comment by mamazu** [comment]
Could it be that the variable scope is only inside the php tags? So if you put everything in one tag it works?

**Comment by JoyceBabu** [comment]
No, putting it within the same `<?php`  block too behaves the same.
