### ISSUE TITLE
Method "cases" does not exist on class My\Beautiful\Enum

### ISSUE THREAD

**Issue by Whax** [phpactor/phpactor#2378]
Hello,

I'm encountering an issue with enums `Method "cases" does not exist on class "xxxx".

![image](https://github.com/phpactor/phpactor/assets/5028767/5f3b1883-87b6-4ab8-ab9a-c94401eb8cb6)

I was thinking it could be mason related as it doesn't provide the latest version but after updating manually the problem persists.
I'm using the latest version avaiable
![image](https://github.com/phpactor/phpactor/assets/5028767/627573d4-3864-42ea-8473-351763a3666e)

**Comment by dantleech** [comment]
- Can you provide the code for one of the enum classes it is complaining about?
- `phpactor status`
- Depenending on when you updated a reindex might be required, additionally you might try `rm -Rf ~/.cache/phpactor/index/....your project`

**Comment by Whax** [comment]
Thanks for your fast reply. Here are the infos

The server seems to be the latest version
```sh
❯ phpactor status
Version: "9847641 (2 days ago) Gh-2373-no-crash-2375
```

Here you can find an example of code
```php
<?php

declare(strict_types=1);

namespace App\Catalog\Domain;

enum Vat: int
{
    case DEFAULT = 16;
    case NONE = 0;

    public function label(): string
    {
        return sprintf("%d %", $this->value);
    }
}
```

I tried with non backed enum too, same problem.

I tried with a fresh install (cleaned all neovim directories + cache), same problem :(

Sorry for bothering you with that, from what I see In the repository It should work and it may be not really phpactor related.

**Comment by dantleech** [comment]
Do you get completion?

![image](https://github.com/phpactor/phpactor/assets/530801/c6704cdb-a5c0-4821-9652-0d1292db6301)

**Comment by Whax** [comment]
Yup !

![image](https://github.com/phpactor/phpactor/assets/5028767/65152549-a3ce-4404-883f-14257e35f983)

**Comment by dantleech** [comment]
And do you get the  missing method diagnostic _there_?

**Comment by Whax** [comment]
I have another message

![image](https://github.com/phpactor/phpactor/assets/5028767/3e04d2ea-6a3e-471c-b2f0-fe3b0dc8b6e4)

**Comment by dantleech** [comment]
yeah, that's just PHPStan saying that this code makes no sense :sweat_smile:

**Comment by dantleech** [comment]
The other thing to consider is if youre PHP runtime is PHP 8.1+ (i.e. has support for Enums). Phpactor requires 8.0 and for some strange reason the Parser uses the Runtime to determine if it supports Enums or not.

**Comment by Whax** [comment]
Oh yeah, indeed, I forgot about it x)

Without phpstan, I've got no missing warning !
![image](https://github.com/phpactor/phpactor/assets/5028767/b205b0e1-18e9-4a3b-a6f8-acde8231e6f2)


Maybe I should try to reproduce the bug with a very neovim minimal install and without Mason. I'll take a look.

Anyway thanks a lot for your help !

**Comment by innocenzi** [comment]
Hey, just chiming in, I also have that issue:

![CleanShot 2023-09-25 at 15 09 53](https://github.com/phpactor/phpactor/assets/16060559/075fa4c1-dc76-4817-ae1b-185c5a6d7c3a)

![CleanShot 2023-09-25 at 15 10 29](https://github.com/phpactor/phpactor/assets/16060559/13ece1ad-04fa-4339-b797-301cd4bb18af)

Strangely enough, autocompletion works:

https://github.com/phpactor/phpactor/assets/16060559/75aa5a07-2aa4-43f0-ae58-34f1e228a998

**Comment by dantleech** [comment]
i cannot reproduce this - can you confirm which version of PHP you are using on your host?

```
php --version
PHP 8.1.19 (cli) (built: May 10 2023 13:43:03) (NTS)
```

**Comment by Whax** [comment]
```sh
PHP 8.2.11 (cli) (built: Oct  1 2023 18:59:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
```
here

**Comment by dantleech** [comment]
can we try deleting the index? `rm -Rf ~/.cache/phpactor/index/<project>-<hash>` and restarting?

**Comment by Whax** [comment]
After cloning manually the latest version, it still doesn't work :(

```sh
❯ phpactor status
Version: "15109f07 (5 days ago) Update-CL
Filesystems: git, simple, composer
Working directory: /home/whax/.local/share/nvim/mason/packages/phpactor

❯ php -v
PHP 8.2.11 (cli) (built: Oct  1 2023 18:59:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
```
![image](https://github.com/phpactor/phpactor/assets/5028767/93209746-840c-4bcd-9c1f-5b098f4cc0cd)

**Comment by BladeMF** [comment]
I have the same problem. Deleted the cache to no avail.
<img width="554" alt="image" src="https://github.com/phpactor/phpactor/assets/12109622/8c76c49d-ec54-47aa-88ee-1e3185d292f0">

**Comment by dantleech** [comment]
hm, ok, seems I can reproduce it on a real project vs. trying to reproduce arbitrarily :+1: 

![image](https://github.com/phpactor/phpactor/assets/530801/78da9c1a-af81-4e8a-899d-023410963526)
