### ISSUE TITLE
File size limit

### ISSUE THREAD

**Issue by vivere-dally** [phpactor/phpactor#2385]
I use phpactor with neovim, installation through mason. I'm using the default configs and the  lsp is working fine in my php files.

However, I am working on a large laravel project, and I observed that phpactor does not provide good completion using the `_ide_helper.php` file. I looked through the logs with `:LspLog` and there is a line:

> [START][2023-10-02 22:44:55] LSP logging initiated
[ERROR][2023-10-02 22:44:55] .../vim/lsp/rpc.lua:734	"rpc"	"$HOME/.local/share/nvim/mason/bin/phpactor"	"stderr"	"Starting language server, use -vvv for verbose output\n"
[WARN][2023-10-02 22:44:59] ...lsp/handlers.lua:537	"<project>/_ide_helper.php is over the maximum file size of 1000000 bytes."

I tried to look through the [configs](https://phpactor.readthedocs.io/en/master/usage/configuration.html), but I did not find a way to set this limit.

**Comment by dantleech** [comment]
I don't think that's coming from Phpactor but Neovim judging by the message
