### ISSUE TITLE
Variant not taken into account

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#239]
I'm trying to get final classes when calling `ClassNew()`

Issues found:

1. the README contradicts itself, `code_transform.class_new.variants` seems to work, but `new_class_variants` is not recognized
2. Under `code_transform.class_new.variants`, I believe it should not be a numeric index, otherwise you get `0` in the vim list, not very descriptive
3. When I use the following config, and select `final`, I don't get a final class, and I don't understand why there should be a for loop:
```
./templates/final.php.twig
namespace {{ prototype.namespace  }};

{% for class in prototype.classes %}
final {{ class.name  }}
{

}
{% endfor %}


./phpactor.yml
code_transform.class_new.variants:
    final: final
```

I tried renaming `final` to `SourceCode` like in the docs, to no avail.
I also tried writing `final: typo`, and did not get an exception.

**Comment by dantleech** [comment]
Really need to create a documentation effort, but this stuff is quite immature, for me it works:

```
$ cat .phpactor.yml                                                                                                                      ⏎ relative_class_to_file_issue ✭ ✱ ◼
code_transform.class_new.variants:
    exception: exception
    symfony_command: symfony_command
$ tree .phpactor                                                                                                                           relative_class_to_file_issue ✭ ✱ ◼
.phpactor
└── templates
    ├── exception
    │   └── SourceCode.php.twig
    ├── symfony_command
    │   └── SourceCode.php.twig
    └── value_object
        └── ClassPrototype.php.twig

4 directories, 3 files
```

**Comment by greg0ire** [comment]
Ooooh ok it's always `SourceCode`. but in a `final` directory.

**Comment by greg0ire** [comment]
I'll fix the docs
