### ISSUE TITLE
Vim extension: Name is imported but not used

### ISSUE THREAD

**Issue by InFog** [phpactor/phpactor#2390]
I have this issue showing that a name is imported but not used. It is actually used, but the error is there:

![image](https://github.com/phpactor/phpactor/assets/72276/f8d22684-e3e6-4ff6-bbad-c06ce6118178)

Any ideas?

I'm using Coc-phpactor.

**Comment by dantleech** [comment]
not really, can you provide the code as a code block instead of a screenshot?

**Comment by InFog** [comment]
Thank you for the answer, @dantleech.

Removing both `require` and `include_once` solved it. The error is gone.

This only happens in files where some kind of manual require like this is used.

**Comment by dantleech** [comment]
ok great, include and require do strange things. marking as a bug.

**Comment by InFog** [comment]
Thanks!

**Comment by InFog** [comment]
Btw, @dantleech, should I provide some sample code where it happens?

**Comment by dantleech** [comment]
No, like I said it's useful to have the code as a

```
text block
```

rather than a screenshot, but it's fine now

**Comment by dantleech** [comment]
should be fixed in #2391 can you confirm?

**Comment by InFog** [comment]
Woah, it is fixed. Thanks a lot, @dantleech!!! Please, enjoy the coffee I sent you :coffee:

**Comment by dantleech** [comment]
Much appreciated!
