### ISSUE TITLE
PHP: Deprecated

### ISSUE THREAD

**Issue by ghost** [phpactor/phpactor#2396]
I installed phpactor: "composer global require phpactor/phpactor", PHP 8.1.24, Windows 11:

Deprecated: Return type of Phpactor\ConfigLoader\Core\PathCandidates::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Users\techlust\AppData\Roaming\Composer\vendor\phpactor\config-loader\lib\Core\PathCandidates.php on line 24

In TextDocumentUri.php line 50: Only "file://" scheme is supported, got "C"

**Comment by dantleech** [comment]
I don't think you'll have much luck getting Phpactor to work under Windows, It should work under WSL though.
