### ISSUE TITLE
How to disable auto refatoring

### ISSUE THREAD

**Issue by eerison** [phpactor/phpactor#2398]
Hello is there anyway to disable auto refactoring?

**Comment by dantleech** [comment]
not sure what you mean, "refactoring" isn't automatic

**Comment by eerison** [comment]
well when I am saving the file, it is adding typehint automatically for the function that is missing it, How could I disable/enable when it is needed?

**Comment by dantleech** [comment]
This is not Phpator, but rather your IDE, which editor are you using? I also suspect this is the PHPCS/Fixer integration and it's applying your existing CS rules? (phpactor has this refactoring, but you would _always_ need to choose it)

**Comment by eerison** [comment]
> This is not Phpator, but rather your IDE, which editor are you using? I also suspect this is the PHPCS/Fixer integration which is being invoked by your IDE and it's applying your existing CS rules? (phpactor has this refactoring/code-action, but you would _always_ need to choose it)

I'm using Astrovim 👀

**Comment by dantleech** [comment]
closing for now, as I don't think this is something phpactor needs to fix :)
