### ISSUE TITLE
Index PHAR files

### ISSUE THREAD

**Issue by calebdw** [phpactor/phpactor#2412]
Hello!

Would it be possible for phpactor to index PHAR files? I was attempting to write a custom PHPStan rule and apparently everything is buried inside the PHAR which isn't indexed and therefore has no autocompletion:

https://github.com/phpstan/phpstan/issues/9819#issuecomment-1697291398

Thanks!

**Comment by CalebDW** [comment]
It looks like the namespace is somewhat detected in the `use` autocomplete, but not everything is found. 


![image](https://github.com/phpactor/phpactor/assets/4176520/da9fbc1d-1ab7-4523-9721-2572720ec51f)

![image](https://github.com/phpactor/phpactor/assets/4176520/77eb05ca-1866-43c2-bd10-96a69c3215b1)

![image](https://github.com/phpactor/phpactor/assets/4176520/22a53223-ece1-4553-8494-82d2f2c713f8)


![image](https://github.com/phpactor/phpactor/assets/4176520/44b3da80-c9be-4c9f-bb24-ce8016a14a92)

**Comment by dantleech** [comment]
Can Neovim/VSCode open files PHAR archives?  It might be possible be but it would be involved at this point.

**Comment by dantleech** [comment]
hmm, then maybe :thinking: you could experiment by hacking Phpactor to index `.phar` files.

**Comment by dantleech** [comment]
ok, it's basically either a Zip or Tar file. Experimenting locally I do not get anything immediately parseable (using the `phpactor.phar`) so I think it would need to be untarred/unzipped and then indexed. Apparently PHPStorm will happily index PHAR files.

**Comment by CalebDW** [comment]
Technically the `phar` can be one of three types (however, the phar extension can convert between the formats very easily):

> Phar archives can be distributed as tar archives, zip archives, or as the custom phar file format designed specifically for the phar extension.

I believe PHPStorm does allow 'jump to definition' and the other code actions...not sure how though.

The solution for other folks has just been to extract the phar manually which would allow their lsp to index the files:
https://github.com/phpstan/phpstan/issues/2972#issuecomment-585143076

**Comment by dantleech** [comment]
This is probably doable, but needs thought.

**Comment by dantleech** [comment]
_should__ work #2602

**Comment by calebdw** [comment]
Awesome!! It looks like it's working, thank you! I'm getting auto-completion and class/method docs


I am getting this error occasionally though:

Error in service "indexer" "Phpactor\Extension\LanguageServerIndexer\Handler\IndexerHandler:Phpactor\LanguageServer\Core\Service\{closure}": internal corruption of phar "/home/cwhite/sources/laravel/laras
tan/vendor/bin/phpstan.phar" (__HALT_COMPILER(); not found)

**Comment by calebdw** [comment]
@mad-briller, just wanted to make you aware about this new feature!

**Comment by mad-briller** [comment]
Looks interesting, I'm using intelephense at the moment but I'll have to give phpactor a try again, it's been a few years

**Comment by dantleech** [comment]
> I am getting this error occasionally though:
should be fixed now.
