### ISSUE TITLE
PHPActor throws error using the Yii2 framework but works anyway. 

### ISSUE THREAD

**Issue by Numkil** [phpactor/phpactor#2464]
Whenever i use the PhpActor LSP when working on a Yii2 project I am bombarded with these errors wherever I have to use the Yii class. 

![Screenshot 2023-12-11 at 11 30 11](https://github.com/phpactor/phpactor/assets/5604686/148c3ad8-4ab5-46b4-ab45-62bd030c1d0e)

Despite this all LSP features on the Yii class like goto definition, method documentation, etc.. are working perfectly fine. This makes me believe that this error is probably a wrong analysis.

**Comment by mamazu** [comment]
Those errors look like Phpstan errors. Did you set that up in your project?
