### ISSUE TITLE
[CB] Transform adds a trailing newline

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#247]
I tried using `:call phpactor#Transform()` and got an extra , unwanted newline at EOF.

# Expected result

```php
<?php 
class MyClass
{
    public function existingMethod()
    {
    }

    public function supportedSearchFields(): array
    {
    }
}
```

# Actual result

```php
<?php 
class MyClass
{
    public function existingMethod()
    {
    }

    public function supportedSearchFields(): array
    {
    }
}
// github doesn't show it but there is an extra line here
```
Apart from that, it's the first time I try this feature and it's really cool!

**Comment by dantleech** [comment]
Yes this has been bugging me for ages too :P

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/phpactor/commit/ccdf6e7cadd7e0f7bcbc6b03bb9a03d350a9e46d
