### ISSUE TITLE
Allow injecting flags to PHP Code Sniffer

### ISSUE THREAD

**Issue by arturolinares** [phpactor/phpactor#2489]
It would be helpful to add cli flags for phpcs. This could be used to choose a standard, for example,

I imagine this could be configured in `.phpactor.json`:

```json
"php_code_sniffer.cli_flags": [
  "--standard=Drupal,DrupalPractice",
  "--extensions=php,moodule,inc,install,theme",
]
```

**Comment by dantleech** [comment]
I added this a month ago in master:

```
    "php_code_sniffer.args": ["--standard=config.xml"],
```

**Comment by dantleech** [comment]
ok, no PR is still open :sweat_smile: https://github.com/phpactor/phpactor/pull/2465

**Comment by dantleech** [comment]
ok, that's merged now :+1:

**Comment by arturolinares** [comment]
A bunch of thanks @dantleech!

**Comment by arturolinares** [comment]
@dantleech if the configuration "php_code_sniffer.cwd" is omitted, phpactor crashes trying to access a null value. Adding a default value (like `%project_root%`) might solve this.

**Comment by dantleech** [comment]
pushed a fix to master :crossed_fingers:
