### ISSUE TITLE
[templates] Decorator inflector

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#249]
Generate a decorator for the context class, e.g.

```
class A extends Some<>Interface
{
}
```

Generates (given name for new class):

```
class XXX implements SomeInterface
{
    private function $innerXXX;

    public function __construct(SomeInterface $innerXXX)
    {
        $this->innerXXX;
    }

    public function contractMethod1()
    {
        $this->innerXXX->contractMethod1();
    }

    // all other contractsk
}
```

**Comment by dantleech** [comment]
Currently it is necessary to create a new class for this in `phpactor/code-transform`. Might be more extensible to "simply" pass the ReflectionClass to the template.

**Comment by mamazu** [comment]
Is this still a thing. Because I couldn't find any code transform generator that generates that. If so could you point me in the right direction?

**Comment by dantleech** [comment]
Sure, mechanically it's very similar to [implement contracts](https://github.com/phpactor/phpactor/blob/873fa51ae06eb3dd568ac02c111503b88b76e723/lib/CodeTransform/Adapter/WorseReflection/Transformer/ImplementContracts.php)

Implement Contracts is a Transformer. Transformers are an old way of applying a "transformation" on the entire document, there is a bridge for them so they integrate seemlessly as code actions. It might be better to simply implement a code action rather than a transformation though as I will describe later.

There are three ways to impleement it:

1. **Code transform**: Invoked on a stub class definition `class Foo implements ClassToBeDecorated {}`.
2. **Code inflection**:  Invoked on an interface (needs user input to specify where the decorated class should be created.
3. **Code action**: as with `code transform` invoked on a stub definition

I tend to favour 3.

If using `implement contracts` as a template there are the following differences:

- **Diagnostics**: are used in "transformers" to suggest a problem that can be fixed with a code action - it doesn't really make sense to use them here. Which means that perhaps implementing a code-action directly would be a better option, in which case the `CodeActionProvider` will say if the code action can be applied or not.
- **Availability**: I think the code action should only be available on an empty class stub that implements one (or more?) interfaces (i.e. no constructor, no other methods)

To implement a code action:

- Create a decoupled class in `CodeTransform` package which actually does the work, f.e. [WorseExtractConstant](https://github.com/phpactor/phpactor/blob/873fa51ae06eb3dd568ac02c111503b88b76e723/lib/CodeTransform/Adapter/WorseReflection/Refactor/WorseExtractConstant.php).
- Create a [code action provider](https://github.com/phpactor/phpactor/blob/873fa51ae06eb3dd568ac02c111503b88b76e723/lib/Extension/LanguageServerCodeTransform/CodeAction/CreateUnresolvableClassProvider.php) to decide if the action should be applied or not (it can probably delegate to the code transform class)
- The code action provider provide code actions referencing an LSP [command](https://github.com/phpactor/phpactor/blob/873fa51ae06eb3dd568ac02c111503b88b76e723/lib/Extension/LanguageServerCodeTransform/LspCommand/CreateClassCommand.php) which would just be a bridge to the CodeTransform class.


-

**Comment by mamazu** [comment]
Okay so correct me if I am wrong about the "Implement Contracts" method: This transformer takes an existing class and only adds methods to it.

Version 3 sounds like a good compromise. The only downside is that you have know how to use the action. (eg. having to generate a stub class)

I will try to implement it like you outlined it. Just one unrelated question why do some namespace and class names contain the word `worse` in them?

**Comment by dantleech** [comment]
WirseReflection is the static reflection and flow analysis package in Phpactor, it's a play on a similar package - BeyterReflectiin. Classes prefixed with Worse are implementations of an knterfacenusing that package.

**Comment by mamazu** [comment]
Okay I have the LSP command down. You said that the code action provider can be delegated to the CodeTransform. As far as I see the implementation, the code transformer only has the `transform` method that actually does the transformation. I don't know how this would work together with the code action provider who just needs a yes or no, if the code can be implemented.

**Comment by dantleech** [comment]
Yeah I assume we did not go the code transformer way, so no need to involve that.

LSP command accepts parameters. You return a reference to that command in the code action provider, the client/editor can then execute the command don't the server.

**Comment by mamazu** [comment]
Okay then I have a follow up question about the command parameters. 

What about a class having multiple interfaces it implements would you say that in the code action or the transformer:

For the code action approach I would generate a list of interfaces that could be decorated and make the user pick one.
For the transformer approach I would just generate decorator for the interface the user's cursor is currently on.

**Comment by dantleech** [comment]
I think we can forget about the transformer use case, as mentioned above they have baked in "diagnostics" which I don't think make sense in this context.

I would start with just the first interface and only offer the action if one interface is present. I'd think that would deliver the most value without too much complexity?

**Comment by mamazu** [comment]
It wouldn't really add too much complexity to add a code action for every interface, but that maybe something for version 2 of the command.

**Comment by dantleech** [comment]
done in #1879
