### ISSUE TITLE
Typed class constants are not available for completion

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#2496]
![image](https://github.com/phpactor/phpactor/assets/11404453/d528d6ff-d49a-4b83-ae11-1fc3b759a54f)

**Comment by dantleech** [comment]
probably parser doesn't support it yet.

**Comment by dantleech** [comment]
confirmed, will need to add support to the parser.

**Comment by dantleech** [comment]
can be as simple as cherry-picking https://github.com/microsoft/tolerant-php-parser/pull/406 into our fork

**Comment by przepompownia** [comment]
Would you like to do it, especially decide when it can be considered ready to merge the PR here?

**Comment by przepompownia** [comment]
Thank you @dantleech for #2736 (and have a nice trip :bike: ).
