### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#2499]
On [this page](https://phpactor.readthedocs.io/en/master/extensions/installing.html), there is a link to [https://phpactor.readthedocs.io/en/master/extensions/extensions/list](https://phpactor.readthedocs.io/en/master/extensions/extensions/list) which leads to a 404.

**Comment by dantleech** [comment]
hmm, that page is no longer relevant and can be deleted. where did you find it?

**Comment by Einenlum** [comment]
I looked for "extensions" in the search. Led me to [here](https://phpactor.readthedocs.io/en/master/extensions.html?highlight=extensions#extensions) and then to [there](https://phpactor.readthedocs.io/en/master/extensions/installing.html).

**Comment by dantleech** [comment]
removed, thanks!

**Comment by Einenlum** [comment]
Just a small comment/question, now we're talking about extensions:
I guess all these extensions like https://github.com/phpactor/behat-extension or https://github.com/phpactor/phpspec-extension are now deprecated since they (at least Behat) are now in the main repo (and the extension:install command doesn't exist anymore)?

**Comment by dantleech** [comment]
yes exactly. i've archived those now

**Comment by vctls** [comment]
Is there still a way to use theses archived extensions?  
I was trying to use [this one](https://phpactor.readthedocs.io/en/master/reference/configuration.html?highlight=annotation#completionworseextension) specifically, for the annotations support.
