### ISSUE TITLE
Documentation about different types of extensions

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#2501]
Your [article](https://www.dantleech.com/blog/2018/11/25/phpactor-extensions/) is a nice introduction but it's a bit outdated now (because of the monorepo).

I think it could be nice to get an overview of the different extensions and which interface one should implement for which case. I'm working on a Pest extension and I have some trouble understanding which part does what (and also the difference between `Completion`, `CompletionExtra` or `CompletionWorse`).

I'm not necessarily talking about a long document in the doc but maybe some comments in the files or in a README could help :relaxed: .

Thanks again for your monumental work! :heart:

**Comment by dantleech** [comment]
I think it's tricky as the API is very unstable. It's likely that we would rewrite parts of the API to accomodate f.e. a Pest extension, or to improve the Prophecy extension for example.

The best approach is to look at the existing "integration" extensions: Symfony, Behat, Prophecy all do stuff (for better ot worse) for completion.
