### ISSUE TITLE
Variables first defined in switch statements have no warning when used later

### ISSUE THREAD

**Issue by kedodrill** [phpactor/phpactor#2503]
**Describe the bug**
Defining a variable in a switch statement can produce odd results if that variable is intentionally or unintentionally used outside of that `case` later on in the code, or in a different `case`. I would expect phpactor to show a warning but it does not.

**To Reproduce**
```php
<?php

// For testing purposes this is equal to 1, but let's say it's supposed to be a dynamic value (could be any value)
$test = 1;

// If $testing was defined here, warnings should not show up.
switch ($test) {
    case 0:
        $testing = ['id' => 1];
        break;
    // We know $test will enter this case
    case 1:
        // This will not work because $testing is undefined. Phpactor should show a warning or error
        $id = $testing['id'];
        break;
}

// This will not work because $testing is undefined. Phpactor should show a warning
echo $testing['id'];
// This should show a warning because $id *could* be undefined (if $test !== 1)
echo $id;
```

**Expected behavior**
If a variable is *first* defined inside a `switch case`, any further usage of that variable *outside* of the switch statement (or in other `case` blocks) should show a warning of a potentially undefined variable.

**Platform and version**
Linux, phpactor 2023-12-03
I am using neovim with native lsp

**Comment by dantleech** [comment]
At this point I'm not especially interested in adding diagnostics like this unless they can also be fixed automatically. The PHPStan or Pslam extensions will.cover this and 1000 other things :)

**Comment by kedodrill** [comment]
@dantleech That makes sense to me. I didn't think about PHPStan or Psalm so I will check those out as well. Closing then.
