### ISSUE TITLE
PHPStan: include the `tip` information where available

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2511]
PHPStan also provides a :bulb:  `tip` key in it's JSON output where applicable. This could be provided as a separate `info` diagnstoic perghaps, or just appended to the existing diagnostic.

**Comment by fbuchlak** [comment]
Seems like you've already resolved this issue in #2512.
Are there any plans on expanding this issue?

**Comment by dantleech** [comment]
No, think it can be closed
