### ISSUE TITLE
Unable to launch new process in in serviceAnnouncement with Neovim LSP

### ISSUE THREAD

**Issue by joshrainwater** [phpactor/phpactor#2533]
I think this might be due to php versions, or possibly missing extensions, but I'm so far unable to find the cause. When attempting to open phpactor as my LSP in neovim, I receive the following error:

`LSP[phpactor] Error in service "serviceAnnouncements" "Phpactor\Extension\LanguageServer\Service\OnDevelopWarningService:Phpactor\LanguageServer\Core\Service\{closure}": Unable to launch new process. 

This is after installing php8.3 and cleaning out older versions, so likely related but I'm not sure where to look for issues exactly.

Thanks!

**Comment by joshrainwater** [comment]
As a quick followup to this: I've installed php using the following on Ubutnu 22.04 and phpactor seems to work successfully:
`sudo apt-get install php8.2 php8.2-cli php8.2-curl php8.2-opcache php8.2-xml php8.2-common php8.2-gd php8.2-readline php8.2-zip php8.2-fpm php8.2-mbstring -y`.

If I change all these params to 8.3 it doesn't. So it seems to be something with changing versions as far as I can see so far.

**Comment by dantleech** [comment]
How did you install Phpactor? Which version are you using?

I can confirm that everything works fine on 8.3 for me, and the tests pass.

can you run `phpactor status` from the command line as that might reproduce the same issue

**Comment by joshrainwater** [comment]
Looks like the installed version is: `Phpactor 2023.12.03.0@1dcb8b2c589912ca8712a75c0a214d365de331fc`

When I run phpactor status, I get roughly the same error:
```
In Process.php line 355:
  Unable to launch a new process.
status
```

I'm installing via script, I copied the installation instructions from the doc site I believe. The script is here: https://github.com/joshrainwater/dotfiles/blob/main/scripts/install-php-environment.sh. I have definitely confirmed the exact same installation process works on php8.2 but not with php8.3.

**Comment by dantleech** [comment]
can confirm with the latest PHAR on PHP 8.3 - and when compiling the PHAR on `master` :thinking: works fine on 8.2 with the PHAR and when not using the PHAR

**Comment by dantleech** [comment]
Working on a fix here https://github.com/phpactor/phpactor/pull/2536

**Comment by joshrainwater** [comment]
I don't actually know how to build the phar... but can confirm it works fine cloning and running the bin in the repo
