### ISSUE TITLE
wording: rename "add missing assignments" to "add missing properties"

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#256]
I can contribute it if you are ok with that change. I think "add missing assignments" is misleading since what you actually do is adding missing properties based on assignments.

**Comment by dantleech** [comment]
Yeah - it adds properties which are assigned but not present. I suppose it makes more sense as `add missing properties`

**Comment by dantleech** [comment]
How else could properties be missing?

**Comment by greg0ire** [comment]
If they are called and supposed to be public, but eww
