### ISSUE TITLE
Bump `symfony/yaml` dependency from 5.x to 6 or later

### ISSUE THREAD

**Issue by Manueljlin** [phpactor/phpactor#2571]
Currently conflicts with laravel/sail on Laravel 10--which requires `^6.0|^7.0`--when adding as a dev project dependency.
Latest Phpactor targets PHP 8.1+ anyways, so it should be good?

**Comment by dantleech** [comment]
Adding ohpactor as a dev dependency is not supported, you should install it as a standalone tool :)

**Comment by dantleech** [comment]
Please feel free to make a PR to bump these dependencies, but closing this issue for now as we don't support installation as a composer dependency (which isn't explicitly documented)
