### ISSUE TITLE
Cannot rename property or method if its definition contains any attribute

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#2577]
```php
<?php

namespace Arctgx\PhpactorAttrCompletion;

use Override;

class Details
{
    #[Override]
    private $foo;

    #[ReturnTypeWillChange]
    public function getFoo()
    {
        return $this->foo;
    }
}
```
Trying to rename `$foo` in the above example I get `LSP Message (phpactor) Could not find corresponding reference to member name "foo" in document "file:///home/arctgx/dev/arctgx/php/phpactor-attr-completion/src/Details.php" at offset 84`. The same exception I get when trying to rename method with attribute. 

https://github.com/phpactor/phpactor/blob/5da647cd525f04c41f2ded6678f44844c58114c8/lib/Rename/Adapter/ReferenceFinder/AbstractReferenceRenamer.php#L81-L89

The example is simplified as much as possible. In practice it was ORM column attribute.

**Comment by dantleech** [comment]
p;resumably that code is using `getFullStartPosition` instead of `StarPosition` somewhere, it should be easy enough to add a test and a fix:

https://github.com/phpactor/phpactor/blob/f504fe3320d0d922491da2ca8a7fc66cb96b14cd/lib/Rename/Tests/Integration/Adapter/ReferenceFinder/MemberRenamerTest.php#L50

happy to help with that.

**Comment by przepompownia** [comment]
![image](https://github.com/phpactor/phpactor/assets/11404453/3db4e494-0fcb-411d-b819-2dfb39d99f64)

At the moment I see using `getStartPosition()` with `method declaration` data set and modified example: 
```php
<?php

class ClassOne
{
    #[ReturnTypeWillChange]
    public function foobar(): string
    {
        return 'foobar';
    }
}
```
With `gg0` `28go` in nvim the cursor lands before `#`. 

My first usage of `NodeUtil::dump`:
![image](https://github.com/phpactor/phpactor/assets/11404453/2cf9e0de-a5c5-46e7-ae77-c19804211831)

I don't see any useful explicit **node** data at the moment.

**Comment by mamazu** [comment]
Does the AttributeGroup have an end maybe?

**Comment by przepompownia** [comment]
yeah, or maybe we have to (more explicity) find `TokenKind::FunctionKeyword` (`134`) followed by `TokenKind::Name`?
```
dap> [...$this->node()->getDescendantNodesAndTokens()]
array(23)
  0: Microsoft\PhpParser\Node\AttributeGroup
...
  8: Microsoft\PhpParser\Token
    fullStart: 62
    kind: 134
    length: 9
    start: 63
  9: Microsoft\PhpParser\Token
    fullStart: 71
    kind: 2
    length: 7
    start: 72
```
I reported the case for class method. We probably have to check if other attributed nodes have such issue too.

**Comment by przepompownia** [comment]
Probably we also have to check how much any approach affects performance.

**Comment by przepompownia** [comment]
Let's try #2627 (at the moment with no separate test for with and without attributes).
