### ISSUE TITLE
Return type added as `string|bool` instead of `string|false`

### ISSUE THREAD

**Issue by calebdw** [phpactor/phpactor#2588]
Hello!

There are several php functions that return `false` if an error occurs (e.g., `date()`). Given that `false` is now a first class type I would expect phpactor to automatically set the return type for a function to be `string|false` instead of `string|bool`:

```php
function test()
{
    return date('Y-m-d', 1);
}
```

Thanks!

**Comment by dantleech** [comment]
This is due to the phpstorm stubs, it would be good to replace those with better stubs (e.g. the ones Psalm/PHPStan uses) for better types all round.

**Comment by calebdw** [comment]
So the `vendor/jetbrains/phpstorm-stubs/date/date.php` stub (the one that opens when I jump to definition has:

```php
/**
 * ...
 * @param int|null $timestamp [optional] Default value: time(). The optional timestamp parameter is an integer Unix timestamp
 * that defaults to the current local time if a timestamp is not given.
 * @return string|false a formatted date string. If a non-numeric value is used for
 * timestamp, false is returned and an
 * E_WARNING level error is emitted.
 */
#[Pure(true)]
#[LanguageLevelTypeAware(["8.0" => "string"], default: "string|false")]
function date(string $format, ?int $timestamp) {}
```

The types appear to be correct?

**Comment by dantleech** [comment]
Hrmph, then it's a "bug"

**Comment by dantleech** [comment]
For some reason we were downgrading the return types and _not_ downgrading them didn't break any tests, so, let's see if anything breaks... :) note that this will only work if the Phpactor thinks the project is on PHP 8.2

**Comment by calebdw** [comment]
Awesome thanks!
