### ISSUE TITLE
Counter of indexer hangs on Phpactor project

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#2607]
![image](https://github.com/phpactor/phpactor/assets/11404453/c61ff601-ade0-4fbf-a495-5f7028cb7899)

```
   Error  18:39:18 .message LSP Message (phpactor) Error in service "indexer" "Phpactor\Extension\LanguageServerIndexer\Handler\IndexerHandler:Phpactor\LanguageServer\Core\Service\{closure}": The percentage must be an integer comprised between 0 and 100.
```

After restarting Phpactor tries to build the whole index again and hangs at the similar percent. At the moment I didn't check what happens in details. 

The regression comes with the recent two commits (PHAR indexing).

**Comment by dantleech** [comment]
should be fixed now, thanks for raising.

**Comment by przepompownia** [comment]
Confirmed on Phpactor: indexing can be completed again.
