### ISSUE TITLE
Installing phpactor with mason in neovim

### ISSUE THREAD

**Issue by julj** [phpactor/phpactor#2621]
I am having trouble installing phpactor with mason in neovim. My web app is running in a Docker, so I created scripts to access php and composer from the host:

~/.bin/composer
```
#!/bin/bash
docker exec mycontainer composer "$@"
```

~/.bin/php
```
#!/bin/bash
docker exec mycontainer php "$@"
```

I added those to the neovim PATH with:

`vim.env.PATH = vim.env.PATH .. ':/home/jricard/.bin'`

and `checkhealth mason` does find both. I left the default config for phpactor, except symfony.enabled = true .My neovim config looks like:

```
{
	"williamboman/mason-lspconfig.nvim",
	config = function()
		require("mason-lspconfig").setup({
			ensure_installed = { "lua_ls", "phpactor" },
		})
	end,
},
{
	"neovim/nvim-lspconfig",
	config = function()
		local lspconfig = require("lspconfig")
		lspconfig.lua_ls.setup({})
		lspconfig.phpactor.setup({
			init_options = {
				["symfony.enabled"] = true,
			},
		})
		vim.keymap.set("n", "K", vim.lsp.buf.hover, {})
		vim.keymap.set("n", "gd", vim.lsp.buf.definition, {})
		vim.keymap.set("n", "<space>ca", vim.lsp.buf.code_action, {})
	end,
}
```
Now, when I run mason install I get the following error:

```
  Failed
    ◍ phpactor
      ▼ Displaying full log
        Cloning git repository "https://github.com/phpactor/phpactor.git"…
        Cloning into '.'...
        From https://github.com/phpactor/phpactor
         * tag               2024.03.09.0 -> FETCH_HEAD
        + composer install --no-interaction --no-dev --optimize-autoloader --classmap-authoritative
        Installing dependencies from lock file
        Verifying lock file contents can be installed on current platform.
        Nothing to install, update or remove
        Generating optimized autoload files
        83 packages you are using are looking for funding.
        Use the `composer fund` command to find out more!

        Run composer recipes at any time to see the status of your Symfony recipes.

        Executing script cache:clear [KO]
         [KO]
        Script cache:clear returned with error code 255
        !!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#89
        !!    #message: """
        !!      Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle".\n
        !!      Did you forget a "use" statement for another namespace?
        !!      """
        !!    #code: 0
        !!    #file: "./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php"
        !!    #line: 126
        !!    trace: {
        !!      ./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:126 { …}
        !!      ./vendor/symfony/http-kernel/Kernel.php:331 { …}
        !!      ./vendor/symfony/http-kernel/Kernel.php:708 { …}
        !!      ./vendor/symfony/http-kernel/Kernel.php:122 { …}
        !!      ./vendor/symfony/framework-bundle/Console/Application.php:148 { …}
        !!      ./vendor/symfony/framework-bundle/Console/Application.php:69 { …}
        !!      ./vendor/symfony/console/Application.php:168 { …}
        !!      ./bin/console:43 {
        !!        › $application = new Application($kernel);
        !!        › $application->run($input);
        !!        › 
        !!        arguments: {
        !!          $input: Symfony\Component\Console\Input\ArgvInput {#2 …}
        !!        }
        !!      }
        !!    }
        !!  }
        !!  2024-03-28T13:55:04+00:00 [critical] Uncaught Error: Class "Symfony\Bundle\WebProfilerBundle\WebProfilerBundle" not found
        !!  
        Script @auto-scripts was called via post-install-cmd
        spawn: bash failed with exit code 255 and signal 0. 
```

WebProfilerBundle is in my `composer.json`'s `require-dev`, and because the install process runs 
`composer install --no-interaction --no-dev --optimize-autoloader --classmap-authoritative` (with the --no-dev option),
it removes WebProfilerBundle.

Does phpactor requires WebProfilerBundle?

How can I configure the mason install to not use `--no-dev` option ?

**Comment by mamazu** [comment]
Aliasing your composer for this project is not the best idea. Because now it's trying to run symfony scripts in the composer directory and this is not going to work.

You don't need to run phpactor inside the same container you can run this on your host machine.

**Comment by julj** [comment]
Ok. So that means that I need to install php and composer on my host machine ?

**Comment by cristianradulescu** [comment]
@julj more context on the error - the fact that Symfony's cache clear command is triggered on Composer install means that you are running Composer install for your project, not for Phpactor. This is most likely due to the container's directory mapping, the work dir is set for the root of the Symfony project and all Composer commands are executed in that directory.

**Comment by julj** [comment]
@mamazu @cristianradulescu thanks for your feedback. I installed php and composer on my host, and the mason's phpactor runs flawlessly. But I would like to avoid having two php and composer install (one on my host and one in my container). Is there any way I can use the composer installed in my container to install phpactor ?

**Comment by dantleech** [comment]
closing this as I don't support running Phpactor in a container, running on the host is fine, feel free to open a [discussion](https://github.com/phpactor/phpactor/discussions)
