### ISSUE TITLE
Unused imports are not "highlighted" with vscode

### ISSUE THREAD

**Issue by rtorralba** [phpactor/phpactor#2640]
I supose maybe is related with vscode configuration but when som imports (use) are not using, vscode don't show any difference like show it in gray.

I searched in issues and found that is implemented bau seems tht teh screenshot is using nvim.

Thanks in advance.

**Comment by mamazu** [comment]
This should be fixed in the current master branch. In the latest release phpactor doesn't yet provide the correct tags on the diagnostic.

**Comment by rtorralba** [comment]
@mamazu can i use master branch (update) with vscode extension?

**Comment by mamazu** [comment]
Sorry for the late reply. This feature should be in the master now. If you could try it again and close the issue that would be great.

**Comment by dantleech** [comment]
Assuming fixed...
