### ISSUE TITLE
Feature request: Typed class constants in PHP 8.3

### ISSUE THREAD

**Issue by madflow** [phpactor/phpactor#2653]
* Feature request: Typed class constants in PHP 8.3
* https://php.watch/versions/8.3/typed-constants
* PHP 8.3

```php
<?php

class Sth
{
    public const array TEST = [];

}

$a = Sth::TEST;
```

```
Constant "TEST" does not exist on class "Sth" phpactor [9, 11]
```

**Comment by mamazu** [comment]
The code in phpactor works as intended. The problem is the parser doesn't correctly recognize the name as it assumes the first token after `const` is the name. So `Sth::array` should be the property it finds.

But a fix is on the way.

**Comment by przepompownia** [comment]
https://github.com/phpactor/phpactor/issues/2496

**Comment by dantleech** [comment]
should be fixewd as of #2736
