### ISSUE TITLE
This studpid language server doesnt work in LazyVim,

### ISSUE THREAD

**Issue by muneebusmani** [phpactor/phpactor#2656]
Why the heck is every other plugin in nvim not working every now and then? i wanted to do some php, installed this lsp for php, and it doesnt show completions even though LazyVim has it preconfigured by the way it should be, 
Just to code php, i have to go through all of this bs because someone lacks to document there code so i have to ask here in github and wait for ages for someone's reply, i've never had issues with doing something in javascript ecosystem in nvim but whenever i try to do any other language, this kind bs happens

**Comment by dantleech** [comment]
Maybe try creating the issue again without the emotion

**Comment by mamazu** [comment]
The problem is that the language server is found but doesn't attach to the php buffer (which from a quick search, seems to be a LazyVim issue as the client attach is running too late) But I have no experience with LazyVim so, I don't know how to configure it.
