### ISSUE TITLE
call site variance not supported `Collection<covariant Foobar>`

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2664]
parser bails out in this case and ignores the `@param`:

```
    /**
     * @param DataSourceExecutor<covariant DataSource> $dataSource
     */
    public function __construct(
        private DataSourceExecutor $dataSource,
    ) {
    }

```

**Comment by calebdw** [comment]
Note that `contravariance` can also be given: https://phpstan.org/blog/guide-to-call-site-generic-variance#call-site-contravariance

**Comment by dantleech** [comment]
fwiw also `bivariance` and `invariant`...
