### ISSUE TITLE
`%project_root%` should be allowed in `indexer.stub_paths` according to docs

### ISSUE THREAD

**Issue by montchr** [phpactor/phpactor#2665]
The documentation for configuration usage says:

> Configured file paths can make use of some special tokens, for example `%cache%/foobar` will expand to `/home/user/.cache/phpactor/foobar`

I have not seen any mention of this usage being disallowed for the values in `indexer.stub_paths`.  And yet:

```console
$ phpactor index:build --reset

In TextDocumentUri.php line 57:

  Filesystem path must be absolute, got "%project_root%/vendor/php-stubs/acf-p
  ro-stubs"
```

This is really unfortunate because it means I cannot share my configuration with others without them needing to manually replace paths.  If it were possible to merge a project-specific and local-only configuration (e.g. `.phpactor.local.json`) into the existing lookup paths with the highest precedence, that could provide a workaround, however that is not currently possible (according to the docs).

**Comment by dantleech** [comment]
hi - if you'd like to make a PR you could change the [IndexerExtension](https://github.com/phpactor/phpactor/blob/ac99b4d8831eb5a249a2b1788cbb5b64a4a1c61c/lib/Indexer/Extension/IndexerExtension.php#L229) to map the `$resolver` over the "stub paths", we already use the resolver in that function to resolve rthe `PARAM_INDEX_PATH`

**Comment by montchr** [comment]
Thanks, looks straightforward enough.  I'll give it a shot when I can.
