### ISSUE TITLE
LSP "Rename" anything doesn't work

### ISSUE THREAD

**Issue by phpwutz** [phpactor/phpactor#2671]
I tried using normalvim and lunarvim, but  "rename" simply doesn't seem to do anything.
The functionality works flawless with any other language i tried (ts, js, rust, c), so I wonder why it's not possible in PHP?
I am willing to contribute, but have not developed on LSP yet, so a rough idea on what would be needed would be much appreciated!
cheers

**Comment by dantleech** [comment]
It _should_ work with pretty much anything...

**Comment by phpwutz** [comment]
hi, i updated my arch again today and "rename" seems to work in normalvim, but not lunarvim. so the problem doesn't seem to be in phpactor itself. i think this can be closed. thanks for your consideration, it's very much appreciated!
