### ISSUE TITLE
Initialised properties don't appear in LSP document symbols

### ISSUE THREAD

**Issue by Geraint** [phpactor/phpactor#2677]
Given this class:

```php
<?php

namespace App;

class Foo
{
    private string $uninitialised;

    private string $initialised = '';
}
```

.. I see these document symbols (using [Trouble](https://github.com/folke/trouble.nvim) in Neovim):

```
  Document Symbols  2 
   └╴  src/App/Foo.php  2 
     └╴  Foo class Foo [5, 7]
       └╴  uninitialised private string $uninitialised; [7, 20]
```

Note that the property `$initialised` doesn't appear in the list of document symbols.

**Comment by mamazu** [comment]
Hey thanks for reporting the issue. I have attached a PR fix. It fixes the problem when using telescope could you check if the properties now also show up with trouble?

**Comment by Geraint** [comment]
> could you check if the properties now also show up with trouble?

Yes - it looks fixed in Trouble, too:

```
  Document Symbols  3 
   └╴  src/App/Foo.php  3 
     └╴  Foo class Foo [5, 7]
       ├╴  uninitialised private string $uninitialised; [7, 20]
       └╴  initialised private string $initialised = ''; [9, 20]
```

Many thanks for fixing this.
