### ISSUE TITLE
Auto completion doesn't suggest the basics on the first try

### ISSUE THREAD

**Issue by saeedvaziry** [phpactor/phpactor#2689]
Hey here,
I am trying to set up phpactor with monaco-editor but having some issues regarding the auto-completions.
![CleanShot 2024-07-08 at 21 04 52](https://github.com/phpactor/phpactor/assets/61919774/51433d11-bf7e-47ff-9b74-6b6ba9575820)
If you see from the video, it doesn't suggest more auto completions when the file is empty. but as soon as I enter something, even a character like `1` or the first line, it starts working fine. and then again if I make the file empty, it doesn't suggest more.

**Comment by dantleech** [comment]
fwiw I get the same "issue" although it's the first time I've noticed it

**Comment by saeedvaziry** [comment]
I would like to contribute but no idea where to start. Do you have any clue where this is happening?

**Comment by dantleech** [comment]
it's a troublesome area but maybe checking for the `SourceFileNode` in addition to the others here: https://github.com/phpactor/phpactor/blob/252b48aacda2939a8224b027cab5d468e3d51639/lib/Completion/Bridge/TolerantParser/CompletionContext.php#L61 and adding a test here: https://github.com/phpactor/phpactor/blob/252b48aacda2939a8224b027cab5d468e3d51639/lib/Completion/Tests/Unit/Bridge/TolerantParser/CompletionContextTest.php#L17

**Comment by saeedvaziry** [comment]
@dantleech it looks like it is an instance of `InlineHtml` and returns `false` here

https://github.com/phpactor/phpactor/blob/252b48aacda2939a8224b027cab5d468e3d51639/lib/Completion/Bridge/TolerantParser/CompletionContext.php#L56-L58

Any idea of solving it?

**Comment by saeedvaziry** [comment]
Looks like started after [this](https://github.com/phpactor/phpactor/pull/2313) PR

**Comment by dantleech** [comment]
Looks like we can be more strict to fix the original issue:

```diff
diff --git a/lib/Completion/Bridge/TolerantParser/CompletionContext.php b/lib/Completion/Bridge/TolerantParser/CompletionContext.php
index 7fa39df3..d3de79fa 100644
--- a/lib/Completion/Bridge/TolerantParser/CompletionContext.php
+++ b/lib/Completion/Bridge/TolerantParser/CompletionContext.php
@@ -59,7 +59,11 @@ class CompletionContext
         $previous = NodeUtil::previousSibling($node->parent);
 
         if ($previous instanceof InlineHtml) {
-            return false;
+            $phpTag = $previous->scriptSectionStartTag?->getText($previous->getFileContents());
+
+            if ($phpTag === '<?' && $node->getStartPosition() === $previous->getEndPosition()) {
+                return false;
+            }
         }
 
         return
diff --git a/lib/Completion/Tests/Integration/Bridge/TolerantParser/ReferenceFinder/ExpressionNameCompletorTest.php b/lib/Completion/Tests/Integration/Bridge/TolerantParser/ReferenceFinder/ExpressionNameCompletorTest.php
index fe495f88..29ddbb10 100644
--- a/lib/Completion/Tests/Integration/Bridge/TolerantParser/ReferenceFinder/ExpressionNameCompletorTest.php
+++ b/lib/Completion/Tests/Integration/Bridge/TolerantParser/ReferenceFinder/ExpressionNameCompletorTest.php
@@ -283,6 +283,16 @@ class ExpressionNameCompletorTest extends IntegrationTestCase
                 self::assertCount(0, $suggestions);
             }
         ];
+        yield 'after php tag' => [
+            [
+                NameSearchResult::create('class', 'Foobar'),
+                NameSearchResult::create('class', 'Class'),
+            ],
+            '<?php F<>',
+            function (Suggestions $suggestions): void {
+                self::assertCount(1, $suggestions);
+            }
+        ];
         yield 'attribute parameter value outside class' => [
             [
                 NameSearchResult::create('class', 'Xxyz'),
```

feel free to create a PR or I'll maybe do it later :)

**Comment by saeedvaziry** [comment]
alright, you already solved the issue. going to copy and paste 😁

**Comment by dantleech** [comment]
I appreciate the effort, while I can quickly cobble together solutions, it can sometimes be a rabbithole so every little helps :)
