### ISSUE TITLE
Zed.dev editor

### ISSUE THREAD

**Issue by xtrasmal** [phpactor/phpactor#2691]
It is a great editor. Would love phpactor support for it 😍

**Comment by dantleech** [comment]
It's an LSP client isn' it? Is it unsupported in any specific way?

**Comment by xtrasmal** [comment]
Yes, it would be straight forward. It needs proper bootstrapping. 
Right now they have a standard extension for PHP, supporting grammar from treesitter and then loading Intelephense.

I've tried copying and pasting to get first class support for phpactor. But my Rust is rusty and haven't had any experience integrating LSP's in editors yet. 
Here is my go at it. Code actions and refactors do not work yet.

https://github.com/xtrasmal/zed-lsp-phpactor

Yesterday I had a small success while installing my phpactor extension next to intelephense.

![image](https://github.com/user-attachments/assets/d622e402-907b-4ffd-9310-997e14554074)

![image](https://github.com/user-attachments/assets/c4aca44f-ebe0-4515-8c1c-e8f9fb4274ce)

![image](https://github.com/user-attachments/assets/a2eb489b-e1e9-44cf-8d8a-ddbbf19e424d)

But after a restart of the editor and some config tinkering I couldn't reproduce it. 

Zed is great. It is like when the sublime text came on the market. A sudden paradigm change. No more electron / chromium bloatware. 
It is being developed by folks who worked at Atom and other editors in the past. It would be great if PHP support would be coming from Phpactor and not intelephense(feels uninspiring, under documented and surely under featured).

**Comment by dantleech** [comment]
Interesting, might check it out!

**Comment by xtrasmal** [comment]
@dantleech https://github.com/xtrasmal/zed-lsp-phpactor
Muhahaha :D 
This is glorious. Your amazing LSP is running in Zed :D
Thanks for phpactor. It is amazing.

**Comment by dantleech** [comment]
Fantastic! We can update the docs

**Comment by maxdeviant** [comment]
We now have Phpactor support in the Zed PHP extension: https://github.com/zed-industries/zed/pull/14604.

**Comment by xtrasmal** [comment]
@maxdeviant that is great news. 
I just need to add that you folks are a bunch of butt-cheecks, for not communicating. I've been struggling whole week, asking for support and shit. 
Then on the day I finally get this shit done...you suddenly add in phpactor support. Would have saved me my last hair on my head.
Nevertheless, great news for the world. Phpactor is 👑

**Comment by xtrasmal** [comment]
@dantleech Thanks again for Phpactor. You should really try Zed out now 😄

I have "CMD-." as a keymap for loading whatever phpactor can fix using the code actions. 
And "Ctrl-space" for changing public to private etc. 
The flow is pretty sweet.

**Comment by xtrasmal** [comment]
@dantleech yes agreed. Although "butt-cheeks" was meant kinda cute
