### ISSUE TITLE
Autoimporting above declare strict types

### ISSUE THREAD

**Issue by calebdw** [phpactor/phpactor#2698]
Hello!

When I'm using `declare(strict_types=1);` in a file, phpactor will import classes above it which is a fatal PHP error:

![image](https://github.com/user-attachments/assets/b6e9e5d6-644b-4aca-af2a-f597be6323d1)

It should be:

![image](https://github.com/user-attachments/assets/de1b782a-5f1e-4ef2-97b2-4da91c2949a0)

Thanks!

**Comment by dantleech** [comment]
should be fixed!

**Comment by calebdw** [comment]
Awesome, thanks!!
