### ISSUE TITLE
ClassNew: There are no class name candidates when creating first file

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#270]
Steps to reproduce:

1. Composerify project and define an autoload rule for `src`, but **do not** `mkdir src`
2. `:e src/MyClass.php`
3. `:call phpactor#ClassNew()`

Expected result: a new class
Actual result: Error from `Phpactor: There are no class name candidates`

Workaround: `mkdir src`

**Comment by dantleech** [comment]
Fixed in `class-to-file` by using webmozart `Path::canonicalize` instead of `realpath`
