### ISSUE TITLE
Conditional `@return` types

### ISSUE THREAD

**Issue by axelrindle** [phpactor/phpactor#2700]
Laravel 11 introduced "conditional return types" which were specified in [PhpStan v1.6.0](https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types), for example:

```php
/**
 * Return a new response from the application.
 *
 * @param  \Illuminate\Contracts\View\View|string|array|null  $content
 * @param  int  $status
 * @param  array  $headers
 * @return ($content is null ? \Illuminate\Contracts\Routing\ResponseFactory : \Illuminate\Http\Response)
 */
function response($content = null, $status = 200, array $headers = [])
{
    $factory = app(ResponseFactory::class);

    if (func_num_args() === 0) {
        return $factory;
    }

    return $factory->make($content ?? '', $status, $headers);
}
```

When I do the following call:

```php
return response()->json(['message' => 'Password has been reset. You\'ve been logged out.']);
```

Note that the `$content` parameter defaults to `null`.

VSCode tells me: **Method "json" does not exist on class "Illuminate\Http\Response" (phpactor)**

*However*, when I *explicitly* specify `$content` as `null`, the correct type is returned:

```php
return response(content: null)->json(['message' => 'Password has been reset. You\'ve been logged out.']);
```

The error is gone. But I'd like to not explicitly do that.

**Comment by dantleech** [comment]
Should be fixed in https://github.com/phpactor/phpactor/pull/2704

**Comment by axelrindle** [comment]
Yes, awesome! Thank you.
