### ISSUE TITLE
Unable to find references RPC

### ISSUE THREAD

**Issue by joel3453245** [phpactor/phpactor#2726]
My aim is to use phpactor's "find all references" feature on a variable. 

I have attempted to do this using the RPC protocol, I have supplied:

- The source code of the file that the variable is in
- The offset of the variable i wish to find references to
- Although not specified in the documentation, I have supplied a path to the file after being prompted by an error to do so

I am supplying my input through stdin, and prior to making the RPC request I have run the phpactor index:clean and index:build commands, giving the directory as the base path of my project directory. 

After making the request for the references action, the below output is returned - indicating no references can be found:

```
{"version":"1.0.0","action":"error","parameters":{"message":"Cannot find references for symbol type \"variable\"","details":"0: Cannot find references for symbol type \"variable\"\n#0 phar:\/\/\/usr\/bin\/phpactor\/lib\/Extension\/ClassMover\/Rpc\/ReferencesHandler.php(236): Phpactor\\Extension\\ClassMover\\Rpc\\ReferencesHandler->doPerformFindOrReplaceReferences()\n#1 phar:\/\/\/usr\/bin\/phpactor\/lib\/Extension\/ClassMover\/Rpc\/ReferencesHandler.php(121): Phpactor\\Extension\\ClassMover\\Rpc\\ReferencesHandler->performFindOrReplaceReferences()\n#2 phar:\/\/\/usr\/bin\/phpactor\/lib\/Extension\/ClassMover\/Rpc\/ReferencesHandler.php(104): Phpactor\\Extension\\ClassMover\\Rpc\\ReferencesHandler->findReferences()\n#3 phar:\/\/\/usr\/bin\/phpactor\/lib\/Extension\/Rpc\/RequestHandler\/RequestHandler.php(27): Phpactor\\Extension\\ClassMover\\Rpc\\ReferencesHandler->handle()\n#4 phar:\/\/\/usr\/bin\/phpactor\/lib\/Extension\/Rpc\/RequestHandler\/ExceptionCatchingHandler.php(20): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle()\n#5 phar:\/\/\/usr\/bin\/phpactor\/lib\/Extension\/Rpc\/RequestHandler\/LoggingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle()\n#6 phar:\/\/\/usr\/bin\/phpactor\/lib\/Extension\/Rpc\/Command\/RpcCommand.php(65): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle()\n#7 phar:\/\/\/usr\/bin\/phpactor\/lib\/Extension\/Rpc\/Command\/RpcCommand.php(45): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest()\n#8 phar:\/\/\/usr\/bin\/phpactor\/vendor\/symfony\/console\/Command\/Command.php(298): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute()\n#9 phar:\/\/\/usr\/bin\/phpactor\/vendor\/symfony\/console\/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#10 phar:\/\/\/usr\/bin\/phpactor\/vendor\/symfony\/console\/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()\n#11 phar:\/\/\/usr\/bin\/phpactor\/lib\/Application.php(48): Symfony\\Component\\Console\\Application->doRun()\n#12 phar:\/\/\/usr\/bin\/phpactor\/vendor\/symfony\/console\/Application.php(171): Phpactor\\Application->doRun()\n#13 phar:\/\/\/usr\/bin\/phpactor\/bin\/phpactor(45): Symfony\\Component\\Console\\Application->run()\n#14 \/usr\/bin\/phpactor(15): require('...')\n#15 {main}"}}
Error Message: Cannot find references for symbol type "variable"
Details:
0: Cannot find references for symbol type "variable"
#0 phar:///usr/bin/phpactor/lib/Extension/ClassMover/Rpc/ReferencesHandler.php(236): Phpactor\Extension\ClassMover\Rpc\ReferencesHandler->doPerformFindOrReplaceReferences()
#1 phar:///usr/bin/phpactor/lib/Extension/ClassMover/Rpc/ReferencesHandler.php(121): Phpactor\Extension\ClassMover\Rpc\ReferencesHandler->performFindOrReplaceReferences()
#2 phar:///usr/bin/phpactor/lib/Extension/ClassMover/Rpc/ReferencesHandler.php(104): Phpactor\Extension\ClassMover\Rpc\ReferencesHandler->findReferences()
#3 phar:///usr/bin/phpactor/lib/Extension/Rpc/RequestHandler/RequestHandler.php(27): Phpactor\Extension\ClassMover\Rpc\ReferencesHandler->handle()
#4 phar:///usr/bin/phpactor/lib/Extension/Rpc/RequestHandler/ExceptionCatchingHandler.php(20): Phpactor\Extension\Rpc\RequestHandler\RequestHandler->handle()
#5 phar:///usr/bin/phpactor/lib/Extension/Rpc/RequestHandler/LoggingHandler.php(25): Phpactor\Extension\Rpc\RequestHandler\ExceptionCatchingHandler->handle()
#6 phar:///usr/bin/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(65): Phpactor\Extension\Rpc\RequestHandler\LoggingHandler->handle()
#7 phar:///usr/bin/phpactor/lib/Extension/Rpc/Command/RpcCommand.php(45): Phpactor\Extension\Rpc\Command\RpcCommand->processRequest()
#8 phar:///usr/bin/phpactor/vendor/symfony/console/Command/Command.php(298): Phpactor\Extension\Rpc\Command\RpcCommand->execute()
#9 phar:///usr/bin/phpactor/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#10 phar:///usr/bin/phpactor/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#11 phar:///usr/bin/phpactor/lib/Application.php(48): Symfony\Component\Console\Application->doRun()
#12 phar:///usr/bin/phpactor/vendor/symfony/console/Application.php(171): Phpactor\Application->doRun()
#13 phar:///usr/bin/phpactor/bin/phpactor(45): Symfony\Component\Console\Application->run()
#14 /usr/bin/phpactor(15): require('...')
#15 {main}

```
If it is helpful for debugging, I have also included the output of the command to the "offset_info" RPC request for the same source code and offset. 
  
    "version": "1.0.0",
    "action": "information",
    "parameters": {
        "information": {
            "symbol": "command",
            "symbol_type": "variable",
            "start": 3340,
            "end": 3348,
            "type": "<missing>",
            "container_type": "<missing>",
            "value": "NULL",
            "offset": 3340,
            "type_path": null,
            "frame": {
                "locals": {
                    "1960": "this = (AUS\\GeoRedirect\\Service\\IpCountryLocator\\MmdbFile) NULL",
                    "1995": "output = (?Symfony\\Component\\Console\\Output\\OutputInterface) NULL",
                    "2197": "output = (?Symfony\\Component\\Console\\Output\\OutputInterface) NULL",
                    "2207": "databaseFile = (string) NULL",
                    "2261": "tarFile = (<missing>) NULL",
                    "2620": "tarFile = (<missing>) NULL",
                    "2630": "url = (<missing>) NULL",
                    "3131": "command = (<missing>) NULL"
                },
                "properties": {
                    "412": "reader = (MaxMind\\Db\\Reader) NULL",
                    "478": "client = (GuzzleHttp\\Client) NULL",
                    "519": "maxmindLicenseKey = (string) NULL"

Any insight on this would be much appreciated, or suggestions as to how I could better achieve my aim (alternative to RPC?). Essentially, I just want to give my static code to the LSP with a target variable, and understand where that variable has been referenced. phpactor is indexing my entire project directory, I am assuming the references feature looks for all references in the indexed project, not just the supplied source code - or am I misunderstanding something?

Much appreciated.

**Comment by dantleech** [comment]
The RPC protocol is basically no longer supported. This features works with LSP

**Comment by joel3453245** [comment]
Thank you very much. That clarifies it for me.
