### ISSUE TITLE
Unable to disable "Class name should probably be..."

### ISSUE THREAD

**Issue by 3ynm** [phpactor/phpactor#2728]
In my project, migration files include date prefixes, causing them not to exactly match the class names. This triggers a warning: `Class name should probably be....`

I do not intend to change the class names to remove the prefixes, so I'd like an option to disable this warning. However, it seems there is no configuration available to do so.

If disabling the warning is not possible, I would prefer that the diagnostics to only highlight the specific offending line, rather than marking the entire class as problematic, as seen on the following image.

![annoying_diagnostics](https://github.com/user-attachments/assets/c2cfebe0-f8c8-4dbf-9828-3f7529cb8694)

**Comment by mamazu** [comment]
I mean there is an option to disable the diagnostic provider for all transformer based diagnostics, but this will also disable way more than you want.
```json
"language_server.diagnostic_providers": [
   "code-action"
   "create-class",
   "implement-contracts"
],
```
as far as I know there is no way to disable this individual one.

**Comment by 3ynm** [comment]
I think the diagnostic would be fine if it didn't mark the whole class as offending

**Comment by dantleech** [comment]
you should now be able to disable any diagnostic by it's displayed code in the LSP as of #2781

**Comment by dantleech** [comment]
fwiw I also updated the diagnostic to only highlight the name: https://github.com/phpactor/phpactor/pull/2783?new_mergebox=false
