### ISSUE TITLE
[CT] Generate / Update class constructor based on new class

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#273]
e.g.

```
$foobar = new ClassBar('hello');
```

1. When generating a new class (as per current logic) the constructor should be completed:

```
class ClassBar
{
    private $hello;

    public function __construct(string $hello)
    {
        $this->hello = $hello;
    }
}
```

2. If the class already exists, then the constructor should be updated.

**Comment by mamazu** [comment]
Which command would invoke the creation from token?

**Comment by dantleech** [comment]
Think this should've been closed. Generate constructor was implemented
