### ISSUE TITLE
FR: support project roots that are subdirectories within git repos

### ISSUE THREAD

**Issue by claytonrcarter** [phpactor/phpactor#2738]
Hi, I'm a little new to phpactor, and I apologize if I'm misunderstanding something or reporting this wrong. 

I primarily work on 1-2 PHP projects that are contained in a monorepo. In other words, I have something like this:
- /.git
- /project-a/composer.json
- /project-b/composer.json

Within the `project-a` directory, I just ran `phpactor.phar status` and got this output (trimmed/redacted):
```
Version: 2024.06.30.0
Filesystems: simple, composer
Working directory: /.../monorepo/project-a

...

  ✔ Composer detected - Phpactor could work faster without an index
  ✔ XDebug is disabled. XDebug has a negative effect on performance.
  ✘ Git not detected. Some operations which would have been better scoped to your project repository will now include vendor paths.
```

Note: "Git not detected", but this is a bogey because this is **definitely within a git repo** and **git works just fine in here**.

In poking around, I think the issue is at https://github.com/phpactor/phpactor/blob/master/lib/Filesystem/Adapter/Git/GitFilesystem.php#L25-L29, because – while that code is is correct that there is no `/project-a/.git` directory – as far as I can tell, none of the git commands in `GitFilesystem` need to be run from the project root: `git ls-files`, `git ls-files $file`, `git mv ...`, `git rm ...` all work fine from within subdirectories.

**Question**: is the limitation for the git fs to work only at the repo root important? Could this be relaxed?

I don't have time to thoroughly test this, but I suspect that something like this may accomplish the same "can we use `git`" check as the current code at https://github.com/phpactor/phpactor/blob/master/lib/Filesystem/Adapter/Git/GitFilesystem.php#L25-L29
```diff
-        if (false === file_exists($path->__toString().'/.git')) {
+        try {
+            $this->exec([
+                'rev-parse',
+                '--is-inside-work-tree',
+            ]);
+        } catch (InvalidArgumentException) {
             throw new NotSupported(
                 'The cwd does not seem to be a git repository root (could not find .git folder)'
             );
         }
```

**Question:** would you be open to a PR that implements this change? Or is there a reason for the current behavior/limitation?

Ref: https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---is-inside-work-tree  
Ref: https://stackoverflow.com/a/16925062

**Comment by dantleech** [comment]
Does this cause a bug? This is also somewhat of a legacy hangover. When working with the language server protocol it should be irrelevant - I think the "git fs" is used when f.e. moving files using the CLI - and I'm guessing it would fall back to just using the normal FS if git isn't supported?

At some point I need to aggressively prune the old functionality.

**Comment by mamazu** [comment]
The only question that needs to be clarified is: If we do this are all of the paths realtive to the git directory and wouldn't that mess with phpactor whose root path is somewehre different?
