### ISSUE TITLE
Show feedback when completion doesn't work.

### ISSUE THREAD

**Issue by lhyaax** [phpactor/phpactor#274]
Hi guy!
![default](https://user-images.githubusercontent.com/3948065/33307163-806f2c94-d450-11e7-9ee3-f885d82c7485.png)

I typed  $this->   ,  completion didn't  work.
![default](https://user-images.githubusercontent.com/3948065/33307253-d7048fb8-d450-11e7-949f-b7e79116f001.png)

**Comment by dantleech** [comment]
This is normally because of a syntax, or other error in the class (e.g. extending an invalid parent).

You can enable [logging](https://github.com/phpactor/phpactor#configuration) logging.enabled:true to find the exact problem:  `logging.enabled:true`

**Comment by dantleech** [comment]
But I do frequently have this issue, the main problem is that when using the omni-complete function, any completion error messages from Phpactor are hidden (same with the neovim plugin). First step would be to work on getting errors shown somehow.

**Comment by dantleech** [comment]
Updated the title of the issue to "show feedback". I think in anycase this would help with this issue.

**Comment by dantleech** [comment]
I think the best way to solve this is to add a `phpactor lint` command / RPC call which could be used by things like `ale`/`syntastic` to show all errors detected by Phpactor (which would include all errors which would stop completion from working).

See #120

**Comment by dantleech** [comment]
Omni-complete now shows an error message when something unexpected prevents the completion from working.
