### ISSUE TITLE
Nvim completion problem with argumnet of prototype function

### ISSUE THREAD

**Issue by klobastov** [phpactor/phpactor#2743]
Same problem https://github.com/hrsh7th/nvim-cmp/issues/645 
How disable function arguments in phpactor LSP after completion function?

ccls allow do that https://github.com/MaskRay/ccls/wiki/Customization#clientsnippetsupport 

Example: 
* write array_red...
* using autocomplete bind
* got `array_reduce($array, $callback)` 

Problem:
nvim-cmp allow navigate between function parameters. I cant apply lsp paramter and move to nex in case where first parameter like `$array` already defined in code before autocomplete

![phpactor1](https://github.com/user-attachments/assets/affd9925-c25d-4576-ba07-42296e5bfb81)
![image](https://github.com/user-attachments/assets/ab84b1dc-8cbe-4f2b-8cee-383bc8ce90ec)

**Comment by bart-jaskulski** [comment]
Phpactor ignores snippets if you tell it through LSP capabilities.

Regarding default config suggested by nvim-cmp, following adjustments would be required:

```lua
-- Set up lspconfig.
local cmp_capabilities = require('cmp_nvim_lsp').default_capabilities()

-- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
  -- override capabilites inside server configuration to disable it only for specific server
  capabilities = vim.tbl_deep_extend(
    "force",
    {},
    cmp_capabilities,
    {
      textDocument = {
        completion = {
          completionItem = {
            snippetSupport = true,
          }
        },
      }

    }
  )
}
```

**Comment by dantleech** [comment]
closing as assuming resolved above
