### ISSUE TITLE
Phpactor vs. Carbon

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#2755]
It takes about 20 seconds to jump to the `Carbon\Carbon` class..

**Comment by Dmitrev** [comment]
For me it's instant though. Could this just be an issue of project size perhaps?

**Comment by dantleech** [comment]
For my reference the latency is in analysing the code until the definition (i.e. to be able to resolve what the call expression type is) not the goto definition operation itself. For my project the latency isn't 20 seconds but it is reliably 0.6 seconds - while being instant on non-Carbon things - the latency coming from evaluating the carbon expression.

**Comment by dantleech** [comment]
problem was down to LSP requesting documentation for the Carbon class which involved ... rendering the documentation of each and every method, fix would be here when it's tidied up: https://github.com/phpactor/phpactor/pull/2768
