### ISSUE TITLE
Code actions not working in nvim lsp

### ISSUE THREAD

**Issue by BenceBakos** [phpactor/phpactor#2761]
Every other feature works, like the badass rename go to definition etc. I suspect problem is with capabilities.

Currently my config looks like this:
```lua

local CmpLsp = require('cmp_nvim_lsp')
local lspconfig = require('lspconfig')

-- Extend cmp capabilities
local lspDefaults = lspconfig.util.default_config

capabilities = CmpLsp.default_capabilities()

lspDefaults.capabilities = vim.tbl_deep_extend(
	'force',
	lspDefaults.capabilities,
	capabilities
)


lspconfig.phpactor.setup({
	init_options = {
		["language_server_phpstan.enabled"] = true,
		["language_server_psalm.enabled"] = true,
		["language_server_php_cs_fixer.enabled"] = true,
		["php_code_sniffer.enabled"] = true,
		["prophecy.enabled"] = true,
	},
	capabilities = capabilities
})

```

_I know this repo is not about neovim, but folks will come here for answer regardless. Couple example code here might also be usefull._

**Comment by dantleech** [comment]
The [documentation](https://phpactor.readthedocs.io/en/master/lsp/vim.html) could be improved.

I have this:

```
local lspconfig = require("lspconfig")
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)
```

in regards to capabilities, but I don't understand how they could affect if code actions work or not.

I would try enabling logging (e.g. at `error` level): https://phpactor.readthedocs.io/en/master/development/debugging.html#logging

and see if there are any issues there

**Comment by BenceBakos** [comment]
Well, I'm honestly not sure what's wrong, overcome the issue by installing this plugin:
https://github.com/gbprod/phpactor.nvim

**Comment by BenceBakos** [comment]
Found the source of the issue. When I set these:
```
				init_options = {
					["language_server_phpstan.enabled"] = true,
					["language_server_psalm.enabled"] = true,
					["language_server_php_cs_fixer.enabled"] = true,
					["php_code_sniffer.enabled"] = true,
					["prophecy.enabled"] = true,
				}
```

Code actions are not working with message "No code actions available". (this happens both in lsp config above, and with the plugin:  https://github.com/gbprod/phpactor.nvim)

**Comment by mamazu** [comment]
Could you maybe provide the code that you're trying to work on?

**Comment by dantleech** [comment]
Oh nice plugin! It shouldn't affect this though. I would also try simply deleting those options and letting Phpactor auto create a local config file.

**Comment by BenceBakos** [comment]
> Oh nice plugin! It shouldn't affect this though. I would also try simply deleting those options and letting Phpactor auto create a local config file.
@dantleech You are right, it doesn't matter if I use mentioned plugin or not.

 > Could you maybe provide the code that you're trying to work on?
@mamazu Happens when I open any file of this project as well: https://github.com/laravel/telescope


**But I found the source of the issue**:

`phpcs` is what causing the issue, I get this error:

```
LSP[phpactor][Warning] Diagnostic provider "phpcs" errored with "Could not decode JSON:
```

in `./vendor/phpactor/language-server/lib/Core/Diagnostics/DiagnosticsEngine.php`

```php
122  $diagnostics = yield $provider->provideDiagnostics($textDocument, $token) ;
```

returns an empty string, because the provider found "non-fixable errors":

`lib/Extension/PhpCodeSniffer/Model/PhpCodeSnifferProcess.php`
```
153  $exitCode = yield $process->join(); //value is 1, refers to "private const EXIT_FOUND_NON_FIXABLE_ERRORS = 1;"
```

**When this happens, code actions does not work.**

**Comment by dantleech** [comment]
Seems like something that can be protected against

**Comment by BenceBakos** [comment]
@dantleech if you have something in mind, feel free to share the outlines, I'm happy to do it in the following days.

**Comment by dantleech** [comment]
basically if the code action s misbehaving we should at least catch and log the error:

https://github.com/phpactor/phpactor/blob/0f8c7ab5357c6e88bad9793f2a4c26e98f821c2f/vendor/phpactor/language-server/lib/Core/CodeAction/AggregateCodeActionProvider.php#L31-L36

- catch any `Exception` from the provider
- report the error to the client (i.e. the IDE)
- log the error to the log file
- remove the provider from the pool (or ensure that it's not called again)

similar to what we do here:

https://github.com/phpactor/language-server/blob/master/lib/Core/Diagnostics/DiagnosticsEngine.php#L123-L129

_note that for whatever reason the code in the diagnostics engine above is broken and never removes the provider!_

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/phpactor/pull/2767
