### ISSUE TITLE
PHPStan Path matching not working?

### ISSUE THREAD

**Issue by tsterker** [phpactor/phpactor#2763]
It seems that any PHPStan rules that involve paths are not working.

This seems to be due to the fact that the [PhpstanLinter](https://github.com/phpactor/phpactor/blob/a64039c5ea8580e3422232483b24368e74bb7559/lib/Extension/LanguageServerPhpstan/Model/Linter/PhpstanLinter.php#L39) is copying the file content to lint to a temporary file, which loses the path context. See details below.

# Setup

I'm using NeoVim ([LunarVim](https://www.lunarvim.org/)) on a Mac with the [`gbprod/phpactor.nvim`](https://github.com/gbprod/phpactor.nvim) plugin.

# Reproduce

Imagine the following `phpstan.neon` that is used for a file in `./tests` that has a method without a return type:

```neon
parameters:
    ignoreErrors:
        - identifier: missingType.return
          paths:
            - ./tests/*
    paths:
        - app/
    excludePaths:
        - tests/
```

The above is not ignoring the `missingType.return`

If I change this to a rule without `paths` it works:

```diff
        - identifier: missingType.return
-          paths:
-            - ./tests/*

```

Similarly, the `excludePaths` are not considered, otherwise I should not need to exclude the error for `missingType.return` in the first place.

# Considerations

## Temporary File with file contents loses path context?

I suspect it might be due to the fact that the path context of a file under test is lost, when its contents are written to a temporary file:

> https://github.com/phpactor/phpactor/blob/a64039c5ea8580e3422232483b24368e74bb7559/lib/Extension/LanguageServerPhpstan/Model/Linter/PhpstanLinter.php#L39

**Update (1):** I confirmed this suspicion by specifying the root path of the temporary files that are generated by the `PhpstanLinter` via `tempnam`. The `missingType.return` are not successfully ignored:

```diff
        - identifier: missingType.return
          paths:
-           - ./tests/*
+           - /private/var/folders/kp/
```

**Update (2):** There is another code path that is taken by the `PhpstanLinter` if it does not receive a `$text` with the file contents. When this path is taken (I manually modified the code), things are working as expected.

> https://github.com/phpactor/phpactor/blob/a64039c5ea8580e3422232483b24368e74bb7559/lib/Extension/LanguageServerPhpstan/Model/Linter/PhpstanLinter.php#L36

## Neovim `null-ls` PHPStan linter working

When I'm configuring [LunarVim](https://www.lunarvim.org/) to use the phpstan linter like shown below, paths work.

This indicates to me that there should be a way for language servers to work that does not rely on temporary files?

```lua
local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
    -- Requires global PHPStan binary in your path.
    -- Might also require a `:MasonInstall phpstan`
    {
        name = "phpstan",
        args = {
            "--configuration=phpstan.neon",
            "--memory-limit=2G"
        },
    },
}
```

**Update:** After some more testing it seems that I also had issues when providing direct file paths vs. directory paths. But I have not fully concluded on this yet...
```neon
# Working
- identifier: missingType.return
  paths:
    - ./tests/

# Not working
- identifier: missingType.return
  paths:
    - ./tests/path/to/FileTest.php
```

**Comment by dantleech** [comment]
Null-ls probably analyses the file in-place while Phpactor analyses the code before you save it.

Last time I checked using a tmp file was the only way, we could potentially optionally disable the use of the tmp file to analyze in-place or ask Phpstan to implement a way to both read from STDIN and spoof the path.

**Comment by tsterker** [comment]
@dantleech 
> Null-ls probably analyses the file in-place while Phpactor analyses the code before you save it.
> 
> Last time I checked using a tmp file was the only way, we could potentially optionally disable the use of the tmp file to analyze in-place or ask Phpstan to implement a way to both read from STDIN and spoof the path.


I did some more investigation and it seems that not using a tmp file also worked for me, at least in my preliminary tests where I modified the code to directly use the file path (I updated the ticket description):

https://github.com/phpactor/phpactor/blob/a64039c5ea8580e3422232483b24368e74bb7559/lib/Extension/LanguageServerPhpstan/Model/Linter/PhpstanLinter.php#L36

Maybe the tmp file is needed in some cases that I have not encountered so far.
Maybe some isolated/docker environments 🤔

Supporting an (experimental?) **opt-out of using a tmp file** would be great!

**Comment by dantleech** [comment]
The TMP file is for as-you-type diagnostics. Without it you need to save the file in order for the diagnostics to be updated. Happy to accept an opt-out PR for that ;)

**Comment by tsterker** [comment]
@dantleech 

> or ask Phpstan to implement a way to both read from STDIN and spoof the path.

I think this would be an interesting approach and probably useful in other contexts.

It seems you did already reach out:
> https://github.com/phpstan/phpstan/issues/3262

But it apparently was not the direction intended for PHPStan back then ([another related issue](https://github.com/phpstan/phpstan/issues/2545#issuecomment-547354947), but maybe things changed.

**Comment by tsterker** [comment]
@dantleech 
> Happy to accept an opt-out PR for that ;)

Here's my attempt/proposal for an opt-out parameter: https://github.com/phpactor/phpactor/pull/2764

It adds support for a new `language_server_phpstan.tmp_file_disabled` parameter which defaults to `false`.

**Comment by tsterker** [comment]
@dantleech thanks for merging the MR!

I initially thought I did not need to touch the documentation because I vaguely remembered your [blog post about self-documentation](https://www.dantleech.com/blog/2023/04/23/self-testing-code-units/). But I realize this might not cover the addition from the MR.

Please let me know if I should also provide a follow-up documentation update MR.

**Comment by dantleech** [comment]
the config reference will get updated before the release, so no worries :+1:

**Comment by dantleech** [comment]
closing as PR was merged
