### ISSUE TITLE
Adding new composer package doesn't trigger re-indexing

### ISSUE THREAD

**Issue by Dmitrev** [phpactor/phpactor#2766]
If let's say I'm in a new PHP project and I install `guzzlehttp/guzzle`. Phpactor will not show me any autocomplete results for Guzzle. 

I have to exit my editor and then run `phpactor cache:clear` to get it indexed. 

Similarly actually anything you change in Composer will not get reflected in the LSP, like the namespace mappings.

```json
{
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
}
```

It will auto infer that the namespace is `Src` based on the dir, and just keep it like thatuntil I cache clear, and then it indexes `App` as a namespace.

Is this a bug, or is there additional setup/hooks needed to support this? I'm using Neovim.

# version
I'm using `dev-master` on commit `6384c83cfbb01c92501f2eb6e10962ce7fa9f452`

https://github.com/phpactor/phpactor/tree/6384c83cfbb01c92501f2eb6e10962ce7fa9f452

**Comment by dantleech** [comment]
You may find installing the inotify-tools package will enable Phpactor to detect ex-editor file changes to the project. In any case it will check for changes every 5 minutes and reindex.

For composer changes to be taken into account you will currently need to restart the language server.

**Comment by Dmitrev** [comment]
Ah yeah that actually makes sense, it would have no way of knowing. I'll try the inotify-tools package you've mentioned I think that would actually solve the issue I'm having. 

I will close this issue as there is nothing actionable left in the issue, thanks @dantleech !
