### ISSUE TITLE
Config key `language_server.diagnostic_ignore_codes` not recognized

### ISSUE THREAD

**Issue by Akmadan23** [phpactor/phpactor#2789]
This is the problematic snippet in my `.phpactor.json`:
```json
{
  "language_server.diagnostic_ignore_codes": [ *whatever* ]
}
```

When I run `phpactor config:dump` I get the following error:

```
Phpactor\MapResolver\InvalidMap: Key(s) "language_server.diagnostic_ignore_codes" are not known, kno...
```

I noticed the same problem occurs with `language_server.diagnostic_exclude_paths` and possibly others I didn't check.

**Comment by mamazu** [comment]
It looks like the option you're trying to configure does not exist. What is the output if you remove this line and run:
```
phpactor config:dump | grep diagnostic
```
Does it show up on the list of possible config options?

**Comment by Akmadan23** [comment]
> Does it show up on the list of possible config options?

Of course not, that's why the error occurs. But these options are listed in the documentation https://phpactor.readthedocs.io/en/master/reference/configuration.html#language-server-diagnostic-ignore-codes

**Comment by mamazu** [comment]
What version of phpcator are you using? `phpactor --version`

**Comment by Akmadan23** [comment]
I installed it from the AUR, so it's the last version `2024.11.05.0`

**Comment by mamazu** [comment]
Yeah is feature is currently only available if you're using the master branch of the project. It will be available in the next version.

**Comment by Akmadan23** [comment]
Oh I see, in fact I thought that could be the case. Looking forward to the new release then, and thank you for helping me out!
