### ISSUE TITLE
Can't find and autocomplete unnamespaced classes

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#282]
Hello,

For classes not having a namespace (e.g `Swift_Mailer`, `Twig_Environment`, ... and so on), phpactor (or at least the autocompletion + adding to uses feature) does not seem to find the class (having class not found, even though they are installed through composer and accessible).

**Comment by dantleech** [comment]
Yep, searching for a class by "short name" only works where the file name is equal to the short name. I guess the solution would be to create an index (by parsing all files) and fallback to file location when that fails - I wanted to avoid indexing but in some use cases it would be a good option.

Creating and using an index shouldn't be too much trouble...

**Comment by Taluu** [comment]
Shouldn't looking through composer do the trick ?

**Comment by dantleech** [comment]
"use include" won't work as above, because we would need to know the FQN i norder to locate with composer.

auto-complete should work though :thinking:

**Comment by Taluu** [comment]
> auto-complete should work though :thinking:

Doesn't seem to be the case :/

But it seems that sometimes I also have this problem with namespaced classes. Example : `Symfony\Bridge\Doctrine\RegistryInterface`... In some classes, as I typehint it, I can add the use (phpactor finds the right class), but then there is no autocomplete at all...

**Comment by dantleech** [comment]
Old-style class names should now be supported (`Twig_Extension` etc.)
