### ISSUE TITLE
Autocomplete not working when using weird import

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#285]
This works:

```php
<?php

namespace Svod\Infrastructure\Searching;

use Elastica\Client;

final class IndexPopulator
{
    /**
     * @var Client
     */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    public function populate()
    {
        $this->client->addConnection(
    }
}
```

This doesn't:

```php
<?php

namespace Svod\Infrastructure\Searching;

use Elastica;

final class IndexPopulator
{
    /**
     * @var Client
     */
    private $client;

    public function __construct(Elastica\Client $client)
    {
        $this->client = $client;
    }

    public function populate()
    {
        $this->client->
    }
}
```

It says "pattern not found"

**Comment by dantleech** [comment]
Makes sense right? Client in the docblock translates to `Svod\Infrastructure\Searching\Client`

**Comment by greg0ire** [comment]
It does not make sense, why would it work in the first case?

**Comment by dantleech** [comment]
Because you import `Elastica\Client;`. If you only type hint `Client` in the `__construct` it would explode no?

**Comment by greg0ire** [comment]
Oh when I fix the docblock it works! I get it now, sorry.

**Comment by dantleech** [comment]
Cool, currently working on a linter to point out these issues via. Ale/Syntastic.

**Comment by greg0ire** [comment]
I was wrongly assuming it was using the construct type hint

**Comment by dantleech** [comment]
btw are you using https://github.com/roxma/nvim-completion-manager out of interest? _Much_ better than omni-complete

**Comment by greg0ire** [comment]
I'm not using neovim, should I?

**Comment by dantleech** [comment]
Meh, I switched to use the above. Actually don't use anything else nvim specific... not sure how hard it would be to implement Phpactor with YouCompleteMe or whatever.
