### ISSUE TITLE
Autocomplete partially working :o

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#286]
Hey,

I just updated phpactor through a `:PlugUpdate`. For *some* classes, it works right off the bat (I have completion for all the private / public members, and so on), but on another case, I don't have anything suggested. The case is the following ;

```php
<?php declare(strict_types=1);
namespace Acme\Foo;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

use Symfony\Bridge\Doctrine\RegistryInterface;

class UniqUnitReferenceValidator extends ConstraintValidator
{
    /** @var RegistryInterface */
    private $registry;

    public function __construct(RegistryInterface $registry)
    {
        $this->registry = $registry;
    }

    public function validate($value, Constraint $constraint)
    {
    }
}
```

Trying to use the `$this->registry`, which should point to `Symfony\Bridge\Doctrine\RegistryInterface`, or even at least offer the properties / `validate` method or other methods in `ContraintValidator`), but instead I have only the basic autocompletion, based on the current tags.

Here are the logs ;

```
[2017-12-08T15:37:44.951645+01:00] phpactor.WARNING: Unable to locate class "Acme\Foo\UniqUnitReferenceValidator" for method "registry" [] []
[2017-12-08T15:37:45.058849+01:00] phpactor.WARNING: Unable to locate class "Acme\Foo\UniqUnitReferenceValidator" for method "registry" [] []
```

This is a new file unknown to git, but even with some files known to git, I have it seems the same error...

**Comment by greg0ire** [comment]
Maybe try using an FQCN in the comment? https://github.com/phpactor/phpactor/issues/285

**Comment by Taluu** [comment]
It was working like this before, so it should be unrelated. I do not even have the visibility over the props (e.g no completion for `$this->`)

**Comment by Taluu** [comment]
BTW, using I guess a mix of ncm + omnifunc (not too sure how to complete with ncm... it's installed, but I guess I should do something else than just installing ncm + ncm-phpactor ?)

**Comment by dantleech** [comment]
Could be a regression, as lots of changes recently. Will check.

**Comment by dantleech** [comment]
```

**Comment by Taluu** [comment]
So no need to use `autocmd FileType php setlocal omnifunc=phpactor#Complete` ? I'll remove it then.

I also have another log line :

```
[2017-12-08T15:50:45.890672+01:00] phpactor.WARNING: Did not know how to resolve node of type "Microsoft\PhpParser\Node\Statement\InlineHtml" with text "<?php " [] []
```

With the same type of file (kinda random)

**Comment by dantleech** [comment]
No, I also have omni-complete, works fine...

**Comment by Taluu** [comment]
Hum, it seems that I had the wrong namespace on my file, which was killing the autocomplete (or something like that ?). I had to correct `Acme\Foo` to `Acme\Foo\Bar` as my class was in `Foo/Bar/Uni....`.

As it doesn't find the "top class", it seems to ignore all completion.

**Comment by dantleech** [comment]
Hopefully the new linter will help here too :P

**Comment by dantleech** [comment]
Can we close this one now?

**Comment by Taluu** [comment]
Sure. :+1:
