### ISSUE TITLE
Support `@param` overloading

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#287]
Currently, only a partial support of `@var` is supported (in properties of an object, and supposedly on variables but can't make it work).

What would be awesome would be supporting method's phpdoc `@param` :

```php
<?php

class Foo extends InheritedClass
{
    /** @var Bar */
    private $bar;

    /** @param $noTypeHint Baz */
    public function baz($noTypeHint)
    {
        /** @var Baz */
        $var = $noTypeHint;

        /** @var $var2 Baz */
        $var2 = $noTypeHint;
    }
}
```

So that `$noTypeHint` is recognized as a `Baz`. Currently it is not recognized as an object. I can't typehint the method with `Baz` because inheritance (in my use case, it's Symfony's `ConstraintValidator`).

And as I said, `$var` and `$var2` aren't recognized too, but this must be something on my end, unless it would be a real bug ? I have the `7bb820d86e7` commit for worse-reflection, and I know there was a commit to fix `@var` support before that (` 6ea88486`).

**Comment by dantleech** [comment]
```
        /** @var SymbolInformation $bar */
        $bar = $baz;
        $bar->
```

works when `SymbolInformation` is imported, but resolving an FQN does not work.

**Comment by dantleech** [comment]
Created #288 for the var issue (it currently only works when you import the class).

**Comment by Taluu** [comment]
Hum, even for an imported class and using the short name, I still have no completion with the `$var`.

**Comment by weirdan** [comment]
Note that according to [phpdoc reference manual](http://docs.phpdoc.org/references/phpdoc/tags/var.html) type comes before the var name: `/** @var Baz $var2 */` (ditto for [@param](http://docs.phpdoc.org/references/phpdoc/tags/param.html))

**Comment by Taluu** [comment]
Indeed for `@param` and `@var`. :}
