### ISSUE TITLE
[WR] Docblock type hinting with FQN

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#288]
```
        /** @var \Phpactor\WorseReflection\Core\Inference\SymbolInformation $bar */
        $bar = $baz;
        $bar->
```

does not work, but importing SymbolInformation is fine.

**Comment by Taluu** [comment]
Kind of related (I think): 

```php
<?php
namespace Acme\Bar;

use Acme\Foo;

class Qux
{
    /** @var Foo\Bar */
    private $bar;

    public function __construct(Foo\Bar $bar)
    {
        $this->bar = $bar;
    }
}
```

Here, neither `$this->bar` nor `$bar` in the constructor are recognized as `Acme\Foo\Bar`. So basically, it doesn't support namespace imports (while it supports FQCN or class imports).

**Comment by dantleech** [comment]
Created https://github.com/phpactor/worse-reflection/pull/24/files

Trying to replace this code, but this is a quick fix.

**Comment by dantleech** [comment]
Fixed with the lastest dependency update.

**Comment by Taluu** [comment]
Hum, I still have no completion for the `Foo\Bar` case ? Would you like a report in another issue ?

**Comment by dantleech** [comment]
Yeah, I noticed the same yesterday, reopening this.

**Comment by dantleech** [comment]
Or ... that _does_ work for me, I was thinking of a different issue.

```
class Bar
{
    /**
     * @var Foo\Baz
     */
    private $baz;
}
```

Given that the class exists above, `baz` is completed.
}

**Comment by Taluu** [comment]
Yeah, if `Foo\Baz` is the FQCN it works. But not if you have an import which aliases a namespace :

```php
<?php
namespace Acme\Bar;

use Acme\Foo; // namespace containing `Bar` class, `Baz` classes

class Qux
{
    /** @var Foo\Bar */
    private $bar;

    public function __construct(Foo\Bar $bar)
    {
        $this->bar = $bar;

        // no completion over `$bar` or `$this->bar`
    }
}
```

**Comment by FatBoyXPC** [comment]
Not sure if this is related, but I had something like this:

```php
class FooController
{
    /** @var App\User $user */
    protected $user;
}
```

When I tried auto completing `$this->user->` I would get `Could not find class "App\Http\FooController\App\User"`, but if I then imported the `User` class at the top everything worked as expected.

**Comment by dantleech** [comment]
> Not sure if this is related, but I had something like this:

Actually that looks correct - your variables docblock is relative? If you were to use `@var \App\User` that should work?

**Comment by dantleech** [comment]
@Taluu the following works for me now ... :thinking: 

![asdasd](https://user-images.githubusercontent.com/530801/36865854-02fe1786-1d91-11e8-9868-206bbcafba96.png)

![untitled](https://user-images.githubusercontent.com/530801/36865971-50aaee28-1d91-11e8-84fe-2f01ec80536d.png)

**Comment by FatBoyXPC** [comment]
@dantleech Yeah, even with the leading `\` I'm getting the same error (that App\Http\Controllers\FooController\App\User is not found). So, I'm okay with using a FQCN in this case in the docblock, but that means I have to add the `\` myself. When creating a docblock it's putting only the class name from the typehint, so I'll call `ExpandClass()` on it, which means I still need to put the `\` myself.

**Comment by dantleech** [comment]
Seems to be fixed now:

![image](https://user-images.githubusercontent.com/530801/38174343-1dc1db68-35cc-11e8-817c-50683b4bb17d.png)

**Comment by dantleech** [comment]
Feel free to re-open if this is still an issue or I misunderstood.

**Comment by FatBoyXPC** [comment]
I still seem to have this issue. I've pulled the latest master branch, ran composer install, and restarted vim. 

All that's missing is the opening php tag and namespace, seems to have went off screen when phpactor came up with an error:

![image](https://user-images.githubusercontent.com/744962/38177097-0ff3fc12-35c9-11e8-9c2b-6ed3989d167d.png)

**Comment by dantleech** [comment]
What's the namespace above?

**Comment by FatBoyXPC** [comment]
```php
<?php

namespace App\Http\Middleware;

use Closure;

class ModifyRequest
{
    /**
     * @var Illuminate\Http\Request
     */
    protected $request;

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $this->request->
        $request->merge([
            'foo' => 'foo',
        ]);

        return $next($request);
    }
}
```

While we're on the topic, the local `$request` variable in the `handle()` method doesn't seem to be recognized. It does if typehinted, but it would be nice if I didn't need the hints!

**Comment by dantleech** [comment]
This is correct behavior - the namespace is `App\Http\Middleware`, therefore the relative qualified name `Illuminate\Http\Request` should resolve to the fully qualified name `App\Http\Middleware\Illuminate\Http\Request`.

When you specify a type hint, it is relative to the current namespace (i.e. you would get the same error if you did `new Illuminate\Http\Request`).

> While we're on the topic, the local $request variable in the handle() method doesn't seem to be recognized

Please raise another ticket (otherwise it becomes very difficult track).

**Comment by dantleech** [comment]
But the later may be a regression from today, which I fixed about 2 hours ago, so try updating before creating the new issue :)

**Comment by FatBoyXPC** [comment]
Is it best to update with `:call phpactor#Update()` or going into the bundle direction, pull and composer install? I've done both, and I imagine `Update()` just does that manually?

**Comment by FatBoyXPC** [comment]
Also - okay, I can make sure to use the leading `\` for the full path. I was under the impression by your screenshot, though, that it wasn't needed. No worries!

**Comment by dantleech** [comment]
> Is it best to update with :call phpactor#Update() or going into the bundle direction, pull and composer install? I've done both, and I imagine Update() just does that manually?

Yep, that's what `Update` does - just be aware that if the VIM plugin was updated (doesn't happen very frequently) you will have to exit and restart VIM (or resource the plugin).

**Comment by dantleech** [comment]
(btw, my screenshot showed a relative example - `Core` was already imported)

**Comment by FatBoyXPC** [comment]
I usually close and reopen vim after updating anyway out of paranoia.

In this case, though, there were no updates available (I updated about an hour ago). Should I still open the other issue?

**Comment by dantleech** [comment]
Yes please :)
