### ISSUE TITLE
Does not work if not in a git repository

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#291]
Hello,

Didn't try yet the latest version, but if there is no `.git` directory in the root directory (not in a git repo for example), phpactor does not work at all

```
[RuntimeException]
  The cwd does not seem to be a git repository root (could not find .git folder
  )
```

**Comment by dantleech** [comment]
Yep, thats an actual limitation - you need both composer and git, it would be possible however to work around this.

**Comment by Taluu** [comment]
It also doesn't work if no composer actually (this could happen, for local projects that does not have any dependencies), but this is related to your comment.

**Comment by sstutz** [comment]
doesn't work for git worktrees either @dantleech just for your information :)

**Comment by dantleech** [comment]
it should now work if git isn't present (if there are 10,000s of files, it will be slow as hell). I think git worktree support should be another issue.
