### ISSUE TITLE
Support for "generic collections types"

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#292]
Don't know if it's implemented (if so you can close...), but supporting "generic-like" types would be awesome :

```php
<?php
use Doctrine\Common\Collections\Collection;

/** @var Collection<Foo> | Foo[] */
$foos = new ArrayCollection(...);
```

WDYT ? Even if it's not really something recognized by php, it is I think used enough to offer a support for that (there is even a RFC in php to allow that : https://wiki.php.net/rfc/generics and https://wiki.php.net/rfc/generic-arrays)

**Comment by dantleech** [comment]
Absolutely, it's on the list

On 14 December 2017 17:21:36 CET, "Baptiste Clavié" <notifications@github.com> wrote:
>Don't know if it's implemented (if so you can close...), but supporting
>"generic-like" types would be awesome :
>
>```php
><?php
>use Doctrine\Common\Collections\Collection;
>
>/** @var Collection<Foo> | Foo[] */
>$foos = new ArrayCollection(...);
>```
>
>WDYT ? Even if it's not really something recognized by php, it is I
>think used enough to offer a support for that (there is even a RFC in
>php to allow that)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpactor/phpactor/issues/292

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dantleech** [comment]
See #356
