### ISSUE TITLE
[Transform] Implementing an interface that references self

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#297]
Given the following interface:

```php
<?php 
interface ValueObjectInterface
{
    public function sameValueAs(self $object): bool;
}
```

When I call `phpactor#Transform()` from vim and then hit `i` like "implement contracts", methods are generated, but a `use self;` statement is added. It should not.

**Comment by greg0ire** [comment]
Moreover, the generated signature should be
`public function sameValueAs(ValueObjectInterface $object): bool`

**Comment by greg0ire** [comment]
I experience a similar issue with the `void` return type: it produces a `use void` statement.

**Comment by Taluu** [comment]
And it seems that `self` is not recognized as the type itself. e.g :

```php
<?php

class Foo 
{
     /** @var self */
     private $foo;

     public function returnSelf(): self
     {
         $this->returnSelf(); // doesn't return completion for Foo
     }
}
```

**Comment by greg0ire** [comment]
Watch out for the recursion tho :P

**Comment by Taluu** [comment]
wrong example but I guess you got the gist. :P

**Comment by dantleech** [comment]
`void` is no longer detected as a class.

**Comment by dantleech** [comment]
:+1: fixed.
