### ISSUE TITLE
crash about 7.2 polyfill

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#303]
After the latest `:call phpactor#Update()`, I get

```
Phpactor returned an error: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Php72" from namespace "Symfony\Polyfill\Php72".
Did you forget a "use" statement for "Symfony\Polyfill\Php72\Php72"? in /home/gparis/workspace/svod/vendor/symfony/polyfill-php72/bootstrap.php:29
Stack trace:
#0 /home/gparis/workspace/svod/vendor/composer/autoload_real.php(66): require()
#1 /home/gparis/workspace/svod/vendor/composer/autoload_real.php(56): composerRequire2c154290397a11c6eb9d2f8ebc7d3da0('25072dd6e247008...', '/home/gparis/wo...')
#2 /home/gparis/workspace/svod/vendor/autoload.php(7): ComposerAutoloaderInit2c154290397a11c6eb9d2f8ebc7d3da0::getLoader()
#3 /home/gparis/.vim/bundle/phpactor/lib/Container/CoreExtension.php(249): require('/home/gparis/wo...')
#4 /home/gparis/.vim/bundle/phpactor/vendor/phpbench/container/lib/Container.php(118): Phpactor\Container\CoreExtension->Phpactor\Container\{closure}(Object(Phpactor\Container\ApplicationCont
ainer))
#5 /home/gparis/.vim/bundle/phpactor/lib/Container/Core in /home/gparis/workspace/svod/vendor/symfony/polyfill-php72/bootstrap.php on line 29

```

**Comment by dantleech** [comment]
PHP version? Symfony version? Are you sure it's a Phpactor issue?

**Comment by greg0ire** [comment]
php 7.1.11

```
symfony/config                           v3.4.2             Symfony Config Component
symfony/console                          v3.4.2             Symfony Console Component
symfony/debug                            v3.4.2             Symfony Debug Component
symfony/event-dispatcher                 v3.4.2             Symfony EventDispatcher Component
symfony/filesystem                       v3.4.2             Symfony Filesystem Component
symfony/finder                           v3.4.2             Symfony Finder Component
symfony/inflector                        v3.4.2             Symfony Inflector Component
symfony/options-resolver                 v3.4.2             Symfony OptionsResolver Component
symfony/polyfill-mbstring                v1.6.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                   v1.6.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72                   v1.6.0             Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                          v3.4.2             Symfony Process Component
symfony/property-access                  v3.4.2             Symfony PropertyAccess Component
symfony/serializer                       v3.4.2             Symfony Serializer Component
symfony/stopwatch                        v3.4.2             Symfony Stopwatch Component
symfony/yaml                             v3.4.2             Symfony Yaml Component
```

I'm not sure what is happening, but it kind of looks like an autoloading conflict (why are the 3 first lines of the stack trace corresponding to files from my project?)

**Comment by greg0ire** [comment]
Requiring vendor/autoload.php doesn't crash, so I'm pretty sure it is a phpactor issue.

**Comment by dantleech** [comment]
`phpactor config:dump`? I'm developing an SF4 project with the same php72 pollyfil and havn't had any issues :/

**Comment by greg0ire** [comment]
```
bin/phpactor config:dump
Config files:
 [𐄂] /home/gparis/.vim/bundle/phpactor/.phpactor.yml
 [✔] /home/gparis/.config/phpactor/phpactor.yml
 [𐄂] /etc/xdg/xdg-i3/phpactor/phpactor.yml
 [𐄂] /etc/xdg/phpactor/phpactor.yml

code_transform.class_new.variants:
  final:final
  phpunit:phpunit
code_transform.template_paths:
  1:/home/gparis/.config/phpactor/templates
code_transform.indentation:    
code_transform.refactor.generate_accessor.prefix:
code_transform.refactor.generate_accessor.upper_case_first:false
autoload:vendor/autoload.php
cwd:/home/gparis/.vim/bundle/phpactor
console_dumper_default:indented
cache_dir:/home/gparis/.vim/bundle/phpactor/lib/Container/../../cache
logging.enabled:false
logging.fingers_crossed:true
logging.path:phpactor.log
logging.level:warning
navigator.autocreate:
rpc.class_search.filesystem:composer
rpc.class_move.filesystem:git
reflection.stub_directory:/home/gparis/.vim/bundle/phpactor/lib/Container/../../vendor/jetbrains/phpstorm-stubs
navigator.destinations:
  source:src/<kernel>.php
  phpspec_test:spec/<kernel>Spec.php
  phpunit_test:tests/<kernel>Test.php
```

I'm working on a zend-expressive project with some sf components.

**Comment by greg0ire** [comment]
I just reproduced the issue at home, then I updated phpactor and the issue is gone… but I did update at work before reporting this. I recall not being on `master` but on a weird `undocument` branch. Closing this for now, I might reopen it on monday 😕

**Comment by dantleech** [comment]
:scream:

**Comment by greg0ire** [comment]
I reinstalled the submodule, and the bug is still here.

**Comment by greg0ire** [comment]
Please note that it's specific to that project though, it works on another one (I don't have the 72 polyfill on that one)

**Comment by dantleech** [comment]
Wierd - there shouldn't be any autoload conflicts - we include the ClassLoader of the project briefly (via. `autoloader.php`) which auto-registers, but we deregister it immediately afterwards. Maybe the polyfill is doing some funky stuff, but works in my SF4 project.

**Comment by greg0ire** [comment]
The last line of the stack trace is quite weird too:

`#5 /home/gparis/.vim/bundle/phpactor/lib/Container/Core in /home/gparis/workspace/svod/vendor/symfony/polyfill-php72/bootstrap.php on line 29`

**Comment by greg0ire** [comment]
That's probably the way a closure line is displayed I guess...

**Comment by greg0ire** [comment]
I'm installing with an old version of Composer (1.4) and cannot upgrade for now because of a bug with 1.6 and our Satis, but that might be the reason, I don't know.

**Comment by dantleech** [comment]
Ah, I guess when we include the `autoload.php` composer reads all the mapped `files` in composer JSON (of which the polyfill `bootstrap.php` is one) and for some reason, the PHP72 polyfill class is not autoloadable at that point.

When we include the autoloader, I was assuming that no classes would be loaded - but in the case where files are explicitly included in the autoloader configuration I guess this might happen and perhaps the existence of an autoloader (Phpactor's autoloader) prevents the class from being loaded with the included autoloader. Maybe. Perhaps.

I guess you could try `composer require symfony/polyfill-php72` on `phpactor` to see if including that in the original autoloader helps.

**Comment by greg0ire** [comment]
1. Thanks this fixes my issue!
2. My colleague just made a merge request on a lib we use in this project, and we got the exact same error. I think it is fair to say this is not a problem with phpactor. So sorry for the disturbance, and thanks a lot for your support, I'm closing this again.

**Comment by dantleech** [comment]
Cool, glad it works, kindof. Let me know if we can improve to avoid the issue.
