### ISSUE TITLE
[CM] (class moving) Updating aliased reference works but another use is added

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#315]
Issue command: `~/.vim/bundle/phpactor/bin/phpactor class:move src/Api/Edito/QueryFunction src/Api/Edito/Middleware`

Result: a file containing `use Svod\Api\Edito\Middleware\LastAddedWorks as LastAddedWorksInterface;` now has it replaced, but an extra `use Svod\Api\Edito\Middleware\LastAddedWorks` is added.

**Comment by greg0ire** [comment]
Tell me if you need a complete reproducer.

**Comment by Taluu** [comment]
I also had the problem. Basically, if you're moving one (or several) classes into the same namespaces, the `use` shouldn't be added, or something along those lines ?

**Comment by dantleech** [comment]
yep, am currently working on `import use` as a refactoring, which should incidentally provide a better way of handling this.

**Comment by dantleech** [comment]
think this was fixed.
