### ISSUE TITLE
PHPUnit `TestCase` not found on use insert

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#32]

**Comment by dantleech** [comment]
Fixed in class-to-file

**Comment by ek-yrabiller** [comment]
@dantleech I have the case when using [Symfony's PHPUnit bridge](https://github.com/symfony/phpunit-bridge).

**Comment by ek-yrabiller** [comment]
Oh, solved by adding this configuration:

```
composer.autoloader_path: ["%project_root%/vendor/autoload.php", "%project_root%/bin/.phpunit/phpunit/vendor/autoload.php"]
```

**Comment by elythyr** [comment]
Maybe we could add this in the documentation, under a framework section or example or something.
Seems like something that can cost a lot of time if not aware of.

**Comment by dantleech** [comment]
This wouldn't be an issue with the Language Server btw.

**Comment by elythyr** [comment]
> This wouldn't be an issue with the Language Server AFAIK, as this would get indexed regardless.

That's a good example of doted directory that should not be excluded.
We didn't automatically ignore them anyway, I think I didn't even add the exclusion in any PR before the ticket was closed ? Tiny memory ><
