### ISSUE TITLE
[WR] Traits properties not included in completion

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#320]
e.g. when completing a `MethodDeclaration` node from the Tolerant Parser library.

**Comment by dantleech** [comment]
Fixed.

**Comment by dantleech** [comment]
Still the case

**Comment by dantleech** [comment]
See #397

**Comment by FatBoyXPC** [comment]
Copying and pasting from the other issue to make following this easier:

When I'm inside a Laravel project, there's a [Request] class that has a method available from a trait that the class uses. I don't see the `input()` method available when I look at the menu.

Reference:
![image](https://user-images.githubusercontent.com/744962/38595772-8ac75f3e-3d1b-11e8-8679-75aa99ea5a2a.png)


[Request]: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Http/Request.php#L19

**Comment by dantleech** [comment]
At least in my case this is because the target class has multiple traits, but only members from the initial trait are reflected/completed. Which traits has `Request` got?

**Comment by FatBoyXPC** [comment]
```php
class Request extends SymfonyRequest implements Arrayable, ArrayAccess
{
    use Concerns\InteractsWithContentTypes,
        Concerns\InteractsWithFlashData,
        Concerns\InteractsWithInput,
        Macroable;
```

**Comment by FatBoyXPC** [comment]
Woo! Any idea when this will be added to `master`? Is it safe enough for me to just stay on `develop`? I suppose I could stay on `develop` until something breaks and then go back to master :)

**Comment by dantleech** [comment]
Yeah, `develop` should be fine in general :)
