### ISSUE TITLE
[Complete] Completion removes and ignores anything after last accessor

### ISSUE THREAD

**Issue by futurityverb** [phpactor/phpactor#321]
For example:

```
$this->me<C-x><C-o>
```
results in this:
```
$this->
      |method1     |
      |method2     |
      |otherMethod1|
      |otherMethod2|
```
when I'd expect it to result in this:
```
$this->me
      |method1|
      |method2|
```
Am I thinking about this incorrectly?

**Comment by dantleech** [comment]
No that's expected behavior with omni-complete atm. If using Neovim try ncm-phactor for a better experience

**Comment by dantleech** [comment]
If you are interested in looking further into this, the VIM Omni-Complete function is [here](https://github.com/phpactor/phpactor/blob/master/plugin/phpactor.vim#L28) (it will currently strip the partially completed string from the source code).

Then there is `src/Application/Complete.php` which would be easy to modify as follows to filter based on the partial match:

```php
        $suggestions = array_filter($suggestions, function (array $suggestion) use ($partialMatch) {
            return 0 === strpos($suggestion['name'], $partialMatch);
        });
```

**Comment by dantleech** [comment]
This can now be addressed in the new completion library: [completion](https://github.com/phpactor/completion).

**Comment by dantleech** [comment]
Fixed!
