### ISSUE TITLE
[WR] Support for nullable types in docblocks

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#329]
It seems that if I have a nullable property (`?string`, `?Foo`, ... etc), it is marked as `unknown` instead of `?string` and so on.

(I'm guessing it's a bug / missing feature on WR ?)

**Comment by dantleech** [comment]
Yes, it is indeed. Should be relatively easy to implement.

**Comment by dantleech** [comment]
Do you mean `@var ?string` is standard: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types

Does PHPStorm support it? I would have expected `@var string|null`

**Comment by Taluu** [comment]
Didn't try with a `@var` or `@param` , but the nnullable typehint. And as it is a core feature of PHP 7.1, it would make sense to support it, nay ?

The psr doesn't seem to have been updated for that.

**Comment by dantleech** [comment]
Hmm.. I only asked because its works for me: https://github.com/phpactor/worse-reflection/commit/45585612cf0b0cde538a3f17fdfedc491f2b23f4

Can you provide an example?

**Comment by Taluu** [comment]
Yup, works on return type and typehint, but not on `@param` and `@var`. Even though it is not really documented in the psr (guess it's dead or something ?), it is still a valid php type, so it should IMO be supported.

**Comment by dantleech** [comment]
What's the use case for using this notation in a docblock? Supporting `<7.1` code?

**Comment by weirdan** [comment]
> Also, don't think PHPStan supports that.

PHPStan, Psalm and Phan support that notation.

**Comment by dantleech** [comment]
This should be "fixed" in #876 - it uses `@var Type|null $foo` by default, the `.phpactor/templates/Property.php.twig` could be overridden to use `?` instad.
