### ISSUE TITLE
The stream or file "phpactor.log" could not be opened

### ISSUE THREAD

**Issue by lukepass** [phpactor/phpactor#331]
Hello, I installed phpactor in VIM and it's working fine.
I would like to make it available outside VIM following the installation:

```
➜  cd /usr/local/bin 
➜  sudo ln -s ~/.vim/bundle/phpactor/bin/phpactor phpactor
```

When I run it I get the following exception:

```
  [UnexpectedValueException]                                                                       
  The stream or file "phpactor.log" could not be opened: failed to open stream: Permission denied
```

How can I solve this? Thanks.

**Comment by greg0ire** [comment]
I usually have a `~/bin` directory that I then add to my `PATH` ([might be done automatically on recent versions of Ubuntu](https://askubuntu.com/questions/9848/what-are-path-and-bin-how-can-i-have-personal-scripts#9849)), for 2 reasons:

- no need to share this with other users of my machine (if any)
- this path fully belongs to me


I think that error message could be improved by given the full path to the log file.

**Comment by dantleech** [comment]
@greg0ire s suggestion is a good practice, however I think the installation in the docs should be fine, but the documented method should work, I use it without issues and `phpactor.log` is created in the current working directory.

1.  Phpactor writes the error log to the current working directory. Does your user have permissio to write to the directory that you are running Phpactor in?
2. We should probably [disable error logging by default](https://github.com/phpactor/phpactor/blob/master/lib/Container/CoreExtension.php#L59) (it currently only logs on WARNING, but these can happen frequently).

If the answer to 1 is `yes` then is it an issue? But in anycase, disabling error logging would probably be sensible, feel free to make a PR :)

**Comment by dantleech** [comment]
@lukepass any update on this?

**Comment by dantleech** [comment]
Logging is now disabled by default
