### ISSUE TITLE
[WR] Infer property types from the constructor

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#340]
As in some editors (like phpstorm I think ?), instead of having to document `/** @var MyType */` on a property, it should be able to detect the type from the assignment in the constructor.

```php
class Foo
{
   private $bar;

    public function __construct(Bar $bar)
    {
        $this->bar = $bar;
    }
}
```

So that I can have the completion / etc on `$this->bar` without having to add the docblock for `private $bar;`

I  think it should be done in worse reflection (I'll let you tag it @dantleech as I'm not really sure).

**Comment by dantleech** [comment]
Problem with this is that the type is mutable, might be interesting to have a framebuilder pass where it initially tried to guess property types from all assignments in the class, and then adding information from annotations.

Would be quite easy with the new frame walkers.

**Comment by dantleech** [comment]
See #552
