### ISSUE TITLE
`phpactor status` fails with custom composer vendor-dir

### ISSUE THREAD

**Issue by luniki** [phpactor/phpactor#346]
If composer.json contains a custom "config.vendor-dir" (see https://getcomposer.org/doc/06-config.md#vendor-dir ), `phpactor status` fails to recognize composer in a project.

**Comment by dantleech** [comment]
You can use the `autoload: path/to/your/autoload.php` (or even pass an array of autoloaders).

```
# .phpactor.yml
autoload: path/to/your/autoload.php
```

But _might_ make sense to select the `composer.json` vendor path if it wans't configured.

**Comment by dantleech** [comment]
i think it's OK to require manual configuration for special cases like this, I added some documentation: http://phpactor.github.io/phpactor/configuration.html#reference

Feel free to re-open if you feel strongly that composer file should be autodetected
