### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by jjanvier** [phpactor/phpactor#347]
Would it be possible to tag a release? Even a `0.1.0` would be cool :)
Because currently it's impossible to install your tool via composer with a project that requires minimum stability `stable`.

**Comment by dantleech** [comment]
I guess my question would be why would you include this as a dependency of your project? 

I personally use it as a globally installed tool and as a VIM plugin. It's a tool that can be used on all of your PHP projects.

**Comment by Taluu** [comment]
Currently, because of all the subprojects that are not declared on packagist, you can't really install it as a global dependency, unless you are addind each dependency / repositories one by one (global or local). The current way, to clone this repo and use `compose install` is not great IMO :s

So you should at least declare the phpactor depepdencies (WR, ... and so on) on packagist, or remerge them back into `phpactor`...

**Comment by dantleech** [comment]
> So you should at least declare the phpactor depepdencies (WR, ... and so on) on packagist, or remerge them back into phpactor...

Yeah, the packages _should_ be on packagist, this is something I'm planning to do.

However, the question remains: is there a use case for installing this as a project dependency?

**Comment by jjanvier** [comment]
OK. Maybe you're right it's not necessary as a project dependency. Maybe it's just a habit. You know, I'm use to `composer require -dev just-another-tool`.

But even if it's not necessary, I think installing tools via composer is today "the standard way". It's really simple and works great.

Also having at least a release would allow to not rely on master (bad thing can happen with one commit ^^) and give the project roadmap some clarity imo. 

Last but not least, it would be really cool, if possible to have the minimum stability set to `stable`. The composer install of your dependencies is reeeaaaally long :)

**Comment by Taluu** [comment]
Yep, as a local dependency I too have difficulties to see the point. IMO, phpactor is a global tool : you should either install it globally through composer or use box or something (can't find the exact name...) to make a phar ?

**Comment by dantleech** [comment]
I created https://github.com/phpactor/phpactor/issues/348 for putting the packages on packagist. Feel free to continue there.
