### ISSUE TITLE
[Docblock] Docblock parser should tolerate extra spaces

### ISSUE THREAD

**Issue by FatBoyXPC** [phpactor/phpactor#365]
In the following code, I get `-- Omni completion (^O^N^P) Pattern not found
` when I ctrl+x ctrl+o on the `$request` variable:

```php
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $request->
        $request->merge([
            'foo' => 'foo',
        ]);

        return $next($request);
    }
```

If I typehint the parameter correctly then I get the expected list of results, but it would be nice if this worked off docblocks alone!

**Comment by dantleech** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/530801/38177507-84b1dbe8-3603-11e8-8320-8cd610cdc5ec.png)

hmm ...

**Comment by dantleech** [comment]
Ha. Found it. You have 2 spaces after the class name in the docblock.

So

```
    /**
     * @param Reflector $reflector
     */
```

Works (1 space)

and

```
    /**
     * @param Reflector  $reflector
     */
```

doesn't (2 or more spaces).

**Comment by FatBoyXPC** [comment]
Woo! I was just writing back how worried I was becoming since things worked for you but not for me in multiple things!

**Comment by dantleech** [comment]
Fixed :crossed_fingers:

**Comment by FatBoyXPC** [comment]
Thanks! Works like a charm!
