### ISSUE TITLE
[COMPL] Omni-complete func. gives feedback with errors, breaks Deoplete

### ISSUE THREAD

**Issue by fenetikm** [phpactor/phpactor#370]
In Drupal, there is a class called ContentEntityBase that uses the __get method for "fields" such that you can validly do:

```php
$content->field_custom->value = 'blah';
```
Unfortunately this throws the following when using deoplete in Vim and omnicompletion (anywhere in the file):

```
Error detected while processing function phpactor#Complete
line 31:
Class "Drupal\Core\Entity\ContentEntityBase" has no properties named "field_custom"
```

**Comment by dantleech** [comment]
I think this is a recent regression, will try and get it fixed ASAP.

**Comment by dantleech** [comment]
Oh, sorry. `__get` is likely never to work (unless we add a Drupal specific extension).

The error shouldn't happen however, at what point in the completion is it thrown?

**Comment by fenetikm** [comment]
Yeah, I wasn't expecting it to "work" just not throw an error.

Not sure about your question with respect to what _points_ are there to be helpful. I hit `<c-x><c-o>` (in a file where `$content->field_custom` is present in another method) then the error is thrown.

Let me know what more specific information I can give you.

**Comment by dantleech** [comment]
I see now that the error is by design - I wanted to tell the user _why_ the auto-completion didn't work. Which it has done here.

I guess Deoplete is using Omnicomplete (I think somebody is developing a plugin for Phpactor).

The question is if Omni-complete should throw the error at all (I don't think there was a better way to do it). Or maybe there could be an option to disable it.

**Comment by fenetikm** [comment]
Right, but this error is being thrown when I am trying to complete something else and actually maybe this is specific to when there is nothing else to complete in the case of an inbuilt php function, e.g. (cursor denoted by <<>>):

```php
public function thething() {
  in_array<<>>
}

public function anotherthing() {
  $content->field_custom->value = 'thing';
}
```

`<c-x><c-o>` pressed triggers the error. It instead of `in_array` I try to complete on `$this->` it works fine.

**Comment by fenetikm** [comment]
Maybe instead of throwing an error it could just give the message of 'Pattern not found' ?

**Comment by dantleech** [comment]
Omni-complete doesn't allow echo messages normally here.

What would be good is having a warning show (e.g. as with ale / syntastic).

```
    if !empty(issues)
        let issueText = join(issues, ', ')

        let list = []
        let pos = getpos('.')
        let currentPath = expand('%')
        call add(list, { 'filename': currentPath, 'lnum': pos[1], 'col': pos[2], 'text': issueText, 'type': 'E'})
        call setqflist(list)
        lrewind
    endif
```

Tried the above but although it adds the error to the location list, it doesn't display anything on the screen. Might have to ask on Stackoverflow.

**Comment by fenetikm** [comment]
Now that I have updated phpactor this particular error has gone away and I do actually just get "Pattern not found." when trying to complete on `in_array`... However, I am now getting a different error on something else which I will try to isolate and open up another issue if  applicable. Thanks again.

**Comment by dantleech** [comment]
Well the issue is still valid. If tools depend on omni-complete not throwing errors, then maybe they should be disabled by default...

**Comment by dantleech** [comment]
Omni-complete errors are now disabled by default.

**Comment by kristijanhusak** [comment]
@fenetikm can you share how did you manage to setup deoplete to work with phpactor omnifunc?

**Comment by fenetikm** [comment]
Oh I get you, I misunderstood what you were trying to achieve - yeah I only trigger it manually since I don't use it that much and it's faster to not have it running automatically. I'll see if I can get it going and report back.

**Comment by dantleech** [comment]
It would be great to get an aynchronous Deoplete plugin going, the [ncm-phpactor](https://github.com/roxma/ncm-phpactor) for Neovim Completion manager is amazing. Somebody did [make a start](https://github.com/joereynolds/deoplete-phpactor) but not sure what the status of that is.

**Comment by kristijanhusak** [comment]
@dantleech I created initial version https://github.com/kristijanhusak/deoplete-phpactor
Still needs some tweaks, and rank is too high. Will finish it during the weekend, and create a PR to add a link to it.

**Comment by kristijanhusak** [comment]
@dantleech I finished it. Should i create PR for gh-pages to add a short description and link to it, or you will do it?

**Comment by dantleech** [comment]
Awesome :) Would be great if you could create a PR for [the vim plugin documentation](https://github.com/phpactor/phpactor/blob/develop/doc/vim-plugin.md) and perahps also the [VIM Doc](https://github.com/phpactor/phpactor/blob/develop/doc/vim-plugin.md) (at some point that one will be generated, but currently I'm maintaining them both).

**Comment by fenetikm** [comment]
Just gave your plugin a shot @kristijanhusak  - works fabulously! 👍
