### ISSUE TITLE
[COM] Completion of inbuilt php functions

### ISSUE THREAD

**Issue by fenetikm** [phpactor/phpactor#371]
Perhaps it is just me but is there a way to get completion of inbuilt php functions with their signatures from phpactor? e.g. `array_filter`, `str_replace` etc.

I am currently using deoplete - is this even something phpactor related? Thanks.

**Comment by dantleech** [comment]
Yeah, it would be possible and is planned, we need to:

- Create an index of built-in PHP functions (using our existing (jetbrains phpstorm stubs).
- Search for functions in composer-included files.
- Add function support to [worse reflection](https://github.com/phpactor/worse-reflection).
- Extract a package for search for things (currently class search is an ad-hoc solution in Phpactor).
- Create add function completion to [phpactor/completion](https://github.com/phpactor/completion).

**Comment by fenetikm** [comment]
All good - excited to hear that it is on the list! I am pretty sure your approach is very similar to felix becker's language server - might be something that could be mined for inspiration ;)

**Comment by dantleech** [comment]
Made a start on function reflection: https://github.com/phpactor/worse-reflection/pull/40

**Comment by dantleech** [comment]
We now have function reflection, and function [goto-definition](https://github.com/phpactor/phpactor/pull/457) - with support for locating functions defined in the Jetbrains function stubs (basically in-built functions).

The next, comparatively easy, step would be to write a new [Completor](https://github.com/phpactor/completion/tree/master/lib/Bridge/TolerantParser/WorseReflection) which uses f.e. `get_defined_functions` and uses the Reflector to pull up the function definition and format the completion  - that's _probably_ the fastest way.

**Comment by dantleech** [comment]
And it's in #458 :tada:
