### ISSUE TITLE
Completion on class property members failing

### ISSUE THREAD

**Issue by fenetikm** [phpactor/phpactor#375]
When trying to query via omnicomplete for members on a property e.g. `$this->logger->` I am getting `Could not find class "Drupal\ua_ccsp_module\Plugin\QueueHandler\Drupal\Core\Logger\LoggerChannelInterface"` where the def of the property is:

```php
  /**
   * The logger channel.
   *
   * @var \Drupal\Core\Logger\LoggerChannelInterface
   */
  protected $logger;
```

It seems to be not respecting the FQCN def and treating it as relative to the namespace (or something)? Unless I am doing something non-standard?

**Comment by fenetikm** [comment]
Hmmm, actually, it seems to be a problem with just this property and not other ones. Will investigate more and report back.

**Comment by fenetikm** [comment]
Ok, so the issue is because there is no corresponding `use` statement in this class for that class `LoggerChannelInterface`. The other properties have `use` statements (because their classes are injected into the constructor but this property is a bit different and a factory is passed in instead. So I guess this is something that needs to be handled in the reflection strategy?

**Comment by dantleech** [comment]
Wierd, this works for me:

```
  /**
   * @var \Drupal\Core\Block\BlockManagerInterface
   */
  private $blockManager;
```

Even if `BlockManagerInterface` is not imported

**Comment by dantleech** [comment]
Assume you have the lastest version of Phpactor?

**Comment by fenetikm** [comment]
My humblest apologies - updating phpactor fixes it! Thanks again.
