### ISSUE TITLE
[WR] Completion for properties/methods that are only in class docblocks

### ISSUE THREAD

**Issue by tweekmonster** [phpactor/phpactor#384]
I have to work with classes that have magic properties.  Would be nice to get completions for properties defined in the class's docblock.

```php
/**
 * @property string $bar
 */
class Foo
{
  public function __get($name)
  {
    ...
  }
}
```

**Comment by dantleech** [comment]
This could be implemented by:

- adding a `propertyTypes` method to the [docblock bridge](https://github.com/phpactor/worse-reflection/blob/master/lib/Bridge/Phpactor/Docblock.php#L69)
- adding a docblock check to the [propertyTypeResolver](https://github.com/phpactor/worse-reflection/blob/master/lib/Core/Reflection/TypeResolver/PropertyTypeResolver.php) (same as [method return type resolver](https://github.com/phpactor/worse-reflection/blob/master/lib/Core/Reflection/TypeResolver/MethodReturnTypeResolver.php))
- adding some [tests](https://github.com/phpactor/worse-reflection/blob/master/tests/Integration/Bridge/TolerantParser/Reflection/ReflectionPropertyTest.php)

**Comment by dantleech** [comment]
I implemented the above in https://github.com/phpactor/phpactor/pull/453 , but I misunderstood, this ticket is about providing completion for methods/properties. Which would be another task (and not currently sure the best way to do it).

**Comment by FrozenDroid** [comment]
+1 for this. In Laravel there's a lot of magic properties and methods. Would like to be able to get completion for them through docblocks

**Comment by dantleech** [comment]
See #682
