### ISSUE TITLE
Autocompletion with traits

### ISSUE THREAD

**Issue by FatBoyXPC** [phpactor/phpactor#397]
When I'm inside a Laravel project, there's a [Request] class that has a method available from a trait that the class uses. I don't see the `input()` method available when I look at the menu.

Reference:
![image](https://user-images.githubusercontent.com/744962/38595772-8ac75f3e-3d1b-11e8-8679-75aa99ea5a2a.png)

[Request]: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Http/Request.php#L19

**Comment by dantleech** [comment]
Duplicated of https://github.com/phpactor/phpactor/issues/320 ?

**Comment by FatBoyXPC** [comment]
I looked at that, decided against it because methods and properties are different things - but they're both traits so I'll post this there :smile:
