### ISSUE TITLE
Emacs interface to Phpactor

### ISSUE THREAD

**Issue by zonuexe** [phpactor/phpactor#416]
Hi, I am a maintainer of Emacs [php-mode](https://github.com/ejmr/php-mode), a member of [emacs-php](https://github.com/emacs-php).

We ware taught about Phpactor at https://github.com/ejmr/php-mode/issues/451 , and I began development of [`phpactor.el`](https://github.com/emacs-php/phpactor.el) today.  This is still the early stage of development, but probably I think that I will complete this within a few days.

Phpactor's RPC interface was easy to understand, so it will not take time to complete it. I appreciate your awesome job.

**Comment by dantleech** [comment]
Hey, that's great news!

You probably realise this already, but the key part is implementing the [dispatcher](https://github.com/phpactor/phpactor/blob/develop/plugin/phpactor.vim#L324) as this will allow back-and-forth communication with Phpactor (for context menu etc).

Let me know if you have any questions :)

**Comment by dantleech** [comment]
Closing now as [phpactor.el](https://github.com/emacs-php/phpactor.el) is well underway :)
