### ISSUE TITLE
Can't autocomplete if a directory doesn't exists

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#429]
In my composer.json, I have the following autoload config :

```json
{
    "autoload": {
        "psr-4": {
            "Test\\": "tests/",
            ...
        }
    }
}
```

If my `tests/` doesn't exist (... yet), phpactor now throws an error and can't do any phpactor commands in vim. Tested on latest master and latest develop.

**Comment by dantleech** [comment]
Hmm, can't reproduce here, can you provide the stack trace? (perhaps through the `--replay` feature if necessary)?

**Comment by dantleech** [comment]
Also, the request / response (or just which command you were running)

**Comment by Taluu** [comment]
Hum, seems I can't reproduce it either. It was better once I removed the line in composer, but even if it is restored, it doesn't seem to crash...

**Comment by dantleech** [comment]
:thinking:
