### ISSUE TITLE
Error when trying to add usings

### ISSUE THREAD

**Issue by snowiow** [phpactor/phpactor#434]
Since the latest update, I get an exception when trying to add a using. The error always looks something like this:
`Error from Phpactor: RecursiveDirectoryIterator::__construct("<path to some vendor dir>/test"): failed to open dir: No such file or directory`

Which is correct. There is a namespace declared for the test directory in the composer.json, but the directory doesn't exist. But should the search crash just because there are some misconfigured 3rd party packages included in the project?

Thanks in advance :)

**Comment by dantleech** [comment]
This should have been fixed in `develop`, you can switch in `.vimrc`: https://phpactor.github.io/phpactor/vim-plugin.html#configuration

Can you confirm that it works? (but might cherry-pick this into `master` as it's affected a few people now).

**Comment by snowiow** [comment]
Yes, on develop it works for me. Thanks

**Comment by dantleech** [comment]
Ah well, I will likely do a release later today or tomorrow, so closing this now.
