### ISSUE TITLE
Expanding a class in an XML file

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#438]
Given the following file:

```xml
<?xml version="1.0" encoding="UTF-8" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <service id="greg0ire_enum.twig.extension.enum" class="EnumExtension">
            <tag name="twig.extension"/>
        </service>
    </services>
</container>
```

when I use `phpactor#ClassExpand()"` with the cursor on the first `E`, I get: 

```xml
<?xml version="1.0" encoding="UTF-8" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <service id="greg0ire_enum.twig.extension.enum" classGreg0ire\Enum\Bridge\Twig\Extension\="EnumExtension">
            <tag name="twig.extension"/>
        </service>
    </services>
</container>
```

It works as expected on any other character.

**Comment by dantleech** [comment]
Strange, looks like this is the code to blame: https://github.com/phpactor/phpactor/blob/develop/plugin/phpactor.vim#L113

**Comment by greg0ire** [comment]
I don't understand what that char variable is representing…
https://github.com/phpactor/phpactor/blob/1b2a6358333481d5092d59a7e725a37f0a2f4755/plugin/phpactor.vim#L110

Why the `- 2`?

**Comment by greg0ire** [comment]
`ciw` might probably work, WDYT? We don't support expanding `B\C` to `A\B\C`, do we?

**Comment by dantleech** [comment]
Not currently - so I guess that should fine (would love to add tests for the VIM plugin at some point).

(eventually this should be made into a toggle (and maybe handled in PHP to intelligently handle the required level of qualification)
