### ISSUE TITLE
XPath Refactoring

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#464]
Editing the AST is not possible with the Tolerant PHP Parser, instead it supplies a small API for building up a change set which can be applied to the source code, which can be cumbersome. In addition Phpactor acts as a filter, so that we (currently) always treat entire files.

We can, however, easily convert the AST to an XML document, which in turn, can be very easily dumped as source code without any loss of information.

XML documents are mutable, and can be traversed with XPath.

- [ ] Replace AST nodes with XPath API
- [ ] Enhance AST DOM with type information
- [ ] Enhance AST DOM with Docblock nodes
- [ ] Allow Macro scripts
- [ ] Make everything Macro scripts!

### jQuery-like API

```php
$node  = // load source code
$nodes = $node->find('//MethodDeclaration//Token')->startingWith('@name', 'hello')->parent();

echo $nodes->value(); // echo the contents of all methods that start with "hello"

// rename variable
$node->find('//Variable//Token')->equals('@name', $myVar')->replace('$newName');
echo $node->value(); // print modified source code
```

If we do this, then we can drop the code builder library and instead rely on [Memio](http://memio.github.io/memio) for _generating_ new code.

### Decoration

The RAW AST tree could be enhanced with more information, f.e from WorseReflection, so that

```xml
<Variable><Token>$foobar</Token></Variable>
```

Becomes

```xml
<Variable type="string"><Token>$foobar</Token></Variable>
```

### Code Queries

With this API we could easily perform queries on an entire code base from the CLI, e.g.

```bash
$ phpactor query "//MemberDeclaration[@name="foobar] and type=BarBar]" ./**/*.php
```

### Renaming

... and we could also replace the current confusion of `references:[member|class]` and `class:move` with a single, more flexible command, for example:

```
$ phpactor query "//MemberDeclaration[@name="foobar] and type="BarBar"]//Token" --replace="Barfoo"`./**/*.php
```

---

Work on the "XML Editor" is going on here: https://github.com/dantleech/xml-editor

**Comment by weirdan** [comment]
Sounds good, but it would have to preserve source code formatting.

**Comment by dantleech** [comment]
> Sounds good, but it would have to preserve source code formatting.

It would preserve the source code formatting (more so than the current, general, approach). But it's quite risky in terms of return-on-investment. Going to stick with more incremental improvements for now. The main goal is to reduce the time required to implement new refactorings.

**Comment by dantleech** [comment]
Putting this idea to rest for now.
