### ISSUE TITLE
[completion] Gherkin / Behat Completion

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#471]
Would be quite interesting to support completion for Behat feature files, could be done:

- Parse `behat.yml[behat.yml.dist`, reflect all contexts.
- Parse the docblocks
- Profit.

Would also need to enable completion, f.e. with OmniComplete in VIM for `.feature` files (possibly with a different completion function to allow completing sentences).

This might be a better candidate for a plugin - when that is an option - in which case it could be coupled with a goto definition handler for going to context stages.

**Comment by haringsrob** [comment]
Check out https://github.com/haringsrob/vim-behat

**Comment by dantleech** [comment]
done in [behat extension](https://github.com/phpactor/behat-extension)
