### ISSUE TITLE
Available contextual actions should be determined by Macros.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#500]
Currently the context menu is determined from a static `menu.json` file, with keys based on the node symbol type.

It would be more effective if the refactorings/transformers (or generally Macros) could be queried to see which could perform an action on the given node / offset in a source file.

This would:

- Reduce the number of menu options in some cases (because some are not relevant).
- Allow more contextual possibilities e.g. the class body (f.e. `generate_method`).
- Increase the ease of extension (i.e. no more `menu.json`).
- Generalization would mean less bugs (no more manual mapping of parameters, more testable).

Pre-requisite would probably be generalizing the refactorings as Macros (#487 ).

Then Macros could implement an interface `ContextuallyAware` (for example).

**Comment by weirdan** [comment]
Would there be any way to make shortcut keys stable? For example, currently 'Go to definition' sometimes invoked with `g` and sometimes with `o`.

**Comment by dantleech** [comment]
I think this would be a separate issue, currently the shortcuts are generated (the first char is used unless it is already taken).

I guess a solution might be to allow the shortcuts to be mapped in the VIM plugin (e.g. `{ "g": "goto_definition" }`) that map would then take precedence. But we should create another issue for this.
