### ISSUE TITLE
[VIM] Unknown function: phpactor#Status()

### ISSUE THREAD

**Issue by YaroslavMolchan** [phpactor/phpactor#507]
Hello, I try to install phpactor as vim plugin using this instructions: https://phpactor.github.io/phpactor/vim-plugin.html

I also installed it with vim-plug, composer install works good, but when I try to check status or other function got same error that function not found.

![image](https://user-images.githubusercontent.com/9335727/41655369-5315dc94-7495-11e8-9491-59ee576d57e4.png)

I used gVIM on Ubuntu 18.04, my VIM version:

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
> Included patches: 1-1453

**Comment by dantleech** [comment]
When using VIM Plug you will need to open a PHP file before Phpactor is registered.

**Comment by dantleech** [comment]
@YaroslavMolchan can you confirm?

**Comment by YaroslavMolchan** [comment]
@dantleech yes, that was a problem, sorry for late reply, forgot about it.
