### ISSUE TITLE
Support PHP 7.2

### ISSUE THREAD

**Issue by cmizzi** [phpactor/phpactor#508]
```bash
>$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for monolog/monolog ^2.0@dev -> satisfiable by monolog/monolog[2.x-dev].
    - monolog/monolog 2.x-dev requires php ^7.1 -> your PHP version (7.2.5-0ubuntu0.18.04.1) overridden by "config.platform.php" version (7.0.0) does not satisfy that requirement.
```
If I change the version of `monolog` in order to make working composer installation, the RPC doesn't work properly.

**Comment by EvanDotPro** [comment]
Interestingly, I was able to install on PHP 7.2 just fine (without any dep errors about monolog), but I'm stuck with:

`"Notice: Undefined property: Microsoft\PhpParser\MissingToken::$parent"`

When trying to jump to definition.

**Comment by dantleech** [comment]
The Monolog issue is related to doing a `composer update` I think. It's currently locked to a version compatible to a version which should work. You should never really do a `composer update`, instead simply do `composer install`.

@EvanDotPro could you create a new issue? If posible include the code that caused it (it may well be 7.2 specific as I don't use that on a daily basis). If you feel it would help, you can also get the stack trace if you run [replay](https://phpactor.github.io/phpactor/developing.html#debugging-rpc) with the `--verbose` flag.

**Comment by dantleech** [comment]
@cmizzi please re-open this issue if a `git reset --hard` and `composer install` does not fix your issue.
