### ISSUE TITLE
Easyer rename variable, Feature on rpc methods (phpactor#ContextMenu())

### ISSUE THREAD

**Issue by talbergs** [phpactor/phpactor#509]
Let the vim plugin contain a ton of methods.

It is tedious to open context menu, then wait for inteligence (possible actions) via rpc, then choose (r)rename or (f)ind references, but I knew that I want to rename beforehand, I would like to map this to hotkey.

phpactor#Transform() is another example

**Comment by dantleech** [comment]
The problem is that Phpactor is extendable at runtime. The VIM plugin is static. I won't add all the possible short-cuts to all the RPC functions.

There is nothing to stop you adding your own shortcuts though, e.g.

```
function! MyGotoDefinition()
    call phpactor#rpc("goto_definition", { "offset": phpactor#_offset(), "source": phpactor#_source(), "path": expand('%:p')})
endfunction
```

**Comment by talbergs** [comment]
yes, the other option, alright then. Thank you for the snippet, there I can begin.
