### ISSUE TITLE
Completion does not work below the modulo-constant construct

### ISSUE THREAD

**Issue by weirdan** [phpactor/phpactor#523]
```php
<?php

class A
{
    const SOME_CONSTANT = 10;
    /** @var string */
    private $q;

    public function works(): void
    {
        if ($i++ % 10 === 0) {

        }
    }
    public function fails(): void
    {
        if (10 % self::SOME_CONSTANT) { // <==== below this line completion stops working
        }
    }

    public function noLongerWorks(): void
    {
    }

}
```

**Comment by dantleech** [comment]
Yeah, it's "Modulo by zero" Fatal Error as it evaluates that expression , the express ion evaluator doesn't currently handle class members. I guess we could add safeguards to avoid division by zero errors.

**Comment by dantleech** [comment]
This is a first try at handling this: https://github.com/phpactor/worse-reflection/pull/46

Basically if the right value is zero-ish, just evaluate as 0 rather than crashing.

**Comment by dantleech** [comment]
Fixed.
