### ISSUE TITLE
VIM: Support balloon popup

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#526]
https://github.com/neovim/neovim/issues/2544

Currently this feature is not supported in Neovim, but in VIM 8 it would allow a "hover" dialog (which could be used to show type information etc).

**Comment by mamazu** [comment]
This is done? Howering works.

**Comment by dantleech** [comment]
This is about vim (not neovim) support for balloon popup. As we don't actively develop the VIM pluigj it can be closed.
