### ISSUE TITLE
platform config in composer.json should be removed

### ISSUE THREAD

**Issue by akrabat** [phpactor/phpactor#532]
This section in composer.json:

```
    "config": {
        "platform": {
            "php": "7.0.0"
        }
    },

```

means that it tries to install with PHP 5.6 and then fails with a parse error rather than failing with a message about the wrong PHP version.

I don't think that this section is needed, and so should be removed.

**Comment by dantleech** [comment]
I can't remember the exact reason for adding this (was probably just a local hack to test on 7.0).

But why would it try to install with 5.6? In anycase, happy to have this removed.

**Comment by dantleech** [comment]
Fixed, I forgot what this did, hence my confusion.

**Comment by dantleech** [comment]
huh, this was being used to make composer update it's deps for 7.0 (and not f.e. 7.2 and breaking compatibility with 7.0).

I think it better to reintroduce the platform req. and add a require `php >= 7.0`.

**Comment by dantleech** [comment]
if I set the required PHP version to `7.1` and the platform to `7.0` it is _not_ possible to install Phpactor. So not sure how it would be possible to install on PHP5.6.

So, a bit confused. But this is required in composer so that I can build Phpactor with dependencies which are supported with the minimal supported PHP version (at the moment 7.0).
_

**Comment by akrabat** [comment]
It seems to allow the other way around. i.e. you can set platform to 7.1 and install from 7.0.

**Comment by akrabat** [comment]
I have no idea why it installed either. I can just as easily detect in my .vimrc though and not include the `Plug` line.

**Comment by dantleech** [comment]
> i.e. you can set platform to 7.1 and install from 7.0.

but only because it has `require: php => ^7.0` I think.

maybe it doesn't make any different when there is ` .lock` file :thinking:
