### ISSUE TITLE
Incorrect offset? completion with multi-byte chars

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#539]
```
    public function getSubscribedEvents(EventCollectionInterface $eventCollection)
    {
        // 姓名


        $this->

```

Causes an exception, as the offset seems to be incorrectly inferred.

**Comment by kristijanhusak** [comment]
Is this caused by the latest change that we had due to performance issues?

**Comment by dantleech** [comment]
I don't think so, as those havn't been merged into `master` yet.

**Comment by kermorgant** [comment]
Just stumbled on the same issue using emacs [phpactor.el](https://github.com/emacs-php/phpactor.el) package

**Comment by dantleech** [comment]
See #538

**Comment by dantleech** [comment]
Should be fixed in https://github.com/phpactor/completion/pull/12 and updated develop when #538 is merged.

**Comment by dantleech** [comment]
Fixed!
