### ISSUE TITLE
[WorseReflection] Allow aliased when importing trait not offered as completion candidate

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#540]
Given a trait used like this

```php
    use TranslatableTrait {
        __construct as private initializeTranslationsCollection;
    }
```

It would be nice to have ``initializeTranslationsCollection`` offered as a completion candidate.

**Comment by dantleech** [comment]
Made a start on this: https://github.com/phpactor/worse-reflection/pull/50/files
