### ISSUE TITLE
[Completion] BC break: rename `info` field in suggestions

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#547]
The `info` field from the completion suggestions is based on the VIM `info` field for completion functions

```
	info		more information about the item, can be displayed in a
			preview window
```

But actually it is used as the `menu` text:

```
	menu		extra text for the popup menu, displayed after "word"
			or "abbr"
```

We should rename this to something more descriptive and decouple it from any VIM meaning.

Change the name to `short_description` or `synopsis`

**Comment by kermorgant** [comment]
also used in [phpactor.el](https://github.com/emacs-php/phpactor.el/blob/c5328bbff39fa7a976e5bcd5943c9950b3159d28/company-phpactor.el#L59) for completion

![image](https://user-images.githubusercontent.com/10561580/43673764-08b46a12-97d1-11e8-97b7-d86c0e296601.png)

**Comment by dantleech** [comment]
Name changed to `short_description`, will probably remove in 0.10.0
