### ISSUE TITLE
[emacs] provide version information in rpc response

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#554]
phpactor.el is distributed through [melpa repository](https://melpa.org/#/phpactor).

Users could get a newer version of phpactor.el and be required to upgrade phpactor by themselves in case of BC in the rpc protocol.

When that happen, it would be useful to retrieve version information from phpactor in order to fail gracefully if an outdated version of phpactor is detected.

**Comment by kermorgant** [comment]
Or just use a date in format YYYYMMDD indicating the date of the last change in the rpc protocol . That would be the easiest to compare against

**Comment by weirdan** [comment]
Do you release on master/develop because of vim plugin managers limitation?

**Comment by dantleech** [comment]
Basically - master is "stable". Also was thinking of using composer to install Phpactor...

**Comment by kermorgant** [comment]
> although the RPC protocol may not change, the features exposed by Phpactor might

I'm not sure I get your point, would you have an example how this might affect the emacs package ?

If you opt for a constant to update in the code, then perhaps it might make sense to version the rpc protocol itself to require a bit less effort (you won't change it on every version, right ;-)

**Comment by dantleech** [comment]
Will provide an independent RPC version in #589
