### ISSUE TITLE
Import class on `extends`: Offer to alias if name same as current class

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#560]
e.g.

```
<?php

namespace Pyz\Yves\StepEngine\Process;

use Spryker\Yves\StepEngine\Process\StepCollection;

class StepCollection extends StepCollection
{
}
```

Should offer to alias `StepCollection` and update the already existing name to the given alias.

**Comment by mamazu** [comment]
This already works for the completion engine.
![image](https://github.com/phpactor/phpactor/assets/14860264/ef03b932-81fc-4252-a8cc-285dac891dc9)

and when accepted it also automatically inserts the aliased import.
![image](https://github.com/phpactor/phpactor/assets/14860264/586b461d-5eb0-4094-a7f8-29ecd6df3d0a)

So do we need a diagnostic for it or is this issue resolved?

**Comment by dantleech** [comment]
Well spotted, it can be closed
