### ISSUE TITLE
don't suggest php functions as completion candidates for return types

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#569]
Here's an example of what would be nice to avoid

![image](https://user-images.githubusercontent.com/10561580/44146162-147b0864-a097-11e8-8b6c-a09e877b5c22.png)

**Comment by kermorgant** [comment]
Just as a reminder (I might take a stab at this in a near future...), here's a related comment from slack 

> could negate it here: 
 https://github.com/phpactor/completion/blob/master/lib/Bridge/TolerantParser/WorseReflection/WorseFunctionCompletor.php#L42
`if ($node->parent instanceof MethodDeclartion) { return }` or similar
not sure if there could be a more generate rule

**Comment by mamazu** [comment]
This is also not reproducible in the most recent version of Phpactor.

**Comment by dantleech** [comment]
indeed
