### ISSUE TITLE
[CT] Render aliases correctly in the code builder

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#574]
**Update**: Currently type aliases provided to the code builder are rendered by their short name only. We should change this logic so that we render them according to the class imports of the context class.

---

Given 

```php

use SM\Factory\Factory as StateMachineFactory;

class Something
{
    public function __construct(StateMachineFactory $smFactory)
    {
    }
```

complete constructor generates a ``@var Factory`` instead of ``@var StateMachineFactory``

```php

class Something
{
    /**
     * @var Factory
     */
    private $smFactory;

    public function __construct(StateMachineFactory $smFactory)
    {
        $this->smFactory            = $smFactory;
    }
```

**Comment by dantleech** [comment]
Fixed in #887
