### ISSUE TITLE
use ordering seems ... incorrect?

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#575]
```
use A\B\C\Process\ExpanderInterface;
use A\B\C\Process\Expander\Exception\SomeException;
```

Phpactor will insert the `SomeExcetpion`, after the previous above, even when some (all?) CS tools will think that it should be before (i.e. comparing **I**nterface and **E**xception, instead of **I**nterface and `\`SomeException)

**Comment by Einenlum** [comment]
Is there somewhere an rule very precisely described to decide of the order of the use statements?

**Comment by dantleech** [comment]
Maybe just a question of taste, could be configurable..
