### ISSUE TITLE
yii 1.1 config to phpactor

### ISSUE THREAD

**Issue by hneis** [phpactor/phpactor#603]
Hey. I cannot configure php actor to work properly with yii 1.1.
When i type -> in my code:
`class A extends B {
public function foo() {
$this->
}
}
`
Appears error: [ncm2_papator@yarp] KeyError: 'suggestions'
But if i remove `extends B` its work fine

`#:phpactor offset:info my.php 1032 --verbose` say:
[Phpactor\WorseReflection\Core\Exception\SourceNotFound]
Could not locate function with Reflection: "ActiveRecordGroupPolicy"

What i can do, to this work?

**Comment by dantleech** [comment]
`[ncm2_papator` <- I assume this is [ncm2-phpactor](https://github.com/phpactor/ncm2-phpactor)?

The `KeyError` sounds like a bug in the plugin for not handling errors?

The second error is more likely the actual problem.

Can you provide a stack trace for the second command and the source code around offsert 1032 ?

**Comment by hneis** [comment]
`#:/home/hneis/nvim/plugged/phpactor/bin/phpactor offset:info /home/hneis/www/uk-standart/protected/models/Room.php 993 --verbose                                             J:3 17:30
[2018-09-27 17:30:15] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Statement\ClassDeclaration [] []
[2018-09-27 17:30:15] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Parameter [] []


  [Phpactor\WorseReflection\Core\Exception\SourceNotFound]
    Could not find source with "ActiveRecordGroupPolicy"
    
    
    Exception trace:
     () at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCodeLocator/ChainSourceLocator.php:36
      Phpactor\WorseReflection\Core\SourceCodeLocator\ChainSourceLocator->locate() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CoreReflector.php:135
       Phpactor\WorseReflection\Core\Reflector\CoreReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php:81
        Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php:74
         Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php:149
          Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->parent() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php:222
           Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->methods() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:371
            Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveParameterFromReflection() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:327
             Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveParameter() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:136
              Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->__resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:107
               Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->_resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:91
                Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:125
                 Phpactor\WorseReflection\Core\Inference\FrameBuilder->resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder/FunctionLikeWalker.php:95
                  Phpactor\WorseReflection\Core\Inference\FrameBuilder\FunctionLikeWalker->walkFunctionLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder/FunctionLikeWalker.php:48
                   Phpactor\WorseReflection\Core\Inference\FrameBuilder\FunctionLikeWalker->walk() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:96
                    Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:79
                     Phpactor\WorseReflection\Core\Inference\FrameBuilder->build() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php:60
                      Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/SourceCode/ContextualSourceCodeReflector.php:52
                       Phpactor\WorseReflection\Core\Reflector\SourceCode\ContextualSourceCodeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php:90
                        Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/lib/Extension/WorseReflection/Application/OffsetInfo.php:45
                         Phpactor\Extension\WorseReflection\Application\OffsetInfo->infoForOffset() at /home/hneis/nvim/plugged/phpactor/lib/Extension/WorseReflection/Command/OffsetInfoCommand.php:50
                          Phpactor\Extension\WorseReflection\Command\OffsetInfoCommand->execute() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Command/Command.php:264
                           Symfony\Component\Console\Command\Command->run() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:874
                            Symfony\Component\Console\Application->doRunCommand() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:228
                             Symfony\Component\Console\Application->doRun() at /home/hneis/nvim/plugged/phpactor/lib/Application.php:48
                              Phpactor\Application->doRun() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:130
                               Symfony\Component\Console\Application->run() at /home/hneis/nvim/plugged/phpactor/bin/phpactor:43
                               
                               
                                 [Phpactor\WorseReflection\Core\Exception\SourceNotFound]
                                   Could not find source with "ActiveRecordGroupPolicy"
                                   
                                   
                                   Exception trace:
                                    () at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCodeLocator/ChainSourceLocator.php:36
                                     Phpactor\WorseReflection\Core\SourceCodeLocator\ChainSourceLocator->locate() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCodeLocator/ChainSourceLocator.php:34
                                      Phpactor\WorseReflection\Core\SourceCodeLocator\ChainSourceLocator->locate() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CoreReflector.php:135
                                       Phpactor\WorseReflection\Core\Reflector\CoreReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php:81
                                        Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php:74
                                         Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php:149
                                          Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->parent() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php:222
                                           Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->methods() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:371
                                            Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveParameterFromReflection() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:327
                                             Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveParameter() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:136
                                              Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->__resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:107
                                               Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->_resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:91
                                                Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:125
                                                 Phpactor\WorseReflection\Core\Inference\FrameBuilder->resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder/FunctionLikeWalker.php:95
                                                  Phpactor\WorseReflection\Core\Inference\FrameBuilder\FunctionLikeWalker->walkFunctionLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder/FunctionLikeWalker.php:48
                                                   Phpactor\WorseReflection\Core\Inference\FrameBuilder\FunctionLikeWalker->walk() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:96
                                                    Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:79
                                                     Phpactor\WorseReflection\Core\Inference\FrameBuilder->build() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php:60
                                                      Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/SourceCode/ContextualSourceCodeReflector.php:52
                                                       Phpactor\WorseReflection\Core\Reflector\SourceCode\ContextualSourceCodeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php:90
                                                        Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/lib/Extension/WorseReflection/Application/OffsetInfo.php:45
                                                         Phpactor\Extension\WorseReflection\Application\OffsetInfo->infoForOffset() at /home/hneis/nvim/plugged/phpactor/lib/Extension/WorseReflection/Command/OffsetInfoCommand.php:50
                                                          Phpactor\Extension\WorseReflection\Command\OffsetInfoCommand->execute() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Command/Command.php:264
                                                           Symfony\Component\Console\Command\Command->run() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:874
                                                            Symfony\Component\Console\Application->doRunCommand() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:228
                                                             Symfony\Component\Console\Application->doRun() at /home/hneis/nvim/plugged/phpactor/lib/Application.php:48
                                                              Phpactor\Application->doRun() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:130
                                                               Symfony\Component\Console\Application->run() at /home/hneis/nvim/plugged/phpactor/bin/phpactor:43
                                                               
                                                               
                                                                 [Phpactor\WorseReflection\Core\Exception\SourceNotFound]
                                                                   Could not locate function with Reflection: "ActiveRecordGroupPolicy"
                                                                   
                                                                   
                                                                   Exception trace:
                                                                    () at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCodeLocator/NativeReflectionFunctionSourceLocator.php:22
                                                                     Phpactor\WorseReflection\Core\SourceCodeLocator\NativeReflectionFunctionSourceLocator->locate() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCodeLocator/ChainSourceLocator.php:34
                                                                      Phpactor\WorseReflection\Core\SourceCodeLocator\ChainSourceLocator->locate() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/SourceCodeLocator/ChainSourceLocator.php:34
                                                                       Phpactor\WorseReflection\Core\SourceCodeLocator\ChainSourceLocator->locate() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CoreReflector.php:135
                                                                        Phpactor\WorseReflection\Core\Reflector\CoreReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/ClassReflector/MemonizedReflector.php:81
                                                                         Phpactor\WorseReflection\Core\Reflector\ClassReflector\MemonizedReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php:74
                                                                          Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectClassLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php:149
                                                                           Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->parent() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflection/ReflectionClass.php:222
                                                                            Phpactor\WorseReflection\Bridge\TolerantParser\Reflection\ReflectionClass->methods() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:371
                                                                             Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveParameterFromReflection() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:327
                                                                              Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveParameter() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:136
                                                                               Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->__resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:107
                                                                                Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->_resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/SymbolContextResolver.php:91
                                                                                 Phpactor\WorseReflection\Core\Inference\SymbolContextResolver->resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:125
                                                                                  Phpactor\WorseReflection\Core\Inference\FrameBuilder->resolveNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder/FunctionLikeWalker.php:95
                                                                                   Phpactor\WorseReflection\Core\Inference\FrameBuilder\FunctionLikeWalker->walkFunctionLike() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder/FunctionLikeWalker.php:48
                                                                                    Phpactor\WorseReflection\Core\Inference\FrameBuilder\FunctionLikeWalker->walk() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:96
                                                                                     Phpactor\WorseReflection\Core\Inference\FrameBuilder->walkNode() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Inference/FrameBuilder.php:79
                                                                                      Phpactor\WorseReflection\Core\Inference\FrameBuilder->build() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Bridge/TolerantParser/Reflector/TolerantSourceCodeReflector.php:60
                                                                                       Phpactor\WorseReflection\Bridge\TolerantParser\Reflector\TolerantSourceCodeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/SourceCode/ContextualSourceCodeReflector.php:52
                                                                                        Phpactor\WorseReflection\Core\Reflector\SourceCode\ContextualSourceCodeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/vendor/phpactor/worse-reflection/lib/Core/Reflector/CompositeReflector.php:90
                                                                                         Phpactor\WorseReflection\Core\Reflector\CompositeReflector->reflectOffset() at /home/hneis/nvim/plugged/phpactor/lib/Extension/WorseReflection/Application/OffsetInfo.php:45
                                                                                          Phpactor\Extension\WorseReflection\Application\OffsetInfo->infoForOffset() at /home/hneis/nvim/plugged/phpactor/lib/Extension/WorseReflection/Command/OffsetInfoCommand.php:50
                                                                                           Phpactor\Extension\WorseReflection\Command\OffsetInfoCommand->execute() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Command/Command.php:264
                                                                                            Symfony\Component\Console\Command\Command->run() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:874
                                                                                             Symfony\Component\Console\Application->doRunCommand() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:228
                                                                                              Symfony\Component\Console\Application->doRun() at /home/hneis/nvim/plugged/phpactor/lib/Application.php:48
                                                                                               Phpactor\Application->doRun() at /home/hneis/nvim/plugged/phpactor/vendor/symfony/console/Application.php:130
                                                                                                Symfony\Component\Console\Application->run() at /home/hneis/nvim/plugged/phpactor/bin/phpactor:43
                                                                                                
                                                                                                offset:info [--frame] [--format FORMAT] [--] <path> <offset>
`

**Comment by dantleech** [comment]
How is `ActiveRecordGroupPolicy` defined? is it autoloaded by composer? or is there magic in the Yii framework?

**Comment by hneis** [comment]
I think it's magically loaded by the yii framework.

**Comment by dantleech** [comment]
> Shoud i wrote $loader->add('some.namespace', 'some/dir'); for all module?

I don't know how Yii works .. but if you have access to the namespace / dir mapping then :+1: I guess.

**Comment by dantleech** [comment]
Phpactor in LSP uses the indexer, so probably this is "fixed" now.
