### ISSUE TITLE
[VIM Plugin] phpactor#GoToDefinition should add to tagstack

### ISSUE THREAD

**Issue by joereynolds** [phpactor/phpactor#620]
If I navigate to a function's definition with `:call phpactor#GoToDefinition()`, I expect to be able to hit `<c-t>` to go to where I was just before I went to the definition.

See `:help tagstack` if you've not heard of it before, it's pretty useful!

**Comment by dantleech** [comment]
Not sure it is possible to "add" to the tagstack (at least I can't find the documentation on that) and Phpactor doesn't use tags.

I personally use `<ctrl>-o` and `<ctrl>-i` to jump forwards and backwards (based on cursor position).

**Comment by joereynolds** [comment]
Fair enough, worth asking I guess :smile:

**Comment by dantleech** [comment]
No absolute reason we couldn't implement this in the plugin itself, but will close for now :)

**Comment by daraul** [comment]
Forgive my ignorance, but is there any reason phpactor can't just generate the tags file?

**Comment by dantleech** [comment]
Anything's possible. But the question is why would you want to?

Phpactor doesn't create any database, it guesses locations using composer (or information available to the environment, e.g. defined functions), it then works in real-time to provide the information required.

It would be relatively easy to build a database and use that instead of composer, and by the same method generate a tags file if you really wanted.

**Comment by daraul** [comment]
I think it'd be useful since vim already has support for ctags out of the box, which means that generating the file should make using phpactor easier for people that are already used to that.

**Comment by daraul** [comment]
Something else that I've stumbled on, is that since phpactor seems to stop working if I'm debugging a php file using Vdebug. Wouldn't generating the tags file get around this?

**Comment by dantleech** [comment]
Phpactor is not indexing your code, it does everything in realtime - generating a ctags file would not be useful for Phpactor, and would mean introducing the overhead of maintaining the tags file.

If Phpactor were to implement indexing it would need to do it with a database or similar, where the relationships between code entities could be maintained, something that ctags cannot do (AFAIK).
