### ISSUE TITLE
Error detected while processing functino phpactor#Complete E714 List required

### ISSUE THREAD

**Issue by CaptainQuirk** [phpactor/phpactor#631]
Hi there,

**Vim version** : **8.1**
**OS** : **Linux Mint 18.2**
**PHP** : **7.2.10**
**composer** : **1.5.6**
**Plugin version** : `bd0bdf6` on **develop**

Just updated the develop branch this morning. I updated the dependencies manually twice to be sure and I just ran `phpactor#Update()` from within **vim**.

I get the aforementioned error when trying to autocomplete (practically all the time since autocomplete happens automatically in my vim setup).

Thanks in advance !

**Comment by dantleech** [comment]
yep, looks like the output format changed, should be fine now :)

**Comment by CaptainQuirk** [comment]
Thanks !
