### ISSUE TITLE
Support inclusion returns

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#662]
If I require a file, and it has a return, I should be able to have a context on it.

```php
class Foo
{
    public function getBar() { }
}
```

```php
<?php
return new Foo;
```

```php
<?php
$foo = require 'get_foo.php';

$foo->getBar();
```

This can be used with the autoloader requirement or a bootstrap file ; it would be great to have a support. :}

Currently, we have to add a `/** @var Foo $foo */` on top of the require instruction. It's not that bad though. :D

**Comment by dantleech** [comment]
PR for basic support: https://github.com/phpactor/worse-reflection/pull/52

Currently it supports simple sasignment as in this example and importing the scope of the included file. Doesn't support registering any new class definitions yet.

**Comment by dantleech** [comment]
Although that is merged, it won't work until the completion library is made aware of the path of the osurce code to complete, which is quite a big change.

**Comment by dantleech** [comment]
fwiw the basic support was removed and won't be coming back soon (imagine legacy projects and 100s of include files all being analysed and you can see why). But also closing because old.
