### ISSUE TITLE
[regression] Custom templates are generating the default class

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#669]
e,g,

```
:call phpactor#ClassNew()
Variant: 
[s]ymfony_command, (e)xception, (p)hpunit_test, (d)efault, (v)alue_object: 
```

always generates the `default` template no matter which variant is selected.

**Comment by mskubas** [comment]
Hi, it's broken again. I couldn't figure out what's wrong but the latest working one is [0.11.1](https://github.com/phpactor/phpactor/releases/tag/0.11.1).

Btw, thank you for this great tool.
