### ISSUE TITLE
Variable type injection via docblock does not completion

### ISSUE THREAD

**Issue by maamo888** [phpactor/phpactor#678]
### Install

```
composer require slim/slim
```

### Code (index.php)

```php
<?php
require 'vendor/autoload.php';

/** @var \Slim\App $app */
$app->|
```

### Phpactor (Snap shot)

<img width="585" alt="phpactor_variable_type_not_completion_" src="https://user-images.githubusercontent.com/14961986/50292976-e2130600-04b5-11e9-8d0a-8ca67a68662f.png">

### In the case of phpcd.vim under the same condition (Snap shot)

<img width="580" alt="phpcd_variable_type_not_completion_" src="https://user-images.githubusercontent.com/14961986/50293389-cbb97a00-04b6-11e9-93e8-8689839f0af0.png">

https://github.com/lvht/phpcd.vim

**Comment by dantleech** [comment]
It will work if it was assigned to something (or was before a for statement):

![untitled](https://user-images.githubusercontent.com/530801/50308321-c9452900-0492-11e9-9801-18a64556940e.png)

**Comment by maamo888** [comment]
In phpactor we could complete the complement by writing the symbol `$app = null;`.

However `phpstorm` and `phpcd.vim` can complement without symbols.

### phpactor (snap shot)

<img width="628" alt="1_phpactor_variable_docblock_completion_1" src="https://user-images.githubusercontent.com/14961986/50318526-00542280-0505-11e9-81b6-dce751f4365e.png">

### phpstorm (snap shot)

<img width="794" alt="2_phpstorm_variable_docblock_completion_1" src="https://user-images.githubusercontent.com/14961986/50318597-82444b80-0505-11e9-8869-234ac5cefbba.png">

### phpcd.vim (snap shot)

<img width="556" alt="3_phpcd_variable_docblock_completion_1" src="https://user-images.githubusercontent.com/14961986/50318600-88d2c300-0505-11e9-8417-b62af0324237.png">

**Comment by maamo888** [comment]
Thanks !
