### ISSUE TITLE
Completion of virtuals method and property

### ISSUE THREAD

**Issue by maamo888** [phpactor/phpactor#682]
Hello dantleech.

Thank you for a useful `phpactor`.

Is this PR feature of `worse-reflection` still not supported?

https://github.com/phpactor/worse-reflection/pull/51

* `@method`
* `@method static`
* `@property`

**Example use case**

* Generater class of `Faker`
    * https://github.com/fzaninotto/Faker/blob/master/src/Faker/Generator.php

* Route Facade class of `Laravel`
    * https://github.com/laravel/framework/blob/5.7/src/Illuminate/Support/Facades/Route.php

* DB Facade class of `Laravel`
    * https://github.com/laravel/framework/blob/5.7/src/Illuminate/Support/Facades/DB.php

**Comment by dantleech** [comment]
This is a duplicate of #384 and fixed in https://github.com/phpactor/worse-reflection

**Comment by maamo888** [comment]
I tried it with this procedure.

```
cd $HOME/.local/share/nvim/plugged/phpactor/vendor/phpactor/worse-reflection
git pull

cd $HOME/.local/share/nvim/plugged/phpactor
composer update
```

Great! It became very comfortable.

**Comment by maamo888** [comment]
I'm waiting for expectation that it will be reflected in the release of phpactor itself.

**Comment by maamo888** [comment]
Hello dantleech.

Completion of virtual method can not be done from this commit. :(

https://github.com/phpactor/phpactor/commit/b7370282ad668c6cd2309f4cbe3a84ff6fb6f8a0

**Comment by maamo888** [comment]
Oh, Sorry, No problem! 

:)

https://github.com/phpactor/phpactor/commit/ed934f7de05c76b7c6f4ff2990177d01716d97be

**Comment by dantleech** [comment]
yes, seems I didn't merge it when I thought I did :laughing:
