### ISSUE TITLE
[Vim] In the find reference quick-fix, get a snippet / context on how the method / variable is used

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#706]
Currently, doing a `phpactor#FindRerences()` gives us the list of files / lines where the member is used, but without any contexts.

Having such a context would really help, especially when you need to filter those

**Comment by dantleech** [comment]
Do you mean showing the line excerpt in the quick-fix list?

**Comment by Taluu** [comment]
Exactly that, currently we only have a `.`

**Comment by dantleech** [comment]
Done

**Comment by Taluu** [comment]
Works great, thanks. :+1:
