### ISSUE TITLE
[completion] Don't truncate union types

### ISSUE THREAD

**Issue by weirdan** [phpactor/phpactor#711]
When completing a variable typed as `A|B` (either from docblock or [catch typehint union](https://wiki.php.net/rfc/multiple-catch)) phpactor only shows `A` in completion menu item description.

**Comment by dantleech** [comment]
Also in develop this seems to work:
![untitled](https://user-images.githubusercontent.com/530801/51353134-9dc05900-1aa7-11e9-9daa-d73511df41cc.png)

Is there a specific scenario?

**Comment by weirdan** [comment]
![image](https://user-images.githubusercontent.com/57403/51355308-770e1c80-1abf-11e9-9482-f3675ad9b3c9.png)

`phpactor` completion is used through `ncm2`, with `phpactor/ncm2-phpactor` bridge

Invoking completion directly from cli, I'm getting this:
```console
$  ~/.config/nvim/bundle/phpactor/bin/phpactor complete --format=json src/App/src/Q.php 141 | jq
{
  "suggestions": [
    {
      "type": "variable",
      "name": "$v",
      "label": "$v",
      "short_description": "float",
      "class_import": null,
      "range": null,
      "info": "float"
    },
    {
      "type": "variable",
      "name": "$p",
      "label": "$p",
      "short_description": "null",
      "class_import": null,
      "range": null,
      "info": "null"
    },
    {
      "type": "variable",
      "name": "$this",
      "label": "$this",
      "short_description": "Q",
      "class_import": null,
      "range": null,
      "info": "Q"
    }
  ],
  "issues": []
}
```
So it does appear to be a problem with the phpactor itself.

Phpactor version: dev-develop@660eb584fcf228e627c94b1894b39e7b12a69a9b

**Comment by weirdan** [comment]
If I **omit var name** in `@var` annotation I do get a union (as in your example). If it's included (as it is in mine) menu only shows the first union member.

**Comment by dantleech** [comment]
https://github.com/phpactor/worse-reflection/commit/5b2bb567b5c6c25db7fa0f75d017cbbff74e1f47
kk

and

https://github.com/phpactor/worse-reflection/commit/4892ffd1d575ecb106c5ee69fc40d9673d1b293fhttps://github.com/phpactor/worse-reflection/commit/4892ffd1d575ecb106c5ee69fc40d9673d1b293f
