### ISSUE TITLE
if ($var instanceof Type) should narrow type in if body

### ISSUE THREAD

**Issue by weirdan** [phpactor/phpactor#740]
Consider the following code
```php
<?php

class A { public function mA(): void {} }
class B { public function mB(): void {} }
class C { public function mC(): void {} }


/** @param A|B|C $c */
function f($c): void
{
    if ($c instanceof A) {
        $c
    } elseif ($c instanceof B) {
        $c
    } elseif ($c instanceof C) {
        $c
    } elseif ($c instanceof RuntimeException) { // never
        $c
    }
}

f(rand(0,1) ? new A : rand(0, 1) ? new B : new C);
```
Here phpactor thinks `$c` is `A|B|C|RuntimeException` in all branches. However it would be much more useful to narrow `$c` to asserted types in the `if` body, so that `$c` is `B` in `$c instanceof B` branch.

Ideally, in `else` branch type would be narrowed to `typeof($c) & !B`, so that in `if ($c instanceof B) { } else { $c }` `$c` would be `A|C`.

There are tools that can do more comprehensive type inference (like [Psalm](https://github.com/vimeo/psalm)), could phpactor perhaps provide a way to integrate those into completion/hover?

**Comment by mamazu** [comment]
In this case `A`, `B`, `C` as classes get properly narrowed.

But in the case where it tries to narrow down to an impossible type, it still doesn't give you a warning and just assumes the type to be true. I don't think that this needs to be part of phpactor since this should be the job of the static analyzer.

**Comment by dantleech** [comment]
yes I think this can be closed. The `if` branch logic was improved significantly with the new type system, but still not perfect. But for above cases I think it works.
