### ISSUE TITLE
Autoload key are not know

### ISSUE THREAD

**Issue by mdphoto** [phpactor/phpactor#743]
Hi, 
Conf :
- Drupal8
- Composer
- Lando (Docker)
- Emacs

I folowed https://phpactor.github.io/phpactor/integrations.html (mismatch in file name phpactor_autoload.php autoload_phpactor.php?)

I create .phpactor.yml and phpactor_autoload.php
But i run phpactor status I'have this error

In Resolver.php line 55:                                                                                                                                                                           
 Key(s) "autoload" are not known, known keys: "console_dumper_default", "xdebug_disable", "command", "class_to_file.project_root", "code_transform.class_new.variants",   
  "code_transform.template_paths", "code_transform.indentation", "code_transform.refactor.generate_accessor.prefix", "code_transform.refactor.generate_accessor.upper_cas  
  e_first", "completion_worse.completor.class.limit", "navigator.destinations", "navigator.autocreate", "rpc.store_replay", "rpc.replay_path", "source_code_filesystem.pr  
  oject_root", "worse_reflection.enable_cache", "worse_reflection.cache_dir", "worse_reflection.stub_dir", "file_path_resolver.project_root", "file_path_resolver.app_nam  
  e", "file_path_resolver.application_root", "file_path_resolver.enable_cache", "logging.enabled", "logging.fingers_crossed", "logging.path", "logging.level", "composer.  
  autoloader_path", "composer.autoload_deregister", "console.verbosity", "console.decorated", "extension_manager.extension_vendor_dir", "extension_manager.vendor_dir", "  
  extension_manager.config_path", "extension_manager.extension_list_path", "extension_manager.root_package_name", "extension_manager.minimum_stability", "extension_manag  
  er.repositories", "extension_manager.quiet", "extension_manager.extension_vendor_dir", "extension_manager.vendor_dir", "extension_manager.config_path", "extension_mana  
  ger.extension_list_path"         ``

**Comment by dantleech** [comment]
it was renamed, it is now `composer.autoloader_path` (and also `composer.autoloader_deregister`. Feel free to make a pull request to fix it, if it fixes it :)

**Comment by mdphoto** [comment]
Thank, I create a pull request.

**Comment by dantleech** [comment]
Thanks :)
