### ISSUE TITLE
Implement a loading message for the vim plugin

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#747]
In a big codebase, when we try to find references of a class member, PHPActor can be quite long to handle the task (which is normal). Then VIM hangs for maybe 30 seconds, with no possibility of interacting and no message.

Could it be possible to add a message from the plugin, to say that it is loading (to know that VIM is not just dead)?

**Comment by elythyr** [comment]
Hi,

I'm wondering if asynchronous refactoring won't be dangerous.
We could overwrite some modifications done by PHPActor if the file is currently open in our editor and we modify it.

But it would be a great fixture to find references in the project.
Like Einenlum I work with a pretty large code base which make those tasks quite long.
It's a bummer to have to wait, not being able to do anything in Vim, in the meanwhile.

I will also use this opportunity to ask if it's possible to tell to PHPActor to ignore some directories when trying to refactor or looking for references ?
But keeping them managed by git ?
I didn't find anything about that for now but I just started my research :)

**Comment by dantleech** [comment]
> I'm wondering if asynchronous refactoring won't be dangerous

Possibly, but it's already the case that open files can be changed by project-wide refactorings.

> I will also use this opportunity to ask if it's possible to tell to PHPActor to ignore some directories when trying to refactor or looking for references ?

It's not currently possible, although "easy" to implement (depending on the exact use case -- per refactoring or globally?). But let's open a separate ticket to discuss further :)

**Comment by elythyr** [comment]
> It's not currently possible, although "easy" to implement. It also depends on the exact use case -- per refactoring or globally?. But let's open a separate ticket to discuss further :)

Thanks, I will keep searching and came back with a new issue if I still feel the need.

**Comment by dantleech** [comment]
We can make find references and such things asynchronous with https://github.com/phpactor/phpactor/pull/890

**Comment by mamazu** [comment]
The current version already shows progress of finding references. So many this issue can be closed now.
