### ISSUE TITLE
phpactor does not understand nullable return typehints

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#753]
When implementing an interface, phpactor does not take in account the nullable return typehints.

Example 1, with scalar return typehint:

```php
<?php

namespace App;

interface TestInterface1
{
    public function returnMaybeString(): ?string;
}
```

If I create a class `Test1` that implements this interface and I ask phpactor to implement contracts:

```php
<?php

namespace App;

class Test1 implements TestInterface1
{
    public function returnMaybeString(): string
    {
    }
}
```

Example 2 with a class return typehint:

```php
<?php

namespace App;

interface TestInterface2
{
    public function returnMaybeFoo(): ?Foo;
}
```

If I ask to implement contracts:

```php
<?php

namespace App;

class Test2 implements TestInterface2
{
    public function returnMaybeFoo(): Foo
    {
    }
}
```
The `?` disappears in the implementations.

**Comment by dantleech** [comment]
Yeah, this is a missing feature :)

**Comment by Einenlum** [comment]
Seems that the Type class in the worse-reflection repo should also be changed to allow nullable: https://github.com/Einenlum/worse-reflection/blob/master/lib/Core/Type.php

**Comment by dantleech** [comment]
Made a (quick) attempt at this https://github.com/phpactor/worse-reflection/pull/55 still needs parameter support.
