### ISSUE TITLE
Use Rector for refactorings?

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#765]
I wonder if it would be possible to integrate Rector to perform refactorings (replacing or augmenting the [code-transform](https://github.com/phpactor/code-transform) package).

https://github.com/rectorphp/rector

Or if it would be worth it:

- Does it provide any advantage over the current system?
- Does Rector come with any pre-existing Rectors (e.g. complete constructor, add missing assignments, etc) which could be reused?
- Can Rectors be parameterized (so that we can provide e.g. method names from the user).

I guess the biggest advantage is that it uses the PHP-Parser and can reformat the code based on the AST (not possible with the tolerant PHP parser). 

cc @TomasVotruba

**Comment by TomasVotruba** [comment]
I don't think it's a good idea. Rector is focused on A to B refactoring, upgrade, migrate or change.

There are no rules like complete assigns into method. It would be very slow as well, since it's not designed for such small code
