### ISSUE TITLE
Custom templates are ignored

### ISSUE THREAD

**Issue by mskubas** [phpactor/phpactor#766]
I can't make phpactor#ClassNew() working on master or develop. It's the same as #669. The latest working one is 0.11.1.

**Comment by dantleech** [comment]
The behavior I found was that the templates _are_ picked up, but are not applied when selected. Instead the default is used.

This is fixed in #767  Please re-open if you experienced a different issue :)

**Comment by mskubas** [comment]
It works. Thanks.
