### ISSUE TITLE
php file encoded in iso-8859-1 with accentuated characters cause issue

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#783]
Hi,

I tried to use goto-definition (phpactor 0.12)  action in a file encoded in iso-8859-1 charset and containing a `ä` character and it resulted in error.

```

In RpcCommand.php line 62:
                                                                               
  Could not decode JSON: ...
```

Removing this character removed the issue.

**Comment by elythyr** [comment]
HI,

Can we have an example to reproduce the issue ?
Where was the character ?
Under the cursor ?
In the source or destination file ?
In a string or a "keyword" like variable, function, class name, etc. ?

We still use this encoding at work and even if we probably don't have a `ä` we still have a bunch of french accents in the strings, never got any problem.

**Comment by kermorgant** [comment]
Hello,

Ah, it's interesting to hear you don't have this issue. I'll try to create an example next week.

As for your questions : the character was in the source file in a comment (prefixed by `//`) , not under the cursor

**Comment by elythyr** [comment]
```php
<?php
// src/Foo.php

namespace App;

class Foo implements Bar
{
    public function __construct()
    {
        // test ä
    }
}
```

```php
<?php
// src/Bar.php

namespace App;

class Bar
{
    public function __construct()
    {
        // test ä
    }
}
```

No problem with that one, if you have time to try it.
If you got an issue I would think there might be a problem with your config somewhere.
If you don't then I will wait for you to provide a reproducible example.

On which branch are you by the way, master or develop ?

**Comment by kermorgant** [comment]
Thanks for the investigation ! I tried on my home machine and that works too.

Will need to check that next week on my work machine (phpactor 0.12 from master, on emacs / osx)

**Comment by kermorgant** [comment]
I took the example file provided above and could reproduce the issue and narrow things a bit

In my work emacs config, I have `(prefer-coding-system 'iso-latin-1-unix)`. When changing to utf-8 (file still being in iso-8859-1), the issue disappears.

Looks like the solution is to look somewhere in emacs or phpactor.el

**Comment by kermorgant** [comment]
I've tried to fix it by considering phpactor's rpc answer to be in utf-8 and it seems to work

**Comment by elythyr** [comment]
Great then!

**Comment by kermorgant** [comment]
Yes, thanks again for your time !
