### ISSUE TITLE
completion issue when autoloader is using classmap strategy

### ISSUE THREAD

**Issue by kermorgant** [phpactor/phpactor#789]
I've recently created a composer configuration for an old project, where composer's "classmap" option is used for autoloader.

```json
	"autoload": {
		"classmap": [
                        "folder1",
                        "folder2",
                        "etc"
	        ]
        }
```

Not sure if it's related to that but completion is not returning an accurate list of suggestions. The suggestions received are OK, but some are missing which is a bit intriguing to me

* I've cleared the cache, 
* dumped manually the atoloader
* verified the classes I'm looking for are really in the autoload_classmap.php and autoload_static.php file).

phpactor:status tells that it finds composer (not git, probably because composer.json is in a subdirectory of the project)

I could try to look at debugging this but any pointers to speed up the process would be welcome.
Trying to reproduce the issue with test files could be a start. I remember having seen sample php files used in integration tests but not sure where they are.

Or any suggestion about whch part of the code to start with var_dumps ?

**Comment by dantleech** [comment]
There is the composer "finder": https://github.com/phpactor/source-code-filesystem/blob/master/lib/Adapter/Composer/ComposerFileListProvider.php

or in this case more likely the code converting from an FQN to a filename: https://github.com/phpactor/class-to-file/blob/master/tests/Integration/Composer/ComposerClassToFileTest.php#L131

**Comment by kermorgant** [comment]
I've use the `replay` from the command line and it seem to be a working directory issue.

`cat ~/.cache/phpactor/replay.json| /usr/bin/php ~/.emacs.d/phpactor/vendor/bin/phpactor rpc --replay`

> Context : As php is only a small part of the codebase, it has been stored under a `/project_root/php` folder. I have placed `composer.json` under `/php` which is considered as the working directory for phpactor when used through emacs.

When run in the `/project_root/php`, I get a partial set of results
When run from `/project_root`, the result set of suggestions is complete.

is there a way to keep composer stuff under php and configure phpactor to

**Comment by kermorgant** [comment]
solved by https://github.com/phpactor/completion/pull/24

**Comment by kermorgant** [comment]
Actually, this did not solve but only improve the situation. I still have classes in vendor/composer/autoload_classmap.php that will not serve as candidates.

**Comment by kermorgant** [comment]
I'm taking short breaks to investigate this, and latest observation is that  `Phpactor\ClassFileConverter\Adapter\Composer\ComposerFileToClass` is instantiated but it seems `fileToClassCandidates` is not invoked during completion

**Comment by kermorgant** [comment]
note : there is no use of namespaces in the code concerned by this bug

**Comment by kermorgant** [comment]
Debugged a bit again by looking at which files were found from the classmap 
![image](https://user-images.githubusercontent.com/10561580/60444315-a2c42f80-9c25-11e9-94af-9970f47632ee.png)

I'm maybe doing something wrong but still missing some files/classes, some created for the test

**Comment by kermorgant** [comment]
This came from a misconfiguration of root folder detection in my emacs config (confusion due to obsolete "vendor" folder not removed from wrong location)

**Comment by dantleech** [comment]
Doh, glad you found it :)
