### ISSUE TITLE
Wrongly file path selection when "test" shares the same namespace as "source"

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#795]
Version: develop, with `phpactor/phpunit-extension`.

To reproduce, you can use the example from: 
https://github.com/przepompownia/phpactor-bug-shared-namespace
- open `src/Domain/Example.php`
- `:call phpactor#Navigate()`, select `test`
The first dialog looks correctly: 
`File "tests/Domain/ExampleTest.php" does not exist, generate new?:`
After confirm I get the message:
`Error from Phpactor: File "/tmp/phpactor-shared-namespace/src/Domain/Example.php" already exists and is non-empty`.

**Comment by dantleech** [comment]
Fix here, but currently lacking test: https://github.com/phpactor/phpactor/pull/796

**Comment by przepompownia** [comment]
Class `ExampleTes`t is generated correctly, but it turns out that it is not the end of the issue. 

Please try to navigate back from `ExampleTest` to source class. Only `test` destination is available.

**Comment by przepompownia** [comment]
Both bugs seems to be fixed :+1:

**Comment by dantleech** [comment]
Thanks for confirming :)
