### ISSUE TITLE
Improve code quality, fix hidden bugs and typos

### ISSUE THREAD

**Issue by szepeviktor** [phpactor/phpactor#808]
Hello @dantleech !

Please consider running `phpstan analyse -l 0 lib/`
Levels go up to 7!

@phpstan has a huge benefit.

**Comment by dantleech** [comment]
Thanks, we already use Phpstan in all of the dependencies of this project, most if not all of the code here will be moved to packages at some point, but yes, it would be good to introduce stan here too.

**Comment by dantleech** [comment]
phpactor is now a monlith and uses phpstan at level 7
