### ISSUE TITLE
composer.lock is broken

### ISSUE THREAD

**Issue by zonuexe** [phpactor/phpactor#812]
There are some inconsistencies between `composer.json` and `composer.lock`.
This problem can be solved by `composer update` or `rm composer.lock && composer install`.

Also consider removing `composer.lock` from Git management.

**Comment by dantleech** [comment]
Is that for master or develop?

If develop I may have fixed it about 30 minutes ago.

We distribute the locked composer file for Phpactor, the application, as otherwise any arbitrary package change beyond our control could break the application. Although, for `develop` maybe it could be removed.

**Comment by zonuexe** [comment]
Yes, I was following the illusion of a few tens of minutes ago.
I knew that Phpactor was redistributing composer.lock for the Vim plugin, but lacked the point of reducing installation time.

However, I feel that it is more efficient to make the packages monorepo.
https://github.com/phpactor/phpactor/issues/803
