### ISSUE TITLE
Error from Phpactor when importing class

### ISSUE THREAD

**Issue by vivoconunxino** [phpactor/phpactor#816]
I've recently done a PlugUpdate and received last changes, until now I could import a class positioning the cursor-> menu->im(p)ort, now it's giving me the following error:

`Key(s) "name" are not known, known keys: "qualified_name", "alias", "offset", "source", "path"`

Although I still call import when auto-completing a class.

**Comment by dantleech** [comment]
Oops, yes this is a regression.

**Comment by dantleech** [comment]
I have added a fix to master, can you verify?

**Comment by vivoconunxino** [comment]
Sure, I've updated again and now works perfectly. Thanks a lot!

**Comment by vivoconunxino** [comment]
Sorry, I did a quick check and worked but in fact it's still some kind of bug going on.

As I said now it imports, but it does at the same namespace, not the real one.

For instance, one of my domains, Booking.
Importing with the cursor-> menu->im(p)ort does a:

`use Booking;`

while the autocompletion import (this works fine):

`use Api\Service\Booking\Domain\Booking;`

**Comment by dantleech** [comment]
Doh, have updated master again -- :crossed_fingers:

**Comment by vivoconunxino** [comment]
Importing from menu now works, except when you are positioned at the last char of the word. In that case an error message shows `No classes found with name " "`. This was working before (I use your software every working day!).

**Comment by Einenlum** [comment]
Same note here. I switched a few days ago to `develop` and it's amazing except this regression: not possible to use a class when we are on the last char (worked before). Same message as @vivoconunxino : `No classes found with name " "`.

**Comment by dantleech** [comment]
Fixed in https://github.com/phpactor/text-document/commit/053f32113cbbc9d2a11ee42151b8f1f48a09e111 and updated in develop, will hopefully that's fine and I'll make tag a new version of `text-document`

**Comment by dantleech** [comment]
Master has been updated.
