### ISSUE TITLE
Error when using go to definition

### ISSUE THREAD

**Issue by gabrielbidula** [phpactor/phpactor#820]
> Error from Phpactor: Key(s) "target" are not known, known keys: "language", "offset", "source", "path"

i get the above error when i try to go to method definition ie:

```
return $this->createPackageFromBackOffice($params);

public function createPackageFromBackOffice(array $params = []): PackageSubscription
```

**Comment by dantleech** [comment]
can you run `:call phpactor#Status()`  in VIM?

**Comment by dantleech** [comment]
This error is almost certainly from having an old version of the VIM plugin running against a newer version of the backend, closing. (please open if this is not the case)
