### ISSUE TITLE
Add a way to transform method single line to multi lines

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#822]
It happens a lot that when I code, there are progressively new items added in a constructor or in a random method and it becomes too long for PSR-2.

Would it be possible to switch multi-line to single-ligne and vice-versa? Would be a nice feature:

```php
<?php

function someFunction($that, $starts, $to, $become, $really, $longer, $than, $expected)
{
}
```
Would become:

```php
<?php

function someFunction(
    $that,
    $starts,
    $to,
    $become,
    $really,
    $longer,
    $than,
    $expected
) {
}
```

**Comment by dantleech** [comment]
Yep install `Plug 'FooSoft/vim-argwrap'` :)

**Comment by Einenlum** [comment]
Oh, nice! It's still not perfect, but it's a good tool! Thx, didn't know it :)
