### ISSUE TITLE
Importing a nullable type doesn't work anymore

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#833]
For the following piece of code (after latest update) :

```php
<?php
namespace App;

$foo = function(): ?Bar { // let's say Bar is in `App\Foo\Bar`
};
```

When trying to import the cursor on `?Bar`, it says it can't find a class matching `?Bar`. If I add a space `? Bar` and then try to import `Bar`, it works as expected.

**Comment by dantleech** [comment]
Fixed in master + develop
