### ISSUE TITLE
[bug] Impossible to import a nullable class

### ISSUE THREAD

**Issue by elythyr** [phpactor/phpactor#850]
### Step to reproduce
Add `?` before a class name that you know will normally be imported and try to import it

### Expected result
The class should be imported.

### Actual result
Message in the status bar: `No classes found with name "?ClassName"`

I didn't check from where it yet, I hope that handling nullable types will be enought.
I updated the `nullablereturntypes` branche on #phpactor/worse-reflection to be applied on parameters too.
When I will have some time I will try it to see if it resolves the issue or if that's something else.

**Comment by dantleech** [comment]
This works for me at least, are you on `develop` ? (although looks like this may have been fixed in a previous [release](https://github.com/phpactor/phpactor/blob/develop/CHANGELOG.md#2019-10-23-0135) )

**Comment by elythyr** [comment]
It might be related to https://github.com/phpactor/phpactor/issues/851
And yes I'm usually always on develop.

I will try on my way home this evening

**Comment by Taluu** [comment]
Wasn't this reported (and solved_ with #833 ?

**Comment by elythyr** [comment]
I finally got the time to test, I don't have the probleme for `?Class` anoymore.
But still for `Something|SomethingElse` because `|` is not a separator, it requires the same fix as #851 
I will create a quick PR for that.
