### ISSUE TITLE
Cannot import a class if there is a trailing comma

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#851]
Given:

```php
    public function test(AppDepl<>oymentSet, \Exception $e)
    {

    }
```
If I try to import the class, it says:

`No classes found with name "AppDeploymentSet,"`         
In this case I need to first create a space between the class name and the comma like this:

```php
    public function test(AppDepl<>oymentSet , \Exception $e)
    {

    }
```        
And then it works.

**Comment by dantleech** [comment]
Should be an easy fix: https://github.com/phpactor/text-document/blob/master/lib/Util/WordAtOffset.php#L10

**Comment by Einenlum** [comment]
@dantleech Yep, sent a PR above, before your comment ;)
