### ISSUE TITLE
Required documentation site update

### ISSUE THREAD

**Issue by DeyV** [phpactor/phpactor#858]
Site https://phpactor.github.io/ is not synchronized with actual code base, for example 
https://phpactor.github.io/phpactor/refactorings.html - missing --transform=fix_namespace_class_name section

**Comment by dantleech** [comment]
It should get updated when master is built. That refactoring is there - Fix Namespace Class name - but it's wrong...

**Comment by dantleech** [comment]
Manually updated the docs, thanks :+1:
