### ISSUE TITLE
[vim-plugin] E474: Invalid Argument on ExtractMethod

### ISSUE THREAD

**Issue by Elidrake** [phpactor/phpactor#866]
I'm attempting to, within a basic PHP class, select a block of code and extract it to a method.  I've visually selected the code and then called phpactor#ExtractMethod(), and this is the error I run into (pulled from verbose vim log):

`
Calling shell to execute: "(php /Users/user/.cache/vimfiles/repos/github.com/phpactor/phpactor/plugin/../bin/phpactor rpc --working-dir=/Users/user/Documents/project) < /var/folders/3m/f6pnm4js0xd4z63s59818dc00000gp/T/vFE0gIn/8>/var/folders/3m/f6pnm4js0xd4z63s59818dc00000gp/T/vFE0gIn/9 2>&1"
Vim(let):E474: Invalid argument
Executing CursorMoved Autocommands for "*"
autocommand call <SID>neomake_cursor_move_delay()
`

An Invalid Argument without any real information as to what's happening.  Any ideas about how I can fix/further diagnose the issue?

I have phpactor installed as an additional plugin in a SpaceVim environment.

Some further information; this error appears when I attempt to run Extract Interface as well, and likely does on most all of the methods.

**Comment by dantleech** [comment]
hmm, can you run `:call phpactor#Status()` ?

I'm not sure about SpaceVim -- is it possible to try on a standard neo/vim to eliminate that as a cause?

**Comment by dantleech** [comment]
or try disabling https://github.com/neomake/neomake ?

**Comment by Elidrake** [comment]
> hmm, can you run `:call phpactor#Status()` ?
> 
> I'm not sure about SpaceVim -- is it possible to try on a standard neo/vim to eliminate that as a cause?

Running Status gives me the following:

`
Error detected while processing function phpactor#Status[1]..phpactor#rpc:
line   10:
E474: Invalid argument
line   12:
E909: Cannot index a special variable
line   13:
E909: Cannot index a special variable
line   15:
E121: Undefined variable: actionName
E116: Invalid arguments for function phpactor#_rpc_dispatch(actionName, parameters)
`

I'll attempt a standard VIM environment when I get the chance.

**Comment by soyuka** [comment]
Version of php @Elidrake ?

I also have this error, I tried to disable every other plugin. Php version:

```
PHP 7.4.2 (cli) (built: Jan 21 2020 18:16:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

```

**Comment by soyuka** [comment]
Oh wow okay, so I tried using `develop` same issue. But then I noticed that I was missing some php extensions, indeed I had warnings (php --version):

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'amqp.so' (tried: /usr/lib/php/modules/amqp.so (/usr/lib/php/modules/amqp.so: undefined symbol: add_next_index_zval), /usr/lib/php/modules/amqp.so.so (/usr/lib/php/modules/amqp.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: blackfire: Unable to initialize module

```

Once these warning fixed, phpactor is working again.

**Comment by dantleech** [comment]
Maybe we can improve thee error reporting ... VIM script is _fun_.

**Comment by elythyr** [comment]
Kind of weird that we need `blackfire` and if the message broker is required it should be in the `composer.json` so that it fails at the `composer install` stage

**Comment by dantleech** [comment]
Note that _we_ don't need blackfire. These are just modules in the users `php.ini` :)

**Comment by dantleech** [comment]
Note however that when I do this I get the following error, which is more descriptive than that one reported:

```
E474: Unidentified byte: PHP Warning:  PHP Startup: Unable to load dynamic library 'blackfire1.so' (tried: /usr/lib/php/20180731/blackfire1.so (/usr/lib
/php/20180731/blackfire1.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/blackfire1.so.so (/usr/lib/php/20180731/b
lackfire1.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0^@PHP Warning:  PHP Startup: Unable to load dynamic lib
rary 'blackfire1.so' (tried: /usr/lib/php/20180731/blackfire1.so (/usr/lib/php/20180731/blackfire1.so: cannot open shared object file: No such file or d
i```

@soyuka is this the same error you had?

**Comment by dantleech** [comment]
Have updated the plugin to catch `json_decode` exceptions, exception is now:

```
E605: Exception not caught: Could not parse response from Phpactor: Vim(let):E474: Unidentified byte: PHP Warning:  PHP Startup: Unable to load dynamic 
library 'blackfire1.so' (tried: /usr/lib/php/20180731/blackfire1.so (/usr/lib/php/20180731/blackfire1.so: cannot open shared object file: No such file o
r directory), /usr/lib/php/20180731/blackfire1.so.so (/usr/lib/php/20180731/blackfire1.so.so: cannot open shared object file: No such file or directory)
) in Unknown on line 0^@PHP Warning:  PHP Startup: Unable to load dynamic library 'blackfire1.so' (tried: /usr/lib/php/20180731/blackfire1.so (/usr/lib/
php/20180731/blackfire1.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/blackfire1.so.so (/usr/lib/php/20180731/bl
ackfire1.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0^@{"version":"1.0.0","action":"echo","parameters":{"mess
age":"Info\n----\nVersion: c13a42f (43 minutes ago) Added-Phpversoin-resolver-extension\nPHP: 7.3.12-1 (supporting
```

**Comment by soyuka** [comment]
nice thanks @dantleech

**Comment by Elidrake** [comment]
I dove a bit deeper, and found that when attempting to run the phpactor binary I'm getting out the following issue:

`Extension "Phpactor\Extension\Php\PhpExtension" does not exist`

Trying to figure out how to solve this.

**Comment by Elidrake** [comment]
Right, so I went ahead and reinstalled the plugin after increasing my local php memory limitation.  It appears during initial installation the composer process had died, causing my issues.  Thanks for improving the debug reporting!

**Comment by dantleech** [comment]
Nice :) thanks for confirming
