### ISSUE TITLE
Can it import class name inline (for vim)

### ISSUE THREAD

**Issue by QzCurious** [phpactor/phpactor#867]
I don't know if it only me wanting a way to transform a class name to its full name. And I think phpactor must good enough to do so. After seeking issues a few time. I found the functionality was [asked and implemented](https://github.com/phpactor/phpactor/issues/114) before!!

At this moment, I'm wondering if we, vim users, should dive into the code to explore how amaze it is. Or it's just accidentally lost its description. Hope these functionality can be described in the [site](https://phpactor.github.io/phpactor/).

After all, I'm don't want to be offensive to ask adding description for everything we can do with it, but want this project can be used efficiently by everyone.

**Comment by dantleech** [comment]
Hi - yes you're correct. This isn't documented on the site currently - it's actually a VIM plugin only feature, would it make sense to add the shortcut to the example mappings?

```
nmap <Leader>e :call phpactor#ClassExpand()<CR>
```

and add it to the [refactorings](https://github.com/phpactor/phpactor/blob/develop/doc/refactorings.md) page?

Feel free to open a pull request :)

**Comment by QzCurious** [comment]
I've made a [**Expand Class**](https://github.com/QzCurious/phpactor/commits/master) section in doc. And I alse modify the code that add a leading `\` to the result of class name to match the definition of [fully qualified name](https://www.php.net/manual/en/language.namespaces.rules.php).
I'd like to know which branch should I make a pull request to, master or develop?

_For the reason that why I just add a leading `\` instead of made a parameter to make it optional is that I think this is a facility but not dependency._

**Comment by dantleech** [comment]
Great! "develop" is the branch
