### ISSUE TITLE
Release 14 by February 1st

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#868]
There are quite some changes in develop currently, and some of them are problematic and blocking the next release:

- [x] Import all classes: does not work properly #864 => #870 
- [x] Goto Implementation(s): Unusably slow in large projects and opinionated (depends on naming conventions to filter)
- [x] The async FZF list implementation breaks the callback system of the menu - there is currently a [dirty hack](https://github.com/phpactor/phpactor/blob/develop/plugin/phpactor.vim#L22) to work around this. *edit*: Have made this functionality experimental.
- [x] #872 Fallback to PHP version in `composer.json` if possible.

We should consider reverting the above if they cannot be fixed.

In addition it would be great to:

- [x] Finish the generated code sanitising work [here](https://github.com/phpactor/code-builder/pull/17])
- [x] Finish support for [nullable types](https://github.com/phpactor/code-transform/pull/30)
- [x] Merge support for [PHP version specific templates]( https://github.com/phpactor/code-builder/pull/14)
- [x] https://github.com/phpactor/phpactor/pull/796

Anything else I'm missing? cc @elythyr @Einenlum

**Comment by elythyr** [comment]
For the "goto implementation" I think it's OK to include it in the release as long as it's well documented that the feature is slow on large project.
I often use ripgrep instead but in some cases I'm willing to take a few minutes to have a better result with this feature.
As long as it doesn't break anything, the user can choose to not use it so it's OK for me.

For the FZF list, I will try to get a look at it, we might have to change a few things or at least not use it for features that returns a list of actions.

**Comment by dantleech** [comment]
I have a pretty good solution for goto implementation - using a lazy index. However I'm currently blocked with the "cs fixer" implementation in code-builder - as it really doesn't work very well. I may well revert that completely and just live with the existing poorly formatted code.

**Comment by elythyr** [comment]
I think it's acceptable, the "poorly formated code" was only in some really specific cases if I remember properly.

**Comment by elythyr** [comment]
Do you think it would be possible to use the monolith for the next release ?

**Comment by dantleech** [comment]
I don't think so - it's very time consuming to setup and I haven't got confidence in any particular plan. I'd rather not add further tasks to the list.

**Comment by dantleech** [comment]
The CS fixer (for generated code) has been completely removed now. Will hopefully get the indexer finished tomorrow.

**Comment by dantleech** [comment]
@elythyr I made a PR to make the FZF / BAT features experimental for this release: https://github.com/phpactor/phpactor/pull/883

**Comment by dantleech** [comment]
Hae added PHP version detection which also checks composer and improved the `workspace-query` [indexer](https://git@github.com/phpactor/workspace-query) to support a basic `--watch` mode.

In addition to enabling `goto implementation` the workspace-query module can also proide source code location - which will provide much better support for non-composer / strange projects / projects which break autoloaders.

It's still experimental though, the indexer is polling currently which means scanning potentially ~30k files every x seconds - it should at least support using `inotify` on Linux-like machines. In addition the VIM plugin should be able to manage the process and keep it running - and that's interesting as VIM and Nvim have different APIs. Probably better to delegate to a third-party plugin if available.

**Comment by elythyr** [comment]
It's indeed to possible to find third-party plugin to deal with async in both Vim and NVim.

**Comment by dantleech** [comment]
Well, it's fairly trivial to do it ourselves I think (this is the [WIP](https://github.com/phpactor/phpactor/pull/890))

**Comment by dantleech** [comment]
One month late: https://www.dantleech.com/blog/2020/03/01/phpactor-14/

... and there was much rejoicing :tada:
