### ISSUE TITLE
Infer PHP version from Composer if possible?

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#872]
PHP 7.4 property types are automatically enabled based on the running PHP version, if a version is not explicitly configured..

Most projects currently are not on 7.4 it might be good to see if the projects `composer.json` has defined a supported PHP version, and if so assume the lowest by default.

**Comment by Taluu** [comment]
How about checking the `platform` instead ?

**Comment by dantleech** [comment]
Platform isn't necessarily the lowest _supported_ version, so I think it makes more sense to use the PHP dependency, but could fallback to `platform` if that doesn't exist ?

**Comment by Taluu** [comment]
I would rather check the platform and then only fallback on the minimum. If there's a platform, then it's a fixed number : you're coding against that.

**Comment by dantleech** [comment]
But if the library / project _supports_ PHP 7.1 (`require: php 7.4`) and the platform is set to 7.4, then the composer will hapilly install the project on 7.1 but then subsequently break because Phpactor generated code for 7.4

**Comment by Taluu** [comment]
The platform is really used on projects, it doesn't really make sense to use it on libs... As you are locking your composer into thinking that it is targetted at the version specified in there.

So if there's one, it should be safe to consider that it's the target IMO

**Comment by dantleech** [comment]
I think `current PHP runtime <= minimum supported version <= platform version` should be fine.

**Comment by dantleech** [comment]
Will be determined by: 1. explicitly configured version 2. composer platform 3. composer pHP requirement 4. Runtime PHP version. https://github.com/phpactor/phpactor/pull/884
