### ISSUE TITLE
Exclude dev dependencies from default install?

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#877]
Since phpactor is used as a library for the final user, shouldn't we exclude dev dependencies by default when installing the plugin?

`Plug 'phpactor/phpactor', {'for': 'php', 'do': 'composer install --no-dev -o'}`
instead of
`Plug 'phpactor/phpactor', {'for': 'php', 'do': 'composer install'}` ?

cf. https://phpactor.github.io/phpactor/vim-plugin.html

**Comment by dantleech** [comment]
Yep -- I think @Taluu may have already commented on this somewhere (can't find the reference) and discovered a coupling to the dev deps - which I think we fixed. But anyway -- if it works, yes let's change it otherwise we should fix it.

**Comment by Taluu** [comment]
IIRC it was one of my first issues in here. :D

**Comment by dantleech** [comment]
Udated the doucumentation in develop
