### ISSUE TITLE
error import class in #_rpc_dispatch

### ISSUE THREAD

**Issue by ftamhar** [phpactor/phpactor#881]
Error import the class as seen in the gif below

![output](https://user-images.githubusercontent.com/24367921/74094023-7b1b3b00-4b15-11ea-83a5-f577055e3035.gif)

I have done debugging as contained in [this site](https://phpactor.github.io/phpactor/developing.html), and get warning:

> `Warning: str_repeat(): Second argument has to be greater than or equal to 0 in .../phpactor/vendor/phpactor/code-builder/lib/Util/TextFormat.php on line 29`

But....
In other files or controllers, this feature is run smoothly.

**Comment by dantleech** [comment]
Can you confirm that you are on the `master` branch? Is there anything that is different about this controller? (would be a bonus to have a code snippet which could reproduce)

**Comment by ftamhar** [comment]
> Can you confirm that you are on the `master` branch? Is there anything that is different about this controller? (would be a bonus to have a code snippet which could reproduce)

yes, i'm in master branch

this is my code in this controller :

> <?php

namespace App\Http\Controllers;

use App\DataWarga;
use App\User;
use App\Validasi;
use DataTables;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class DataController extends Controller {

    public function __construct() {
        $this->middleware('auth');
    }

    public function Validasis() {
        return DataTables::eloquent(Validasi::select(DB::raw('user_id, warga_id, valid, validasis.updated_at'))->orderBy('validasis.updated_at', 'desc')->where('valid', 1)->with([
            'user',
            'datawarga.kecamatan',
            'datawarga.kelurahan',
        ]))->addColumn('kecamatan', function(Validasi $v) {
            return $v->datawarga->kecamatan->name;
        })->addColumn('desa', function(Validasi $v) {
            return $v->datawarga->kelurahan->name;
        })->addColumn('user_name', function(Validasi $v) {
            return $v->user->name;
        })->addColumn('total', function(Validasi $v) {
            return $v->datawarga->total;
        })->addColumn('gambar_ktp', function(Validasi $v) {
            return $v->datawarga->gambar_ktp;
        })->addColumn('gambar_lantai', function(Validasi $v) {
            return $v->datawarga->gambar_lantai;
        })->addColumn('gambar_dinding', function(Validasi $v) {
            return $v->datawarga->gambar_dinding;
        })->addColumn('gambar_atap', function(Validasi $v) {
            return $v->datawarga->gambar_atap;
        })->addColumn('gambar', function(Validasi $a) {
            $foto1 = 0;
            $foto2 = 0;
            $foto3 = 0;
            $foto4 = 0;
            $foto = 0;
            if (file_exists('./assets/foto/' . $a->datawarga->gambar_ktp)) {
                $foto1 = 1;
            }
            if (file_exists('./assets/foto/' . $a->datawarga->gambar_lantai)) {
                $foto2 = 1;
            }
            if (file_exists('./assets/foto/' . $a->datawarga->gambar_dinding)) {
                $foto3 = 1;
            }
            if (file_exists('./assets/foto/' . $a->datawarga->gambar_atap)) {
                $foto4 = 1;
            }
            if ($foto1 == 1 && $foto2 == 1 && $foto3 == 1 && $foto4 == 1) {
                $foto = 1;
            }
            return [
                $foto1,
                $foto2,
                $foto3,
                $foto4,
                $foto,
            ];
        })->addColumn('dusun', function(Validasi $v) {
            return $v->datawarga->dusun;
        })->addColumn('nik', function(Validasi $v) {
            return $v->datawarga->nik;
        })->addColumn('tanggal', function(Validasi $v) {
            return $v->updated_at->diffForHumans();
        })->addColumn('name', function(Validasi $v) {
            return $v->datawarga->name;
        })->removeColumn([
            'user',
            'datawarga',
            'user_id',
            'updated_at',
        ])->addIndexColumn()->toJson();
    }

    public function Warga() {
        if(auth()->user()->hasAnyRole(['operator','super-admin','admin'])){
            $datas = DataWarga::select(DB::raw('data_wargas.name, kec_id, kel_id, nik, dusun, total, data_wargas.id, gambar_ktp, gambar_lantai, gambar_dinding, gambar_atap'))->orderBy('data_wargas.id')->with([
            'kecamatan',
            'kelurahan',
            'validasi',
        ])->whereIn('kel_id', json_decode(auth()->user()->desas, 1))->whereIn('kec_id', json_decode(auth()->user()->kecamatans, 1));
        } else {
            $datas = DataWarga::select(DB::raw('data_wargas.name, kec_id, kel_id, nik, dusun, data_wargas.id, gambar_ktp, gambar_lantai, gambar_dinding, gambar_atap'))->orderBy('data_wargas.id')->with([
            'kecamatan',
            'kelurahan',
            'validasi',
        ])->whereIn('kel_id', json_decode(auth()->user()->desas, 1))->whereIn('kec_id', json_decode(auth()->user()->kecamatans, 1));
        }
        return DataTables::eloquent($datas)->addIndexColumn()->addColumn('kecamatan', function(DataWarga $d) {
            return $d->kecamatan->name;
        })->addColumn('kelurahan', function(DataWarga $d) {
            return $d->kelurahan->name;
        })->addColumn('gambar', function(DataWarga $a) {
                $foto1 = 0;
                $foto2 = 0;
                $foto3 = 0;
                $foto4 = 0;
                $foto = 0;
                if (file_exists('./assets/foto/' . $a->gambar_ktp)) {
                    $foto1 = 1;
                }
                if (file_exists('./assets/foto/' . $a->gambar_lantai)) {
                    $foto2 = 1;
                }
                if (file_exists('./assets/foto/' . $a->gambar_dinding)) {
                    $foto3 = 1;
                }
                if (file_exists('./assets/foto/' . $a->gambar_atap)) {
                    $foto4 = 1;
                }
                if ($foto1 == 1 && $foto2 == 1 && $foto3 == 1 && $foto4 == 1) {
                    $foto = 1;
                }
                return [
                    $foto1,
                    $foto2,
                    $foto3,
                    $foto4,
                    $foto,
                ];
            })->addColumn('validasi', function(DataWarga $d) {
                if (isset($d->validasi->valid)) {
                    return $d->validasi->valid;
                }
                return "0";
            })->toJson();
    }

    public function Users() {
        $model = User::select([
            'id',
            'name',
            'username',
            'last_login',
        ])->orderBy('last_login', 'desc')->with([
            'roles',
            'permissions',
        ]);

        return DataTables::eloquent($model)->addIndexColumn()->addColumn('name', function(User $user) {
            return ucwords($user->name);
        })->addColumn('username', function(User $user) {
            return $user->username;
        })->addColumn('last_login', function(User $user) {
            if ($user->last_login) {
                return $user->last_login->diffForHumans();
            }
            return $user->last_login;
        })->addColumn('roles', function(User $user) {
            $r = $user->roles->map(function($r){
                return $r->name;
            });
            $r = json_decode($r);
            $ret = Role::orderBy('name')->get()->map(function($role) use ($r,$user){
                if(in_array($role->name, $r)){
                return ucwords($role->name).': <input type="checkbox" data-type="2" checked data-name="'.$role->name.'" data-user_id="'.$user->id.'" class="editor-active">';
                }
                return ucwords($role->name).': <input type="checkbox" data-type="2" data-name="'.$role->name.'" data-user_id="'.$user->id.'" class="editor-active">';
            })->implode('<br/>');
            return $ret;
        })->addColumn('permissions', function(User $user) {
            $r = $user->permissions->map(function($r){
                return $r->name;
            });
            $r = json_decode($r);
            $per = Permission::orderBy('name')->get()->map(function($permis)use ($r,$user){
                if(in_array($permis->name, $r)){
                    return ucwords($permis->name).': <input type="checkbox" data-type="1" checked data-name="'.$permis->name.'" data-user_id="'.$user->id.'" class="editor-active">';
                }
                return ucwords($permis->name).': <input type="checkbox" data-type="1" data-name="'.$permis->name.'" data-user_id="'.$user->id.'" class="editor-active">';
            })->implode('<br/>');
            return $per;
        })->addColumn('aksi', function(User $user) {
            $a = '<a href="' . url('admin/users/edit-user') . '/' . $user->id . '" class="btn btn-sm btn-info">Edit</a>';
            $a .= '<br/><br/><a href="' . url('admin/users/delete-user') . '/' . $user->id . '" onclick="return yakin()" class="btn btn-sm btn-danger">Hapus</a>';

            return $a;
        })->rawColumns([
            'aksi',
            'roles',
            'permissions'
        ])->toJson();
    }

    public function Roles() {
        return DataTables::of(Role::select('name', 'id')->orderBy('name'))->addIndexColumn()->addColumn('aksi', function(Role $user) {
            $a = '&nbsp<a href="' . url('admin/role/delete') . '/' . $user->id . '" onclick="return yakin()" class="btn btn-sm btn-danger">Hapus</a>';

            return $a;
        })->rawColumns(['aksi'])->make(TRUE);
    }

    public function Permissions() {
        return DataTables::of(Permission::select('name', 'id')->orderBy('name'))->addIndexColumn()->addColumn('aksi', function(Permission $user) {
            $a = '&nbsp<a href="' . url('admin/permission/delete') . '/' . $user->id . '" onclick="return yakin()" class="btn btn-sm btn-danger">Hapus</a>';

            return $a;
        })->rawColumns(['aksi'])->make(TRUE);
    }
}


error occurs when I delete `use App\Validasi;` and i want to re-import it

**Comment by dantleech** [comment]
I can't see anything obvious that could cause this without a stack trace.

I've added an exception upstream: https://github.com/phpactor/code-builder/commit/4bd8f08bbb0a13de2f791d8cac409db17edaf39f

Perhaps if you apply that change in Phpactor you will get an exception and can paste the stack trace here?

**Comment by ftamhar** [comment]
error is gone where i run
###
`phpactor#Update()`
`delete the vendor folder`
`$ composer install`

thanks for your response 😊

**Comment by dantleech** [comment]
odd, but glad you fixed it :)

**Comment by ftamhar** [comment]
yeah, I hope this error does not happen again.
