### ISSUE TITLE
Why fixed php in composer's config.platform ?

### ISSUE THREAD

**Issue by Einenlum** [phpactor/phpactor#885]
Any reason to have this specific version in the platform?

cf. https://github.com/phpactor/phpactor/blob/develop/composer.json#L69

```json
    "config": {
        "platform": {
            "php": "7.1.3"
        }
    }
```

**Comment by dantleech** [comment]
It's historical, can't remember.. probably to do with the build

**Comment by dantleech** [comment]
https://github.com/phpactor/phpactor/pull/545 :thinking:

**Comment by Einenlum** [comment]
Thanks!

**Comment by dantleech** [comment]
Still would be nice if I could remember why :stuck_out_tongue:

**Comment by dantleech** [comment]
Should probably remove it and see what problems it causes :)

**Comment by dantleech** [comment]
OK, so the issue is:

```
ocramius/package-versions 1.5.1 requires php ^7.3.0 -> your PHP version (7.2.15) does not satisfy that requirement.
```

So we can't test 7.2 if we don't pretend our platform we can't test 7.2
