### ISSUE TITLE
LS: Double dollar sign in completion response

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#904]
- use phpactor as language server
- open any class with a function body e.g. `lib/Extension/Core/Console/PhpactorCommandLoader.php`
- inside the body write `$thi` and select `$this`.

Additional dollar sign appears then in response. 
This error does not occur when perfoming the same completion using omnifunc.

```
[Trace - 00:25:50] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/user/.vim/bundle/phpactor/lib/Extension/Core/Console/PhpactorCommandLoader.php",
        "version": 6
    },
    "contentChanges": [
        {
            "text": "<?php\n\nnamespace Phpactor\\Extension\\Core\\Console;\n\nuse Symfony\\Component\\Console\\CommandLoader\\ContainerCommandLoader;\n\nclass PhpactorCommandLoader extends ContainerCommandLoader\n{\n    public function get($name)\n    {\n        $$this\n        $command = parent::get($name);\n        $command->setName($name);\n\n        return $command;\n    }\n}\n"
        }
    ]
}
``

**Comment by dantleech** [comment]
hm, I remember seeing something like this on CoC (but not the NeoVim_LanguageServer which confused me), probably an off-by-one error with offset somewhere ...

**Comment by dantleech** [comment]
hmm, for me this works with CoC:

```
[2020-03-07 08:26:49] phpactor.INFO: REQUEST {"jsonrpc":"2.0","id":8,"method":"textDocument/completion","params":{"textDocument":{"uri":"file:///home/daniel/www/phpactor/phpactor/lib/Extension/Core/Console/PhpactorCommandLoader.php"},"position":{"line":10,"character":11},"context":{"triggerKind":3}}} []           [2020-03-07 08:26:49] phpactor.INFO: RESPONSE {"id":8,"result":"[object] (LanguageServerProtocol\\CompletionList: {\"isIncomplete\":true,\"items\":[{\"label\":\"$this\",\"kind\":6,\"detail\":\"PhpactorCommandLoader\",\"documentation\":null,\"sortText\":null,\"filterText\":null,\"insertText\":null,\"textEdit\":null,\"additionalTextEdits\":null,\"command\":null,\"data\":null,\"insertTextFormat\":null}]})","responseError":null,"jsonrpc":"2.0"} []                                                                              [2020-03-07 08:26:50] phpactor.INFO: REQUEST {"jsonrpc":"2.0","method":"textDocument/didChange","params":
{"textDocument":{"uri":"file:///home/daniel/www/phpactor/phpactor/lib/Extension/Core/Console/PhpactorCommandLoader.php","version":13},"contentChanges":[{"text":"<?php\n\nnamespace Phpactor\\Extension\\Core\\Console;\n\nuse Symfony\\Component\\Console\\CommandLoader\\ContainerCommandLoader;\n\nclass PhpactorCommandLoader extends ContainerCommandLoader\n{\n    public function get($name)\n    {\n        $this-\n        
$command = parent::get($name);\n        $command->setName($name);\n\n        return $command;\n    }\n}\n"}]}} []                                                                                                 [
```

Which language server are you using?

**Comment by przepompownia** [comment]
phpactor language-server of course ;)

I switched for a while to phpls to compare requests made from the same place (a new line of the function body with indents):
```
phpls:
Params: {
    "textDocument": {
        "uri": "file:///home/user/.vim/bundle/phpactor/lib/Extension/Core/Console/PhpactorCommandLoader.php"
    },
    "position": {
        "line": 10,
        "character": 9
    },
    "context": {
        "triggerKind": 2,
        "triggerCharacter": "$"
    }
}
```
```
phpactor - languageserver
[Trace - 13:25:18] Sending request 'textDocument/completion - (1)'.
params: {
    "textdocument": {
        "uri": "file:///home/user/.vim/bundle/phpactor/lib/extension/core/console/phpactorcommandloader.php"
    },
    "position": {
        "line": 10,
        "character": 10
    },
    "context": {
        "triggerkind": 1
    }
}
```
Phpls returns the correct response. One difference I see is that it reports `$` and `\` as `triggerCharacters`.

I have also installed a fresh minimal vim directory with pathogen, coc and phpactor only. The same error occurs. I tried also original vim, another terminal emulators with no positive effect.

**Comment by dantleech** [comment]
Sorry I meant Language Client (e.g. CoC)

**Comment by przepompownia** [comment]
Currently I use CoC. I can try with ALE and install another client in a separate minimal environment.

**Comment by przepompownia** [comment]
Trying to use another clients I encounter lots of bugs that discourage me to spend too much more time for them to test purposes only. I did not able to auto-trigger completion with any other client. 

Standalone ALE proved to be the least problematic: using omnifunc that make a request to a server I did not get double dollar sign. 

The other approaches included asyncomplete-lsp with dependencies and deoplete with LanguageClient-neovim. The latter worked for me a half year ago before I switched to using CoC. 

I think that learning how to efficiently debug phpactor will be worth spending time instead. 

I noticed that the response from phpls contains `textEdit` entry and phpactor has an undocumented and probably unused option `language_server_completion.provide_text_edit`. I tried to directly set `$provideTextEdit` in the constructor but the suggestion did not equipped with range so (if I am not wrong) `textEdit` entry was not attached to the response.

**Comment by dantleech** [comment]
> I tried to directly set $provideTextEdit in the constructor

It seems it's only currently supported by the class completor (https://github.com/phpactor/completion/blob/master/lib/Bridge/TolerantParser/SourceCodeFilesystem/ScfClassCompletor.php#L121) which doesn't seem to trigger with CoC anyway.

**Comment by dantleech** [comment]
If you don't know already, starting the language server in a separate process can help debugging:

```
./bin/phpactor language-server --address=127.0.0.1:8889 -vvv
```
`:CocConfig`:
```
    "languageserver": {
        "phpactor": {
            "host": "127.0.0.1",
            "filetypes": ["php"],
            "port": 8889
        }
    }
```

**Comment by przepompownia** [comment]
Thanks, I have tested both the above and `logging.path`.

 I have also set `rpc.store_replay: true` but cannot know how to update `~/.cache/phpactor/replay.json` by the latest response. My `replay.json` is over a dozen hours older than the last request (without switching rpc.store_replay to false in the meantime).

**Comment by dantleech** [comment]
RPC replay only works for Phpactor's RPC. RPC is Phpactor's own "Language Server Protocol".

**Comment by przepompownia** [comment]
Indeed, the file was updated after testing `PhpactorGotoType`.

Trying to replay a LSP request (from a separate connection) seems to be not so simple - it requires to make dependencies (with below script `makeRequest initialize.json initialized.json didopen.json didChange.json didChange2.json completion.json`): 
```sh
#!/usr/bin/env bash

createPayload() {
    declare bodyFile port contentLength body
    bodyFile="$1"
    contentLength="$(stat -c %s "$bodyFile")"
    body="$(< "$bodyFile")"

    printf \
        'Content-Length: %s\r\n\r\n%s\r\n\r\n' \
        "$contentLength" "$body"
}

makeRequest() {
    declare bodyFile port
    port="8888"

    exec 3<>"/dev/tcp/127.0.0.1/${port}"

    for bodyFile in "$@"; do
        createPayload "$bodyFile" >&3
    done

    exec 3>&-
}

makeRequest "$@"
```

**Comment by dantleech** [comment]
Ah, there is also `language-server --record=log.lsp` you could then in theory `cat log.lsp | phpactor language-server` ?

**Comment by przepompownia** [comment]
It strongly simplifies replaying :+1: 

I found the similar issue for Serenata. In the last version there is no dollar sign in a `label`. See
https://gitlab.com/Serenata/Serenata/-/commit/d67e8e3ba049f35da64f7ac0e137bde6715490e3
https://gitlab.com/Serenata/Serenata/-/issues/315 

After removing dollar sign from `WorseLocalVariableCompletor::complete()` and adding it to trigger character set in `CompletionHandler` completion by LSP works as expected. Maybe moving the dollar sign from `WorseLocalVariableCompletor::complete()` to some place specific to RPC completion will be a solution?

**Comment by dantleech** [comment]
We could also trim the $ in LSP client. Not sure if one way is better than the other.

**Comment by dantleech** [comment]
Hmm, I guess with other trigger chars `:` or `>` we don't include them - maybe it does make sense to not include the `$` by default :thinking: 

Anyway, if we wanted to trim it in the handler it would be here: https://github.com/phpactor/language-server-completion-extension/blob/master/lib/Handler/CompletionHandler.php and we could modify it based on the suggestion->type() I guess.

**Comment by przepompownia** [comment]
Something like [this](https://github.com/phpactor/language-server-completion-extension/pull/2)?

**Comment by dantleech** [comment]
@

**Comment by przepompownia** [comment]
Indeed, I have `setlocal iskeyword-=$` for php and bash filetype. 

Assuming version with phpactor RPC, we can set it in ftplugin. To decide how a standalone language server should behave, we probably should check it from some non-vim client.

>  it seems to be what Intelliphense does.

Intellephense's response contains label with leading dollar sign, but also contains TextEdit which is used to modify document instead of label. Maybe its authors had a similar issue.

**Comment by dantleech** [comment]
> Indeed, I have setlocal iskeyword-=$ for php and bash filetype.

Out of curiosity, why remove it?

> Intellephense's response contains label with leading dollar sign,

The PHP language server is also including a `$` and a text edit:

https://github.com/felixfbecker/php-language-server/blob/3d074fa81ae5ade51b1f28cce44e5bf7db4f87fe/src/CompletionProvider.php#L219

I wonder if we should leave the `$` in the label and also return a text edit in the future.

I have created a PR https://github.com/phpactor/language-server-completion-extension/pull/3 to make it configurable, but might make sense to remove the config.

to make it configurable. But I wonder if we should leave it in the label

**Comment by dantleech** [comment]
oh, actually there is a config option in phpactor: `language_server_completion.provide_text_edit` :thinking:

**Comment by przepompownia** [comment]
Is this option used anywhere? It seems to not work.

**Comment by dantleech** [comment]
hmm, the parameter is not connected to the class, and currently it would only work with class completion: https://github.com/phpactor/completion/blob/master/lib/Bridge/TolerantParser/SourceCodeFilesystem/ScfClassCompletor.php

obviously something I was working on some time ago :)

**Comment by dantleech** [comment]
I'll add text edits in completion to the list ...

**Comment by przepompownia** [comment]
> Out of curiosity, why remove it?

Maybe working some time with `$` would remember me why I removed it from `iskeyword` more than six years ago.

**Comment by przepompownia** [comment]
> The PHP language server is also including a $ and a text edit

Maybe a label can matter if a client does not support TextEdit handling.

**Comment by dantleech** [comment]
Yeah, I've found it difficult to decide initially if it should or should not be included. In other languages a variables has no prefix. Also if you were, hypothetically, to complete just based on cursor position (with no leading text) you would want the `$var` and not `var`, as with functions.

But in anycase, we can add text edits later and avoid this issue :)
