### ISSUE TITLE
Completion provide same results multple time

### ISSUE THREAD

**Issue by camilledejoye** [phpactor/phpactor#905]
![image](https://user-images.githubusercontent.com/11501572/76163367-b7a67a80-6145-11ea-82e5-4aa6a8dedbda.png)

As we can see the method `doFoo` is present twice, this appends with `$second` too.

**Comment by dantleech** [comment]
Maybe a decorator to remove duplicates? https://github.com/phpactor/completion/tree/master/lib/Bridge/TolerantParser/WorseReflection

**Comment by elythyr** [comment]
The thing is that we use `yield` so we never have all the results at once.
Also with the the `ChainCompletor` or something like that we could have other issues of duplicates later on.
So maybe a decorator at the end of the chain can ensure that all `Suggestion` are unique.
But we would still need to stop using `yield` for this decorator.

Not sure of what would be best...

**Comment by dantleech** [comment]
We can still use `yield`? It does mean tracking the suggestions and blocking those which are duplicates.

**Comment by dantleech** [comment]
Also not sure if this is a problem with WorseReflection providing the same method twice...

**Comment by elythyr** [comment]
> We can still use yield? It does mean tracking the suggestions and blocking those which are duplicates.

So we will have an internal collection of suggestions and do something like:
```php
if (!$this->suggestionAlreadySent($suggestion)) {
    yield $suggestion;
}
```
I guess so because suggestions will still be retrieved "as they come", my bad.

> Also not sure if this is a problem with WorseReflection providing the same method twice...
I don't know and that's pretty much why I suggested to add the decorator at the last possible moment, so no matter which completor(s) is used the final result will be unique.

**Comment by dantleech** [comment]
Fixed in #958

**Comment by dantleech** [comment]
(https://github.com/phpactor/completion/blob/master/lib/Core/Completor/DedupeCompletor.php)

**Comment by mamazu** [comment]
Should also be fixed.

**Comment by dantleech** [comment]
have not seen this behavior in a long time.
