### ISSUE TITLE
Segmentation fault when extract method

### ISSUE THREAD

**Issue by rtorralba** [phpactor/phpactor#909]
Hi,

When I try to extract method it remain freeze some seconds and then return a segmentation fault.

Phpactor returned an error: Segmentation fault (core dumped)

Vim version 8.1

Info
----
Version: c44f7f3 (hace 6 días) Fix-force-reload-behavior-with-useOpenWindow
PHP: 7.2.24-0ubuntu0.18.04.3 (supporting 5.6.4)

Diagnostics
-----------
[✔] Composer detected - faster class location and more features!
[✔] Git detected - enables faster refactorings in your repository scope!
[✔] XDebug is disabled. XDebug has a negative effect on performance.

**Comment by rtorralba** [comment]
I tried with older version first and updated because is maybe fixed but not. Then not seems a recent change the problem

**Comment by rtorralba** [comment]
php 7.2 crashes with following message: No symbol table info available. zend_parse_parameters_throw()

**Comment by dantleech** [comment]
:grimacing: any additional info? stack trace? maybe the source code?

**Comment by dantleech** [comment]
as we are now resticting to 7.4 closing this.
