### ISSUE TITLE
Go to Definition doesn't work with zend 1 classes

### ISSUE THREAD

**Issue by afranioce** [phpactor/phpactor#911]
I working with a application with [zend framework 1](https://framework.zend.com/manual/1.12/en/zend.loader.autoloader.html)

working if the class has the same name of file, even without the namespace, but class with name different like `Zend_Controller_Action` and path is `Zend/Controller/Action.php` even without the namespace

return this error
```
Error from Phpactor: Could not find source with "Zend_Controller_Action", Word "Zend_Controller_Action" could not be resolved to a class
```

**Comment by dantleech** [comment]
Yes -- as of now Phpactor will not work with "old" class names (as far as I an aware) and requires a 1-1 correlation between class name and file name.

The next release however will support [an indexer](https://github.com/phpactor/phpactor/pull/890) - which will happily discover all class names.
