### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#913]
Support generics! We already have support for things such as `FoobarCollection<Barfoo>` - but this is only saying that it's a collection of Barfoo (and it not generics at all).

It would be great to replace this with real generics as supported by Phpstan / Psalm.

**Comment by weeman1337** [comment]
Does the parser already support `@template` / `@iplements` etc. doc block tags? If [this is the place](https://github.com/phpactor/worse-reflection/blob/master/lib/Core/DocBlock/DocBlock.php) it doesn't look like that.

As a starting point would it help to teach the parser reading all the tags into `DocBlock`?

**Comment by dantleech** [comment]
No that one does not support generics. [this one does](https://github.com/phpactor/docblock-parser).

Supporting generics however seems a _very_ big task, which would involve an overdue rewrite of the type inference system. Unless I'm missing some easy picks. Not sure when I will find the time/motification to do this.

A lower hanging fruit for the above parser would be to include documented classes when finding references.

**Comment by weeman1337** [comment]
> No that one does not support generics. this one does.

Funny there seems to be multiple ways for doing most things in Phpactor somewhere :D 

> Supporting generics however seems a very big task mainly because it would involve an overdue rewrite of the type inference system. Unless I'm missing some easy picks. Not sure when I will find the time/motivation to do this.

I am motivated :) Generics are becoming quite common nowadays.  
More and more tools support it and so they appear in code in more and more places.

Is it possible to approach that in smaller steps? I would like to help out but just "rewrite the type inference" is too large for me to understand. If you could sketch some steps on the way I could try implementing them.

**Comment by dantleech** [comment]
> Funny there seems to be multiple ways for doing most things in Phpactor somewhere :D

Well this would be the "new" way, but that doc block parser is experimental and not used anywhere currently - it's also slower at the expense of being more accurate.

> I am motivated :) Generics are becoming quite common nowadays.

There are multiple problems:

- Rewriting the type inference system
  - Supporting types as _types_: Currently a string is `Type::string()`, an array is `Type::array('string')`. But this only goes so far, and is far from supporting generics. A new type would look like `new IteratorType(new StringType(), new UnionType([new StringType(), new NullType()))` for example.
  - Very probably replacing the existing "SymbolContextResolver"
     - It's horrendous
     - The changes required by the new type system would imply as much
 - Maintaining B/C with the existing Type system (i.e. the methods that return `Type` in worse reflection) to avoid having to rewrite large parts of Phpactor.

You could look  PHPStan and Psalm for inspiration, and WR for how not to do it (it needs to be modular, not a monolithic class with extensiblity added on badly afterwards).

But yeah, I would expect this to be very challenging.

**Comment by weeman1337** [comment]
Thanks for the explanation. I think I will pick this up after my other points on the list are done.

A practical way could be:
1. sketching a concept including the new PHP type constructs
2. replacing the `Type` stuff with the new type classes (no functional change)
3. put the new doc block parser into place (no functional change)
4. wire it up with the new types (→ generics, union type, etc. support from here)

**Comment by dantleech** [comment]
> replacing the Type stuff with the new type classes (no functional change)

public API methods such as `$reflectionClass->method('foo')->type()` return `Type`. You need to use the Reflection API in the type inference engine to resolve method types etc. So you need to preserve `Type` and also add a new API method to return the new type. [this is where I got to with my exerimenting](https://github.com/phpactor/worse-reflection/pull/101)

**Comment by dantleech** [comment]
a good first step might be replacing the existing Docblock parser -- but be mindful of performance (will need a benchmark) as the Dcoblcok parser is significantly slower than the existing "parser" (it's dumb but fast) - but maybe performance gains can be made elsewhere

**Comment by dantleech** [comment]
basic generics are supported (`@implements` and `@extends`) with full support on the way, closing.
