### ISSUE TITLE
Language Server: Indexer

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#917]
Automatically start the [Indexer](https://github.com/phpactor/workspace-query) and update files as they are modified.

The indexer provides the following capabilities to Phpactor:

- Jump to implementations (`:PhpactorGotoImplementations`)
- Working with legacy PHP projects (e.g. without composer)

WIP Here: https://github.com/phpactor/language-server-workspace-query-extension (note will probably move it to the workspace-query extension).

- [x] Automatically start indexing service (added concept services to the Phpactor language server)
- [x] Linux: Wait for file modifications using `inotify` *
- [x] Mac: Wait for file modifications using `fswatch` (??)
- [x] POSIX: Find watcher
- [x] Report progress to client https://github.com/neoclide/coc.nvim/issues/1582 - cannot get this to work currently. [gitter link](https://gitter.im/neoclide/coc.nvim?at=5e6e21a969387244e392df2a) (have added manual notifications ... )
- [x] Allow selection of active indexers
- [x] Brute force indexer (to work, f.e. with windows, or when no other method can be used)

* Initially I thought we could update based on editor changes - but as Phpactor does lots of things ex-editor this would not be sufficient.

---

```
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling
```

:point_up: potentially the reason the language server stops working (seen in a `tail` process which couldn't use `inotify` anymore)

**Comment by expipiplus1** [comment]
@dantleech Please update this issue if you get the progress reporting working! I'm curious about how it works with cocn.nvim. FWIW it worked automatically for haskell-ide-engine with the coc extension https://github.com/expipiplus1/vscode-hie-server

From the talk on neoclide/coc.nvim#1582 I was surprised that it ended up working though and would like to be unsurprised :)

**Comment by dantleech** [comment]
The indexer now uses https://github.com/phpactor/amp-fswatch to monitor for changes, it uses monitors in realtime with `inotifywait` (Linux) or fallsack to POSIX `find` for polling. There is also support for `fswatch` which is cross-platform, but it doesn't work superbly at the moment.

**Comment by dantleech** [comment]
@expipiplus1 I could _not_ get this working by sending a `window/workDoneProgress/create` method from the client.

Another thing to try is to use the `workDoneToken` provided by the client, f.e., with the `initialize` call.
