### ISSUE TITLE
Release: April 2020

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#918]
The Language Server release:

https://github.com/phpactor/phpactor/issues/528

Packaging changes:
- [ ] Merge extensions with implementations #910

**Comment by przepompownia** [comment]
Even if phpactor used as language server only still contains lots of vim-specific code, it seems to be editor-agnostic as a language server. It then could be promoted on https://langserver.org/

**Comment by dantleech** [comment]
Closed in favour of #528
