### ISSUE TITLE
Cannot open the context menu when cwd != workspace root

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#921]
Example: `https://github.com/przepompownia/phpcd.vim/blob/master/php/PHPCD.php` from one of abandoned projects but used to test phpactor behaviour. 

Trying to open `PhpactorContextMenu` ends with
```
Error from Phpactor: Could not find source with "Lvht\MsgpackRpc\Handler"
```
when I open PHPCD.php from outside its project. 

Problem does not exist only when the current directory is the project root directory. 

Another example, but on phpactor I described in https://github.com/phpactor/phpactor/issues/920#issuecomment-599264322 It also prevents from opening the menu.

**Comment by dantleech** [comment]
See https://github.com/phpactor/phpactor/issues/660 it's currently expected that the project root is and stays the one in which VIM was started - but it might be possible to implement a strategy to somehow safely detect the project root (note we don't want to start refactoring the users home directory)

**Comment by dantleech** [comment]
@przepompownia can be closed now?
