### ISSUE TITLE
[vim] Copy FQN to clipboard command

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#922]
Not sure how often this would be useful.

**Comment by elythyr** [comment]
You'll be surprised how often I have to do it :D
First example in mind is to declare a service in Symfony DIC.

**Comment by dantleech** [comment]
Yeah, I probably need it more often than I realize - and I think Phpstorm has something similar (?) anyway, it's an easy one :)

**Comment by mamazu** [comment]
Yep, that would be nice. What would be the best way to tackle it? Making a vim command that does that?
