### ISSUE TITLE
Add donation button

### ISSUE THREAD

**Issue by alexdrupal** [phpactor/phpactor#924]
Hello

I cannot tell you how I am amazed of phpactor. I've been trying a lot of PHP autocomplete solutions for VIM and yours is the best one! I really like it and want to donate you some $$...

Please add donation button on Github and on your page so people can support your work.
Thanks man!

**Comment by dantleech** [comment]
Hi thanks for the support, I'm not currently interested in this, maybe in the future :)

**Comment by dantleech** [comment]
you can do this from the repo home page (https://github.com/phpactor/phpactor):

![image](https://user-images.githubusercontent.com/530801/157439533-3c89a020-827b-4c82-ab80-685e5ac3271a.png)
