### ISSUE TITLE
Recognize Symfony services

### ISSUE THREAD

**Issue by alexdrupal** [phpactor/phpactor#925]
Hello

Maybe it is a part of phpactor extension, but I'd like to get proper autocomplete results for the:

`$this->get('service_name')->`

Right now it doesn't complete anything.
And a secong point - would be great to have autocomplete for the service names as well.

Thank you!

**Comment by dantleech** [comment]
Hi, this would be possible via. an extension, see the [phpunit extension](https://github.com/phpactor/phpunit-extension) for how to add type information (it adds types based on `Assert::assertInstanceOf`).

I think @Taluu was thinking about this at one point - I'm not using the Symfony DI container regularly, so not sure what would be required exactly.

**Comment by Taluu** [comment]
Never had the time to dedicate to this, but the idea was to do it as Psalm's and phpstan's sf extension, by reading the generated xml.

Anyway, with sf4+, it shouldn't be considered a good practice to have such a plug-in (except maybe for test container ?)

**Comment by alexdrupal** [comment]
Thanks guys.
