### ISSUE TITLE
Refactoring a static member variable forgets $ sign

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#926]
I'm trying to make this file comply with the Doctrine coding standards: https://github.com/doctrine/sql-formatter/blob/master/src/SqlFormatter.php

Workflow:
1. hover static member variable
2. `:call phpactor#ContextMenu()`
3. `replace references`

I end up with the following result

```php
class A
{
    private static $renamed;

    public function foo()
    {
         self::renamed = 'a'; // $ sign misses after refactoring
    }
```

**Comment by dantleech** [comment]
Should work in develop now...

**Comment by greg0ire** [comment]
Thanks!
