### ISSUE TITLE
ftplugin/php.vim not loaded

### ISSUE THREAD

**Issue by fefas** [phpactor/phpactor#927]
Hi,

I have just installed phpactor plugin using `dein`:
```
call dein#add('phpactor/phpactor', {'on_ft' : 'php', 'build': 'composer install --no-dev -o'}
```

However, I am getting the following error when trying to execute `call phpactor#Status()`:
```
Error detected while processing function phpactor#Status[1]..phpactor#rpc:
line    6:
E121: Undefined variable: g:phpactorPhpBin
line    7:
E121: Undefined variable: cmd
E116: Invalid arguments for function system(cmd, json_encode(request))
Error detected while processing function phpactor#Status[1]..phpactor#rpc:
line   13:
E605: Exception not caught: Could not parse response from Phpactor: Vim(let):E121: Undefined variable: result
```

I could fix it by adding this to my `.vimrc`:
```
source ~/.vim/dein/repos/github.com/phpactor/phpactor/ftplugin/php.vim
```

What should be done to fix this problem? Since there is a check if phpactor is loaded at the beginning of the `php.vim` script, maybe it could be always included in `phpactor.vim`.

**Comment by dantleech** [comment]
The VIM plugin is slowly being refactored. It is now better to use the new commands e.g. `:PhpactorStatus` which will only be available after loading a PHP file.

**Comment by dantleech** [comment]
I've updated the documentation in `develop` to indicate that the command should be used https://github.com/phpactor/phpactor/commit/2cfb3494b8a649f39e3903d54138e78f803f45b8 let me know if that makes sense.
