### ISSUE TITLE
Keep autocomplete open while params are entered

### ISSUE THREAD

**Issue by alexdrupal** [phpactor/phpactor#930]
Hello

Any way to get autocomplete open till I enter the last param into the method I autocomplete ?
Probably close after ) entered?

**Comment by dantleech** [comment]
Not currently - I don't think it's possible with native omnifunc completion, so it would need to be a special integration with an auto-complete manager or a language server client.

**Comment by dantleech** [comment]
This does work with [CoC](https://github.com/neoclide/coc.nvim) and the (phpactor) language server, e.g.
![Untitled](https://user-images.githubusercontent.com/530801/77911929-90952180-7289-11ea-91c7-5de1d252dd45.png)

next release should include the LS by default.

**Comment by alexdrupal** [comment]
Thanks @dantleech 
I am using asyncomplete and will check if I can configure it to work similar to CoC.
I don't like CoC due to the usage of TS and Node.... Actually the whole purpose of using VIM is low CPU and Memory usage. If we switch to solutions like VSCode / Atom or something similar - it is better to use Netbeans of PHPStorm because they are real IDEs and their usage of resources is understandable.

**Comment by dantleech** [comment]
Yes indeed -- Nvim will have it by default in 5.0 however: https://neovim.io/doc/user/lsp.html

The above is specific to the language server protocol (there is an explicit handler for "signature help")

**Comment by alexdrupal** [comment]
Let's see :+1:
