### ISSUE TITLE
Goto Implementation should work on class members.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#931]
e.g.

```
$this->foobarClient->doSo<>mething()
```

if `foobarClient` is an interface then invoking `PhpactorGotoimplementations` on `<>` should if there is a single implementation it should be opened and the cursor moved to the method (as with goto definition).

If multiple implementations, perhaps we can preserve the method name and still goto the method position after selection.

**Comment by elythyr** [comment]
> If multiple implementations, perhaps we can preserve the method name and still goto the method position after selection.

Are we still talking about LSP ?
If it's for the RPC then I guess we don't even have to remember anything since the reference hold the position information.

**Comment by dantleech** [comment]
We would need to resolve the container class of the member, find implementation(s) of that, then open that file at the position of the method implementation.
