### ISSUE TITLE
Every Phpactor command in Vim 8 results in same error

### ISSUE THREAD

**Issue by pelachile** [phpactor/phpactor#934]
running `:PhpactorStatus ` from inside Vim results in 

```
Phpactor returned an error:

  Too many arguments, expected arguments "command".


rpc [--replay] [--pretty]
```

In fact every command issues the exact same error. 

OSX 10.15.3 Vim 8.1

**Comment by dantleech** [comment]
Hi, how did you install Phpactor? (Plug?)

**Comment by pelachile** [comment]
Yes sir

**Comment by pelachile** [comment]
Made it worse:

<img width="1675" alt="Screen Shot 2020-04-02 at 3 37 23 PM" src="https://user-images.githubusercontent.com/1620350/78298430-ea9b1e80-74f7-11ea-805c-547b03362fdc.png">

**Comment by dantleech** [comment]
Sorry, that was for the `develop` version of Phpactor, this should work 
better for you:

```
diff --git a/autoload/phpactor.vim b/autoload/phpactor.vim
index cfe43e3..816218e 100644
--- a/autoload/phpactor.vim
+++ b/autoload/phpactor.vim
@@ -433,7 +433,7 @@ function! phpactor#rpc(action, arguments)

      let request = { "action": a:action, "parameters": a:arguments }

-    let cmd = g:phpactorPhpBin . ' ' . g:phpactorbinpath . ' rpc 
--working-dir=' . g:phpactorInitialCwd
+    let cmd = [g:phpactorPhpBin , g:phpactorbinpath,'rpc', 
'--working-dir=' . g:phpactorInitialCwd]
      let result = system(cmd, json_encode(request))

      if (v:shell_error == 0)
```

**Comment by dantleech** [comment]
Sorry, that was for the `develop` version of Phpactor, this should work
better for you:

```diff
diff --git a/autoload/phpactor.vim b/autoload/phpactor.vim
index cfe43e3..816218e 100644
--- a/autoload/phpactor.vim
+++ b/autoload/phpactor.vim
@@ -433,7 +433,7 @@ function! phpactor#rpc(action, arguments)

      let request = { "action": a:action, "parameters": a:arguments }

-    let cmd = g:phpactorPhpBin . ' ' . g:phpactorbinpath . ' rpc
--working-dir=' . g:phpactorInitialCwd
+    let cmd = [g:phpactorPhpBin , g:phpactorbinpath,'rpc',
'--working-dir=' . g:phpactorInitialCwd]
      let result = system(cmd, json_encode(request))

      if (v:shell_error == 0)
```

**Comment by pelachile** [comment]
Didn't help

<img width="1675" alt="Screen Shot 2020-04-02 at 5 07 23 PM" src="https://user-images.githubusercontent.com/1620350/78304470-6f8c3500-7504-11ea-8613-a5f113127ee6.png">

**Comment by pelachile** [comment]
How is phpactorInitialCwd being set?

**Comment by pelachile** [comment]
I get the menu working:
<img width="1669" alt="Screen Shot 2020-04-02 at 5 26 25 PM" src="https://user-images.githubusercontent.com/1620350/78305663-21c4fc00-7507-11ea-9535-ea6f84f6c0e5.png">


Then I get this error:
Vim(let):E121: Undefined variable: phpactorInitialCwd

Which is better than before. Before it would put Vim into visual mode and nothing would happen

**Comment by dantleech** [comment]
That is set in the file-type plugin:

https://github.com/phpactor/phpactor/blob/ff3ae50641d9bf3faf665c0df8f46fb0b2767578/ftplugin/php.vim#L8

Which mean you will need to open a PHP file before it's available - but equally `:PhpactorStatus` should not be available until you do that :thinking:

**Comment by pelachile** [comment]
I appreciate you trying. I just wanted to get away from PHP Storm and I love vim, but I'll just have to get better at PHP and Laravel so I won't need autocomplete. I'll just revert back to my old vim.
Thanks!

**Comment by dantleech** [comment]
OK, sorry this didn't work for you, Hopefully we'll discover the issue you're having in the future :)

**Comment by pelachile** [comment]
Just for your piece of mind, I got it to work. I installed NeoVim and just have a script to load different configs for either Vim or NeoVim. Anyway, after installing NeoVim and getting everything setup I still couldn't get your plugin to work, I was having the same initial error. However, I applied the fix to the phpactor.vim file and Viola!

**Comment by dantleech** [comment]
Ah ok - so the https://github.com/phpactor/phpactor/issues/934#issuecomment-608103195 fix addresses the issue?

Very odd that it doesn't work in standard VIM though - I wonder if there are some plugins conflicting. I think @greg0ire is using latest `mater` with standard VIM?

**Comment by greg0ire** [comment]
I am indeed, and I have been using whatever commit `master` was at this morning all day long. Didn't code that much but I remember using phpactor. My configuration can be seen at https://github.com/greg0ire/dotvim/

**Comment by pelachile** [comment]
I think it might have something to do with Powerline but I didn't test it. Powerline took forever to get working correctly and I didn't want to risk messing it up.

**Comment by dantleech** [comment]
closing as old
