### ISSUE TITLE
Language server unavailable

### ISSUE THREAD

**Issue by przepompownia** [phpactor/phpactor#937]
The fresh phpactor version contains language server extension by default. I have it in vendor packages, but phpactor does not detect it.

**Comment by przepompownia** [comment]
Please also review `config/travis/extensions-to-test`. It still contains the old extension.

**Comment by dantleech** [comment]
Yes -- I'm working on this currently ...

**Comment by dantleech** [comment]
... and it's not working out. I'll revert today package changes tomorrow....

**Comment by dantleech** [comment]
Should work now
