### ISSUE TITLE
[LSP] Progress Notification

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#946]
Initializing progress (for indexing) involves sending a REQUEST to the client and receiving a RESPONSE.

Currently we can only send notifications, so the following does not work:

```
            $transmitter->transmit(new RequestMessage(1, 'window/workDoneProgress/create', [
                'token' => $token,
            ]));
            $transmitter->transmit(new NotificationMessage('$/progress', [
                'token' => $token,
                'value' => [
                    'kind' => 'begin',
                    'title' => 'Indexing',
                ],
            ]));
```

We would need to add the ability to make requests to the client to the Transmitter class.

---

This doesn't currently seem to work with CoC - however CoC does send a progress token on intitialization, which could be used -- probably.

**Comment by mamazu** [comment]
Doesn't this already exist in PhpActor? At least for indexing there is already a progress indicator.

**Comment by dantleech** [comment]
can also send requests via. the API so closing
