### ISSUE TITLE
Update documentation (incl. README)

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#948]
- [x] CoC configuration examples, including Phpactor config in `additionalOptions`.
- [x] Phpactor local config is not loaded - should use LS config instead. 
- [x] Inotify configuration (sysctl ... )
- [x] LSP feature list
  - Snippets
  - Completion
  - Goto type
  - Goto definition
  - etc.

- [x] ... consider allowing "help" to be added to extension parameter definitions (generate reference)

- [x] Developer documentation:
   - logging options
   - running the language server
   - etc.

**Comment by dantleech** [comment]
Would be nice to migrate the whole thing to RST and readthedocs

**Comment by elythyr** [comment]
>  Inotify configuration (sysctl ... )

What about [watchman](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#optional-install-watchman-for-file-watching) ?
They talk about it but I don't know if it could be of interest or not ?

**Comment by dantleech** [comment]
Yes, we are currently doing this on the server - I didn't realise it was possible from the client side too. But would not be in this release.
