### ISSUE TITLE
[ampfs-watch] Inotify MOVE events do not register indivual files.

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#961]
When comoser installs packages it creates temproary files e.g.

```
 /home/daniel/www/phpactor/language-server/vendor/composer/3a12399b/thephpleague-event-d2cc124/src/AbstractListener
.php
```

It then moves them, but `inotify` only registers the MOVE event, and does not identify the newly moved files.

While the Indexer would happily index an entire directory - we currently filter out any files/folders not ending with `*.php` so the folder never makes it to the indexer.

**Comment by elythyr** [comment]
It might be a stupid question but should we not ignore the `vendor/composer` directory completely ?
I don't see the point of indexing temporary composer files since we will never edit or even care about them in any way.

**Comment by dantleech** [comment]
We can ignore it but this isn't related to the problem. (could still be an issue if they make it into the index).

The individual files would still not be registered.

**Comment by dantleech** [comment]
https://github.com/phpactor/amp-fswatch/pull/6
